<<Top>>

Next: [[#Starting-Rules][Starting Rules]]  
[[[#SEC_Contents][Contents]]]

* Bovine parser development [[#Bovine-parser-development][¶]]
:PROPERTIES:
:CUSTOM_ID: Bovine-parser-development
:CLASS: top
:END:
The /bovine/ parser is the original /Semantic/ parser, and is an
implementation of an LL parser. It is good for simple languages. It has
many conveniences making grammar writing easy. The conveniences make it
less powerful than a Bison-like LALR parser. For more information, see
[[https://www.gnu.org/software/emacs/manual/html_mono/wisent.html#Top][Wisent Parser Development]].

Bovine LL grammars are stored in files with a =.by= extension. When
compiled, the contents is converted into a file of the form
=NAME-by.el=.

Copyright © 1999--2004, 2012--2026 Free Software Foundation, Inc.

#+begin_quote
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being “A GNU Manual,” and
with the Back-Cover Texts as in (a) below. A copy of the license is
included in the section entitled “GNU Free Documentation License”.

(a) The FSF's Back-Cover Text is: “You have the freedom to copy and
modify this GNU manual.”
#+end_quote

<<SEC_Contents>>
** Table of Contents
:PROPERTIES:
:CUSTOM_ID: table-of-contents
:CLASS: contents-heading
:END:

- [[#Starting-Rules][1 Starting Rules]]
- [[#Bovine-Grammar-Rules][2 Bovine Grammar Rules]]
  - [[#How-Lexical-Tokens-Match][2.1 How Lexical Tokens Match]]
  - [[#Grammar_002dto_002dLisp-Details][2.2 Grammar-to-Lisp Details]]
  - [[#Order-of-components-in-rules][2.3 Order of components in rules]]
- [[#Optional-Lambda-Expression][3 Optional Lambda Expressions]]
- [[#Bovine-Examples][4 Examples]]
- [[#GNU-Free-Documentation-License][Appendix A GNU Free Documentation License]]

--------------

<<Starting-Rules>>

Next: [[#Bovine-Grammar-Rules][Bovine Grammar Rules]], Previous:
[[#Top][Bovine parser development]], Up:
[[#Top][Bovine parser development]]   [[[#SEC_Contents][Contents]]]

** 1 Starting Rules [[#Starting-Rules-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Starting-Rules-1
:CLASS: chapter
:END:
In Bison, one and only one nonterminal is designated as the “start”
symbol. In /Semantic/, one or more nonterminals can be designated as the
“start” symbol. They are declared following the =%start= keyword
separated by spaces.

If no =%start= keyword is used in a grammar, then the very first is
used. Internally the first start nonterminal is targeted by the reserved
symbol =bovine-toplevel=, so it can be found by the parser harness.

To find locally defined variables, the local context handler needs to
parse the body of functional code. The =scopestart= declaration
specifies the name of a nonterminal used as the goal to parse a local
context. Internally the scopestart nonterminal is targeted by the
reserved symbol =bovine-inner-scope=, so it can be found by the parser
harness.

--------------

<<Bovine-Grammar-Rules>>

Next: [[#Optional-Lambda-Expression][Optional Lambda Expressions]],
Previous: [[#Starting-Rules][Starting Rules]], Up:
[[#Top][Bovine parser development]]   [[[#SEC_Contents][Contents]]]

** 2 Bovine Grammar Rules [[#Bovine-Grammar-Rules-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Bovine-Grammar-Rules-1
:CLASS: chapter
:END:
The rules are what allow the compiler to create tags from a language
file. Once the setup is done in the prologue, you can start writing
rules.

#+begin_src example-preformatted
result : components1 optional-semantic-action1)
       | components2 optional-semantic-action2
       ;
#+end_src

=result= is a nonterminal, that is a symbol synthesized in your grammar.
=components= is a list of elements that are to be matched if =result= is
to be made. =optional-semantic-action= is an optional sequence of
simplified Emacs Lisp expressions for concocting the parse tree.

In bison, each time an element of =components= is found, it is /shifted/
onto the parser stack. (The stack of matched elements.) When all
=components=' elements have been matched, it is /reduced/ to =result=.
See
[[https://www.gnu.org/software/bison/manual/bison.html#Algorithm][Algorithm]]
in The GNU Bison Manual.

A particular =result= written into your grammar becomes the parser's
goal. It is designated by a =%start= statement (see
[[#Starting-Rules][Starting Rules]]). The value returned by the
associated =optional-semantic-action= is the parser's result. It should
be a tree of /Semantic/ /tags/.

=components= is made up of symbols. A symbol such as =FOO= means that a
syntactic token of class =FOO= must be matched.

- [[#How-Lexical-Tokens-Match][How Lexical Tokens Match]]
- [[#Grammar_002dto_002dLisp-Details][Grammar-to-Lisp Details]]
- [[#Order-of-components-in-rules][Order of components in rules]]

--------------

<<How-Lexical-Tokens-Match>>

Next: [[#Grammar_002dto_002dLisp-Details][Grammar-to-Lisp Details]], Up:
[[#Bovine-Grammar-Rules][Bovine Grammar Rules]]  
[[[#SEC_Contents][Contents]]]

*** 2.1 How Lexical Tokens Match [[#How-Lexical-Tokens-Match-1][¶]]
:PROPERTIES:
:CUSTOM_ID: How-Lexical-Tokens-Match-1
:CLASS: section
:END:
A lexical rule must be used to define how to match a lexical token.

For instance:

#+begin_src example-preformatted
%keyword FOO "foo"
#+end_src

Means that =FOO= is a reserved language keyword, matched as such by
looking up into a keyword table. This is because ="foo"= will be
converted to =FOO= in the lexical analysis stage. Thus the symbol =FOO=
won't be available any other way.

If we specify our token in this way:

#+begin_src example-preformatted
%token <symbol> FOO "foo"
#+end_src

then =FOO= will match the string ="foo"= explicitly, but it won't do so
at the lexical level, allowing use of the text ="foo"= in other forms of
regular expressions.

In that case, =FOO= is a =symbol=-type token. To match, a =symbol= must
first be encountered, and then it must =string-match "foo"=.

- *Caution:* :: Be especially careful to remember that ="foo"=, and more
  generally the %token's match-value string, is a regular expression!

Non symbol tokens are also allowed. For example:

#+begin_src example-preformatted
%token <punctuation> PERIOD "[.]"

filename : symbol PERIOD symbol
         ;
#+end_src

=PERIOD= is a =punctuation=-type token that will explicitly match one
period when used in the above rule.

- *Please Note:* :: =symbol=, =punctuation=, etc., are predefined
  lexical token types, based on the /syntax class/-character
  associations currently in effect.

--------------

<<Grammar_002dto_002dLisp-Details>>

Next: [[#Order-of-components-in-rules][Order of components in rules]],
Previous: [[#How-Lexical-Tokens-Match][How Lexical Tokens Match]], Up:
[[#Bovine-Grammar-Rules][Bovine Grammar Rules]]  
[[[#SEC_Contents][Contents]]]

*** 2.2 Grammar-to-Lisp Details [[#Grammar_002dto_002dLisp-Details-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Grammar_002dto_002dLisp-Details-1
:CLASS: section
:END:
For the bovinator, lexical token matching patterns are /inlined/. When
the grammar-to-lisp converter encounters a lexical token declaration of
the form:

#+begin_src example-preformatted
%token <type> token-name match-value
#+end_src

It substitutes every occurrences of =token-name= in rules, by its
expanded form:

#+begin_src example-preformatted
type match-value
#+end_src

For example:

#+begin_src example-preformatted
%token <symbol> MOOSE "moose"

find_a_moose: MOOSE
            ;
#+end_src

Will generate this pseudo equivalent-rule:

#+begin_src example-preformatted
find_a_moose: symbol "moose"   ;; invalid syntax!
            ;
#+end_src

Thus, from the bovinator point of view, the =components= part of a rule
is made up of symbols and strings. A string in the mix means that the
previous symbol must have the additional constraint of exactly matching
it, as described in
[[#How-Lexical-Tokens-Match][How Lexical Tokens Match]].

- *Please Note:* :: For the bovinator, this task was mixed into the
  language definition to simplify implementation, though Bison's
  technique is more efficient.

--------------

<<Order-of-components-in-rules>>

Previous: [[#Grammar_002dto_002dLisp-Details][Grammar-to-Lisp Details]],
Up: [[#Bovine-Grammar-Rules][Bovine Grammar Rules]]  
[[[#SEC_Contents][Contents]]]

*** 2.3 Order of components in rules [[#Order-of-components-in-rules-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Order-of-components-in-rules-1
:CLASS: section
:END:
If a rule has multiple components, order is important, for example

#+begin_src example-preformatted
headerfile : symbol PERIOD symbol
           | symbol
           ;
#+end_src

would match ‘=foo.h=' or the C++ header ‘=foo='. The bovine parser will
first attempt to match the long form, and then the short form. If they
were in reverse order, then the long form would never be tested.

--------------

<<Optional-Lambda-Expression>>

Next: [[#Bovine-Examples][Examples]], Previous:
[[#Bovine-Grammar-Rules][Bovine Grammar Rules]], Up:
[[#Top][Bovine parser development]]   [[[#SEC_Contents][Contents]]]

** 3 Optional Lambda Expressions [[#Optional-Lambda-Expressions][¶]]
:PROPERTIES:
:CUSTOM_ID: Optional-Lambda-Expressions
:CLASS: chapter
:END:
The OLE (/Optional Lambda Expression/) is converted into a bovine
lambda. This lambda has special short-cuts to simplify reading the
semantic action definition. An OLE like this:

#+begin_src example-preformatted
( $1 )
#+end_src

results in a lambda return which consists entirely of the string or
object found by matching the first (zeroth) element of match. An OLE
like this:

#+begin_src example-preformatted
( ,(foo $1) )
#+end_src

executes =foo= on the first argument, and then splices its return into
the return list whereas:

#+begin_src example-preformatted
( (foo $1) )
#+end_src

executes =foo=, and that is placed in the return list.

Here are other things that can appear inline:

- =$1= :: The first object matched.

- =,$1= :: The first object spliced into the list (assuming it is a list
  from a non-terminal).

- ='$1= :: The first object matched, placed in a list. I.e., =( $1 )=.

- =foo= :: The symbol =foo= (exactly as displayed).

- =(foo)= :: A function call to foo which is stuck into the return list.

- =,(foo)= :: A function call to foo which is spliced into the return
  list.

- ='(foo)= :: A function call to foo which is stuck into the return list
  in a list.

- =(EXPAND ==$1== ==nonterminal== ==depth==)= :: A list starting with
  =EXPAND= performs a recursive parse on the token passed to it
  (represented by ‘=$1=' above.) The /semantic list/ is a common token
  to expand, as there are often interesting things in the list. The
  =nonterminal= is a symbol in your table which the bovinator will start
  with when parsing. =nonterminal='s definition is the same as any other
  nonterminal. =depth= should be at least ‘=1=' when descending into a
  semantic list.

- =(EXPANDFULL ==$1== ==nonterminal== ==depth==)= :: Is like =EXPAND=,
  except that the parser will iterate over =nonterminal= until there are
  no more matches. (The same way the parser iterates over the starting
  rule (see [[#Starting-Rules][Starting Rules]]). This lets you have
  much simpler rules in this specific case, and also lets you have
  positional information in the returned tokens, and error skipping.

- =(ASSOC ==symbol1== ==value1== ==symbol2== ==value2== …)= :: This is
  used for creating an association list. Each =symbol= is included in
  the list if the associated =value= is non-=nil=. While the items are
  all listed explicitly, the created structure is an association list of
  the form:

  #+begin_src example-preformatted
  ((symbol1 . value1) (symbol2 . value2) ...)
  #+end_src

- =(TAG ==name== ==class== [==attributes==])= :: This creates one tag in
  the current buffer.

  - =name= :: Is a string that represents the tag in the language.

  - =class= :: Is the kind of tag being create, such as =function=, or
    =variable=, though any symbol will work.

  - =attributes= :: Is an optional set of labeled values such as
    =:constant-flag t :parent "parenttype"=.

- =(TAG-VARIABLE ==name== ==type== ==default-value== [==attributes==])=\\
  =(TAG-FUNCTION ==name== ==type== ==arg-list== [==attributes==])=\\
  =(TAG-TYPE ==name== ==type== ==members== ==parents== [==attributes==])=\\
  =(TAG-INCLUDE ==name== ==system-flag== [==attributes==])=\\
  =(TAG-PACKAGE ==name== ==detail== [==attributes==])=\\
  =(TAG-CODE ==name== ==detail== [==attributes==])= :: Create a tag with
  =name= of respectively the class =variable=, =function=, =type=,
  =include=, =package=, and =code=.

If the symbol =%quotemode backquote= is specified, then use =,@= to
splice a list in, and =,= to evaluate the expression. This lets you send
=$1= as a symbol into a list instead of having it expanded inline.

--------------

<<Bovine-Examples>>

Next:
[[#GNU-Free-Documentation-License][GNU Free Documentation License]],
Previous: [[#Optional-Lambda-Expression][Optional Lambda Expressions]],
Up: [[#Top][Bovine parser development]]   [[[#SEC_Contents][Contents]]]

** 4 Examples [[#Examples][¶]]
:PROPERTIES:
:CUSTOM_ID: Examples
:CLASS: chapter
:END:
The rule:

#+begin_src example-preformatted
any-symbol: symbol
          ;
#+end_src

is equivalent to

#+begin_src example-preformatted
any-symbol: symbol
            ( $1 )
          ;
#+end_src

which, if it matched the string ‘="A"=', would return

#+begin_src example-preformatted
( "A" )
#+end_src

If this rule were used like this:

#+begin_src example-preformatted
%token <punctuation> EQUAL "="
...
assign: any-symbol EQUAL any-symbol
        ( $1 $3 )
      ;
#+end_src

it would match ‘="A=B"=', and return

#+begin_src example-preformatted
( ("A") ("B") )
#+end_src

The letters ‘=A=' and ‘=B=' come back in lists because ‘=any-symbol=' is
a nonterminal, not an actual lexical element.

To get a better result with nonterminals, use , to splice lists in like
this:

#+begin_src example-preformatted
%token <punctuation> EQUAL "="
...
assign: any-symbol EQUAL any-symbol
        ( ,$1 ,$3 )
      ;
#+end_src

which would return

#+begin_src example-preformatted
( "A" "B" )
#+end_src

--------------

<<GNU-Free-Documentation-License>>

Previous: [[#Bovine-Examples][Examples]], Up:
[[#Top][Bovine parser development]]   [[[#SEC_Contents][Contents]]]

** Appendix A GNU Free Documentation License [[#GNU-Free-Documentation-License-1][¶]]
:PROPERTIES:
:CUSTOM_ID: GNU-Free-Documentation-License-1
:CLASS: appendix
:END:

#+begin_center
Version 1.3, 3 November 2008
#+end_center

#+begin_src display-preformatted
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
https://fsf.org/

Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed.
#+end_src

0. [@0] PREAMBLE

   The purpose of this License is to make a manual, textbook, or other
   functional and useful document /free/ in the sense of freedom: to
   assure everyone the effective freedom to copy and redistribute it,
   with or without modifying it, either commercially or noncommercially.
   Secondarily, this License preserves for the author and publisher a
   way to get credit for their work, while not being considered
   responsible for modifications made by others.

   This License is a kind of “copyleft”, which means that derivative
   works of the document must themselves be free in the same sense. It
   complements the GNU General Public License, which is a copyleft
   license designed for free software.

   We have designed this License in order to use it for manuals for free
   software, because free software needs free documentation: a free
   program should come with manuals providing the same freedoms that the
   software does. But this License is not limited to software manuals;
   it can be used for any textual work, regardless of subject matter or
   whether it is published as a printed book. We recommend this License
   principally for works whose purpose is instruction or reference.

1. APPLICABILITY AND DEFINITIONS

   This License applies to any manual or other work, in any medium, that
   contains a notice placed by the copyright holder saying it can be
   distributed under the terms of this License. Such a notice grants a
   world-wide, royalty-free license, unlimited in duration, to use that
   work under the conditions stated herein. The “Document”, below,
   refers to any such manual or work. Any member of the public is a
   licensee, and is addressed as “you”. You accept the license if you
   copy, modify or distribute the work in a way requiring permission
   under copyright law.

   A “Modified Version” of the Document means any work containing the
   Document or a portion of it, either copied verbatim, or with
   modifications and/or translated into another language.

   A “Secondary Section” is a named appendix or a front-matter section
   of the Document that deals exclusively with the relationship of the
   publishers or authors of the Document to the Document's overall
   subject (or to related matters) and contains nothing that could fall
   directly within that overall subject. (Thus, if the Document is in
   part a textbook of mathematics, a Secondary Section may not explain
   any mathematics.) The relationship could be a matter of historical
   connection with the subject or with related matters, or of legal,
   commercial, philosophical, ethical or political position regarding
   them.

   The “Invariant Sections” are certain Secondary Sections whose titles
   are designated, as being those of Invariant Sections, in the notice
   that says that the Document is released under this License. If a
   section does not fit the above definition of Secondary then it is not
   allowed to be designated as Invariant. The Document may contain zero
   Invariant Sections. If the Document does not identify any Invariant
   Sections then there are none.

   The “Cover Texts” are certain short passages of text that are listed,
   as Front-Cover Texts or Back-Cover Texts, in the notice that says
   that the Document is released under this License. A Front-Cover Text
   may be at most 5 words, and a Back-Cover Text may be at most 25
   words.

   A “Transparent” copy of the Document means a machine-readable copy,
   represented in a format whose specification is available to the
   general public, that is suitable for revising the document
   straightforwardly with generic text editors or (for images composed
   of pixels) generic paint programs or (for drawings) some widely
   available drawing editor, and that is suitable for input to text
   formatters or for automatic translation to a variety of formats
   suitable for input to text formatters. A copy made in an otherwise
   Transparent file format whose markup, or absence of markup, has been
   arranged to thwart or discourage subsequent modification by readers
   is not Transparent. An image format is not Transparent if used for
   any substantial amount of text. A copy that is not “Transparent” is
   called “Opaque”.

   Examples of suitable formats for Transparent copies include plain
   ASCII without markup, Texinfo input format, LaTeX input format, SGML
   or XML using a publicly available DTD, and standard-conforming simple
   HTML, PostScript or PDF designed for human modification. Examples of
   transparent image formats include PNG, XCF and JPG. Opaque formats
   include proprietary formats that can be read and edited only by
   proprietary word processors, SGML or XML for which the DTD and/or
   processing tools are not generally available, and the
   machine-generated HTML, PostScript or PDF produced by some word
   processors for output purposes only.

   The “Title Page” means, for a printed book, the title page itself,
   plus such following pages as are needed to hold, legibly, the
   material this License requires to appear in the title page. For works
   in formats which do not have any title page as such, “Title Page”
   means the text near the most prominent appearance of the work's
   title, preceding the beginning of the body of the text.

   The “publisher” means any person or entity that distributes copies of
   the Document to the public.

   A section “Entitled XYZ” means a named subunit of the Document whose
   title either is precisely XYZ or contains XYZ in parentheses
   following text that translates XYZ in another language. (Here XYZ
   stands for a specific section name mentioned below, such as
   “Acknowledgements”, “Dedications”, “Endorsements”, or “History”.) To
   “Preserve the Title” of such a section when you modify the Document
   means that it remains a section “Entitled XYZ” according to this
   definition.

   The Document may include Warranty Disclaimers next to the notice
   which states that this License applies to the Document. These
   Warranty Disclaimers are considered to be included by reference in
   this License, but only as regards disclaiming warranties: any other
   implication that these Warranty Disclaimers may have is void and has
   no effect on the meaning of this License.

2. VERBATIM COPYING

   You may copy and distribute the Document in any medium, either
   commercially or noncommercially, provided that this License, the
   copyright notices, and the license notice saying this License applies
   to the Document are reproduced in all copies, and that you add no
   other conditions whatsoever to those of this License. You may not use
   technical measures to obstruct or control the reading or further
   copying of the copies you make or distribute. However, you may accept
   compensation in exchange for copies. If you distribute a large enough
   number of copies you must also follow the conditions in section 3.

   You may also lend copies, under the same conditions stated above, and
   you may publicly display copies.

3. COPYING IN QUANTITY

   If you publish printed copies (or copies in media that commonly have
   printed covers) of the Document, numbering more than 100, and the
   Document's license notice requires Cover Texts, you must enclose the
   copies in covers that carry, clearly and legibly, all these Cover
   Texts: Front-Cover Texts on the front cover, and Back-Cover Texts on
   the back cover. Both covers must also clearly and legibly identify
   you as the publisher of these copies. The front cover must present
   the full title with all words of the title equally prominent and
   visible. You may add other material on the covers in addition.
   Copying with changes limited to the covers, as long as they preserve
   the title of the Document and satisfy these conditions, can be
   treated as verbatim copying in other respects.

   If the required texts for either cover are too voluminous to fit
   legibly, you should put the first ones listed (as many as fit
   reasonably) on the actual cover, and continue the rest onto adjacent
   pages.

   If you publish or distribute Opaque copies of the Document numbering
   more than 100, you must either include a machine-readable Transparent
   copy along with each Opaque copy, or state in or with each Opaque
   copy a computer-network location from which the general network-using
   public has access to download using public-standard network protocols
   a complete Transparent copy of the Document, free of added material.
   If you use the latter option, you must take reasonably prudent steps,
   when you begin distribution of Opaque copies in quantity, to ensure
   that this Transparent copy will remain thus accessible at the stated
   location until at least one year after the last time you distribute
   an Opaque copy (directly or through your agents or retailers) of that
   edition to the public.

   It is requested, but not required, that you contact the authors of
   the Document well before redistributing any large number of copies,
   to give them a chance to provide you with an updated version of the
   Document.

4. MODIFICATIONS

   You may copy and distribute a Modified Version of the Document under
   the conditions of sections 2 and 3 above, provided that you release
   the Modified Version under precisely this License, with the Modified
   Version filling the role of the Document, thus licensing distribution
   and modification of the Modified Version to whoever possesses a copy
   of it. In addition, you must do these things in the Modified Version:

   1. Use in the Title Page (and on the covers, if any) a title distinct
      from that of the Document, and from those of previous versions
      (which should, if there were any, be listed in the History section
      of the Document). You may use the same title as a previous version
      if the original publisher of that version gives permission.
   2. List on the Title Page, as authors, one or more persons or
      entities responsible for authorship of the modifications in the
      Modified Version, together with at least five of the principal
      authors of the Document (all of its principal authors, if it has
      fewer than five), unless they release you from this requirement.
   3. State on the Title page the name of the publisher of the Modified
      Version, as the publisher.
   4. Preserve all the copyright notices of the Document.
   5. Add an appropriate copyright notice for your modifications
      adjacent to the other copyright notices.
   6. Include, immediately after the copyright notices, a license notice
      giving the public permission to use the Modified Version under the
      terms of this License, in the form shown in the Addendum below.
   7. Preserve in that license notice the full lists of Invariant
      Sections and required Cover Texts given in the Document's license
      notice.
   8. Include an unaltered copy of this License.
   9. Preserve the section Entitled “History”, Preserve its Title, and
      add to it an item stating at least the title, year, new authors,
      and publisher of the Modified Version as given on the Title Page.
      If there is no section Entitled “History” in the Document, create
      one stating the title, year, authors, and publisher of the
      Document as given on its Title Page, then add an item describing
      the Modified Version as stated in the previous sentence.
   10. Preserve the network location, if any, given in the Document for
       public access to a Transparent copy of the Document, and likewise
       the network locations given in the Document for previous versions
       it was based on. These may be placed in the “History” section.
       You may omit a network location for a work that was published at
       least four years before the Document itself, or if the original
       publisher of the version it refers to gives permission.
   11. For any section Entitled “Acknowledgements” or “Dedications”,
       Preserve the Title of the section, and preserve in the section
       all the substance and tone of each of the contributor
       acknowledgements and/or dedications given therein.
   12. Preserve all the Invariant Sections of the Document, unaltered in
       their text and in their titles. Section numbers or the equivalent
       are not considered part of the section titles.
   13. Delete any section Entitled “Endorsements”. Such a section may
       not be included in the Modified Version.
   14. Do not retitle any existing section to be Entitled “Endorsements”
       or to conflict in title with any Invariant Section.
   15. Preserve any Warranty Disclaimers.

   If the Modified Version includes new front-matter sections or
   appendices that qualify as Secondary Sections and contain no material
   copied from the Document, you may at your option designate some or
   all of these sections as invariant. To do this, add their titles to
   the list of Invariant Sections in the Modified Version's license
   notice. These titles must be distinct from any other section titles.

   You may add a section Entitled “Endorsements”, provided it contains
   nothing but endorsements of your Modified Version by various
   parties---for example, statements of peer review or that the text has
   been approved by an organization as the authoritative definition of a
   standard.

   You may add a passage of up to five words as a Front-Cover Text, and
   a passage of up to 25 words as a Back-Cover Text, to the end of the
   list of Cover Texts in the Modified Version. Only one passage of
   Front-Cover Text and one of Back-Cover Text may be added by (or
   through arrangements made by) any one entity. If the Document already
   includes a cover text for the same cover, previously added by you or
   by arrangement made by the same entity you are acting on behalf of,
   you may not add another; but you may replace the old one, on explicit
   permission from the previous publisher that added the old one.

   The author(s) and publisher(s) of the Document do not by this License
   give permission to use their names for publicity for or to assert or
   imply endorsement of any Modified Version.

5. COMBINING DOCUMENTS

   You may combine the Document with other documents released under this
   License, under the terms defined in section 4 above for modified
   versions, provided that you include in the combination all of the
   Invariant Sections of all of the original documents, unmodified, and
   list them all as Invariant Sections of your combined work in its
   license notice, and that you preserve all their Warranty Disclaimers.

   The combined work need only contain one copy of this License, and
   multiple identical Invariant Sections may be replaced with a single
   copy. If there are multiple Invariant Sections with the same name but
   different contents, make the title of each such section unique by
   adding at the end of it, in parentheses, the name of the original
   author or publisher of that section if known, or else a unique
   number. Make the same adjustment to the section titles in the list of
   Invariant Sections in the license notice of the combined work.

   In the combination, you must combine any sections Entitled “History”
   in the various original documents, forming one section Entitled
   “History”; likewise combine any sections Entitled “Acknowledgements”,
   and any sections Entitled “Dedications”. You must delete all sections
   Entitled “Endorsements.”

6. COLLECTIONS OF DOCUMENTS

   You may make a collection consisting of the Document and other
   documents released under this License, and replace the individual
   copies of this License in the various documents with a single copy
   that is included in the collection, provided that you follow the
   rules of this License for verbatim copying of each of the documents
   in all other respects.

   You may extract a single document from such a collection, and
   distribute it individually under this License, provided you insert a
   copy of this License into the extracted document, and follow this
   License in all other respects regarding verbatim copying of that
   document.

7. AGGREGATION WITH INDEPENDENT WORKS

   A compilation of the Document or its derivatives with other separate
   and independent documents or works, in or on a volume of a storage or
   distribution medium, is called an “aggregate” if the copyright
   resulting from the compilation is not used to limit the legal rights
   of the compilation's users beyond what the individual works permit.
   When the Document is included in an aggregate, this License does not
   apply to the other works in the aggregate which are not themselves
   derivative works of the Document.

   If the Cover Text requirement of section 3 is applicable to these
   copies of the Document, then if the Document is less than one half of
   the entire aggregate, the Document's Cover Texts may be placed on
   covers that bracket the Document within the aggregate, or the
   electronic equivalent of covers if the Document is in electronic
   form. Otherwise they must appear on printed covers that bracket the
   whole aggregate.

8. TRANSLATION

   Translation is considered a kind of modification, so you may
   distribute translations of the Document under the terms of section 4.
   Replacing Invariant Sections with translations requires special
   permission from their copyright holders, but you may include
   translations of some or all Invariant Sections in addition to the
   original versions of these Invariant Sections. You may include a
   translation of this License, and all the license notices in the
   Document, and any Warranty Disclaimers, provided that you also
   include the original English version of this License and the original
   versions of those notices and disclaimers. In case of a disagreement
   between the translation and the original version of this License or a
   notice or disclaimer, the original version will prevail.

   If a section in the Document is Entitled “Acknowledgements”,
   “Dedications”, or “History”, the requirement (section 4) to Preserve
   its Title (section 1) will typically require changing the actual
   title.

9. TERMINATION

   You may not copy, modify, sublicense, or distribute the Document
   except as expressly provided under this License. Any attempt
   otherwise to copy, modify, sublicense, or distribute it is void, and
   will automatically terminate your rights under this License.

   However, if you cease all violation of this License, then your
   license from a particular copyright holder is reinstated (a)
   provisionally, unless and until the copyright holder explicitly and
   finally terminates your license, and (b) permanently, if the
   copyright holder fails to notify you of the violation by some
   reasonable means prior to 60 days after the cessation.

   Moreover, your license from a particular copyright holder is
   reinstated permanently if the copyright holder notifies you of the
   violation by some reasonable means, this is the first time you have
   received notice of violation of this License (for any work) from that
   copyright holder, and you cure the violation prior to 30 days after
   your receipt of the notice.

   Termination of your rights under this section does not terminate the
   licenses of parties who have received copies or rights from you under
   this License. If your rights have been terminated and not permanently
   reinstated, receipt of a copy of some or all of the same material
   does not give you any rights to use it.

10. FUTURE REVISIONS OF THIS LICENSE

    The Free Software Foundation may publish new, revised versions of
    the GNU Free Documentation License from time to time. Such new
    versions will be similar in spirit to the present version, but may
    differ in detail to address new problems or concerns. See
    [[https://www.gnu.org/licenses/]].

    Each version of the License is given a distinguishing version
    number. If the Document specifies that a particular numbered version
    of this License “or any later version” applies to it, you have the
    option of following the terms and conditions either of that
    specified version or of any later version that has been published
    (not as a draft) by the Free Software Foundation. If the Document
    does not specify a version number of this License, you may choose
    any version ever published (not as a draft) by the Free Software
    Foundation. If the Document specifies that a proxy can decide which
    future versions of this License can be used, that proxy's public
    statement of acceptance of a version permanently authorizes you to
    choose that version for the Document.

11. RELICENSING

    “Massive Multiauthor Collaboration Site” (or “MMC Site”) means any
    World Wide Web server that publishes copyrightable works and also
    provides prominent facilities for anybody to edit those works. A
    public wiki that anybody can edit is an example of such a server. A
    “Massive Multiauthor Collaboration” (or “MMC”) contained in the site
    means any set of copyrightable works thus published on the MMC site.

    “CC-BY-SA” means the Creative Commons Attribution-Share Alike 3.0
    license published by Creative Commons Corporation, a not-for-profit
    corporation with a principal place of business in San Francisco,
    California, as well as future copyleft versions of that license
    published by that same organization.

    “Incorporate” means to publish or republish a Document, in whole or
    in part, as part of another Document.

    An MMC is “eligible for relicensing” if it is licensed under this
    License, and if all works that were first published under this
    License somewhere other than this MMC, and subsequently incorporated
    in whole or in part into the MMC, (1) had no cover texts or
    invariant sections, and (2) were thus incorporated prior to November
    1, 2008.

    The operator of an MMC Site may republish an MMC contained in the
    site under CC-BY-SA on the same site at any time before August 1,
    2009, provided the MMC is eligible for relicensing.

*** ADDENDUM: How to use this License for your documents [[#ADDENDUM_003a-How-to-use-this-License-for-your-documents][¶]]
:PROPERTIES:
:CUSTOM_ID: ADDENDUM_003a-How-to-use-this-License-for-your-documents
:CLASS: heading
:END:
To use this License in a document you have written, include a copy of
the License in the document and put the following copyright and license
notices just after the title page:

#+begin_src example-preformatted
  Copyright (C)  year  your name.
  Permission is granted to copy, distribute and/or modify this document
  under the terms of the GNU Free Documentation License, Version 1.3
  or any later version published by the Free Software Foundation;
  with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
  Texts.  A copy of the license is included in the section entitled ``GNU
  Free Documentation License''.
#+end_src

If you have Invariant Sections, Front-Cover Texts and Back-Cover Texts,
replace the “with...Texts.” line with this:

#+begin_src example-preformatted
    with the Invariant Sections being list their titles, with
    the Front-Cover Texts being list, and with the Back-Cover Texts
    being list.
#+end_src

If you have Invariant Sections without Cover Texts, or some other
combination of the three, merge those two alternatives to suit the
situation.

If your document contains nontrivial examples of program code, we
recommend releasing these examples in parallel under your choice of free
software license, such as the GNU General Public License, to permit
their use in free software.
