<<Frequently-Asked-Questions>>
*** 1 Frequently Asked Questions [[#Frequently-Asked-Questions-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Frequently-Asked-Questions-1
:CLASS: section
:END:
**** Abstract [[#Abstract][¶]]
:PROPERTIES:
:CUSTOM_ID: Abstract
:CLASS: subheading
:END:
This is the new Gnus Frequently Asked Questions list.

Please submit features and suggestions to the
[[mailto:ding@gnus.org][ding list]].

- [[#FAQ-_002d-Introduction][Introduction]]
- [[#FAQ-1-_002d-Installation-FAQ][Installation FAQ]]
- [[#FAQ-2-_002d-Startup-_002f-Group-buffer][Startup / Group buffer]]
- [[#FAQ-3-_002d-Getting-Messages][Getting Messages]]
- [[#FAQ-4-_002d-Reading-messages][Reading messages]]
- [[#FAQ-5-_002d-Composing-messages][Composing messages]]
- [[#FAQ-6-_002d-Old-messages][Old messages]]
- [[#FAQ-7-_002d-Gnus-in-a-dial_002dup-environment][Gnus in a dial-up environment]]
- [[#FAQ-8-_002d-Getting-help][Getting help]]
- [[#FAQ-9-_002d-Tuning-Gnus][Tuning Gnus]]
- [[#FAQ-_002d-Glossary][Glossary]]

--------------

<<FAQ-_002d-Introduction>>

Next: [[#FAQ-1-_002d-Installation-FAQ][Installation FAQ]], Up:
[[#Frequently-Asked-Questions][Frequently Asked Questions]]  

**** 1.1 Introduction [[#Introduction][¶]]
:PROPERTIES:
:CUSTOM_ID: Introduction
:CLASS: subsection
:END:
This is the Gnus Frequently Asked Questions list.

Gnus is a Usenet Newsreader and Electronic Mail User Agent implemented
as a part of Emacs. It's been around in some form since the early 1990s,
and has been distributed as a standard part of Emacs for much of that
time. Gnus 5 is the latest (and greatest) incarnation. The original
version was called GNUS, and was written by Masanobu UMEDA. When autumn
crept up in 1994, Lars Magne Ingebrigtsen grew bored and decided to
rewrite Gnus.

Its biggest strength is the fact that it is extremely customizable. It
is somewhat intimidating at first glance, but most of the complexity can
be ignored until you're ready to take advantage of it. If you receive a
reasonable volume of e-mail (you're on various mailing lists), or you
would like to read high-volume mailing lists but cannot keep up with
them, or read high volume newsgroups or are just bored, then Gnus is
what you want.

This FAQ was maintained by Justin Sheehy until March 2002. He would like
to thank Steve Baur and Per Abrahamsen for doing a wonderful job with
this FAQ before him. We would like to do the same: thanks, Justin!

The information contained here was compiled with the assistance of the
Gnus development mailing list, and any errors or misprints are the Gnus
team's fault, sorry.

--------------

<<FAQ-1-_002d-Installation-FAQ>>

Next:
[[#FAQ-2-_002d-Startup-_002f-Group-buffer][Startup / Group buffer]],
Previous: [[#FAQ-_002d-Introduction][Introduction]], Up:
[[#Frequently-Asked-Questions][Frequently Asked Questions]]  

**** 1.2 Installation FAQ [[#Installation-FAQ][¶]]
:PROPERTIES:
:CUSTOM_ID: Installation-FAQ
:CLASS: subsection
:END:

--------------

**** Question 1.1 [[#Question-1_002e1][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-1_002e1
:CLASS: subsubheading
:END:
What is the latest version of Gnus and where can I find it?

**** Answer [[#Answer][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer
:CLASS: subsubheading
:END:
The latest version of Gnus is bundled with Emacs.

--------------

**** Question 1.2 [[#Question-1_002e2][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-1_002e2
:CLASS: subsubheading
:END:
I sometimes read references to No Gnus and Oort Gnus, what are those?

**** Answer [[#Answer-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-1
:CLASS: subsubheading
:END:
Oort Gnus was the name of the development version of Gnus, which became
Gnus 5.10 in autumn 2003. No Gnus was the name of the development
version that became Gnus 5.12.

--------------

<<FAQ-2-_002d-Startup-_002f-Group-buffer>>

Next: [[#FAQ-3-_002d-Getting-Messages][Getting Messages]], Previous:
[[#FAQ-1-_002d-Installation-FAQ][Installation FAQ]], Up:
[[#Frequently-Asked-Questions][Frequently Asked Questions]]  

**** 1.3 Startup / Group buffer [[#Startup-_002f-Group-buffer][¶]]
:PROPERTIES:
:CUSTOM_ID: Startup-_002f-Group-buffer
:CLASS: subsection
:END:

--------------

**** Question 2.1 [[#Question-2_002e1][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-2_002e1
:CLASS: subsubheading
:END:
Every time I start Gnus I get a message "Gnus auto-save file exists. Do
you want to read it?", what does this mean and how to prevent it?

**** Answer [[#Answer-2][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-2
:CLASS: subsubheading
:END:
This message means that the last time you used Gnus, it wasn't properly
exited and therefore couldn't write its information to disk (e.g., which
messages you read), you are now asked if you want to restore that
information from the auto-save file.

To prevent this message make sure you exit Gnus via q in group buffer
instead of just killing Emacs.

--------------

**** Question 2.2 [[#Question-2_002e2][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-2_002e2
:CLASS: subsubheading
:END:
Gnus doesn't remember which groups I'm subscribed to, what's this?

**** Answer [[#Answer-3][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-3
:CLASS: subsubheading
:END:
You get the message described in the q/a pair above while starting Gnus,
right? It's another symptom for the same problem, so read the answer
above.

--------------

**** Question 2.3 [[#Question-2_002e3][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-2_002e3
:CLASS: subsubheading
:END:
How to change the format of the lines in Group buffer?

**** Answer [[#Answer-4][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-4
:CLASS: subsubheading
:END:
You've got to tweak the value of the variable gnus-group-line-format.
See the manual node "Group Line Specification" for information on how to
do this. An example for this (guess from whose .gnus :-)):

#+begin_src example-preformatted
(setq gnus-group-line-format "%P%M%S[%5t]%5y : %(%g%)\n")
#+end_src

--------------

**** Question 2.4 [[#Question-2_002e4][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-2_002e4
:CLASS: subsubheading
:END:
My group buffer is a bit crowded. Is there a way to sort groups into
categories so I can browse them more easily?

**** Answer [[#Answer-5][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-5
:CLASS: subsubheading
:END:
Gnus offers the topic mode, it allows you to sort your groups in, well,
topics. For example, all groups dealing with Linux under the topic
‘=linux=', all dealing with music under the topic ‘=music=' and all
dealing with Scottish music under the topic ‘=scottish=' which is a
subtopic of ‘=music='.

To enter topic mode, just hit t while in Group buffer. Now you can use T
n to create a topic at point and T m to move a group to a specific
topic. For more commands see the manual or the menu. You might want to
include the ‘=%P=' specifier at the beginning of your
=gnus-group-line-format= variable to have the groups nicely indented.

--------------

**** Question 2.5 [[#Question-2_002e5][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-2_002e5
:CLASS: subsubheading
:END:
How to manually sort the groups in Group buffer? How to sort the groups
in a topic?

**** Answer [[#Answer-6][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-6
:CLASS: subsubheading
:END:
Move point over the group you want to move and hit C-k, now move point
to the place where you want the group to be and hit C-y.

--------------

<<FAQ-3-_002d-Getting-Messages>>

Next: [[#FAQ-4-_002d-Reading-messages][Reading messages]], Previous:
[[#FAQ-2-_002d-Startup-_002f-Group-buffer][Startup / Group buffer]], Up:
[[#Frequently-Asked-Questions][Frequently Asked Questions]]  

**** 1.4 Getting Messages [[#Getting-Messages][¶]]
:PROPERTIES:
:CUSTOM_ID: Getting-Messages
:CLASS: subsection
:END:

--------------

**** Question 3.1 [[#Question-3_002e1][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-3_002e1
:CLASS: subsubheading
:END:
I just installed Gnus, started it via M-x gnus but it only says "nntp
(news) open error", what to do?

**** Answer [[#Answer-7][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-7
:CLASS: subsubheading
:END:
You've got to tell Gnus where to fetch the news from. Read the
documentation for information on how to do this. As a first start, put
those lines in =~/.gnus.el=:

#+begin_src example-preformatted
(setq gnus-select-method '(nntp "news.yourprovider.net"))
(setq user-mail-address "you@yourprovider.net")
(setq user-full-name "Your Name")
#+end_src

--------------

**** Question 3.2 [[#Question-3_002e2][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-3_002e2
:CLASS: subsubheading
:END:
I'm working under Windows and have no idea what =~/.gnus.el= means.

**** Answer [[#Answer-8][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-8
:CLASS: subsubheading
:END:
The ~/ means the home directory where Gnus and Emacs look for the
configuration files. However, you don't really need to know what this
means, it suffices that Emacs knows what it means :-) You can type C-x
C-f ~/.gnus.el RET (yes, with the forward slash, even on Windows), and
Emacs will open the right file for you. (It will most likely be new, and
thus empty.) However, I'd discourage you from doing so, since the
directory Emacs chooses will most certainly not be what you want, so
let's do it the correct way. The first thing you've got to do is to
create a suitable directory (no blanks in names please), e.g.,
c:\myhome. Then you must set the environment variable HOME to this
directory. To do this under Windows 9x or Me include the line

#+begin_src example-preformatted
SET HOME=C:\myhome
#+end_src

in your autoexec.bat and reboot. Under NT, 2000 and XP, hit
Winkey+Pause/Break to enter system options (if it doesn't work, go to
Control Panel -> System -> Advanced). There you'll find the possibility
to set environment variables. Create a new one with name HOME and value
C:\myhome. Rebooting is not necessary.

Now to create =~/.gnus.el=, say C-x C-f ~/.gnus.el RET C-x C-s. in
Emacs.

--------------

**** Question 3.3 [[#Question-3_002e3][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-3_002e3
:CLASS: subsubheading
:END:
My news server requires authentication, how to store user name and
password on disk?

**** Answer [[#Answer-9][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-9
:CLASS: subsubheading
:END:
Create a file ~/.authinfo which includes for each server a line like
this

#+begin_src example-preformatted
machine news.yourprovider.net login YourUserName password YourPassword
#+end_src

. Make sure that the file isn't readable to others if you work on an OS
which is capable of doing so. (Under Unix say

#+begin_src example-preformatted
chmod 600 ~/.authinfo
#+end_src

in a shell.)

--------------

**** Question 3.4 [[#Question-3_002e4][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-3_002e4
:CLASS: subsubheading
:END:
Gnus seems to start up OK, but I can't find out how to subscribe to a
group.

**** Answer [[#Answer-10][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-10
:CLASS: subsubheading
:END:
If you know the name of the group say U name.of.group RET in group
buffer (use the tab-completion Luke). Otherwise hit ^ in group buffer,
this brings you to the server buffer. Now place point (the cursor) over
the server which carries the group you want, hit RET, move point to the
group you want to subscribe to and say u to subscribe to it.

--------------

**** Question 3.5 [[#Question-3_002e5][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-3_002e5
:CLASS: subsubheading
:END:
Gnus doesn't show all groups / Gnus says I'm not allowed to post on this
server as well as I am, what's that?

**** Answer [[#Answer-11][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-11
:CLASS: subsubheading
:END:
Some providers allow restricted anonymous access and full access only
after authorization. To make Gnus send authinfo to those servers append

#+begin_src example-preformatted
force yes
#+end_src

to the line for those servers in ~/.authinfo.

--------------

**** Question 3.6 [[#Question-3_002e6][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-3_002e6
:CLASS: subsubheading
:END:
I want Gnus to fetch news from several servers, is this possible?

**** Answer [[#Answer-12][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-12
:CLASS: subsubheading
:END:
Of course. You can specify more sources for articles in the variable
gnus-secondary-select-methods. Add something like this in =~/.gnus.el=:

#+begin_src example-preformatted
(add-to-list 'gnus-secondary-select-methods
             '(nntp "news.yourSecondProvider.net"))
(add-to-list 'gnus-secondary-select-methods
             '(nntp "news.yourThirdProvider.net"))
#+end_src

--------------

**** Question 3.7 [[#Question-3_002e7][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-3_002e7
:CLASS: subsubheading
:END:
And how about local spool files?

**** Answer [[#Answer-13][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-13
:CLASS: subsubheading
:END:
No problem, this is just one more select method called nnspool, so you
want this:

#+begin_src example-preformatted
(add-to-list 'gnus-secondary-select-methods '(nnspool ""))
#+end_src

Or this if you don't want an NNTP Server as primary news source:

#+begin_src example-preformatted
(setq gnus-select-method '(nnspool ""))
#+end_src

Gnus will look for the spool file in /usr/spool/news, if you want
something different, change the line above to something like this:

#+begin_src example-preformatted
(add-to-list 'gnus-secondary-select-methods
             '(nnspool ""
                       (nnspool-directory "/usr/local/myspoolddir")))
#+end_src

This sets the spool directory for this server only. You might have to
specify more stuff like the program used to post articles, see the Gnus
manual on how to do this.

--------------

**** Question 3.8 [[#Question-3_002e8][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-3_002e8
:CLASS: subsubheading
:END:
OK, reading news works now, but I want to be able to read my mail with
Gnus, too. How to do it?

**** Answer [[#Answer-14][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-14
:CLASS: subsubheading
:END:
That's a bit harder since there are many possible sources for mail, many
possible ways for storing mail and many different ways for sending mail.
The most common cases are these: 1: You want to read your mail from a
pop3 server and send them directly to a SMTP Server 2: Some program like
fetchmail retrieves your mail and stores it on disk from where Gnus
shall read it. Outgoing mail is sent by Sendmail, Postfix or some other
MTA. Sometimes, you even need a combination of the above cases.

However, the first thing to do is to tell Gnus in which way it should
store the mail, in Gnus terminology which back end to use. Gnus supports
many different back ends, the most commonly used one is nnml. It stores
every mail in one file and is therefore quite fast. However you might
prefer a one file per group approach if your file system has problems
with many small files, the nnfolder back end is then probably the choice
for you. To use nnml add the following to =~/.gnus.el=:

#+begin_src example-preformatted
(add-to-list 'gnus-secondary-select-methods '(nnml ""))
#+end_src

As you might have guessed, if you want nnfolder, it's

#+begin_src example-preformatted
(add-to-list 'gnus-secondary-select-methods '(nnfolder ""))
#+end_src

Now we need to tell Gnus, where to get its mail from. If it's a POP3
server, then you need something like this:

#+begin_src example-preformatted
(with-eval-after-load "mail-source"
  (add-to-list 'mail-sources '(pop :server "pop.YourProvider.net"
                                   :user "yourUserName"
                                   :password "yourPassword")))
#+end_src

Make sure =~/.gnus.el= isn't readable to others if you store your
password there. If you want to read your mail from a traditional spool
file on your local machine, it's

#+begin_src example-preformatted
(with-eval-after-load "mail-source"
  (add-to-list 'mail-sources '(file :path "/path/to/spool/file"))
#+end_src

If it's a Maildir, with one file per message as used by postfix, Qmail
and (optionally) fetchmail it's

#+begin_src example-preformatted
(with-eval-after-load "mail-source"
  (add-to-list 'mail-sources '(maildir :path "/path/to/Maildir/"
                                       :subdirs ("cur" "new")))
#+end_src

And finally if you want to read your mail from several files in one
directory, for example because procmail already split your mail, it's

#+begin_src example-preformatted
(with-eval-after-load "mail-source"
  (add-to-list 'mail-sources
               '(directory :path "/path/to/procmail-dir/"
                           :suffix ".prcml")))
#+end_src

Where :suffix ".prcml" tells Gnus only to use files with the suffix
.prcml.

OK, now you only need to tell Gnus how to send mail. If you want to send
mail via sendmail (or whichever MTA is playing the role of sendmail on
your system), you don't need to do anything. However, if you want to
send your mail to an SMTP Server you need the following in your
=~/.gnus.el=

#+begin_src example-preformatted
(setq send-mail-function 'smtpmail-send-it)
(setq message-send-mail-function 'smtpmail-send-it)
(setq smtpmail-default-smtp-server "smtp.yourProvider.net")
#+end_src

--------------

**** Question 3.9 [[#Question-3_002e9][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-3_002e9
:CLASS: subsubheading
:END:
And what about IMAP?

**** Answer [[#Answer-15][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-15
:CLASS: subsubheading
:END:
There are two ways of using IMAP with Gnus. The first one is to use IMAP
like POP3, that means Gnus fetches the mail from the IMAP server and
stores it on disk. If you want to do this (you don't really want to do
this) add the following to =~/.gnus.el=

#+begin_src example-preformatted
(add-to-list 'mail-sources '(imap :server "mail.mycorp.com"
                                  :user "username"
                                  :pass "password"
                                  :stream network
                                  :authentication login
                                  :mailbox "INBOX"
                                  :fetchflag "\\Seen"))
#+end_src

You might have to tweak the values for stream and/or authentication, see
the Gnus manual node "Mail Source Specifiers" for possible values.

If you want to use IMAP the way it's intended, you've got to follow a
different approach. You've got to add the nnimap back end to your select
method and give the information about the server there.

#+begin_src example-preformatted
(add-to-list 'gnus-secondary-select-methods
             '(nnimap "Give the baby a name"
                      (nnimap-address "imap.yourProvider.net")
                      (nnimap-port 143)))
#+end_src

Again, you might have to specify how to authenticate to the server if
Gnus can't guess the correct way, see the Manual Node "IMAP" for
detailed information.

--------------

**** Question 3.10 [[#Question-3_002e10][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-3_002e10
:CLASS: subsubheading
:END:
At the office we use one of those MS Exchange servers, can I use Gnus to
read my mail from it?

**** Answer [[#Answer-16][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-16
:CLASS: subsubheading
:END:
Offer your administrator a pair of new running shoes for activating IMAP
on the server and follow the instructions above.

--------------

**** Question 3.11 [[#Question-3_002e11][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-3_002e11
:CLASS: subsubheading
:END:
Can I tell Gnus not to delete the mails on the server it retrieves via
POP3?

**** Answer [[#Answer-17][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-17
:CLASS: subsubheading
:END:
Yes, if the POP3 server supports the UIDL control (maybe almost servers
do it nowadays). To do that, add a =:leave ==value= pair to each POP3
mail source. See ‘Mail Source Specifiers', for details on =value=.

--------------

<<FAQ-4-_002d-Reading-messages>>

Next: [[#FAQ-5-_002d-Composing-messages][Composing messages]], Previous:
[[#FAQ-3-_002d-Getting-Messages][Getting Messages]], Up:
[[#Frequently-Asked-Questions][Frequently Asked Questions]]  

**** 1.5 Reading messages [[#Reading-messages][¶]]
:PROPERTIES:
:CUSTOM_ID: Reading-messages
:CLASS: subsection
:END:

--------------

**** Question 4.1 [[#Question-4_002e1][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-4_002e1
:CLASS: subsubheading
:END:
When I enter a group, all read messages are gone. How to view them
again?

**** Answer [[#Answer-18][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-18
:CLASS: subsubheading
:END:
If you enter the group by saying RET in group buffer with point over the
group, only unread and ticked messages are loaded. Say C-u RET instead
to load all available messages. If you want only the 300 newest say C-u
300 RET

Loading only unread messages can be annoying if you have threaded view
enabled, say

#+begin_src example-preformatted
(setq gnus-fetch-old-headers 'some)
#+end_src

in =~/.gnus.el= to load enough old articles to prevent teared threads,
replace 'some with =t= to load all articles (Warning: Both settings
enlarge the amount of data which is fetched when you enter a group and
slow down the process of entering a group).

You can say /o N in the summary buffer to load the last N messages.

If you don't want all old messages, but the parent of the message you're
just reading, you can say ^, if you want to retrieve the whole thread
the message you're just reading belongs to, A T is your friend.

--------------

**** Question 4.2 [[#Question-4_002e2][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-4_002e2
:CLASS: subsubheading
:END:
How to tell Gnus to show an important message every time I enter a
group, even when it's read?

**** Answer [[#Answer-19][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-19
:CLASS: subsubheading
:END:
You can tick important messages. To do this hit u while point is in
summary buffer over the message. When you want to remove the mark, hit
either d (this deletes the tick mark and set's unread mark) or M c
(which deletes all marks for the message).

--------------

**** Question 4.3 [[#Question-4_002e3][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-4_002e3
:CLASS: subsubheading
:END:
How to view the headers of a message?

**** Answer [[#Answer-20][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-20
:CLASS: subsubheading
:END:
Say t to show all headers, one more t hides them again.

--------------

**** Question 4.4 [[#Question-4_002e4][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-4_002e4
:CLASS: subsubheading
:END:
How to view the raw unformatted message?

**** Answer [[#Answer-21][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-21
:CLASS: subsubheading
:END:
Type C-u g to show the raw message g returns to normal view.

--------------

**** Question 4.5 [[#Question-4_002e5][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-4_002e5
:CLASS: subsubheading
:END:
How can I change the headers Gnus displays by default at the top of the
article buffer?

**** Answer [[#Answer-22][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-22
:CLASS: subsubheading
:END:
The variable gnus-visible-headers controls which headers are shown, its
value is a regular expression, header lines which match it are shown. So
if you want author, subject, date, and if the header exists, Followup-To
and MUA / NUA say this in =~/.gnus.el=:

#+begin_src example-preformatted
(setq gnus-visible-headers
      '("^From" "^Subject" "^Date" "^Newsgroups" "^Followup-To"
        "^User-Agent" "^X-Newsreader" "^X-Mailer"))
#+end_src

--------------

**** Question 4.6 [[#Question-4_002e6][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-4_002e6
:CLASS: subsubheading
:END:
I'd like Gnus NOT to render HTML-mails but show me the text part if it's
available. How to do it?

**** Answer [[#Answer-23][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-23
:CLASS: subsubheading
:END:
Say

#+begin_src example-preformatted
(with-eval-after-load "mm-decode"
  (add-to-list 'mm-discouraged-alternatives "text/html")
  (add-to-list 'mm-discouraged-alternatives "text/richtext"))
#+end_src

in =~/.gnus.el=. If you don't want HTML rendered, even if there's no
text alternative add

#+begin_src example-preformatted
(setq mm-automatic-display (remove "text/html" mm-automatic-display))
#+end_src

too.

--------------

**** Question 4.7 [[#Question-4_002e7][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-4_002e7
:CLASS: subsubheading
:END:
Can I use some other browser than w3m to render my HTML-mails?

**** Answer [[#Answer-24][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-24
:CLASS: subsubheading
:END:
You've got the choice between ‘=shr=', ‘=w3m=', ‘=links=', and ‘=lynx='.
Which one is used is specified in the variable =mm-text-html-renderer=,
so if you want links to render your mail, say:

#+begin_src example-preformatted
(setq mm-text-html-renderer 'links)
#+end_src

--------------

**** Question 4.8 [[#Question-4_002e8][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-4_002e8
:CLASS: subsubheading
:END:
Is there anything I can do to make poorly formatted mails more readable?

**** Answer [[#Answer-25][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-25
:CLASS: subsubheading
:END:
Gnus offers you several functions to “wash” incoming mail, you can find
them if you browse through the menu, item Article->Washing. The most
interesting ones are probably “Wrap long lines” (W w), “Decode ROT13” (W
r) and “Outlook Deuglify” which repairs the dumb quoting used by many
users of Microsoft products (W Y f gives you full deuglify. See W Y C-h
or have a look at the menus for other deuglifications).

--------------

**** Question 4.9 [[#Question-4_002e9][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-4_002e9
:CLASS: subsubheading
:END:
Is there a way to automatically ignore posts by specific authors or with
specific words in the subject? And can I highlight more interesting ones
in some way?

**** Answer [[#Answer-26][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-26
:CLASS: subsubheading
:END:
You want Scoring. Scoring means, that you define rules which assign each
message an integer value. Depending on the value the message is
highlighted in summary buffer (if it's high, say +2000) or automatically
marked read (if the value is low, say −800) or some other action
happens.

There are basically three ways of setting up rules which assign the
scoring-value to messages. The first and easiest way is to set up rules
based on the article you are just reading. Say you're reading a message
by a guy who always writes nonsense and you want to ignore his messages
in the future. Hit L, to set up a rule which lowers the score. Now Gnus
asks you which the criteria for lowering the Score shall be. Hit ? twice
to see all possibilities, we want a which means the author (the from
header). Now Gnus wants to know which kind of matching we want. Hit
either e for an exact match or s for substring-match and delete
afterwards everything but the name to score down all authors with the
given name no matter which email address is used. Now you need to tell
Gnus when to apply the rule and how long it should last, hit p to apply
the rule now and let it last forever. If you want to raise the score
instead of lowering it say I instead of L.

You can also set up rules by hand. To do this say V f in summary buffer.
Then you are asked for the name of the score file, it's
name.of.group.SCORE for rules valid in only one group or all.Score for
rules valid in all groups. See the Gnus manual for the exact syntax,
basically it's one big list whose elements are lists again. the first
element of those lists is the header to score on, then one more list
with what to match, which score to assign, when to expire the rule and
how to do the matching. If you find me very interesting, you could add
the following to your all.Score:

#+begin_src example-preformatted
(("references" ("hschmi22.userfqdn.rz-online.de" 500 nil s))
 ("message-id" ("hschmi22.userfqdn.rz-online.de" 999 nil s)))
#+end_src

This would add 999 to the score of messages written by me and 500 to the
score of messages which are a (possibly indirect) answer to a message
written by me. Of course nobody with a sane mind would do this :-)

The third alternative is adaptive scoring. This means Gnus watches you
and tries to find out what you find interesting and what annoying and
sets up rules which reflect this. Adaptive scoring can be a huge help
when reading high traffic groups. If you want to activate adaptive
scoring say

#+begin_src example-preformatted
(setq gnus-use-adaptive-scoring t)
#+end_src

in =~/.gnus.el=.

--------------

**** Question 4.10 [[#Question-4_002e10][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-4_002e10
:CLASS: subsubheading
:END:
How can I disable threading in some (e.g., mail-) groups, or set other
variables specific for some groups?

**** Answer [[#Answer-27][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-27
:CLASS: subsubheading
:END:
While in group buffer move point over the group and hit G c, this opens
a buffer where you can set options for the group. At the bottom of the
buffer you'll find an item that allows you to set variables locally for
the group. To disable threading enter gnus-show-threads as name of
variable and =nil= as value. Hit button done at the top of the buffer
when you're ready.

--------------

**** Question 4.11 [[#Question-4_002e11][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-4_002e11
:CLASS: subsubheading
:END:
Can I highlight messages written by me and follow-ups to those?

**** Answer [[#Answer-28][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-28
:CLASS: subsubheading
:END:
Stop those "Can I ..." questions, the answer is always yes in Gnus
Country :-). It's a three step process: First we make faces
(specifications of how summary-line shall look like) for those postings,
then we'll give them some special score and finally we'll tell Gnus to
use the new faces.

--------------

**** Question 4.12 [[#Question-4_002e12][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-4_002e12
:CLASS: subsubheading
:END:
The number of total messages in a group which Gnus displays in group
buffer is by far to high, especially in mail groups. Is this a bug?

**** Answer [[#Answer-29][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-29
:CLASS: subsubheading
:END:
No, that's a matter of design of Gnus, fixing this would mean
reimplementation of major parts of Gnus' back ends. Gnus thinks
“highest-article-number − lowest-article-number =
total-number-of-articles”. This works OK for Usenet groups, but if you
delete and move many messages in mail groups, this fails. To cure the
symptom, enter the group via C-u RET (this makes Gnus get all messages),
then hit M P b to mark all messages and then say B m name.of.group to
move all messages to the group they have been in before, they get new
message numbers in this process and the count is right again (until you
delete and move your mail to other groups again).

--------------

**** Question 4.13 [[#Question-4_002e13][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-4_002e13
:CLASS: subsubheading
:END:
I don't like the layout of summary and article buffer, how to change it?
Perhaps even a three pane display?

**** Answer [[#Answer-30][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-30
:CLASS: subsubheading
:END:
You can control the windows configuration by calling the function
gnus-add-configuration. The syntax is a bit complicated but explained
very well in the manual node "Window Layout". Some popular examples:

Instead 25% summary 75% article buffer 35% summary and 65% article (the
1.0 for article means "take the remaining space"):

#+begin_src example-preformatted
(gnus-add-configuration
 '(article (vertical 1.0 (summary .35 point) (article 1.0))))
#+end_src

A three pane layout, Group buffer on the left, summary buffer top-right,
article buffer bottom-right:

#+begin_src example-preformatted
(gnus-add-configuration
 '(article
   (horizontal 1.0
               (vertical 25
                         (group 1.0))
               (vertical 1.0
                         (summary 0.25 point)
                         (article 1.0)))))
(gnus-add-configuration
 '(summary
   (horizontal 1.0
               (vertical 25
                         (group 1.0))
               (vertical 1.0
                         (summary 1.0 point)))))
#+end_src

--------------

**** Question 4.14 [[#Question-4_002e14][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-4_002e14
:CLASS: subsubheading
:END:
I don't like the way the Summary buffer looks, how to tweak it?

**** Answer [[#Answer-31][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-31
:CLASS: subsubheading
:END:
You've got to play around with the variable gnus-summary-line-format.
Its value is a string of symbols which stand for things like author,
date, subject etc. A list of the available specifiers can be found in
the manual node “Summary Buffer Lines” and the often forgotten node
“Formatting Variables” and its sub-nodes. There you'll find useful
things like positioning the cursor and tabulators which allow you a
summary in table form, but sadly hard tabulators are broken in 5.8.8.

Gnus offers you some very nice new specifiers, e.g., %B which draws a
thread-tree and %&user-date which gives you a date where the details are
dependent of the articles age. Here's an example which uses both:

#+begin_src example-preformatted
(setq gnus-summary-line-format ":%U%R %B %s %-60=|%4L |%-20,20f |%&user-date; \n")
#+end_src

resulting in:

#+begin_src example-preformatted
:O     Re: [Richard Stallman] rfc2047.el          |  13 |Lars Magne Ingebrigt |Sat 23:06
:O     Re: Revival of the ding-patches list       |  13 |Lars Magne Ingebrigt |Sat 23:12
:R  >  Re: Find correct list of articles for a gro|  25 |Lars Magne Ingebrigt |Sat 23:16
:O  \->  ...                                      |  21 |Kai Grossjohann      | 0:01
:R  >  Re: Cry for help: deuglify.el - moving stuf|  28 |Lars Magne Ingebrigt |Sat 23:34
:O  \->  ...                                      | 115 |Raymond Scholz       | 1:24
:O    \->  ...                                    |  19 |Lars Magne Ingebrigt |15:33
:O     Slow mailing list                          |  13 |Lars Magne Ingebrigt |Sat 23:49
:O     Re: '@' mark not documented                |  13 |Lars Magne Ingebrigt |Sat 23:50
:R  >  Re: Gnus still doesn't count messages prope|  23 |Lars Magne Ingebrigt |Sat 23:57
:O  \->  ...                                      |  18 |Kai Grossjohann      | 0:35
:O    \->  ...                                    |  13 |Lars Magne Ingebrigt | 0:56
#+end_src

--------------

**** Question 4.15 [[#Question-4_002e15][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-4_002e15
:CLASS: subsubheading
:END:
How to split incoming mails in several groups?

**** Answer [[#Answer-32][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-32
:CLASS: subsubheading
:END:
Gnus offers two possibilities for splitting mail, the easy
nnmail-split-methods and the more powerful Fancy Mail Splitting. I'll
only talk about the first one, refer to the manual, node "Fancy Mail
Splitting" for the latter.

The value of nnmail-split-methods is a list, each element is a list
which stands for a splitting rule. Each rule has the form "group where
matching articles should go to", "regular expression which has to be
matched", the first rule which matches wins. The last rule must always
be a general rule (regular expression .*) which denotes where articles
should go which don't match any other rule. If the folder doesn't exist
yet, it will be created as soon as an article lands there. By default
the mail will be send to all groups whose rules match. If you don't want
that (you probably don't want), say

#+begin_src example-preformatted
(setq nnmail-crosspost nil)
#+end_src

in =~/.gnus.el=.

An example might be better than thousand words, so here's my
nnmail-split-methods. Note that I send duplicates in a special group and
that the default group is spam, since I filter all mails out which are
from some list I'm subscribed to or which are addressed directly to me
before. Those rules kill about 80% of the Spam which reaches me (Email
addresses are changed to prevent spammers from using them):

#+begin_src example-preformatted
(setq nnmail-split-methods
  '(("duplicates" "^Gnus-Warning:.*duplicate")
    ("Emacs-devel" "^\\(To:\\|Cc:\\).*localpart@gnu.invalid.*")
    ("Gnus-Tut" "^\\(To:\\|Cc:\\).*localpart@socha.invalid.*")
    ("tcsh" "^\\(To:\\|Cc:\\).*localpart@mx.gw.invalid.*")
    ("BAfH" "^\\(To:\\|Cc:\\).*localpart@.*uni-muenchen.invalid.*")
    ("Hamster-src" "^\\(Cc:\\|To:\\).*hamster-sourcen@yahoogroups.\\(de\\|com\\).*")
    ("Tagesschau" "^From: tagesschau <localpart@www.tagesschau.invalid>$")
    ("Replies" "^\\(Cc:\\|To:\\).*localpart@Frank-Schmitt.invalid.*")
    ("EK" "^From:.*\\(localpart@privateprovider.invalid\\|localpart@workplace.invalid\\).*")
    ("Spam" "^Content-Type:.*\\(ks_c_5601-1987\\|EUC-KR\\|big5\\|iso-2022-jp\\).*")
    ("Spam" "^Subject:.*\\(This really work\\|XINGA\\|ADV:\\|XXX\\|adult\\|sex\\).*")
    ("Spam" "^Subject:.*\\(\=\?ks_c_5601-1987\?\\|\=\?euc-kr\?\\|\=\?big5\?\\).*")
    ("Spam" "^X-Mailer:\\(.*BulkMailer.*\\|.*MIME::Lite.*\\|\\)")
    ("Spam" "^X-Mailer:\\(.*CyberCreek Avalanche\\|.*http\:\/\/GetResponse\.com\\)")
    ("Spam" "^From:.*\\(verizon\.net\\|prontomail\.com\\|money\\|ConsumerDirect\\).*")
    ("Spam" "^Delivered-To: GMX delivery to spamtrap@gmx.invalid$")
    ("Spam" "^Received: from link2buy.com")
    ("Spam" "^Cc: .*azzrael@t-online.invalid")
    ("Spam" "^X-Mailer-Version: 1.50 BETA")
    ("Uni" "^\\(Cc:\\|To:\\).*localpart@uni-koblenz.invalid.*")
    ("Inbox" "^\\(Cc:\\|To:\\).*\\(my\ name\\|address@one.invalid\\|address@two.invalid\\)")
    ("Spam" "")))
#+end_src

--------------

**** Question 4.16 [[#Question-4_002e16][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-4_002e16
:CLASS: subsubheading
:END:
How can I ensure more contrast when viewing HTML mail?

**** Answer [[#Answer-33][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-33
:CLASS: subsubheading
:END:
Gnus' built-in simple HTML renderer (you use it if the value of
=mm-text-html-renderer= is =shr=) uses the colors which are declared in
the HTML mail. However, it adjusts them in order to prevent situations
like dark gray text on black background. In case the results still have
a too low contrast for you, increase the values of the variables
=shr-color-visible-distance-min= and =shr-color-visible-luminance-min=.

--------------

<<FAQ-5-_002d-Composing-messages>>

Next: [[#FAQ-6-_002d-Old-messages][Old messages]], Previous:
[[#FAQ-4-_002d-Reading-messages][Reading messages]], Up:
[[#Frequently-Asked-Questions][Frequently Asked Questions]]  

**** 1.6 Composing messages [[#Composing-messages][¶]]
:PROPERTIES:
:CUSTOM_ID: Composing-messages
:CLASS: subsection
:END:

--------------

**** Question 5.1 [[#Question-5_002e1][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-5_002e1
:CLASS: subsubheading
:END:
What are the basic commands I need to know for sending mail and
postings?

**** Answer [[#Answer-34][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-34
:CLASS: subsubheading
:END:
To start composing a new mail hit m either in Group or Summary buffer,
for a posting, it's either a in Group buffer and filling the Newsgroups
header manually or a in the Summary buffer of the group where the
posting shall be send to. Replying by mail is r if you don't want to
cite the author, or import the cited text manually and R to cite the
text of the original message. For a follow up to a newsgroup, it's f and
F (analogously to r and R).

Enter new headers above the line saying "--text follows this line--",
enter the text below the line. When ready hit C-c C-c, to send the
message, if you want to finish it later hit C-c C-d to save it in the
drafts group, where you can start editing it again by saying D e.

--------------

**** Question 5.2 [[#Question-5_002e2][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-5_002e2
:CLASS: subsubheading
:END:
How to enable automatic word-wrap when composing messages?

**** Answer [[#Answer-35][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-35
:CLASS: subsubheading
:END:
Starting from No Gnus, automatic word-wrap is already enabled by
default, see the variable message-fill-column.

For other versions of Gnus, say

#+begin_src example-preformatted
(unless (boundp 'message-fill-column)
  (add-hook 'message-mode-hook
            (lambda ()
              (setq fill-column 72)
              (turn-on-auto-fill))))
#+end_src

in =~/.gnus.el=.

You can reformat a paragraph by hitting M-q (as usual).

--------------

**** Question 5.3 [[#Question-5_002e3][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-5_002e3
:CLASS: subsubheading
:END:
How to set stuff like From, Organization, Reply-To, signature...?

**** Answer [[#Answer-36][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-36
:CLASS: subsubheading
:END:
There are other ways, but you should use posting styles for this. (See
below why.) This example should make the syntax clear:

#+begin_src example-preformatted
(setq gnus-posting-styles
  '((".*"
     (name "Frank Schmitt")
     (address "me@there.invalid")
     (organization "Hamme net, kren mer och nimmi")
     (signature-file "~/.signature")
     ("X-SampleHeader" "foobar")
     (eval (setq some-variable "Foo bar")))))
#+end_src

The ".*" means that this settings are the default ones (see below),
valid values for the first element of the following lists are signature,
signature-file, organization, address, name or body. The attribute name
can also be a string. In that case, this will be used as a header name,
and the value will be inserted in the headers of the article; if the
value is =nil=, the header name will be removed. You can also say (eval
(foo bar)), then the function foo will be evaluated with argument bar
and the result will be thrown away.

--------------

**** Question 5.4 [[#Question-5_002e4][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-5_002e4
:CLASS: subsubheading
:END:
Can I set things like From, Signature etc group based on the group I
post too?

**** Answer [[#Answer-37][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-37
:CLASS: subsubheading
:END:
That's the strength of posting styles. Before, we used ".*" to set the
default for all groups. You can use a regexp like "^gmane" and the
following settings are only applied to postings you send to the gmane
hierarchy, use ".*binaries" instead and they will be applied to postings
send to groups containing the string binaries in their name etc.

You can instead of specifying a regexp specify a function which is
evaluated, only if it returns true, the corresponding settings take
effect. Two interesting candidates for this are =message-news-p= which
returns =t= if the current Group is a newsgroup and the corresponding
=message-mail-p=.

Note that all forms that match are applied, that means in the example
below, when I post to gmane.mail.spam.spamassassin.general, the settings
under ".*" are applied and the settings under message-news-p and those
under "^gmane" and those under
"^gmane\\.mail\\.spam\\.spamassassin\\.general$". Because of this put
general settings at the top and specific ones at the bottom.

#+begin_src example-preformatted
(setq gnus-posting-styles
      '((".*" ;;default
         (name "Frank Schmitt")
         (organization "Hamme net, kren mer och nimmi")
         (signature-file "~/.signature"))
        ((message-news-p) ;;Usenet news?
         (address "mySpamTrap@Frank-Schmitt.invalid")
         (reply-to "hereRealRepliesOnlyPlease@Frank-Schmitt.invalid"))
        ((message-mail-p) ;;mail?
         (address "usedForMails@Frank-Schmitt.invalid"))
        ("^gmane" ;;this is mail, too in fact
         (address "usedForMails@Frank-Schmitt.invalid")
         (reply-to nil))
        ("^gmane\\.mail\\.spam\\.spamassassin\\.general$"
         (eval (set (make-local-variable 'message-sendmail-envelope-from)
                    "Azzrael@rz-online.de")))))
#+end_src

--------------

**** Question 5.5 [[#Question-5_002e5][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-5_002e5
:CLASS: subsubheading
:END:
Is there a spell-checker? Perhaps even on-the-fly spell-checking?

**** Answer [[#Answer-38][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-38
:CLASS: subsubheading
:END:
You can use ispell.el to spell-check stuff in Emacs, and flyspell.el for
on-the-fly spell-checking. So the first thing to do is to make sure that
you've got either [[https://hunspell.github.io/][hunspell]],
[[https://www.cs.hmc.edu/~geoff/ispell.html][ispell]] or
[[http://aspell.net][aspell]] installed and in your Path.

Ispell.el assumes you use ispell. If you use aspell say

#+begin_src example-preformatted
(setq ispell-program-name "aspell")
#+end_src

in your Emacs configuration file.

If you want your outgoing messages to be spell-checked, say

#+begin_src example-preformatted
(add-hook 'message-send-hook 'ispell-message)
#+end_src

In your =~/.gnus.el=, if you prefer on-the-fly spell-checking say

#+begin_src example-preformatted
(add-hook 'message-mode-hook (lambda () (flyspell-mode 1)))
#+end_src

--------------

**** Question 5.6 [[#Question-5_002e6][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-5_002e6
:CLASS: subsubheading
:END:
Can I set the dictionary based on the group I'm posting to?

**** Answer [[#Answer-39][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-39
:CLASS: subsubheading
:END:
Yes, say something like

#+begin_src example-preformatted
(add-hook 'gnus-select-group-hook
          (lambda ()
            (cond
             ((string-match
               "^de\\." (gnus-group-real-name gnus-newsgroup-name))
              (ispell-change-dictionary "deutsch8"))
             (t
              (ispell-change-dictionary "english")))))
#+end_src

in =~/.gnus.el=. Change "^de\\." and "deutsch8" to something that suits
your needs.

--------------

**** Question 5.7 [[#Question-5_002e7][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-5_002e7
:CLASS: subsubheading
:END:
Is there some kind of address-book, so I needn't remember all those
email addresses?

**** Answer [[#Answer-40][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-40
:CLASS: subsubheading
:END:
There's a very basic solution for this, mail aliases. You can store your
mail addresses in a ~/.mailrc file using a simple alias syntax:

#+begin_src example-preformatted
alias al        "Al <al@english-heritage.invalid>"
#+end_src

Then typing your alias (followed by a space or punctuation character) on
a To: or Cc: line in the message buffer will cause Gnus to insert the
full address for you. See the node "Mail Aliases" in Message (not Gnus)
manual for details.

However, what you really want is the Insidious Big Brother Database
bbdb. Get it from [[https://bbdb.sourceforge.net/][bbdb's website]]. Now
place the following in =~/.gnus.el=, to activate bbdb for Gnus:

#+begin_src example-preformatted
(require 'bbdb)
(bbdb-initialize 'gnus 'message)
#+end_src

Now you probably want some general bbdb configuration, place them in
~/.emacs:

#+begin_src example-preformatted
(require 'bbdb)
;;If you don't live in Northern America, you should disable the
;;syntax check for telephone numbers by saying
(setq bbdb-north-american-phone-numbers-p nil)
;;Tell bbdb about your email address:
(setq bbdb-user-mail-names
      (regexp-opt '("Your.Email@here.invalid"
                    "Your.other@mail.there.invalid")))
;;cycling while completing email addresses
(setq bbdb-complete-name-allow-cycling t)
;;No popup-buffers
(setq bbdb-use-pop-up nil)
#+end_src

Now you should be ready to go. Say M-x bbdb RET RET to open a bbdb
buffer showing all entries. Say c to create a new entry, b to search
your BBDB and C-o to add a new field to an entry. If you want to add a
sender to the BBDB you can also just hit : on the posting in the summary
buffer and you are done. When you now compose a new mail, hit TAB to
cycle through know recipients.

--------------

**** Question 5.8 [[#Question-5_002e8][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-5_002e8
:CLASS: subsubheading
:END:
Sometimes I see little images at the top of article buffer. What's that
and how can I send one with my postings, too?

**** Answer [[#Answer-41][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-41
:CLASS: subsubheading
:END:
Those images are called X-Faces. They are 48*48 pixel b/w pictures,
encoded in a header line. If you want to include one in your posts,
you've got to convert some image to a X-Face. So fire up some image
manipulation program (say Gimp), open the image you want to include, cut
out the relevant part, reduce color depth to 1 bit, resize to 48*48 and
save as bitmap. Now you should get the compface package from
[[ftp://ftp.cs.indiana.edu/pub/faces/][this site]]. and create the
actual X-face by saying

#+begin_src example-preformatted
cat file.xbm | xbm2ikon | compface > file.face
cat file.face | sed 's/["\\]/\\&/g' > file.face.quoted
#+end_src

If you can't use compface, there's an online X-face converter at
[[https://www.dairiki.org/xface/]]. If you use MS Windows, you could
also use the WinFace program, which used to be available from
‘=http://www.xs4all.nl/~walterln/winface/='. Now you only have to tell
Gnus to include the X-face in your postings by saying

#+begin_src example-preformatted
(setq message-default-headers
      (with-temp-buffer
        (insert "X-Face: ")
        (insert-file-contents "~/.xface")
        (buffer-string)))
#+end_src

in =~/.gnus.el=. You can add an entry

#+begin_src example-preformatted
(x-face-file "~/.xface")
#+end_src

to =gnus-posting-styles=.

--------------

**** Question 5.9 [[#Question-5_002e9][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-5_002e9
:CLASS: subsubheading
:END:
Sometimes I accidentally hit r instead of f in newsgroups. Can Gnus warn
me, when I'm replying by mail in newsgroups?

**** Answer [[#Answer-42][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-42
:CLASS: subsubheading
:END:
Put this in =~/.gnus.el=:

#+begin_src example-preformatted
(setq gnus-confirm-mail-reply-to-news t)
#+end_src

--------------

**** Question 5.10 [[#Question-5_002e10][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-5_002e10
:CLASS: subsubheading
:END:
How to tell Gnus not to generate a sender header?

**** Answer [[#Answer-43][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-43
:CLASS: subsubheading
:END:
Gnus doesn't generate a sender header by default.

--------------

**** Question 5.11 [[#Question-5_002e11][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-5_002e11
:CLASS: subsubheading
:END:
I want Gnus to locally store copies of my send mail and news, how to do
it?

**** Answer [[#Answer-44][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-44
:CLASS: subsubheading
:END:
You must set the variable gnus-message-archive-group to do this. You can
set it to a string giving the name of the group where the copies shall
go or like in the example below use a function which is evaluated and
which returns the group to use.

#+begin_src example-preformatted
(setq gnus-message-archive-group
        '((if (message-news-p)
              "nnml:Send-News"
            "nnml:Send-Mail")))
#+end_src

--------------

**** Question 5.12 [[#Question-5_002e12][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-5_002e12
:CLASS: subsubheading
:END:
I want Gnus to kill the buffer after successful sending instead of
keeping it alive as "Sent mail to...", how to do it?

**** Answer [[#Answer-45][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-45
:CLASS: subsubheading
:END:
Add this to your ~/.gnus:

#+begin_src example-preformatted
(setq message-kill-buffer-on-exit t)
#+end_src

--------------

**** Question 5.13 [[#Question-5_002e13][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-5_002e13
:CLASS: subsubheading
:END:
People tell me my Message-IDs are not correct, why aren't they and how
to fix it?

**** Answer [[#Answer-46][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-46
:CLASS: subsubheading
:END:
The message-ID is a unique identifier for messages you send. To make it
unique, Gnus need to know which machine name to put after the "@". If
the name of the machine where Gnus is running isn't suitable (it
probably isn't at most private machines) you can tell Gnus what to use
by saying:

#+begin_src example-preformatted
(setq message-user-fqdn "yourmachine.yourdomain.tld")
#+end_src

in =~/.gnus.el=. If you use Gnus 5.9 or earlier, you can use this
instead (works for newer versions as well):

#+begin_src example-preformatted
(with-eval-after-load "message"
  (let ((fqdn "yourmachine.yourdomain.tld"));; <-- Edit this!
    (if (boundp 'message-user-fqdn)
        (setq message-user-fqdn fqdn)
      (gnus-message 1 "Redefining `message-make-fqdn'.")
      (defun message-make-fqdn ()
        "Return user's fully qualified domain name."
        fqdn))))
#+end_src

If you have no idea what to insert for "yourmachine.yourdomain.tld",
you've got several choices. You can either ask your provider if he
allows you to use something like yourUserName.userfqdn.provider.net, or
you can use somethingUnique.yourdomain.tld if you own the domain
yourdomain.tld, or you can register at a service which gives private
users a FQDN for free.

Finally you can tell Gnus not to generate a Message-ID for News at all
(and letting the server do the job) by saying

#+begin_src example-preformatted
(setq message-required-news-headers
  (remove' Message-ID message-required-news-headers))
#+end_src

you can also tell Gnus not to generate Message-IDs for mail by saying

#+begin_src example-preformatted
(setq message-required-mail-headers
  (remove' Message-ID message-required-mail-headers))
#+end_src

, however some mail servers don't generate proper Message-IDs, too, so
test if your Mail Server behaves correctly by sending yourself a Mail
and looking at the Message-ID.

--------------

<<FAQ-6-_002d-Old-messages>>

Next:
[[#FAQ-7-_002d-Gnus-in-a-dial_002dup-environment][Gnus in a dial-up environment]],
Previous: [[#FAQ-5-_002d-Composing-messages][Composing messages]], Up:
[[#Frequently-Asked-Questions][Frequently Asked Questions]]  

**** 1.7 Old messages [[#Old-messages][¶]]
:PROPERTIES:
:CUSTOM_ID: Old-messages
:CLASS: subsection
:END:

--------------

**** Question 6.1 [[#Question-6_002e1][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-6_002e1
:CLASS: subsubheading
:END:
How to import my old mail into Gnus?

**** Answer [[#Answer-47][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-47
:CLASS: subsubheading
:END:
The easiest way is to tell your old mail program to export the messages
in mbox format. Most Unix mailers are able to do this, if you come from
the MS Windows world, you may find tools at
[[https://sourceforge.net/projects/mbx2mbox/]].

Now you've got to import this mbox file into Gnus. To do this, create a
nndoc group based on the mbox file by saying G f /path/file.mbox RET in
Group buffer. You now have read-only access to your mail. If you want to
import the messages to your normal Gnus mail groups hierarchy, enter the
nndoc group you've just created by saying C-u RET (thus making sure all
messages are retrieved), mark all messages by saying M P b and either
copy them to the desired group by saying B c name.of.group RET or send
them through nnmail-split-methods (respool them) by saying B r.

--------------

**** Question 6.2 [[#Question-6_002e2][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-6_002e2
:CLASS: subsubheading
:END:
How to archive interesting messages?

**** Answer [[#Answer-48][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-48
:CLASS: subsubheading
:END:
If you stumble across an interesting message, say in gnu.emacs.gnus and
want to archive it there are several solutions. The first and easiest is
to save it to a file by saying O f. However, wouldn't it be much more
convenient to have more direct access to the archived message from Gnus?
If you say yes, put this snippet by Frank Haun <pille3003@fhaun.de> in
=~/.gnus.el=:

#+begin_src example-preformatted
(defun my-archive-article (&optional n)
  "Copies one or more article(s) to a corresponding `nnml:' group, e.g.,
`gnus.ding' goes to `nnml:1.gnus.ding'.  And `nnml:List-gnus.ding' goes
to `nnml:1.List-gnus-ding'.

Use process marks or mark a region in the summary buffer to archive
more then one article."
  (interactive "P")
  (let ((archive-name
         (format
          "nnml:1.%s"
          (replace-regexp-in-string "^.*:" "" gnus-newsgroup-name))))
    (gnus-summary-copy-article n archive-name)))
#+end_src

You can now say M-x my-archive-article in summary buffer to archive the
article under the cursor in a nnml group. (Change nnml to your preferred
back end.)

Of course you can also make sure the cache is enabled by saying

#+begin_src example-preformatted
(setq gnus-use-cache t)
#+end_src

then you only have to set either the tick or the dormant mark for
articles you want to keep, setting the read mark will remove them from
cache.

--------------

**** Question 6.3 [[#Question-6_002e3][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-6_002e3
:CLASS: subsubheading
:END:
How to search for a specific message?

**** Answer [[#Answer-49][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-49
:CLASS: subsubheading
:END:
There are several ways for this, too. For a posting from a Usenet group
the easiest solution is probably to ask
[[https://groups.google.com][groups.google.com]], if you found the
posting there, tell Google to display the raw message, look for the
message-id, and say M-^ the@message.id RET in a summary buffer. There's
a Gnus interface for ‘=groups.google.com=' which you can call with G W)
in group buffer.

Another idea which works for both mail and news groups is to enter the
group where the message you are searching is and use the standard Emacs
search C-s, it's smart enough to look at articles in collapsed threads,
too. If you want to search bodies, too try M-s instead. Further on there
are the gnus-summary-limit-to-foo functions, which can help you, too.

--------------

**** Question 6.4 [[#Question-6_002e4][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-6_002e4
:CLASS: subsubheading
:END:
How to get rid of old unwanted mail?

**** Answer [[#Answer-50][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-50
:CLASS: subsubheading
:END:
You can of course just mark the mail you don't need anymore by saying #
with point over the mail and then say B DEL to get rid of them forever.
You could also instead of actually deleting them, send them to a
junk-group by saying B m nnml:trash-bin which you clear from time to
time, but both are not the intended way in Gnus.

In Gnus, we let mail expire like news expires on a news server. That
means you tell Gnus the message is expirable (you tell Gnus "I don't
need this mail anymore") by saying E with point over the mail in summary
buffer. Now when you leave the group, Gnus looks at all messages which
you marked as expirable before and if they are old enough (default is
older than a week) they are deleted.

--------------

**** Question 6.5 [[#Question-6_002e5][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-6_002e5
:CLASS: subsubheading
:END:
I want that all read messages are expired (at least in some groups). How
to do it?

**** Answer [[#Answer-51][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-51
:CLASS: subsubheading
:END:
If you want all read messages to be expired (e.g., in mailing lists
where there's an online archive), you've got two choices: auto-expire
and total-expire. Auto-expire means, that every article which has no
marks set and is selected for reading is marked as expirable, Gnus hits
E for you every time you read a message. Total-expire follows a slightly
different approach, here all article where the read mark is set are
expirable.

To activate auto-expire, include auto-expire in the Group parameters for
the group. (Hit G c in summary buffer with point over the group to
change group parameters). For total-expire add total-expire to the
group-parameters.

Which method you choose is merely a matter of taste: Auto-expire is
faster, but it doesn't play together with Adaptive Scoring, so if you
want to use this feature, you should use total-expire.

If you want a message to be excluded from expiration in a group where
total or auto expire is active, set either tick (hit u) or dormant mark
(hit u), when you use auto-expire, you can also set the read mark (hit
d).

--------------

**** Question 6.6 [[#Question-6_002e6][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-6_002e6
:CLASS: subsubheading
:END:
I don't want expiration to delete my mails but to move them to another
group.

**** Answer [[#Answer-52][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-52
:CLASS: subsubheading
:END:
Say something like this in =~/.gnus.el=:

#+begin_src example-preformatted
(setq nnmail-expiry-target "nnml:expired")
#+end_src

(If you want to change the value of nnmail-expiry-target on a per group
basis see the question "How can I disable threading in some (e.g.,
mail-) groups, or set other variables specific for some groups?")

--------------

<<FAQ-7-_002d-Gnus-in-a-dial_002dup-environment>>

Next: [[#FAQ-8-_002d-Getting-help][Getting help]], Previous:
[[#FAQ-6-_002d-Old-messages][Old messages]], Up:
[[#Frequently-Asked-Questions][Frequently Asked Questions]]  

**** 1.8 Gnus in a dial-up environment [[#Gnus-in-a-dial_002dup-environment][¶]]
:PROPERTIES:
:CUSTOM_ID: Gnus-in-a-dial_002dup-environment
:CLASS: subsection
:END:

--------------

**** Question 7.1 [[#Question-7_002e1][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-7_002e1
:CLASS: subsubheading
:END:
I don't have a permanent connection to the net, how can I minimize the
time I've got to be connected?

**** Answer [[#Answer-53][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-53
:CLASS: subsubheading
:END:
You've got basically two options: Either you use the Gnus Agent (see
below) for this, or you can install programs which fetch your news and
mail to your local disk and Gnus reads the stuff from your local
machine.

If you want to follow the second approach, you need a program which
fetches news and offers them to Gnus, a program which does the same for
mail and a program which receives the mail you write from Gnus and sends
them when you're online.

Let's talk about Unix systems first: For the news part, the easiest
solution is a small nntp server like
[[https://www.leafnode.org/][Leafnode]] or
[[https://patrik.iki.fi/sn/][sn]], of course you can also install a full
featured news server like [[https://www.isc.org/othersoftware/][inn]].
Then you want to fetch your Mail, popular choices are
[[https://www.fetchmail.info/][fetchmail]] and
[[https://pyropus.ca/software/getmail/][getmail]]. You should tell those
to write the mail to your disk and Gnus to read it from there. Last but
not least the mail sending part: This can be done with every MTA like
[[https://www.proofpoint.com/us/open-source-email-solution][sendmail]]
or [[https://www.exim.org/][exim]].

On windows boxes I'd vote for
[[http://www.tglsoft.de/freeware_hamster.html][Hamster]], it's a small
freeware, open-source program which fetches your mail and news from
remote servers and offers them to Gnus (or any other mail and/or news
reader) via nntp respectively POP3 or IMAP. It also includes a smtp
server for receiving mails from Gnus.

--------------

**** Question 7.2 [[#Question-7_002e2][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-7_002e2
:CLASS: subsubheading
:END:
So what was this thing about the Agent?

**** Answer [[#Answer-54][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-54
:CLASS: subsubheading
:END:
The Gnus agent is part of Gnus, it allows you to fetch mail and news and
store them on disk for reading them later when you're offline. It kind
of mimics offline newsreaders like Forte Agent. It is enabled by
default.

You've got to select the servers whose groups can be stored locally. To
do this, open the server buffer (that is press ^ while in the group
buffer). Now select a server by moving point to the line naming that
server. Finally, agentize the server by typing J a. If you make a
mistake, or change your mind, you can undo this action by typing J r.
When you're done, type 'q' to return to the group buffer. Now the next
time you enter a group on an agentized server, the headers will be
stored on disk and read from there the next time you enter the group.

--------------

**** Question 7.3 [[#Question-7_002e3][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-7_002e3
:CLASS: subsubheading
:END:
I want to store article bodies on disk, too. How to do it?

**** Answer [[#Answer-55][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-55
:CLASS: subsubheading
:END:
You can tell the agent to automatically fetch the bodies of articles
which fulfill certain predicates, this is done in a special buffer which
can be reached by saying J c in group buffer. Please refer to the
documentation for information which predicates are possible and how
exactly to do it.

Further on you can tell the agent manually which articles to store on
disk. There are two ways to do this: Number one: In the summary buffer,
process mark a set of articles that shall be stored in the agent by
saying # with point over the article and then type J s. The other
possibility is to set, again in the summary buffer, downloadable (%)
marks for the articles you want by typing @ with point over the article
and then typing J u. What's the difference? Well, process marks are
erased as soon as you exit the summary buffer while downloadable marks
are permanent. You can actually set downloadable marks in several groups
then use fetch session ('J s' in the GROUP buffer) to fetch all of those
articles. The only downside is that fetch session also fetches all of
the headers for every selected group on an agentized server. Depending
on the volume of headers, the initial fetch session could take hours.

--------------

**** Question 7.4 [[#Question-7_002e4][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-7_002e4
:CLASS: subsubheading
:END:
How to tell Gnus not to try to send mails / postings while I'm offline?

**** Answer [[#Answer-56][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-56
:CLASS: subsubheading
:END:
All you've got to do is to tell Gnus when you are online (plugged) and
when you are offline (unplugged), the rest works automatically. You can
toggle plugged/unplugged state by saying J j in group buffer. To start
Gnus unplugged say M-x gnus-unplugged instead of M-x gnus. Note that for
this to work, the agent must be active.

--------------

<<FAQ-8-_002d-Getting-help>>

Next: [[#FAQ-9-_002d-Tuning-Gnus][Tuning Gnus]], Previous:
[[#FAQ-7-_002d-Gnus-in-a-dial_002dup-environment][Gnus in a dial-up environment]],
Up: [[#Frequently-Asked-Questions][Frequently Asked Questions]]  

**** 1.9 Getting help [[#Getting-help][¶]]
:PROPERTIES:
:CUSTOM_ID: Getting-help
:CLASS: subsection
:END:

--------------

**** Question 8.1 [[#Question-8_002e1][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-8_002e1
:CLASS: subsubheading
:END:
How to find information and help inside Emacs?

**** Answer [[#Answer-57][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-57
:CLASS: subsubheading
:END:
The first stop should be the Gnus manual (Say C-h i d m Gnus RET to
start the Gnus manual, then walk through the menus or do a full-text
search with s). Then there are the general Emacs help commands starting
with C-h, type C-h ? ? to get a list of all available help commands and
their meaning. Finally M-x apropos-command lets you search through all
available functions and M-x apropos searches the bound variables.

--------------

**** Question 8.2 [[#Question-8_002e2][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-8_002e2
:CLASS: subsubheading
:END:
I can't find anything in the Gnus manual about X (e.g., attachments,
PGP, MIME...), is it not documented?

**** Answer [[#Answer-58][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-58
:CLASS: subsubheading
:END:
There's not only the Gnus manual but also the manuals for message,
emacs-mime, sieve, and EasyPG Assistant. Those packages are distributed
with Emacs and used by Gnus. They are documented in separate info files,
so you should have a look in those manuals, too.

--------------

**** Question 8.3 [[#Question-8_002e3][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-8_002e3
:CLASS: subsubheading
:END:
Which websites should I know?

**** Answer [[#Answer-59][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-59
:CLASS: subsubheading
:END:
The most important one is the
[[https://www.gnus.org][official Gnus website]].

Tell me about other sites which are interesting.

--------------

**** Question 8.4 [[#Question-8_002e4][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-8_002e4
:CLASS: subsubheading
:END:
Which mailing lists and newsgroups are there?

**** Answer [[#Answer-60][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-60
:CLASS: subsubheading
:END:
There's the newsgroup gnu.emacs.gnus which deals with general Gnus
questions. If you have questions about development versions of Gnus, you
should better ask on the ding mailing list, see below.

If you want to stay in the big8, news.software.readers is also read by
some Gnus users (but chances for qualified help are much better in the
above groups). If you speak German, there's de.comm.software.gnus.

The ding mailing list (ding@gnus.org) deals with development of Gnus.

--------------

**** Question 8.5 [[#Question-8_002e5][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-8_002e5
:CLASS: subsubheading
:END:
Where to report bugs?

**** Answer [[#Answer-61][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-61
:CLASS: subsubheading
:END:
Say M-x gnus-bug, this will start a message to the
[[mailto:bugs@gnus.org][gnus bug mailing list]] including information
about your environment which make it easier to help you.

--------------

**** Question 8.6 [[#Question-8_002e6][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-8_002e6
:CLASS: subsubheading
:END:
I need real-time help, where to find it?

**** Answer [[#Answer-62][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-62
:CLASS: subsubheading
:END:
Point your IRC client to irc.libera.chat, channel #gnus.

--------------

<<FAQ-9-_002d-Tuning-Gnus>>

Next: [[#FAQ-_002d-Glossary][Glossary]], Previous:
[[#FAQ-8-_002d-Getting-help][Getting help]], Up:
[[#Frequently-Asked-Questions][Frequently Asked Questions]]  

**** 1.10 Tuning Gnus [[#Tuning-Gnus][¶]]
:PROPERTIES:
:CUSTOM_ID: Tuning-Gnus
:CLASS: subsection
:END:

--------------

**** Question 9.1 [[#Question-9_002e1][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-9_002e1
:CLASS: subsubheading
:END:
Starting Gnus is really slow, how to speed it up?

**** Answer [[#Answer-63][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-63
:CLASS: subsubheading
:END:
The reason for this could be the way Gnus reads its active file, see the
node "The Active File" in the Gnus manual for things you might try to
speed the process up. An other idea would be to byte compile your
=~/.gnus.el= (say M-x byte-compile-file RET ~/.gnus.el RET to do it).
Finally, if you have require statements in your .gnus, you could replace
them with =with-eval-after-load=, which loads the stuff not at startup
time, but when it's needed. Say you've got this in your =~/.gnus.el=:

#+begin_src example-preformatted
(require 'message)
(add-to-list 'message-syntax-checks '(sender . disabled))
#+end_src

then as soon as you start Gnus, message.el is loaded. If you replace it
with

#+begin_src example-preformatted
(with-eval-after-load "message"
  (add-to-list 'message-syntax-checks '(sender . disabled)))
#+end_src

it's loaded when it's needed.

--------------

**** Question 9.2 [[#Question-9_002e2][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-9_002e2
:CLASS: subsubheading
:END:
How to speed up the process of entering a group?

**** Answer [[#Answer-64][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-64
:CLASS: subsubheading
:END:
A speed killer is setting the variable =gnus-fetch-old-headers= to
anything different from =nil=, so don't do this if speed is an issue.

You could increase the value of =gc-cons-threshold= by saying something
like:

#+begin_src example-preformatted
(setq gc-cons-threshold 3500000)
#+end_src

in ~/.emacs.

--------------

**** Question 9.3 [[#Question-9_002e3][¶]]
:PROPERTIES:
:CUSTOM_ID: Question-9_002e3
:CLASS: subsubheading
:END:
Sending mail becomes slower and slower, what's up?

**** Answer [[#Answer-65][¶]]
:PROPERTIES:
:CUSTOM_ID: Answer-65
:CLASS: subsubheading
:END:
The reason could be that you told Gnus to archive the messages you wrote
by setting gnus-message-archive-group. Try to use a nnml group instead
of an archive group, this should bring you back to normal speed.

--------------

<<FAQ-_002d-Glossary>>

Previous: [[#FAQ-9-_002d-Tuning-Gnus][Tuning Gnus]], Up:
[[#Frequently-Asked-Questions][Frequently Asked Questions]]  

**** 1.11 Glossary [[#Glossary][¶]]
:PROPERTIES:
:CUSTOM_ID: Glossary
:CLASS: subsection
:END:
- /~/.gnus.el/ :: When the term =~/.gnus.el= is used it just means your
  Gnus configuration file. You might as well call it =~/.gnus= or
  specify another name.

- /Back End/ :: In Gnus terminology a back end is a virtual server, a
  layer between core Gnus and the real NNTP-, POP3-, IMAP- or
  whatever-server which offers Gnus a standardized interface to
  functions like "get message", "get Headers" etc.

- /Message/ :: In this FAQ message means either a mail or a posting to a
  Usenet Newsgroup or to some other fancy back end, no matter of which
  kind it is.

- /MUA/ :: MUA is an acronym for Mail User Agent, it's the program you
  use to read and write e-mails.

- /NUA/ :: NUA is an acronym for News User Agent, it's the program you
  use to read and write Usenet news.
