<<Top>>

Next: [[#Introduction][Introduction]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

* Htmlfontify [[#Htmlfontify][¶]]
:PROPERTIES:
:CUSTOM_ID: Htmlfontify
:CLASS: top
:END:
This manual documents Htmlfontify, a source code -> crosslinked +
formatted + syntax colorized html transformer.

Copyright © 2002--2026 Free Software Foundation, Inc.

#+begin_quote
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being “A GNU Manual,” and
with the Back-Cover Texts as in (a) below. A copy of the license is
included in the section entitled “GNU Free Documentation License”.

(a) The FSF's Back-Cover Text is: “You have the freedom to copy and
modify this GNU manual.”
#+end_quote

<<SEC_Contents>>
** Table of Contents
:PROPERTIES:
:CUSTOM_ID: table-of-contents
:CLASS: contents-heading
:END:

- [[#Introduction][1 Introduction]]
- [[#Usage-_0026-Examples][2 Usage & Examples]]
  - [[#Interactive][2.1 Interactive]]
  - [[#Non_002dinteractive][2.2 Non-interactive]]
  - [[#Variables][2.3 Variables]]
  - [[#Data-Structures][2.4 Data Structures]]
  - [[#Examples][2.5 Examples]]
- [[#Customization][3 Customization]]
- [[#Requirements][4 Requirements]]
- [[#GNU-Free-Documentation-License][Appendix A GNU Free Documentation License]]
- [[#Index][Index]]

--------------

<<Introduction>>

Next: [[#Usage-_0026-Examples][Usage & Examples]], Previous:
[[#Top][Htmlfontify]], Up: [[#Top][Htmlfontify]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

** 1 Introduction [[#Introduction-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Introduction-1
:CLASS: chapter
:END:
Htmlfontify provides a means of converting individual Emacs buffers,
source files, or entire source trees to html, preserving formatting and
Emacs colorization / syntax highlighting as much as possible through
careful application of CSS stylesheets and html tags.

It can also turn instances of functions, methods and (for some
languages) variables and other constructs and items into links to their
definitions, and create an index file (or files) of all such symbols,
also linked to their points of definition.

Htmlfontify also provides several customization items, which should
allow it to mesh more-or-less seamlessly with various templating or
publishing systems (in the event, for instance, that you don't want to
produce the html pages directly).

--------------

<<Usage-_0026-Examples>>

Next: [[#Customization][Customization]], Previous:
[[#Introduction][Introduction]], Up: [[#Top][Htmlfontify]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

** 2 Usage & Examples [[#Usage-_0026-Examples-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Usage-_0026-Examples-1
:CLASS: chapter
:END:
Htmlfontify can be used both interactively and as part of another elisp
function. If you're running it in a modern Emacs, it will also run when
attached to a terminal (i.e., without X) or even when in batch mode.

- [[#Interactive][Interactive]]
- [[#Non_002dinteractive][Non-interactive]]
- [[#Variables][Variables]]
- [[#Data-Structures][Data Structures]]
- [[#Examples][Examples]]

--------------

<<Interactive>>

Next: [[#Non_002dinteractive][Non-interactive]], Up:
[[#Usage-_0026-Examples][Usage & Examples]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

*** 2.1 Interactive [[#Interactive-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Interactive-1
:CLASS: section
:END:
Htmlfontify provides the following interactive functions:

- <<index-htmlfontify_002dbuffer>>=htmlfontify-buffer=
  [[#index-htmlfontify_002dbuffer][¶]] ::

  #+begin_src lisp-preformatted


  (htmlfontify-buffer &optional srcdir file)
  #+end_src

  Create a new buffer, named for the current buffer + a .html extension,
  containing an inline CSS-stylesheet and formatted CSS-markup html that
  reproduces the look of the current Emacs buffer as closely as
  possible.

  “Dangerous” characters in the existing buffer are turned into html
  entities, so you should even be able to do html-within-html fontified
  display.

  You should, however, note that random control or non-ASCII characters
  such as ^L (U+000C FORM FEED (FF)) or ¤ (U+00A4 CURRENCY SIGN) won't
  get mapped yet.

  If the =srcdir= and =file= arguments are set, lookup etags derived
  entries in the [[#hfy_002dtags_002dcache][hfy-tags-cache]] and add
  html anchors and hyperlinks as appropriate.

- <<index-htmlfontify_002drun_002detags>>=htmlfontify-run-etags=
  [[#index-htmlfontify_002drun_002detags][¶]] ::

  #+begin_src lisp-preformatted


  (htmlfontify-run-etags srcdir)
  #+end_src

  Load the etags cache for =srcdir=. See
  [[#hfy_002dload_002dtags_002dcache][hfy-load-tags-cache]].

- <<index-htmlfontify_002dcopy_002dand_002dlink_002ddir>>=htmlfontify-copy-and-link-dir=
  [[#index-htmlfontify_002dcopy_002dand_002dlink_002ddir][¶]] ::

  #+begin_src lisp-preformatted


  (htmlfontify-copy-and-link-dir srcdir dstdir &optional f-ext l-ext)
  #+end_src

  Trawl =srcdir= and write fontified-and-hyperlinked output in =dstdir=.
  =f-ext= and =l-ext= specify values for [[#hfy_002dextn][hfy-extn]] and
  [[#hfy_002dlink_002dextn][hfy-link-extn]].

  You may also want to set [[#hfy_002dpage_002dheader][hfy-page-header]]
  and [[#hfy_002dpage_002dfooter][hfy-page-footer]].

- <<index-htmlfontify_002dload_002drgb_002dfile>>=htmlfontify-load-rgb-file=
  [[#index-htmlfontify_002dload_002drgb_002dfile][¶]] ::

  #+begin_src lisp-preformatted


  (htmlfontify-load-rgb-file &optional file)
  #+end_src

  Load an X11 style rgb.txt file (search =hfy-rgb-load-path= if =file=
  is not specified).

  Note that this is not necessary if all you want is the standard X11
  (XFree86 4.1.0) color name -> rgb triplet mapping. Htmlfontify has a
  copy built in, for use when it cannot contact an X server.

  Loads the variable =hfy-rgb-txt-color-map=, which is used by
  [[#hfy_002dfallback_002dcolor_002dvalues][hfy-fallback-color-values]].

- <<index-htmlfontify_002dunload_002drgb_002dfile>>=htmlfontify-unload-rgb-file=
  [[#index-htmlfontify_002dunload_002drgb_002dfile][¶]] ::

  #+begin_src lisp-preformatted


  (htmlfontify-unload-rgb-file)
  #+end_src

  Unload the currently loaded X11 style rgb.txt file (if any).

--------------

<<Non_002dinteractive>>

Next: [[#Variables][Variables]], Previous:
[[#Interactive][Interactive]], Up:
[[#Usage-_0026-Examples][Usage & Examples]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

*** 2.2 Non-interactive [[#Non_002dinteractive-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Non_002dinteractive-1
:CLASS: section
:END:
In addition to the aforementioned interactive methods, Htmlfontify
provides the following non-interactive ones:

- <<index-hfy_002dface_002dto_002dstyle>>=hfy-face-to-style=
  [[#index-hfy_002dface_002dto_002dstyle][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-face-to-style fn)
  #+end_src

  Take =fn=, a font or =defface= style font specification, (as returned
  by =face-attr-construct= or
  [[#hfy_002dface_002dattr_002dfor_002dclass][hfy-face-attr-for-class]])
  and return a [[#hfy_002dstyle_002dassoc][hfy-style-assoc]].

  See also:
  [[#hfy_002dface_002dto_002dstyle_002di][hfy-face-to-style-i]],
  [[#hfy_002dflatten_002dstyle][hfy-flatten-style]].

- <<index-hfy_002dfallback_002dcolor_002dvalues>>=hfy-fallback-color-values=
  [[#index-hfy_002dfallback_002dcolor_002dvalues][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-fallback-color-values color-string)
  #+end_src

  Use a fallback method for obtaining the rgb values for a color. If
  [[#htmlfontify_002dload_002drgb_002dfile][htmlfontify-load-rgb-file]]
  has been called, it uses the color map specified, otherwise it uses
  Htmlfontify's built in map.

- <<index-hfy_002dcombined_002dface_002dspec>>=hfy-combined-face-spec=
  [[#index-hfy_002dcombined_002dface_002dspec][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-combined-face-spec face)
  #+end_src

  Return a =defface= style alist of possible specifications for =face=,
  with any entries resulting from user customization
  (=custom-set-faces=) taking precedence.

  See also: [[#hfy_002ddefault_002dface_002ddef][hfy-default-face-def]]

- <<index-hfy_002dword_002dregex>>=hfy-word-regex=
  [[#index-hfy_002dword_002dregex][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-word-regex string)
  #+end_src

  Return a regex that matches =string= as the first =match-string=, with
  non word characters on either side (vaguely emulating the perl =\b=
  regex atom).

- <<index-hfy_002dforce_002dfontification>>=hfy-force-fontification=
  [[#index-hfy_002dforce_002dfontification][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-force-fontification)
  #+end_src

  Emacs's fontification is designed for interactive use. As such, it
  sometimes does things like deferring fontification until a section of
  the buffer is exposed and rendered, or until Emacs is idle for a
  while. Sometimes, in non-interactive circumstances, or if it can't see
  X, it doesn't bother with some of the harder stuff. While this is all
  great from the perspective of a user waiting for Emacs to load a 20000
  line file and colorize it, it's a pain from the point of view from
  non-interactive code. This function lies, cheats, steals and generally
  bullies Emacs into fontifying a buffer from start to finish, with all
  the extra frills, whether it thinks it needs to or not. Oh yes: it
  operates on the current buffer.

- <<index-hfy_002dlink_002dstyle_002dstring>>=hfy-link-style-string=
  [[#index-hfy_002dlink_002dstyle_002dstring][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-link-style-string style-string)
  #+end_src

  Replace the end of a CSS style declaration =style-string= with the
  contents of the variable
  [[#hfy_002dsrc_002ddoc_002dlink_002dstyle][hfy-src-doc-link-style]],
  removing text matching the regex
  [[#hfy_002dsrc_002ddoc_002dlink_002dunstyle][hfy-src-doc-link-unstyle]]
  first, if necessary.

- <<index-hfy_002dprepare_002dindex_002di>>=hfy-prepare-index-i=
  [[#index-hfy_002dprepare_002dindex_002di][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-prepare-index-i srcdir dstdir filename &optional stub map)
  #+end_src

  Prepare a tags index buffer for =srcdir=.
  [[#hfy_002dtags_002dcache][hfy-tags-cache]] must already have an entry
  for =srcdir= for this to work.
  [[#hfy_002dpage_002dheader][hfy-page-header]],
  [[#hfy_002dpage_002dfooter][hfy-page-footer]],
  [[#hfy_002dlink_002dextn][hfy-link-extn]] and
  [[#hfy_002dextn][hfy-extn]] all play a part here.

  If =stub= is set, prepare an (appropriately named) index buffer
  specifically for entries beginning with =stub=.

  If =map= is set, use that instead of
  [[#hfy_002dtags_002dcache][hfy-tags-cache]].

- <<index-hfy_002dcompile_002dstylesheet>>=hfy-compile-stylesheet=
  [[#index-hfy_002dcompile_002dstylesheet][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-compile-stylesheet)
  #+end_src

  Trawl the current buffer, construct and return a
  [[#hfy_002dsheet_002dassoc][hfy-sheet-assoc]].

- <<index-hfy_002dcss_002dname>>=hfy-css-name=
  [[#index-hfy_002dcss_002dname][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-css-name fn)
  #+end_src

  Strip some of the boring bits from a font-name and return a CSS style
  name. If =fn= is a =defface= attribute list, either construct a name
  for it, store it in the cache, and return it, or just fetch it from
  the cache if it's already there.

- <<index-hfy_002dmake_002ddirectory>>=hfy-make-directory=
  [[#index-hfy_002dmake_002ddirectory][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-make-directory dir)
  #+end_src

  Approximate equivalent of =mkdir -p ==dir=.

- <<index-hfy_002dtriplet>>=hfy-triplet=
  [[#index-hfy_002dtriplet][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-triplet color)
  #+end_src

  Takes a color name (string) and return a CSS rgb(R, G, B) triplet
  string. Uses the definition of “white” to map the numbers to the 0-255
  range, so if you've redefined white, (especially if you've redefined
  it to have a triplet member lower than that of the color you are
  processing, strange things may happen).

- <<index-hfy_002ddefault_002dfooter>>=hfy-default-footer=
  [[#index-hfy_002ddefault_002dfooter][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-default-footer file)
  #+end_src

  Default value for [[#hfy_002dpage_002dfooter][hfy-page-footer]]

- <<index-hfy_002dlist_002dfiles>>=hfy-list-files=
  [[#index-hfy_002dlist_002dfiles][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-list-files directory)
  #+end_src

  Return a list of files under =directory=. Strips any leading ‘=./='
  from each filename.

- <<index-hfy_002dcolor_002dvals>>=hfy-color-vals=
  [[#index-hfy_002dcolor_002dvals][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-color-vals color)
  #+end_src

  Where =color= is a color name or #XXXXXX style triplet, return a list
  of 3 (16 bit) rgb values for said color. If a window system is
  unavailable, calls
  [[#hfy_002dfallback_002dcolor_002dvalues][hfy-fallback-color-values]].

- <<index-hfy_002dhref_002dstub>>=hfy-href-stub=
  [[#index-hfy_002dhref_002dstub][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-href-stub this-file def-files tag)
  #+end_src

  Return an href stub for a tag href: if =def-files= (list of files
  containing definitions for the tag in question) contains only one
  entry, the href should link straight to that file. Otherwise, the link
  should be to the index file.

  We are not yet concerned with the file extensions/tag line number and
  so on at this point.

  If [[#hfy_002dsplit_002dindex][hfy-split-index]] is set, and the href
  will be to an index file rather than a source file, append a ‘=.X=' to
  [[#hfy_002dindex_002dfile][hfy-index-file]], where ‘=X=' is the
  uppercased first character of =tag=.

  See also: [[#hfy_002drelstub][hfy-relstub]],
  [[#hfy_002dindex_002dfile][hfy-index-file]].

- <<index-hfy_002dline_002dnumber>>=hfy-line-number=
  [[#index-hfy_002dline_002dnumber][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-line-number)
  #+end_src

  Returns the line number of the point in the current buffer.

- <<index-hfy_002dmerge_002dadjacent_002dspans>>=hfy-merge-adjacent-spans=
  [[#index-hfy_002dmerge_002dadjacent_002dspans][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-merge-adjacent-spans face-map)
  #+end_src

  Where =face-map= is a
  [[#hfy_002dfacemap_002dassoc][hfy-facemap-assoc]] for the current
  buffer, this function merges adjacent style blocks which are of the
  same value and are separated by nothing more interesting than
  whitespace.

  =<span class="foo">narf</span> <span class="foo">brain</span>=

  (as interpreted from =face-map=) would become:

  =<span class="foo">narf brain</span>=

  Returns a modified copy of =face-map= (also a
  [[#hfy_002dfacemap_002dassoc][hfy-facemap-assoc]]).

- <<index-hfy_002dmark_002dtag_002dnames>>=hfy-mark-tag-names=
  [[#index-hfy_002dmark_002dtag_002dnames][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-mark-tag-names srcdir file)
  #+end_src

  Mark tags in =file= (lookup =srcdir= in
  [[#hfy_002dtags_002dcache][hfy-tags-cache]]) with the =hfy-anchor=
  property, with a value of ‘=tag.line-number='.

- <<index-hfy_002dweight>>=hfy-weight= [[#index-hfy_002dweight][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-weight weight)
  #+end_src

  Derive a font-weight CSS specifier from an Emacs weight specification
  symbol.

- <<index-hfy_002dsize>>=hfy-size= [[#index-hfy_002dsize][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-size height)
  #+end_src

  Derive a CSS font-size specifier from an Emacs font =:height=
  attribute. Does not cope with the case where height is a function to
  be applied to the height of the underlying font.

- <<index-hfy_002ddefault_002dheader>>=hfy-default-header=
  [[#index-hfy_002ddefault_002dheader][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-default-header file style)
  #+end_src

  Default value for [[#hfy_002dpage_002dheader][hfy-page-header]]

- <<index-hfy_002dfamily>>=hfy-family= [[#index-hfy_002dfamily][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-family family)
  #+end_src

  Derives a CSS font-family specifier from an Emacs =:family= attribute.

- <<index-hfy_002dmark_002dtag_002dhrefs>>=hfy-mark-tag-hrefs=
  [[#index-hfy_002dmark_002dtag_002dhrefs][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-mark-tag-hrefs srcdir file)
  #+end_src

  Mark href start points with the =hfy-link= property (value: href
  string).

  Mark href end points with the =hfy-endl= property (value =t=).

  Avoid overlapping links, and mark links in descending length of tag
  name in order to prevent subtags from usurping supertags; e.g., “term”
  for “terminal”).

- <<index-hfy_002dbox>>=hfy-box= [[#index-hfy_002dbox][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-box box)
  #+end_src

  Derive CSS border-* attributes from the Emacs =:box= attribute.

- <<index-hfy_002dbox_002dto_002dstyle>>=hfy-box-to-style=
  [[#index-hfy_002dbox_002dto_002dstyle][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-box-to-style spec)
  #+end_src

  Convert a complex =:box= Emacs font attribute set to a list of CSS
  border-* attributes. Don't call this directly---it is called by
  [[#hfy_002dbox][hfy-box]] when necessary.

- <<index-hfy_002dhtml_002denkludge_002dbuffer>>=hfy-html-enkludge-buffer=
  [[#index-hfy_002dhtml_002denkludge_002dbuffer][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-html-enkludge-buffer)
  #+end_src

  Mark dangerous ‘=["<>]=' characters with the =hfy-quoteme= property.

  See also
  [[#hfy_002dhtml_002ddekludge_002dbuffer][hfy-html-dekludge-buffer]].

- <<index-hfy_002dbuffer>>=hfy-buffer= [[#index-hfy_002dbuffer][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-buffer)
  #+end_src

  Generate and return an Htmlfontify html output buffer for the current
  buffer. May trample an existing buffer.

- <<index-hfy_002dfontified_002dp>>=hfy-fontified-p=
  [[#index-hfy_002dfontified_002dp][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-fontified-p)
  #+end_src

  =font-lock= doesn't like to say a buffer's been fontified when in
  batch mode, but we want to know if we should fontify or raw copy, so
  in batch mode we check for non-default face properties. Otherwise we
  test =font-lock-mode= and =font-lock-fontified= for truth.

- <<index-hfy_002dlookup>>=hfy-lookup= [[#index-hfy_002dlookup][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-lookup face style)
  #+end_src

  Where =style= is a [[#hfy_002dsheet_002dassoc][hfy-sheet-assoc]] and
  =face= is an Emacs face, return the relevant =css= style name.

- <<index-hfy_002dfontify_002dbuffer>>=hfy-fontify-buffer=
  [[#index-hfy_002dfontify_002dbuffer][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-fontify-buffer &optional srcdir file)
  #+end_src

  Implement the guts of [[#htmlfontify_002dbuffer][htmlfontify-buffer]].

- <<index-hfy_002dcolor>>=hfy-color= [[#index-hfy_002dcolor][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-color color)
  #+end_src

  Convert an Emacs :foreground property to a CSS color property.

- <<index-hfy_002dflatten_002dstyle>>=hfy-flatten-style=
  [[#index-hfy_002dflatten_002dstyle][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-flatten-style style)
  #+end_src

  Take =style= (see
  [[#hfy_002dface_002dto_002dstyle_002di][hfy-face-to-style-i]], see
  [[#hfy_002dface_002dto_002dstyle][hfy-face-to-style]]) and merge any
  multiple attributes appropriately. Currently only font-size is merged
  down to a single occurrence---others may need special handling, but I
  haven't encountered them yet. Returns a
  [[#hfy_002dstyle_002dassoc][hfy-style-assoc]].

- <<index-hfy_002dsize_002dto_002dint>>=hfy-size-to-int=
  [[#index-hfy_002dsize_002dto_002dint][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-size-to-int spec)
  #+end_src

  Convert =spec=, a CSS font-size specifier, back to an Emacs =:height=
  attribute value. Used while merging multiple font-size attributes.

- <<index-hfy_002dsprintf_002dstylesheet>>=hfy-sprintf-stylesheet=
  [[#index-hfy_002dsprintf_002dstylesheet][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-sprintf-stylesheet css file)
  #+end_src

  Generates a header, via [[#hfy_002dpage_002dheader][hfy-page-header]],
  for =file=, containing the stylesheet derived from =css=, which is a
  [[#hfy_002dsheet_002dassoc][hfy-sheet-assoc]]. Returns a string
  containing the same.

- <<index-hfy_002drelstub>>=hfy-relstub=
  [[#index-hfy_002drelstub][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-relstub file &optional start)
  #+end_src

  Return a ‘=../=' stub of the appropriate length for the current source
  tree depth (as determined from =file=).

- <<index-hfy_002dcompile_002dface_002dmap>>=hfy-compile-face-map=
  [[#index-hfy_002dcompile_002dface_002dmap][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-compile-face-map)
  #+end_src

  Compile and return a [[#hfy_002dfacemap_002dassoc][hfy-facemap-assoc]]
  for the current buffer.

- <<index-hfy_002dprepare_002dindex>>=hfy-prepare-index=
  [[#index-hfy_002dprepare_002dindex][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-prepare-index srcdir dstdir)
  #+end_src

  Return as list of index buffer(s), as determined by
  [[#hfy_002dsplit_002dindex][hfy-split-index]]. Uses
  [[#hfy_002dprepare_002dindex_002di][hfy-prepare-index-i]] to do this.

- <<index-hfy_002dprepare_002dtag_002dmap>>=hfy-prepare-tag-map=
  [[#index-hfy_002dprepare_002dtag_002dmap][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-prepare-tag-map srcdir dstdir)
  #+end_src

  Prepare the counterpart(s) to the index buffer(s)---a list of buffers
  with the same structure, but listing (and linking to) instances of
  tags (as opposed to their definitions).

  See also: [[#hfy_002dprepare_002dindex][hfy-prepare-index]],
  [[#hfy_002dsplit_002dindex][hfy-split-index]]

- <<index-hfy_002dsubtract_002dmaps>>=hfy-subtract-maps=
  [[#index-hfy_002dsubtract_002dmaps][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-subtract-maps srcdir)
  #+end_src

  Internal function---strips definitions of tags from the instance map.
  See: [[#hfy_002dtags_002dcache][hfy-tags-cache]] and
  [[#hfy_002dtags_002drmap][hfy-tags-rmap]]

- <<index-hfy_002dface_002dto_002dstyle_002di>>=hfy-face-to-style-i=
  [[#index-hfy_002dface_002dto_002dstyle_002di][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-face-to-style-i fn)
  #+end_src

  The guts of [[#hfy_002dface_002dto_002dstyle][hfy-face-to-style]].
  =fn= should be a =defface= font specification, as returned by
  =face-attr-construct= or
  [[#hfy_002dface_002dattr_002dfor_002dclass][hfy-face-attr-for-class]].
  Note that this function does not get font-sizes right if they are
  based on inherited modifiers (via the :inherit) attribute, and any
  other modifiers that are cumulative if they appear multiple times need
  to be merged by the
  user---[[#hfy_002dflatten_002dstyle][hfy-flatten-style]] should do
  this.

- <<index-hfy_002dface_002dto_002dcss>>=hfy-face-to-css=
  [[#index-hfy_002dface_002dto_002dcss][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-face-to-css fn)
  #+end_src

  Take =fn=, a font or =defface= specification (cf.
  =face-attr-construct=) and return a CSS style specification.

  See also: [[#hfy_002dface_002dto_002dstyle][hfy-face-to-style]]

- <<index-hfy_002dhtml_002dquote>>=hfy-html-quote=
  [[#index-hfy_002dhtml_002dquote][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-html-quote char-string)
  #+end_src

  Map a string (usually 1 character long) to an html safe string
  (entity) if need be.

- <<index-hfy_002dlink_002dstyle>>=hfy-link-style=
  [[#index-hfy_002dlink_002dstyle][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-link-style style-string)
  #+end_src

  Convert the CSS style spec =style-string= to its equivalent hyperlink
  style.

  See: [[#hfy_002dlink_002dstyle_002dfun][hfy-link-style-fun]].

- <<index-hfy_002dp_002dto_002dface>>=hfy-p-to-face=
  [[#index-hfy_002dp_002dto_002dface][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-p-to-face props)
  #+end_src

  Given =props=, a list of text-properties, return the value of the face
  property, or =nil=.

- <<index-hfy_002dbox_002dto_002dborder_002dassoc>>=hfy-box-to-border-assoc=
  [[#index-hfy_002dbox_002dto_002dborder_002dassoc][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-box-to-border-assoc spec)
  #+end_src

  Helper function for
  [[#hfy_002dbox_002dto_002dstyle][hfy-box-to-style]].

- <<index-hfy_002dface_002dattr_002dfor_002dclass>>=hfy-face-attr-for-class=
  [[#index-hfy_002dface_002dattr_002dfor_002dclass][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-face-attr-for-class face &optional class)
  #+end_src

  Return the face attributes for =face=. If =class= is set, it must be a
  =defface= alist key [see below]. Prior to version 0.18, the first face
  specification returned by
  [[#hfy_002dcombined_002dface_002dspec][hfy-combined-face-spec]] which
  /didn't/ clash with =class= was returned. In versions from 0.18
  onwards, each font attribute list is scored, and the non-conflicting
  list with the highest score is returned. (A specification with a class
  of =t= is considered to match any class you specify. This matches
  Emacs's behavior when deciding on which face attributes to use, to the
  best of my understanding ).

  If =class= is =nil=, then you just get whatever =face-attr-construct=
  returns; i.e., the current specification in effect for =face=.

  See [[#hfy_002ddisplay_002dclass][hfy-display-class]], for details of
  valid values for =class=.

- <<index-hfy_002dface_002dat>>=hfy-face-at=
  [[#index-hfy_002dface_002dat][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-face-at P)
  #+end_src

  Find face in effect at point P. If overlays are to be considered (see
  [[#hfy_002doptimizations][hfy-optimizations]]) then this may return a
  =defface= style list of face properties instead of a face symbol.

- <<index-hfy_002dbgcol>>=hfy-bgcol= [[#index-hfy_002dbgcol][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-bgcol color)
  #+end_src

  As per [[#hfy_002dcolor][hfy-color]] but for background colors.

- <<index-hfy_002dkludge_002dcperl_002dmode>>=hfy-kludge-cperl-mode=
  [[#index-hfy_002dkludge_002dcperl_002dmode][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-kludge-cperl-mode)
  #+end_src

  cperl mode does its best to not do some of its fontification when not
  in a windowing system---we try to trick it...

- <<index-hfy_002dhref>>=hfy-href= [[#index-hfy_002dhref][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-href this-file def-files tag tag-map)
  #+end_src

  Return a relative href to the tag in question, based on

  =this-file= [[#hfy_002dlink_002dextn][hfy-link-extn]]
  [[#hfy_002dextn][hfy-extn]] =def-files= =tag= and =tag-map=

  =this-file= is the current source file =def-files= is a list of file
  containing possible link endpoints for =tag= =tag= is the =tag= in
  question =tag-map= is the entry in
  [[#hfy_002dtags_002dcache][hfy-tags-cache]].

- <<index-hfy_002dshell>>=hfy-shell= [[#index-hfy_002dshell][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-shell)
  #+end_src

  Returns a best guess at a Bourne compatible shell to use: If the
  current shell doesn't look promising, fall back to
  [[#hfy_002dshell_002dfile_002dname][hfy-shell-file-name]].

- <<index-hfy_002dload_002dtags_002dcache>>=hfy-load-tags-cache=
  [[#index-hfy_002dload_002dtags_002dcache][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-load-tags-cache srcdir)
  #+end_src

  Run [[#hfy_002detags_002dcmd][hfy-etags-cmd]] on =srcdir=: load
  [[#hfy_002dtags_002dcache][hfy-tags-cache]] and
  [[#hfy_002dtags_002dsortl][hfy-tags-sortl]].

- <<index-hfy_002dparse_002dtags_002dbuffer>>=hfy-parse-tags-buffer=
  [[#index-hfy_002dparse_002dtags_002dbuffer][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-parse-tags-buffer srcdir buffer)
  #+end_src

  Parse a =buffer= containing etags formatted output, loading the
  [[#hfy_002dtags_002dcache][hfy-tags-cache]] and
  [[#hfy_002dtags_002dsortl][hfy-tags-sortl]] entries for =srcdir=.

- <<index-hfy_002dinterq>>=hfy-interq= [[#index-hfy_002dinterq][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-interq set-a set-b)
  #+end_src

  Return the intersection (using =eq=) of 2 lists.

- <<index-hfy_002dtext_002dp>>=hfy-text-p=
  [[#index-hfy_002dtext_002dp][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-text-p srcdir file)
  #+end_src

  Is =srcdir=/=file= text? Uses
  [[#hfy_002distext_002dcommand][hfy-istext-command]] to determine this.

- <<index-hfy_002dopt>>=hfy-opt= [[#index-hfy_002dopt][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-opt symbol)
  #+end_src

  Is [[#hfy_002doptimizations][hfy-optimizations]] member =symbol= set
  or not?

- <<index-hfy_002ddirname>>=hfy-dirname=
  [[#index-hfy_002ddirname][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-dirname file)
  #+end_src

  Return everything preceding the last ‘=/=' from a relative filename,
  on the assumption that this will produce the name of a relative
  directory. Hardly bombproof, but good enough in the context in which
  it is being used.

- <<index-hfy_002dhtml_002ddekludge_002dbuffer>>=hfy-html-dekludge-buffer=
  [[#index-hfy_002dhtml_002ddekludge_002dbuffer][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-html-dekludge-buffer)
  #+end_src

  Transform all dangerous characters marked with the =hfy-quoteme=
  property using [[#hfy_002dhtml_002dquote][hfy-html-quote]]

  See also
  [[#hfy_002dhtml_002denkludge_002dbuffer][hfy-html-enkludge-buffer]].

- <<index-hfy_002dcopy_002dand_002dfontify_002dfile>>=hfy-copy-and-fontify-file=
  [[#index-hfy_002dcopy_002dand_002dfontify_002dfile][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-copy-and-fontify-file srcdir dstdir file)
  #+end_src

  Open =file= in =srcdir=---if fontified, write a fontified copy to
  =dstdir= adding an extension of [[#hfy_002dextn][hfy-extn]].
  Fontification is actually done by
  [[#htmlfontify_002dbuffer][htmlfontify-buffer]]. If the buffer is not
  fontified, just copy it.

- <<index-hfy_002ddecor>>=hfy-decor= [[#index-hfy_002ddecor][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-decor tag val)
  #+end_src

  Derive CSS text-decoration specifiers from various Emacs font
  attributes.

- <<index-hfy_002dslant>>=hfy-slant= [[#index-hfy_002dslant][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-slant slant)
  #+end_src

  Derive a font-style CSS specifier from the Emacs :slant
  attribute---CSS does not define the reverse-* styles, so just maps
  those to the regular specifiers.

- <<index-hfy_002dtags_002dfor_002dfile>>=hfy-tags-for-file=
  [[#index-hfy_002dtags_002dfor_002dfile][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-tags-for-file srcdir file)
  #+end_src

  List of etags tags that have definitions in this =file=. Looks up the
  tags cache in [[#hfy_002dtags_002dcache][hfy-tags-cache]] using
  =srcdir= as the key.

- <<index-hfy_002dwidth>>=hfy-width= [[#index-hfy_002dwidth][¶]] ::

  #+begin_src lisp-preformatted


  (hfy-width width)
  #+end_src

  Convert an Emacs =:width= attribute to a CSS font-stretch attribute.

--------------

<<Variables>>

Next: [[#Data-Structures][Data Structures]], Previous:
[[#Non_002dinteractive][Non-interactive]], Up:
[[#Usage-_0026-Examples][Usage & Examples]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

*** 2.3 Variables [[#Variables-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Variables-1
:CLASS: section
:END:
Important variables that are not customization items:

- <<index-hfy_002dtags_002dcache>>=hfy-tags-cache=
  [[#index-hfy_002dtags_002dcache][¶]] ::

  This is an alist of the form:

  #+begin_src example-preformatted
  (("/src/dir/0" . tag-hash0) ("/src/dir/1" tag-hash1) ... )
  #+end_src

  Each tag hash entry then contains entries of the form:

  #+begin_src example-preformatted
  "tag_string" => (("file/name.ext" line char) ... )
  #+end_src

  i.e., an alist mapping (relative) file paths to line and character
  offsets.

  See [[#hfy_002dload_002dtags_002dcache][hfy-load-tags-cache]].

- <<index-hfy_002dtags_002drmap>>=hfy-tags-rmap=
  [[#index-hfy_002dtags_002drmap][¶]] ::

  =hfy-tags-rmap= is an alist of the form:

  #+begin_src lisp-preformatted
  (("/src/dir" . tag-rmap-hash))
  #+end_src

  Where tag-rmap-hash has entries of the form:

  #+begin_src example-preformatted
  "tag_string" => ( "file/name.ext" line char )
  #+end_src

  Unlike [[#hfy_002dtags_002dcache][hfy-tags-cache]] these are the
  locations of occurrences of tagged items, not the locations of their
  definitions.

- <<index-hfy_002dtags_002dsortl>>=hfy-tags-sortl=
  [[#index-hfy_002dtags_002dsortl][¶]] ::

  =hfy-tags-sortl= is an alist of the form:

  #+begin_src example-preformatted
  (("/src/dir" . (tag0 tag1 tag2)) ... )
  #+end_src

  Where the tags are stored in descending order of length.

  See: [[#hfy_002dload_002dtags_002dcache][hfy-load-tags-cache]].

--------------

<<Data-Structures>>

Next: [[#Examples][Examples]], Previous: [[#Variables][Variables]], Up:
[[#Usage-_0026-Examples][Usage & Examples]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

*** 2.4 Data Structures [[#Data-Structures-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Data-Structures-1
:CLASS: section
:END:
Some of the (informal) data structures used in Htmlfontify are detailed
here:

- <<index-hfy_002dstyle_002dassoc>>=hfy-style-assoc=
  [[#index-hfy_002dstyle_002dassoc][¶]] ::

  An assoc representing/describing an Emacs face. Properties may be
  repeated, in which case later properties should be treated as if they
  were inherited from a “parent” font. (For some properties, only the
  first encountered value is of any importance, for others the values
  might be cumulative, and for others they might be cumulative in a
  complex way.)

  Some examples:

  #+begin_src lisp-preformatted
  (hfy-face-to-style 'default) =>

    (("background"      . "rgb(0, 0, 0)"      )
     ("color"           . "rgb(255, 255, 255)")
     ("font-style"      . "normal"            )
     ("font-weight"     . "500"               )
     ("font-stretch"    . "normal"            )
     ("font-family"     . "misc-fixed"        )
     ("font-size"       . "13pt"              )
     ("text-decoration" . "none"              ))

  (hfy-face-to-style 'Info-title-3-face) =>

    (("font-weight"     . "700"        )
     ("font-family"     . "helv"       )
     ("font-size"       . "120%"       )
     ("text-decoration" . "none")      )
  #+end_src

- <<index-hfy_002dsheet_002dassoc>>=hfy-sheet-assoc=
  [[#index-hfy_002dsheet_002dassoc][¶]] ::

  An assoc with elements of the form
  ‘=(face-name style-name . style-string)='. The actual stylesheet for
  each page is derived from one of these.

  #+begin_src lisp-preformatted
  ((default       "default" . "{ background: black; color: white}")
   (font-lock-string-face "string"  . "{ color: rgb(64,224,208) }"))
  #+end_src

- <<index-hfy_002dfacemap_002dassoc>>=hfy-facemap-assoc=
  [[#index-hfy_002dfacemap_002dassoc][¶]] ::

  An assoc of =(point . ==face-symbol==)= or
  =(point . ==defface== attribute list)= and =(point . end)= elements,
  in descending order of point value (i.e., from the file's end to its
  beginning). The map is in reverse order because inserting a
  ‘=<style>=' tag (or any other string) at =point= invalidates the map
  for all entries with a greater value of point. By traversing the map
  from greatest to least =point=, we still invalidate the map as we go,
  but only those points we have already dealt with (and therefore no
  longer care about) will be invalid at any time.

  #+begin_src lisp-preformatted
  ((64820 . end)
   (64744 . font-lock-comment-face)
   (64736 . end)
   (64722 . font-lock-string-face)
   (64630 . end)
   (64623 . font-lock-string-face)
   (64449 . end)
   ;; Big similar section elided.  You get the idea.
   (5459 . end)
   (5431 . (:inherit font-lock-keyword-face :background "7e7e7e"))
   (5431 . end)
   (4285 . font-lock-constant-face)
   (4285 . end)
   (4221 . font-lock-comment-face)
   (4221 . end)
   (4197 . font-lock-constant-face)
   (4197 . end)
   (1 . font-lock-comment-face))
  #+end_src

--------------

<<Examples>>

Previous: [[#Data-Structures][Data Structures]], Up:
[[#Usage-_0026-Examples][Usage & Examples]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

*** 2.5 Examples [[#Examples-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Examples-1
:CLASS: section
:END:
The following is a lump of code I use to fontify source code on my site,
[[http://rtfm.etla.org/]] (which was the reason, incidentally, that
Htmlfontify was written in the first place).

#+begin_src lisp-preformatted
(defvar rtfm-section nil)

;; Constructs an appropriate header string to fit in with rtfm's
;; templating system, based on the file and the stylesheet string
(defun rtfm-build-page-header (file style)
  (format "#define  TEMPLATE red+black.html
#define  DEBUG    1
#include <build/menu-dirlist|>\n
html-css-url := /css/red+black.css
title        := rtfm.etla.org ( %s / src/%s )
bodytag      :=
head         <=STYLESHEET;\n
%s
STYLESHEET
main-title   := rtfm / %s / src/%s\n
main-content <=MAIN_CONTENT;\n" rtfm-section file style rtfm-section file))

;; the footer:
(defun rtfm-build-page-footer (file) "\nMAIN_CONTENT\n")

(defun rtfm-fontify-buffer (section)
  (interactive "s section[eg- emacs / p4-blame]: ")
  (require 'htmlfontify)
  (let ((hfy-page-header  'rtfm-build-page-header)
    (hfy-page-footer  'rtfm-build-page-footer)
    (rtfm-section                     section))
    (htmlfontify-buffer)
    )
  )

;; Here's the function I actually call---it asks me for a section label,
;; and source and destination directories, and then binds a couple of
;; customization variable in a let before calling htmlfontify:
(defun rtfm-build-source-docs (section srcdir destdir)
  (interactive
   "s section[eg- emacs / p4-blame]:\nD source-dir: \nD output-dir: ")
  (require 'htmlfontify)
  (hfy-load-tags-cache srcdir)
  (let ((hfy-page-header  'rtfm-build-page-header)
    (hfy-page-footer  'rtfm-build-page-footer)
    (rtfm-section                     section)
    (hfy-index-file                   "index")
    (auto-mode-alist (append auto-mode-alist
                 '(("dbi\\(shell\\|gtk\\)$" . cperl-mode)
                   ("\\.xpm$"               . c-mode    ))))
    )
    (htmlfontify-run-etags srcdir)
    (htmlfontify-copy-and-link-dir srcdir destdir ".src" ".html")))
#+end_src

--------------

<<Customization>>

Next: [[#Requirements][Requirements]], Previous:
[[#Usage-_0026-Examples][Usage & Examples]], Up: [[#Top][Htmlfontify]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

** 3 Customization [[#Customization-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Customization-1
:CLASS: chapter
:END:
Htmlfontify provides the following variable and customization entries:

- <<index-hfy_002dlink_002dstyle_002dfun>>=hfy-link-style-fun=
  [[#index-hfy_002dlink_002dstyle_002dfun][¶]] ::

  Set this to a function, which will be called with one argument (a
  ‘={ foo: bar; …}=' CSS style-string)---it should return a copy of its
  argument, altered so as to make any changes you want made for text
  which is a hyperlink, in addition to being in the class to which that
  style would normally be applied.

- <<index-hfy_002dhtml_002dquote_002dregex>>=hfy-html-quote-regex=
  [[#index-hfy_002dhtml_002dquote_002dregex][¶]] ::

  Regex to match (with a single back-reference per match) strings in
  HTML which should be quoted with
  [[#hfy_002dhtml_002dquote][hfy-html-quote]] (and see
  [[#hfy_002dhtml_002dquote_002dmap][hfy-html-quote-map]]) to make them
  safe.

- <<index-hfy_002dpage_002dfooter>>=hfy-page-footer=
  [[#index-hfy_002dpage_002dfooter][¶]] ::

  As [[#hfy_002dpage_002dheader][hfy-page-header]], but generates the
  output footer (and takes only 1 argument, the filename).

- <<index-hfy_002ddisplay_002dclass>>=hfy-display-class=
  [[#index-hfy_002ddisplay_002dclass][¶]] ::

  Display class to use to determine which display class to use when
  calculating a face's attributes. This is useful when, for example, you
  are running Emacs on a tty or in batch mode, and want Htmlfontify to
  have access to the face spec you would use if you were connected to an
  X display.

  Some valid class specification elements are:

  #+begin_src lisp-preformatted
    (class      color)
    (class      grayscale)
    (background dark)
    (background light)
    (type       x-toolkit)
    (type       tty)
    (type       motif)
    (type       lucid)
  #+end_src

  Multiple values for a tag may be combined, to indicate that any one or
  more of these values in the specification key constitutes a match. For
  example, =((class color grayscale) (type tty))= would match any of:

  #+begin_src lisp-preformatted
    ((class color))
    ((class grayscale))
    ((class color grayscale)))
    ((class color foo))
    ((type  tty))
    ((type  tty) (class color))
  #+end_src

- <<index-hfy_002dpage_002dheader>>=hfy-page-header=
  [[#index-hfy_002dpage_002dheader][¶]] ::

  Function called with two arguments (the filename relative to the top
  level source directory being etagged and fontified), and a string
  containing the ‘=<style>…</style>=' text to embed in the
  document---the string returned will be used as the header for the
  htmlfontified version of the source file.

  See also: [[#hfy_002dpage_002dfooter][hfy-page-footer]]

- <<index-hfy_002dsrc_002ddoc_002dlink_002dstyle>>=hfy-src-doc-link-style=
  [[#index-hfy_002dsrc_002ddoc_002dlink_002dstyle][¶]] ::

  String to add to the ‘=<style> a=' variant of an Htmlfontify CSS
  class.

- <<index-hfy_002dsplit_002dindex>>=hfy-split-index=
  [[#index-hfy_002dsplit_002dindex][¶]] ::

  Whether or not to split the index
  [[#hfy_002dindex_002dfile][hfy-index-file]] alphabetically on the
  first letter of each tag. Useful when the index would otherwise be
  large and take a long time to render or be difficult to navigate.

- <<index-hfy_002dexclude_002dfile_002drules>>=hfy-exclude-file-rules=
  [[#index-hfy_002dexclude_002dfile_002drules][¶]] :: Regular
  expressions to exclude files which shouldn't be fontified.

- <<index-hfy_002dextn>>=hfy-extn= [[#index-hfy_002dextn][¶]] ::

  File extension used for output files.

- <<index-hfy_002ddefault_002dface_002ddef>>=hfy-default-face-def=
  [[#index-hfy_002ddefault_002dface_002ddef][¶]] ::

  Fallback =defface= specification for the face =default=, used when
  [[#hfy_002ddisplay_002dclass][hfy-display-class]] has been set (the
  normal Htmlfontify way of extracting potentially non-current face
  information doesn't necessarily work for =default=).

  For example, I customize this to:

  #+begin_src lisp-preformatted
  ((t :background "black" :foreground "white" :family "misc-fixed"))
  #+end_src

- <<index-hfy_002dinit_002dkludge_002dhook>>=hfy-init-kludge-hook=
  [[#index-hfy_002dinit_002dkludge_002dhook][¶]] ::

  List of functions to call when starting htmlfontify-buffer to do any
  kludging necessary to get highlighting modes to behave as you want,
  even when not running under a window system.

- <<index-hfy_002dshell_002dfile_002dname>>=hfy-shell-file-name=
  [[#index-hfy_002dshell_002dfile_002dname][¶]] ::

  Should be set to a Bourne compatible shell, which will be invoked for
  the more complex shell interactions needed by Htmlfontify. Currently
  this is only required/used when using GNU etags, see
  [[#hfy_002detags_002dcmd_002dalist][hfy-etags-cmd-alist]] for details.

- <<index-hfy_002doptimizations>>=hfy-optimizations=
  [[#index-hfy_002doptimizations][¶]] ::

  Optimizations to turn on. So far, the following have been implemented:

  - =merge-adjacent-tags= :: If two (or more) span tags are adjacent,
    identical and separated by nothing more than whitespace, they will
    be merged into one span.

  - =zap-comment-links= :: Suppress hyperlinking of tags found in
    comments.

  - =zap-string-links= :: Suppress hyperlinking of tags found in
    strings.

  - =div-wrapper= :: Add ‘=<div class="default"> </div>=' tags around
    the fontified body. (Some people like this because they cut and
    paste the html into a page with different colors than the fontified
    code.)

  - =keep-overlays= :: Preserve overlay highlighting (cf. =ediff= or
    =goo-font-lock=) as well as basic faces. Can result in extremely
    verbose highlighting if there are many overlays (as is the case with
    =goo-font-lock=).

  And the following are planned but not yet available:

  - =kill-context-leak= :: Suppress hyperlinking between files
    highlighted by different modes.

  Note: like compiler optimizations, these optimize the /output/ of the
  code, not the processing of the source itself, and are therefore
  likely to slow Htmlfontify down, at least a little. Except for
  skip-refontification, which can never slow you down, but may result in
  incomplete fontification.

- <<index-hfy_002dsrc_002ddoc_002dlink_002dunstyle>>=hfy-src-doc-link-unstyle=
  [[#index-hfy_002dsrc_002ddoc_002dlink_002dunstyle][¶]] ::

  Regex to remove from the ‘=<style> a=' variant of an Htmlfontify CSS
  class.

- <<index-hfy_002dlink_002dextn>>=hfy-link-extn=
  [[#index-hfy_002dlink_002dextn][¶]] ::

  File extension used for href links---useful where the Htmlfontify
  output files are going to be processed again, with a resulting change
  in file extension. If =nil=, then any code using this should fall back
  to [[#hfy_002dextn][hfy-extn]].

- <<index-hfy_002distext_002dcommand>>=hfy-istext-command=
  [[#index-hfy_002distext_002dcommand][¶]] ::

  Command to run with the name of a file, to see whether it is a text
  file or not. The command should emit a string containing the word
  ‘=text=' if the file is a text file, and a string not containing
  ‘=text=' otherwise.

- <<index-hfy_002detags_002dcmd_002dalist>>=hfy-etags-cmd-alist=
  [[#index-hfy_002detags_002dcmd_002dalist][¶]] ::

  An alist of possible shell commands that will generate etags output
  that Htmlfontify can use. ‘=%s=' will be replaced by
  [[#hfy_002detags_002dbin][hfy-etags-bin]].

- <<index-hfy_002detags_002dbin>>=hfy-etags-bin=
  [[#index-hfy_002detags_002dbin][¶]] ::

  The location of the etags binary (we begin by assuming it's in your
  path).

  Note that if etags is not in your path, you will need to alter the
  shell commands in
  [[#hfy_002detags_002dcmd_002dalist][hfy-etags-cmd-alist]].

  [As of version 0.17, this requirement has been removed: it should all
  just work(tm).]

- <<index-hfy_002detags_002dcmd>>=hfy-etags-cmd=
  [[#index-hfy_002detags_002dcmd][¶]] ::

  An etags shell command to run in the source directory to generate a
  tags file for the whole source tree from there on down. The command
  should emit the etags output on standard output.

  Two canned commands are provided---they drive Emacs's etags and
  exuberant-ctags's etags respectively.

- <<index-hfy_002detag_002dregex>>=hfy-etag-regex=
  [[#index-hfy_002detag_002dregex][¶]] ::

  Regex used to parse an etags entry: must have 3 subexps,
  corresponding, in order, to:

  1. The tag
  2. The line
  3. The character (point) at which the tag occurs

- <<index-hfy_002dindex_002dfile>>=hfy-index-file=
  [[#index-hfy_002dindex_002dfile][¶]] ::

  Name (sans extension) of the index file produced during
  fontification-and-hyperlinking.

- <<index-hfy_002dinstance_002dfile>>=hfy-instance-file=
  [[#index-hfy_002dinstance_002dfile][¶]] ::

  Name (sans extension) of the tag usage index file produced during
  fontification-and-hyperlinking.

- <<index-hfy_002dhtml_002dquote_002dmap>>=hfy-html-quote-map=
  [[#index-hfy_002dhtml_002dquote_002dmap][¶]] ::

  An alist of character -> entity mappings used to make the text
  html-safe.

--------------

<<Requirements>>

Next:
[[#GNU-Free-Documentation-License][GNU Free Documentation License]],
Previous: [[#Customization][Customization]], Up: [[#Top][Htmlfontify]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

** 4 Requirements [[#Requirements-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Requirements-1
:CLASS: chapter
:END:
Htmlfontify has a couple of external requirements:

- A copy of etags (exuberant-ctags or GNU etags). Htmlfontify attempts
  to autodetect the version you have and customize itself accordingly,
  but you should be able to override this.

  See: [[#Customization][Customization]]

- A copy of sed (e.g., GNU sed).

- A copy of the =file= command.

--------------

<<GNU-Free-Documentation-License>>

Next: [[#Index][Index]], Previous: [[#Requirements][Requirements]], Up:
[[#Top][Htmlfontify]]   [[[#SEC_Contents][Contents]]][[[#Index][Index]]]

** Appendix A GNU Free Documentation License [[#GNU-Free-Documentation-License-1][¶]]
:PROPERTIES:
:CUSTOM_ID: GNU-Free-Documentation-License-1
:CLASS: appendix
:END:

#+begin_center
Version 1.3, 3 November 2008
#+end_center

#+begin_src display-preformatted
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
https://fsf.org/

Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed.
#+end_src

0. [@0] PREAMBLE

   The purpose of this License is to make a manual, textbook, or other
   functional and useful document /free/ in the sense of freedom: to
   assure everyone the effective freedom to copy and redistribute it,
   with or without modifying it, either commercially or noncommercially.
   Secondarily, this License preserves for the author and publisher a
   way to get credit for their work, while not being considered
   responsible for modifications made by others.

   This License is a kind of “copyleft”, which means that derivative
   works of the document must themselves be free in the same sense. It
   complements the GNU General Public License, which is a copyleft
   license designed for free software.

   We have designed this License in order to use it for manuals for free
   software, because free software needs free documentation: a free
   program should come with manuals providing the same freedoms that the
   software does. But this License is not limited to software manuals;
   it can be used for any textual work, regardless of subject matter or
   whether it is published as a printed book. We recommend this License
   principally for works whose purpose is instruction or reference.

1. APPLICABILITY AND DEFINITIONS

   This License applies to any manual or other work, in any medium, that
   contains a notice placed by the copyright holder saying it can be
   distributed under the terms of this License. Such a notice grants a
   world-wide, royalty-free license, unlimited in duration, to use that
   work under the conditions stated herein. The “Document”, below,
   refers to any such manual or work. Any member of the public is a
   licensee, and is addressed as “you”. You accept the license if you
   copy, modify or distribute the work in a way requiring permission
   under copyright law.

   A “Modified Version” of the Document means any work containing the
   Document or a portion of it, either copied verbatim, or with
   modifications and/or translated into another language.

   A “Secondary Section” is a named appendix or a front-matter section
   of the Document that deals exclusively with the relationship of the
   publishers or authors of the Document to the Document's overall
   subject (or to related matters) and contains nothing that could fall
   directly within that overall subject. (Thus, if the Document is in
   part a textbook of mathematics, a Secondary Section may not explain
   any mathematics.) The relationship could be a matter of historical
   connection with the subject or with related matters, or of legal,
   commercial, philosophical, ethical or political position regarding
   them.

   The “Invariant Sections” are certain Secondary Sections whose titles
   are designated, as being those of Invariant Sections, in the notice
   that says that the Document is released under this License. If a
   section does not fit the above definition of Secondary then it is not
   allowed to be designated as Invariant. The Document may contain zero
   Invariant Sections. If the Document does not identify any Invariant
   Sections then there are none.

   The “Cover Texts” are certain short passages of text that are listed,
   as Front-Cover Texts or Back-Cover Texts, in the notice that says
   that the Document is released under this License. A Front-Cover Text
   may be at most 5 words, and a Back-Cover Text may be at most 25
   words.

   A “Transparent” copy of the Document means a machine-readable copy,
   represented in a format whose specification is available to the
   general public, that is suitable for revising the document
   straightforwardly with generic text editors or (for images composed
   of pixels) generic paint programs or (for drawings) some widely
   available drawing editor, and that is suitable for input to text
   formatters or for automatic translation to a variety of formats
   suitable for input to text formatters. A copy made in an otherwise
   Transparent file format whose markup, or absence of markup, has been
   arranged to thwart or discourage subsequent modification by readers
   is not Transparent. An image format is not Transparent if used for
   any substantial amount of text. A copy that is not “Transparent” is
   called “Opaque”.

   Examples of suitable formats for Transparent copies include plain
   ASCII without markup, Texinfo input format, LaTeX input format, SGML
   or XML using a publicly available DTD, and standard-conforming simple
   HTML, PostScript or PDF designed for human modification. Examples of
   transparent image formats include PNG, XCF and JPG. Opaque formats
   include proprietary formats that can be read and edited only by
   proprietary word processors, SGML or XML for which the DTD and/or
   processing tools are not generally available, and the
   machine-generated HTML, PostScript or PDF produced by some word
   processors for output purposes only.

   The “Title Page” means, for a printed book, the title page itself,
   plus such following pages as are needed to hold, legibly, the
   material this License requires to appear in the title page. For works
   in formats which do not have any title page as such, “Title Page”
   means the text near the most prominent appearance of the work's
   title, preceding the beginning of the body of the text.

   The “publisher” means any person or entity that distributes copies of
   the Document to the public.

   A section “Entitled XYZ” means a named subunit of the Document whose
   title either is precisely XYZ or contains XYZ in parentheses
   following text that translates XYZ in another language. (Here XYZ
   stands for a specific section name mentioned below, such as
   “Acknowledgements”, “Dedications”, “Endorsements”, or “History”.) To
   “Preserve the Title” of such a section when you modify the Document
   means that it remains a section “Entitled XYZ” according to this
   definition.

   The Document may include Warranty Disclaimers next to the notice
   which states that this License applies to the Document. These
   Warranty Disclaimers are considered to be included by reference in
   this License, but only as regards disclaiming warranties: any other
   implication that these Warranty Disclaimers may have is void and has
   no effect on the meaning of this License.

2. VERBATIM COPYING

   You may copy and distribute the Document in any medium, either
   commercially or noncommercially, provided that this License, the
   copyright notices, and the license notice saying this License applies
   to the Document are reproduced in all copies, and that you add no
   other conditions whatsoever to those of this License. You may not use
   technical measures to obstruct or control the reading or further
   copying of the copies you make or distribute. However, you may accept
   compensation in exchange for copies. If you distribute a large enough
   number of copies you must also follow the conditions in section 3.

   You may also lend copies, under the same conditions stated above, and
   you may publicly display copies.

3. COPYING IN QUANTITY

   If you publish printed copies (or copies in media that commonly have
   printed covers) of the Document, numbering more than 100, and the
   Document's license notice requires Cover Texts, you must enclose the
   copies in covers that carry, clearly and legibly, all these Cover
   Texts: Front-Cover Texts on the front cover, and Back-Cover Texts on
   the back cover. Both covers must also clearly and legibly identify
   you as the publisher of these copies. The front cover must present
   the full title with all words of the title equally prominent and
   visible. You may add other material on the covers in addition.
   Copying with changes limited to the covers, as long as they preserve
   the title of the Document and satisfy these conditions, can be
   treated as verbatim copying in other respects.

   If the required texts for either cover are too voluminous to fit
   legibly, you should put the first ones listed (as many as fit
   reasonably) on the actual cover, and continue the rest onto adjacent
   pages.

   If you publish or distribute Opaque copies of the Document numbering
   more than 100, you must either include a machine-readable Transparent
   copy along with each Opaque copy, or state in or with each Opaque
   copy a computer-network location from which the general network-using
   public has access to download using public-standard network protocols
   a complete Transparent copy of the Document, free of added material.
   If you use the latter option, you must take reasonably prudent steps,
   when you begin distribution of Opaque copies in quantity, to ensure
   that this Transparent copy will remain thus accessible at the stated
   location until at least one year after the last time you distribute
   an Opaque copy (directly or through your agents or retailers) of that
   edition to the public.

   It is requested, but not required, that you contact the authors of
   the Document well before redistributing any large number of copies,
   to give them a chance to provide you with an updated version of the
   Document.

4. MODIFICATIONS

   You may copy and distribute a Modified Version of the Document under
   the conditions of sections 2 and 3 above, provided that you release
   the Modified Version under precisely this License, with the Modified
   Version filling the role of the Document, thus licensing distribution
   and modification of the Modified Version to whoever possesses a copy
   of it. In addition, you must do these things in the Modified Version:

   1. Use in the Title Page (and on the covers, if any) a title distinct
      from that of the Document, and from those of previous versions
      (which should, if there were any, be listed in the History section
      of the Document). You may use the same title as a previous version
      if the original publisher of that version gives permission.
   2. List on the Title Page, as authors, one or more persons or
      entities responsible for authorship of the modifications in the
      Modified Version, together with at least five of the principal
      authors of the Document (all of its principal authors, if it has
      fewer than five), unless they release you from this requirement.
   3. State on the Title page the name of the publisher of the Modified
      Version, as the publisher.
   4. Preserve all the copyright notices of the Document.
   5. Add an appropriate copyright notice for your modifications
      adjacent to the other copyright notices.
   6. Include, immediately after the copyright notices, a license notice
      giving the public permission to use the Modified Version under the
      terms of this License, in the form shown in the Addendum below.
   7. Preserve in that license notice the full lists of Invariant
      Sections and required Cover Texts given in the Document's license
      notice.
   8. Include an unaltered copy of this License.
   9. Preserve the section Entitled “History”, Preserve its Title, and
      add to it an item stating at least the title, year, new authors,
      and publisher of the Modified Version as given on the Title Page.
      If there is no section Entitled “History” in the Document, create
      one stating the title, year, authors, and publisher of the
      Document as given on its Title Page, then add an item describing
      the Modified Version as stated in the previous sentence.
   10. Preserve the network location, if any, given in the Document for
       public access to a Transparent copy of the Document, and likewise
       the network locations given in the Document for previous versions
       it was based on. These may be placed in the “History” section.
       You may omit a network location for a work that was published at
       least four years before the Document itself, or if the original
       publisher of the version it refers to gives permission.
   11. For any section Entitled “Acknowledgements” or “Dedications”,
       Preserve the Title of the section, and preserve in the section
       all the substance and tone of each of the contributor
       acknowledgements and/or dedications given therein.
   12. Preserve all the Invariant Sections of the Document, unaltered in
       their text and in their titles. Section numbers or the equivalent
       are not considered part of the section titles.
   13. Delete any section Entitled “Endorsements”. Such a section may
       not be included in the Modified Version.
   14. Do not retitle any existing section to be Entitled “Endorsements”
       or to conflict in title with any Invariant Section.
   15. Preserve any Warranty Disclaimers.

   If the Modified Version includes new front-matter sections or
   appendices that qualify as Secondary Sections and contain no material
   copied from the Document, you may at your option designate some or
   all of these sections as invariant. To do this, add their titles to
   the list of Invariant Sections in the Modified Version's license
   notice. These titles must be distinct from any other section titles.

   You may add a section Entitled “Endorsements”, provided it contains
   nothing but endorsements of your Modified Version by various
   parties---for example, statements of peer review or that the text has
   been approved by an organization as the authoritative definition of a
   standard.

   You may add a passage of up to five words as a Front-Cover Text, and
   a passage of up to 25 words as a Back-Cover Text, to the end of the
   list of Cover Texts in the Modified Version. Only one passage of
   Front-Cover Text and one of Back-Cover Text may be added by (or
   through arrangements made by) any one entity. If the Document already
   includes a cover text for the same cover, previously added by you or
   by arrangement made by the same entity you are acting on behalf of,
   you may not add another; but you may replace the old one, on explicit
   permission from the previous publisher that added the old one.

   The author(s) and publisher(s) of the Document do not by this License
   give permission to use their names for publicity for or to assert or
   imply endorsement of any Modified Version.

5. COMBINING DOCUMENTS

   You may combine the Document with other documents released under this
   License, under the terms defined in section 4 above for modified
   versions, provided that you include in the combination all of the
   Invariant Sections of all of the original documents, unmodified, and
   list them all as Invariant Sections of your combined work in its
   license notice, and that you preserve all their Warranty Disclaimers.

   The combined work need only contain one copy of this License, and
   multiple identical Invariant Sections may be replaced with a single
   copy. If there are multiple Invariant Sections with the same name but
   different contents, make the title of each such section unique by
   adding at the end of it, in parentheses, the name of the original
   author or publisher of that section if known, or else a unique
   number. Make the same adjustment to the section titles in the list of
   Invariant Sections in the license notice of the combined work.

   In the combination, you must combine any sections Entitled “History”
   in the various original documents, forming one section Entitled
   “History”; likewise combine any sections Entitled “Acknowledgements”,
   and any sections Entitled “Dedications”. You must delete all sections
   Entitled “Endorsements.”

6. COLLECTIONS OF DOCUMENTS

   You may make a collection consisting of the Document and other
   documents released under this License, and replace the individual
   copies of this License in the various documents with a single copy
   that is included in the collection, provided that you follow the
   rules of this License for verbatim copying of each of the documents
   in all other respects.

   You may extract a single document from such a collection, and
   distribute it individually under this License, provided you insert a
   copy of this License into the extracted document, and follow this
   License in all other respects regarding verbatim copying of that
   document.

7. AGGREGATION WITH INDEPENDENT WORKS

   A compilation of the Document or its derivatives with other separate
   and independent documents or works, in or on a volume of a storage or
   distribution medium, is called an “aggregate” if the copyright
   resulting from the compilation is not used to limit the legal rights
   of the compilation's users beyond what the individual works permit.
   When the Document is included in an aggregate, this License does not
   apply to the other works in the aggregate which are not themselves
   derivative works of the Document.

   If the Cover Text requirement of section 3 is applicable to these
   copies of the Document, then if the Document is less than one half of
   the entire aggregate, the Document's Cover Texts may be placed on
   covers that bracket the Document within the aggregate, or the
   electronic equivalent of covers if the Document is in electronic
   form. Otherwise they must appear on printed covers that bracket the
   whole aggregate.

8. TRANSLATION

   Translation is considered a kind of modification, so you may
   distribute translations of the Document under the terms of section 4.
   Replacing Invariant Sections with translations requires special
   permission from their copyright holders, but you may include
   translations of some or all Invariant Sections in addition to the
   original versions of these Invariant Sections. You may include a
   translation of this License, and all the license notices in the
   Document, and any Warranty Disclaimers, provided that you also
   include the original English version of this License and the original
   versions of those notices and disclaimers. In case of a disagreement
   between the translation and the original version of this License or a
   notice or disclaimer, the original version will prevail.

   If a section in the Document is Entitled “Acknowledgements”,
   “Dedications”, or “History”, the requirement (section 4) to Preserve
   its Title (section 1) will typically require changing the actual
   title.

9. TERMINATION

   You may not copy, modify, sublicense, or distribute the Document
   except as expressly provided under this License. Any attempt
   otherwise to copy, modify, sublicense, or distribute it is void, and
   will automatically terminate your rights under this License.

   However, if you cease all violation of this License, then your
   license from a particular copyright holder is reinstated (a)
   provisionally, unless and until the copyright holder explicitly and
   finally terminates your license, and (b) permanently, if the
   copyright holder fails to notify you of the violation by some
   reasonable means prior to 60 days after the cessation.

   Moreover, your license from a particular copyright holder is
   reinstated permanently if the copyright holder notifies you of the
   violation by some reasonable means, this is the first time you have
   received notice of violation of this License (for any work) from that
   copyright holder, and you cure the violation prior to 30 days after
   your receipt of the notice.

   Termination of your rights under this section does not terminate the
   licenses of parties who have received copies or rights from you under
   this License. If your rights have been terminated and not permanently
   reinstated, receipt of a copy of some or all of the same material
   does not give you any rights to use it.

10. FUTURE REVISIONS OF THIS LICENSE

    The Free Software Foundation may publish new, revised versions of
    the GNU Free Documentation License from time to time. Such new
    versions will be similar in spirit to the present version, but may
    differ in detail to address new problems or concerns. See
    [[https://www.gnu.org/licenses/]].

    Each version of the License is given a distinguishing version
    number. If the Document specifies that a particular numbered version
    of this License “or any later version” applies to it, you have the
    option of following the terms and conditions either of that
    specified version or of any later version that has been published
    (not as a draft) by the Free Software Foundation. If the Document
    does not specify a version number of this License, you may choose
    any version ever published (not as a draft) by the Free Software
    Foundation. If the Document specifies that a proxy can decide which
    future versions of this License can be used, that proxy's public
    statement of acceptance of a version permanently authorizes you to
    choose that version for the Document.

11. RELICENSING

    “Massive Multiauthor Collaboration Site” (or “MMC Site”) means any
    World Wide Web server that publishes copyrightable works and also
    provides prominent facilities for anybody to edit those works. A
    public wiki that anybody can edit is an example of such a server. A
    “Massive Multiauthor Collaboration” (or “MMC”) contained in the site
    means any set of copyrightable works thus published on the MMC site.

    “CC-BY-SA” means the Creative Commons Attribution-Share Alike 3.0
    license published by Creative Commons Corporation, a not-for-profit
    corporation with a principal place of business in San Francisco,
    California, as well as future copyleft versions of that license
    published by that same organization.

    “Incorporate” means to publish or republish a Document, in whole or
    in part, as part of another Document.

    An MMC is “eligible for relicensing” if it is licensed under this
    License, and if all works that were first published under this
    License somewhere other than this MMC, and subsequently incorporated
    in whole or in part into the MMC, (1) had no cover texts or
    invariant sections, and (2) were thus incorporated prior to November
    1, 2008.

    The operator of an MMC Site may republish an MMC contained in the
    site under CC-BY-SA on the same site at any time before August 1,
    2009, provided the MMC is eligible for relicensing.

*** ADDENDUM: How to use this License for your documents [[#ADDENDUM_003a-How-to-use-this-License-for-your-documents][¶]]
:PROPERTIES:
:CUSTOM_ID: ADDENDUM_003a-How-to-use-this-License-for-your-documents
:CLASS: heading
:END:
To use this License in a document you have written, include a copy of
the License in the document and put the following copyright and license
notices just after the title page:

#+begin_src example-preformatted
  Copyright (C)  year  your name.
  Permission is granted to copy, distribute and/or modify this document
  under the terms of the GNU Free Documentation License, Version 1.3
  or any later version published by the Free Software Foundation;
  with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
  Texts.  A copy of the license is included in the section entitled ``GNU
  Free Documentation License''.
#+end_src

If you have Invariant Sections, Front-Cover Texts and Back-Cover Texts,
replace the “with...Texts.” line with this:

#+begin_src example-preformatted
    with the Invariant Sections being list their titles, with
    the Front-Cover Texts being list, and with the Back-Cover Texts
    being list.
#+end_src

If you have Invariant Sections without Cover Texts, or some other
combination of the three, merge those two alternatives to suit the
situation.

If your document contains nontrivial examples of program code, we
recommend releasing these examples in parallel under your choice of free
software license, such as the GNU General Public License, to permit
their use in free software.

--------------

<<Index>>

Previous:
[[#GNU-Free-Documentation-License][GNU Free Documentation License]], Up:
[[#Top][Htmlfontify]]   [[[#SEC_Contents][Contents]]][[[#Index][Index]]]

** Index [[#Index-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Index-1
:CLASS: unnumbered
:END:
- =Concepts= ::

  | Jump to:   | [[#Index_cp_letter-D][*D*]]   [[#Index_cp_letter-E][*E*]]   [[#Index_cp_letter-F][*F*]]   [[#Index_cp_letter-H][*H*]]   [[#Index_cp_letter-I][*I*]]   [[#Index_cp_letter-N][*N*]]   [[#Index_cp_letter-R][*R*]]   [[#Index_cp_letter-U][*U*]]   [[#Index_cp_letter-V][*V*]]   |

  |                | Index Entry                                                               | Section                                     |
  | -------------- |                                                                           |                                             |
  | D              |                                                                           |                                             |
  |                | [[#index-Data-Structures][Data Structures]]                               | [[#Data-Structures][Data Structures]]       |
  | -------------- |                                                                           |                                             |
  | E              |                                                                           |                                             |
  |                | [[#index-Examples][Examples]]                                             | [[#Examples][Examples]]                     |
  | -------------- |                                                                           |                                             |
  | F              |                                                                           |                                             |
  |                | [[#index-functions-_0028interactive_0029][functions (interactive)]]       | [[#Interactive][Interactive]]               |
  |                | [[#index-functions-_0028noninteractive_0029][functions (noninteractive)]] | [[#Non_002dinteractive][Non-interactive]]   |
  | -------------- |                                                                           |                                             |
  | H              |                                                                           |                                             |
  |                | [[#index-hfy_002dfacemap_002dassoc][=hfy-facemap-assoc=]]                 | [[#Data-Structures][Data Structures]]       |
  |                | [[#index-hfy_002dsheet_002dassoc][=hfy-sheet-assoc=]]                     | [[#Data-Structures][Data Structures]]       |
  |                | [[#index-hfy_002dstyle_002dassoc][=hfy-style-assoc=]]                     | [[#Data-Structures][Data Structures]]       |
  | -------------- |                                                                           |                                             |
  | I              |                                                                           |                                             |
  |                | [[#index-Interactive][Interactive]]                                       | [[#Interactive][Interactive]]               |
  |                | [[#index-Introduction][Introduction]]                                     | [[#Introduction][Introduction]]             |
  | -------------- |                                                                           |                                             |
  | N              |                                                                           |                                             |
  |                | [[#index-Noninteractive][Noninteractive]]                                 | [[#Non_002dinteractive][Non-interactive]]   |
  | -------------- |                                                                           |                                             |
  | R              |                                                                           |                                             |
  |                | [[#index-Requirements_002c-Prerequisites][Requirements, Prerequisites]]   | [[#Requirements][Requirements]]             |
  | -------------- |                                                                           |                                             |
  | U              |                                                                           |                                             |
  |                | [[#index-Usage-_0026-Examples][Usage & Examples]]                         | [[#Usage-_0026-Examples][Usage & Examples]] |
  | -------------- |                                                                           |                                             |
  | V              |                                                                           |                                             |
  |                | [[#index-variables][variables]]                                           | [[#Variables][Variables]]                   |
  |                | [[#index-variables-_0028customization_0029][variables (customization)]]   | [[#Customization][Customization]]           |
  | -------------- |                                                                           |                                             |

  | Jump to:   | [[#Index_cp_letter-D][*D*]]   [[#Index_cp_letter-E][*E*]]   [[#Index_cp_letter-F][*F*]]   [[#Index_cp_letter-H][*H*]]   [[#Index_cp_letter-I][*I*]]   [[#Index_cp_letter-N][*N*]]   [[#Index_cp_letter-R][*R*]]   [[#Index_cp_letter-U][*U*]]   [[#Index_cp_letter-V][*V*]]   |

- =Functions= ::

  |                | Index Entry                                                                               | Section                                   |
  | -------------- |                                                                                           |                                           |
  | H              |                                                                                           |                                           |
  |                | [[#index-hfy_002dbgcol][=hfy-bgcol=]]                                                     | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dbox][=hfy-box=]]                                                         | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dbox_002dto_002dborder_002dassoc][=hfy-box-to-border-assoc=]]             | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dbox_002dto_002dstyle][=hfy-box-to-style=]]                               | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dbuffer][=hfy-buffer=]]                                                   | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dcolor][=hfy-color=]]                                                     | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dcolor_002dvals][=hfy-color-vals=]]                                       | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dcombined_002dface_002dspec][=hfy-combined-face-spec=]]                   | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dcompile_002dface_002dmap][=hfy-compile-face-map=]]                       | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dcompile_002dstylesheet][=hfy-compile-stylesheet=]]                       | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dcopy_002dand_002dfontify_002dfile][=hfy-copy-and-fontify-file=]]         | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dcss_002dname][=hfy-css-name=]]                                           | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002ddecor][=hfy-decor=]]                                                     | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002ddefault_002dfooter][=hfy-default-footer=]]                               | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002ddefault_002dheader][=hfy-default-header=]]                               | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002ddirname][=hfy-dirname=]]                                                 | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dface_002dat][=hfy-face-at=]]                                             | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dface_002dattr_002dfor_002dclass][=hfy-face-attr-for-class=]]             | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dface_002dto_002dcss][=hfy-face-to-css=]]                                 | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dface_002dto_002dstyle][=hfy-face-to-style=]]                             | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dface_002dto_002dstyle_002di][=hfy-face-to-style-i=]]                     | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dfallback_002dcolor_002dvalues][=hfy-fallback-color-values=]]             | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dfamily][=hfy-family=]]                                                   | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dflatten_002dstyle][=hfy-flatten-style=]]                                 | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dfontified_002dp][=hfy-fontified-p=]]                                     | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dfontify_002dbuffer][=hfy-fontify-buffer=]]                               | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dforce_002dfontification][=hfy-force-fontification=]]                     | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dhref][=hfy-href=]]                                                       | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dhref_002dstub][=hfy-href-stub=]]                                         | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dhtml_002ddekludge_002dbuffer][=hfy-html-dekludge-buffer=]]               | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dhtml_002denkludge_002dbuffer][=hfy-html-enkludge-buffer=]]               | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dhtml_002dquote][=hfy-html-quote=]]                                       | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dinterq][=hfy-interq=]]                                                   | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dkludge_002dcperl_002dmode][=hfy-kludge-cperl-mode=]]                     | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dline_002dnumber][=hfy-line-number=]]                                     | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dlink_002dstyle][=hfy-link-style=]]                                       | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dlink_002dstyle_002dstring][=hfy-link-style-string=]]                     | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dlist_002dfiles][=hfy-list-files=]]                                       | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dload_002dtags_002dcache][=hfy-load-tags-cache=]]                         | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dlookup][=hfy-lookup=]]                                                   | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dmake_002ddirectory][=hfy-make-directory=]]                               | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dmark_002dtag_002dhrefs][=hfy-mark-tag-hrefs=]]                           | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dmark_002dtag_002dnames][=hfy-mark-tag-names=]]                           | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dmerge_002dadjacent_002dspans][=hfy-merge-adjacent-spans=]]               | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dopt][=hfy-opt=]]                                                         | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dp_002dto_002dface][=hfy-p-to-face=]]                                     | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dparse_002dtags_002dbuffer][=hfy-parse-tags-buffer=]]                     | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dprepare_002dindex][=hfy-prepare-index=]]                                 | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dprepare_002dindex_002di][=hfy-prepare-index-i=]]                         | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dprepare_002dtag_002dmap][=hfy-prepare-tag-map=]]                         | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002drelstub][=hfy-relstub=]]                                                 | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dshell][=hfy-shell=]]                                                     | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dsize][=hfy-size=]]                                                       | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dsize_002dto_002dint][=hfy-size-to-int=]]                                 | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dslant][=hfy-slant=]]                                                     | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dsprintf_002dstylesheet][=hfy-sprintf-stylesheet=]]                       | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dsubtract_002dmaps][=hfy-subtract-maps=]]                                 | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dtags_002dfor_002dfile][=hfy-tags-for-file=]]                             | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dtext_002dp][=hfy-text-p=]]                                               | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dtriplet][=hfy-triplet=]]                                                 | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dweight][=hfy-weight=]]                                                   | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dwidth][=hfy-width=]]                                                     | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-hfy_002dword_002dregex][=hfy-word-regex=]]                                       | [[#Non_002dinteractive][Non-interactive]] |
  |                | [[#index-htmlfontify_002dbuffer][=htmlfontify-buffer=]]                                   | [[#Interactive][Interactive]]             |
  |                | [[#index-htmlfontify_002dcopy_002dand_002dlink_002ddir][=htmlfontify-copy-and-link-dir=]] | [[#Interactive][Interactive]]             |
  |                | [[#index-htmlfontify_002dload_002drgb_002dfile][=htmlfontify-load-rgb-file=]]             | [[#Interactive][Interactive]]             |
  |                | [[#index-htmlfontify_002drun_002detags][=htmlfontify-run-etags=]]                         | [[#Interactive][Interactive]]             |
  |                | [[#index-htmlfontify_002dunload_002drgb_002dfile][=htmlfontify-unload-rgb-file=]]         | [[#Interactive][Interactive]]             |
  | -------------- |                                                                                           |                                           |

- =Variables & Customization= ::

  |                | Index Entry                                                                     | Section                           |
  | -------------- |                                                                                 |                                   |
  | H              |                                                                                 |                                   |
  |                | [[#index-hfy_002ddefault_002dface_002ddef][=hfy-default-face-def=]]             | [[#Customization][Customization]] |
  |                | [[#index-hfy_002ddisplay_002dclass][=hfy-display-class=]]                       | [[#Customization][Customization]] |
  |                | [[#index-hfy_002detag_002dregex][=hfy-etag-regex=]]                             | [[#Customization][Customization]] |
  |                | [[#index-hfy_002detags_002dbin][=hfy-etags-bin=]]                               | [[#Customization][Customization]] |
  |                | [[#index-hfy_002detags_002dcmd][=hfy-etags-cmd=]]                               | [[#Customization][Customization]] |
  |                | [[#index-hfy_002detags_002dcmd_002dalist][=hfy-etags-cmd-alist=]]               | [[#Customization][Customization]] |
  |                | [[#index-hfy_002dexclude_002dfile_002drules][=hfy-exclude-file-rules=]]         | [[#Customization][Customization]] |
  |                | [[#index-hfy_002dextn][=hfy-extn=]]                                             | [[#Customization][Customization]] |
  |                | [[#index-hfy_002dhtml_002dquote_002dmap][=hfy-html-quote-map=]]                 | [[#Customization][Customization]] |
  |                | [[#index-hfy_002dhtml_002dquote_002dregex][=hfy-html-quote-regex=]]             | [[#Customization][Customization]] |
  |                | [[#index-hfy_002dindex_002dfile][=hfy-index-file=]]                             | [[#Customization][Customization]] |
  |                | [[#index-hfy_002dinit_002dkludge_002dhook][=hfy-init-kludge-hook=]]             | [[#Customization][Customization]] |
  |                | [[#index-hfy_002dinstance_002dfile][=hfy-instance-file=]]                       | [[#Customization][Customization]] |
  |                | [[#index-hfy_002distext_002dcommand][=hfy-istext-command=]]                     | [[#Customization][Customization]] |
  |                | [[#index-hfy_002dlink_002dextn][=hfy-link-extn=]]                               | [[#Customization][Customization]] |
  |                | [[#index-hfy_002dlink_002dstyle_002dfun][=hfy-link-style-fun=]]                 | [[#Customization][Customization]] |
  |                | [[#index-hfy_002doptimizations][=hfy-optimizations=]]                           | [[#Customization][Customization]] |
  |                | [[#index-hfy_002dpage_002dfooter][=hfy-page-footer=]]                           | [[#Customization][Customization]] |
  |                | [[#index-hfy_002dpage_002dheader][=hfy-page-header=]]                           | [[#Customization][Customization]] |
  |                | [[#index-hfy_002dshell_002dfile_002dname][=hfy-shell-file-name=]]               | [[#Customization][Customization]] |
  |                | [[#index-hfy_002dsplit_002dindex][=hfy-split-index=]]                           | [[#Customization][Customization]] |
  |                | [[#index-hfy_002dsrc_002ddoc_002dlink_002dstyle][=hfy-src-doc-link-style=]]     | [[#Customization][Customization]] |
  |                | [[#index-hfy_002dsrc_002ddoc_002dlink_002dunstyle][=hfy-src-doc-link-unstyle=]] | [[#Customization][Customization]] |
  |                | [[#index-hfy_002dtags_002dcache][=hfy-tags-cache=]]                             | [[#Variables][Variables]]         |
  |                | [[#index-hfy_002dtags_002drmap][=hfy-tags-rmap=]]                               | [[#Variables][Variables]]         |
  |                | [[#index-hfy_002dtags_002dsortl][=hfy-tags-sortl=]]                             | [[#Variables][Variables]]         |
  | -------------- |                                                                                 |                                   |
