<<Top>>

Next: [[#Overview][Overview]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

* Interactive Do [[#Interactive-Do][¶]]
:PROPERTIES:
:CUSTOM_ID: Interactive-Do
:CLASS: top
:END:
This file documents the Ido package for GNU Emacs.

Copyright © 2013--2026 Free Software Foundation, Inc.

#+begin_quote
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being “A GNU Manual”, and
with the Back-Cover Texts as in (a) below. A copy of the license is
included in the section entitled “GNU Free Documentation License”.

(a) The FSF's Back-Cover Text is: “You have the freedom to copy and
modify this GNU manual.”
#+end_quote

<<SEC_Contents>>
** Table of Contents
:PROPERTIES:
:CUSTOM_ID: table-of-contents
:CLASS: contents-heading
:END:

- [[#Overview][1 Overview]]
  - [[#Activation][1.1 Activation]]
  - [[#Working-Directories][1.2 Working Directories]]
- [[#Matching][2 Matching]]
  - [[#Interactive-Substring-Matching][2.1 Interactive Substring Matching]]
  - [[#Prefix-Matching][2.2 Prefix Matching]]
  - [[#Flexible-Matching][2.3 Flexible Matching]]
  - [[#Regexp-Matching][2.4 Regular Expression Matching]]
- [[#Highlighting][3 Highlighting]]
- [[#Hidden-Buffers-and-Files][4 Hidden Buffers and Files]]
- [[#Customization][5 Customization]]
  - [[#Changing-List-Order][5.1 Changing List Order]]
  - [[#Find-File-At-Point][5.2 Find File At Point]]
  - [[#Ignoring][5.3 Ignoring Buffers and Files]]
  - [[#Misc-Customization][5.4 Miscellaneous Customization]]
- [[#Misc][6 Miscellaneous]]
  - [[#All-Matching][6.1 All Matching]]
  - [[#Replacement][6.2 Replacement]]
  - [[#Other-Packages][6.3 Other Packages]]
- [[#GNU-Free-Documentation-License][Appendix A GNU Free Documentation License]]
- [[#Function-Index][Function Index]]
- [[#Variable-Index][Variable Index]]

--------------

<<Overview>>

Next: [[#Matching][Matching]], Previous: [[#Top][Interactive Do]], Up:
[[#Top][Interactive Do]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

** 1 Overview [[#Overview-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Overview-1
:CLASS: chapter
:END:
This document describes a set of features that can interactively do
things with buffers and files. All the features are described here in
detail.

The /Ido/ package lets you switch between buffers and visit files and
directories with a minimum of keystrokes. It is a superset of Iswitchb,
the interactive buffer switching package by Stephen Eglen.

This package was originally written by Kim F. Storm, based on the
=iswitchb.el= package by Stephen Eglen.

- [[#Activation][Activation]]
- [[#Working-Directories][Working Directories]]

--------------

<<Activation>>

Next: [[#Working-Directories][Working Directories]], Up:
[[#Overview][Overview]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

*** 1.1 Activation [[#Activation-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Activation-1
:CLASS: section
:END:
This package is distributed with Emacs, so there is no need to install
any additional files in order to start using it. To activate, use M-x
ido-mode.

You may wish to add the following expressions to your initialization
file (see
[[https://www.gnu.org/software/emacs/manual/html_mono/emacs.html#Init-File][The Emacs Initialization File]]
in GNU Emacs Manual), if you make frequent use of features from this
package.

#+begin_src example-preformatted
(require 'ido)
(ido-mode t)
#+end_src

--------------

<<Working-Directories>>

Previous: [[#Activation][Activation]], Up: [[#Overview][Overview]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

*** 1.2 Working Directories [[#Working-Directories-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Working-Directories-1
:CLASS: section
:END:
/Working directories/ are directories where files have most recently
been opened. The current directory is inserted at the front of this
=ido-work-directory-list= whenever a file is opened with =ido-find-file=
and other file-related functions.

- User Option: *ido-max-work-directory-list*
  [[#index-ido_002dmax_002dwork_002ddirectory_002dlist][¶]] :: This user
  option specifies maximum number of working directories to record.

- User Option: *ido-max-dir-file-cache*
  [[#index-ido_002dmax_002ddir_002dfile_002dcache][¶]] :: This user
  option specifies maximum number of working directories to be cached.
  This is the size of the cache of =file-name-all-completions= results.
  Each cache entry is time stamped with the modification time of the
  directory. Some systems, like MS-Windows, have unreliable directory
  modification times, so you may choose to disable caching on such
  systems, or explicitly refresh the cache contents using the command
  =ido-reread-directory= (usually C-l) in the minibuffer.

--------------

<<Matching>>

Next: [[#Highlighting][Highlighting]], Previous:
[[#Overview][Overview]], Up: [[#Top][Interactive Do]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

** 2 Matching [[#Matching-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Matching-1
:CLASS: chapter
:END:
This section describes features of this package that have to do with
various kinds of /matching/: among buffers, files, and directories.

- [[#Interactive-Substring-Matching][Interactive Substring Matching]]
- [[#Prefix-Matching][Prefix Matching]]
- [[#Flexible-Matching][Flexible Matching]]
- [[#Regexp-Matching][Regular Expression Matching]]

--------------

<<Interactive-Substring-Matching>>

Next: [[#Prefix-Matching][Prefix Matching]], Up: [[#Matching][Matching]]
  [[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

*** 2.1 Interactive Substring Matching [[#Interactive-Substring-Matching-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Interactive-Substring-Matching-1
:CLASS: section
:END:
As you type in a substring, the list of buffers or files currently
matching the substring is displayed as you type. The list is ordered so
that the most recent buffers or files visited come at the start of the
list.

The buffer or file at the start of the list will be the one visited when
you press RET. By typing more of the substring, the list is narrowed
down so that gradually the buffer or file you want will be at the top of
the list. Alternatively, you can use C-s and C-r (or the right and left
arrow keys) to rotate buffer or file names in the list until the one you
want is at the top of the list.

Completion is also available so that you can see what is common to all
of the matching buffers or files as you type.

For example, if there are two buffers called =123456= and =123=, with
=123456= the most recent, when using =ido-switch-buffer=, you first of
all get presented with the list of all the buffers

#+begin_src example-preformatted
Buffer: {123456 | 123}
#+end_src

If you then press 2:

#+begin_src example-preformatted
Buffer: 2[3]{123456 | 123}
#+end_src

The items listed in {...} are the matching buffers, most recent first
(buffers visible in the current frame are put at the end of the list by
default). At any time you can select the item at the head of the list by
pressing RET. You can also put the first element at the end of the list
by pressing C-s or RIGHT, or bring the last element to the head of the
list by pressing C-r or LEFT.

The item in [...] indicates what can be added to your input by pressing
TAB (=ido-complete=). In this case, you will get "3" added to your
input.

So, press TAB:

#+begin_src example-preformatted
Buffer: 23{123456 | 123}
#+end_src

At this point, you still have two matching buffers. If you want the
first buffer in the list, you can simply press RET. If you want the
second in the list, you can press C-s to move it to the top of the list
and then press RET to select it.

However, if you type 4, you'll only have one match left:

#+begin_src example-preformatted
Buffer: 234[123456]
#+end_src

Since there is only one matching buffer left, it is given in [] and it
is shown in the =ido-only-match= face (ForestGreen). You can now press
TAB or RET to go to that buffer.

If you want to create a new buffer named =234=, you can press C-j
(=ido-select-text=) instead of TAB or RET.

If instead, you type a:

#+begin_src example-preformatted
Buffer: 234a [No match]
#+end_src

There are no matching buffers. If you press RET or TAB, you can be
prompted to create a new buffer called =234a=.

Of course, where this function really comes in handy is when you can
specify the buffer using only a few keystrokes. In the above example,
the quickest way to get to the =123456= file would be just to type 4 and
then RET (assuming there isn't any newer buffer with 4 in its name).

Likewise, if you use C-x C-f (=ido-find-file=), the list of files and
directories in the current directory is provided in the same fashion as
the buffers above. The files and directories are normally sorted in
alphabetical order, but the most recently visited directory is placed
first to speed up navigating to directories that you have visited
recently.

In addition to scrolling through the list using <right> and <left>, you
can use <up> and <down> to quickly scroll the list to the next or
previous subdirectory.

To go down into a subdirectory and continue the file selection on the
files in that directory, simply move the directory to the head of the
list and hit RET.

To go up to the parent directory, delete any partial file name already
specified (e.g., using DEL) and hit DEL.

To go to the root directory (on the current drive), enter two slashes.
On MS-DOS or Windows, to select the root of another drive, enter ‘=X:/='
where ‘=X=' is the drive letter. To go to the home directory, enter
‘=~/='. To enter Dired for this directory, use C-d.

You can also visit files on other hosts using the ange-ftp notations
‘=/host:=' and ‘=/user@host:='.

You can type M-p and M-n to change to previous/next directories from the
history, M-s to search for a file matching your input, and M-k to remove
the current directory from the history.

If for some reason you cannot specify the proper file using
=ido-find-file=, you can press C-f to enter the normal =find-file=. You
can also press C-b to drop into =ido-switch-buffer=.

--------------

<<Prefix-Matching>>

Next: [[#Flexible-Matching][Flexible Matching]], Previous:
[[#Interactive-Substring-Matching][Interactive Substring Matching]], Up:
[[#Matching][Matching]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

*** 2.2 Prefix Matching [[#Prefix-Matching-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Prefix-Matching-1
:CLASS: section
:END:
The standard way of completion with *nix shells and Emacs is to insert a
/prefix/ and then hitting TAB (or another completion key). Because this
behavior has become second nature to a lot of Emacs users, Ido offers,
in addition to the default substring matching method (see above), also
the prefix matching method. The kind of matching is the only difference
to the description of the substring matching above.

You can toggle prefix matching with C-p (=ido-toggle-prefix=).

For example, if you have two buffers =123456= and =123= then hitting 2
does not match because 2 is not a prefix in any of the buffer names.

--------------

<<Flexible-Matching>>

Next: [[#Regexp-Matching][Regular Expression Matching]], Previous:
[[#Prefix-Matching][Prefix Matching]], Up: [[#Matching][Matching]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

*** 2.3 Flexible Matching [[#Flexible-Matching-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Flexible-Matching-1
:CLASS: section
:END:
- User Option: *ido-enable-flex-matching*
  [[#index-ido_002denable_002dflex_002dmatching][¶]] :: If non-=nil=,
  Ido will do flexible string matching. Flexible matching means that if
  the entered string does not match any item, any item containing the
  entered characters in the given sequence will match.

If =ido-enable-flex-matching= is non-=nil=, Ido will do a more flexible
matching (unless regexp matching is active) to find possible matches
among the available buffer or file names if no matches are found using
the normal prefix or substring matching.

The flexible matching implies that any item which simply contains all of
the entered characters in the specified sequence will match.

For example, if you have four files =alpha=, =beta=, =gamma=, and
=delta=, entering ‘=aa=' will match =alpha= and =gamma=, while ‘=ea='
matches =beta= and =delta=. If prefix matching is also active, ‘=aa='
only matches =alpha=, while ‘=ea=' does not match any files.

--------------

<<Regexp-Matching>>

Previous: [[#Flexible-Matching][Flexible Matching]], Up:
[[#Matching][Matching]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

*** 2.4 Regular Expression Matching [[#Regular-Expression-Matching][¶]]
:PROPERTIES:
:CUSTOM_ID: Regular-Expression-Matching
:CLASS: section
:END:
There is limited provision for regexp matching within Ido, enabled
through =ido-enable-regexp= (toggle with C-t). This allows you to type
‘=[ch]$=' for example and see all file names ending in ‘=c=' or ‘=h='.

- User Option: *ido-enable-regexp*
  [[#index-ido_002denable_002dregexp][¶]] ::

  If the value of this user option is non-=nil=, Ido will do regexp
  matching. The value of this user option can be toggled within ido-mode
  using =ido-toggle-regexp=.

*Please note:* Ido-style completion is inhibited when you enable regexp
matching.

--------------

<<Highlighting>>

Next: [[#Hidden-Buffers-and-Files][Hidden Buffers and Files]], Previous:
[[#Matching][Matching]], Up: [[#Top][Interactive Do]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

** 3 Highlighting [[#Highlighting-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Highlighting-1
:CLASS: chapter
:END:
The highlighting of matching items is controlled via =ido-use-faces=.
The faces used are =ido-first-match=, =ido-only-match= and =ido-subdir=.

Coloring of the matching items was suggested by Carsten Dominik.

--------------

<<Hidden-Buffers-and-Files>>

Next: [[#Customization][Customization]], Previous:
[[#Highlighting][Highlighting]], Up: [[#Top][Interactive Do]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

** 4 Hidden Buffers and Files [[#Hidden-Buffers-and-Files-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Hidden-Buffers-and-Files-1
:CLASS: chapter
:END:
Normally, Ido does not include hidden buffers (whose names start with a
space) and hidden files and directories (whose names start with =.=) in
the list of possible completions. However, if the substring you enter
does not match any of the visible buffers or files, Ido will
automatically look for completions among the hidden buffers or files.

You can toggle the display of hidden buffers and files with C-a
(=ido-toggle-ignore=).

--------------

<<Customization>>

Next: [[#Misc][Miscellaneous]], Previous:
[[#Hidden-Buffers-and-Files][Hidden Buffers and Files]], Up:
[[#Top][Interactive Do]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

** 5 Customization [[#Customization-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Customization-1
:CLASS: chapter
:END:
You can customize the =ido= group to change Ido functionality:

#+begin_src example-preformatted
M-x customize-group RET ido RET
#+end_src

or customize a certain variable:

#+begin_src example-preformatted
M-x customize-variable RET ido-xxxxx RET
#+end_src

To modify the key bindings, use the =ido-setup-hook=. For example:

#+begin_src example-preformatted
(add-hook 'ido-setup-hook 'ido-my-keys)

(defun ido-my-keys ()
 "Add my key bindings for Ido."
 (keymap-set ido-completion-map "SPC" 'ido-next-match))
#+end_src

- [[#Changing-List-Order][Changing List Order]]
- [[#Find-File-At-Point][Find File At Point]]
- [[#Ignoring][Ignoring Buffers and Files]]
- [[#Misc-Customization][Miscellaneous Customization]]

--------------

<<Changing-List-Order>>

Next: [[#Find-File-At-Point][Find File At Point]], Up:
[[#Customization][Customization]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

*** 5.1 Changing List Order [[#Changing-List-Order-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Changing-List-Order-1
:CLASS: section
:END:
By default, the list of current files is most recent first, oldest last,
with the exception that the files visible in the current frame are put
at the end of the list. A hook exists to allow other functions to order
the list. For example, if you add:

#+begin_src example-preformatted
(add-hook 'ido-make-buffer-list-hook 'ido-summary-buffers-to-end)
#+end_src

then all files matching "Summary" are moved to the end of the list. (I
find this handy for keeping the INBOX Summary and so on out of the way.)
It also moves files matching ‘=output\*$=' to the end of the list (these
are created by AUCTeX when compiling.) Other functions could be made
available which alter the list of matching files (either deleting or
rearranging elements.)

--------------

<<Find-File-At-Point>>

Next: [[#Ignoring][Ignoring Buffers and Files]], Previous:
[[#Changing-List-Order][Changing List Order]], Up:
[[#Customization][Customization]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

*** 5.2 Find File At Point [[#Find-File-At-Point-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Find-File-At-Point-1
:CLASS: section
:END:
Find File At Point, also known generally as “ffap”, is an intelligent
system for opening files and URLs.

The following expression will make Ido guess the context:

#+begin_src example-preformatted
(setq ido-use-filename-at-point 'guess)
#+end_src

You can disable URL ffap support by toggling =ido-use-url-at-point=.

- User Option: *ido-use-url-at-point*
  [[#index-ido_002duse_002durl_002dat_002dpoint][¶]] :: If the value of
  this user option is non-=nil=, Ido will look for a URL at point. If
  found, call =find-file-at-point= to visit it.

--------------

<<Ignoring>>

Next: [[#Misc-Customization][Miscellaneous Customization]], Previous:
[[#Find-File-At-Point][Find File At Point]], Up:
[[#Customization][Customization]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

*** 5.3 Ignoring Buffers and Files [[#Ignoring-Buffers-and-Files][¶]]
:PROPERTIES:
:CUSTOM_ID: Ignoring-Buffers-and-Files
:CLASS: section
:END:
Ido is capable of ignoring buffers, directories, files and extensions
using regular expressions.

- User Option: *ido-ignore-buffers*
  [[#index-ido_002dignore_002dbuffers][¶]] :: This variable takes a list
  of regular expressions for buffers to ignore in =ido-switch-buffer=.

- User Option: *ido-ignore-directories*
  [[#index-ido_002dignore_002ddirectories][¶]] :: This variable takes a
  list of regular expressions for (sub)directories names to ignore in
  =ido-dired= and =ido-find-file=.

- User Option: *ido-ignore-files*
  [[#index-ido_002dignore_002dfiles][¶]] :: This variable takes a list
  of regular expressions for files to ignore in =ido-find-file=.

- User Option: *ido-ignore-unc-host-regexps*
  [[#index-ido_002dignore_002dunc_002dhost_002dregexps][¶]] :: This
  variable takes a list of regular expressions matching UNC hosts to
  ignore. The letter case will be ignored if =ido-downcase-unc-hosts= is
  non-=nil=.

To make Ido use =completion-ignored-extensions= you need to enable it:

#+begin_src example-preformatted
(setq ido-ignore-extensions t)
#+end_src

Now you can customize =completion-ignored-extensions= as well. Go ahead
and add all the useless object files, backup files, shared library files
and other computing flotsam you don't want Ido to show.

*Please note:* Ido will still complete the ignored elements if it would
otherwise not show any other matches. So if you type out the name of an
ignored file, Ido will still let you open it just fine.

--------------

<<Misc-Customization>>

Previous: [[#Ignoring][Ignoring Buffers and Files]], Up:
[[#Customization][Customization]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

*** 5.4 Miscellaneous Customization [[#Miscellaneous-Customization][¶]]
:PROPERTIES:
:CUSTOM_ID: Miscellaneous-Customization
:CLASS: section
:END:
- User Option: *ido-mode* [[#index-ido_002dmode][¶]] :: This user option
  determines for which functional group (buffer and files) Ido behavior
  should be enabled.

- User Option: *ido-case-fold* [[#index-ido_002dcase_002dfold][¶]] :: If
  the value of this user option is non-=nil=, searching of buffer and
  file names should ignore case.

- User Option: *ido-show-dot-for-dired*
  [[#index-ido_002dshow_002ddot_002dfor_002ddired][¶]] :: If the value
  of this user option is non-=nil=, always put ‘=.=' as the first item
  in file name lists. This allows the current directory to be opened
  immediately with Dired

- User Option: *ido-enable-dot-prefix*
  [[#index-ido_002denable_002ddot_002dprefix][¶]] :: If the value of
  this user option is non-=nil=, Ido will match leading dot as prefix.
  I.e., hidden files and buffers will match only if you type a dot as
  first char (even if =ido-enable-prefix= is =nil=).

- User Option: *ido-confirm-unique-completion*
  [[#index-ido_002dconfirm_002dunique_002dcompletion][¶]] :: If the
  value of this user option is non-=nil=, even a unique completion must
  be confirmed. This means that =ido-complete= (TAB) must always be
  followed by =ido-exit-minibuffer= (RET) even when there is only one
  unique completion.

- User Option: *ido-cannot-complete-command*
  [[#index-ido_002dcannot_002dcomplete_002dcommand][¶]] :: When
  =ido-complete= can't complete any more, it will run the command
  specified by this user option. The most useful values are
  =ido-completion-help=, which pops up a window with completion
  alternatives, or =ido-next-match= or =ido-prev-match=, which cycle the
  buffer list.

- User Option: *ido-max-file-prompt-width*
  [[#index-ido_002dmax_002dfile_002dprompt_002dwidth][¶]] :: This user
  option specifies the upper limit of the prompt string. If its value is
  an integer, it specifies the number of characters of the string. If
  its value is a floating point number, it specifies a fraction of the
  frame width.

- User Option: *ido-max-window-height*
  [[#index-ido_002dmax_002dwindow_002dheight][¶]] :: If the value of
  this user option is non-=nil=, its value will override the variable
  =max-mini-window-height=, which is the maximum height for resizing
  mini-windows (the minibuffer and the echo area). If it's a floating
  point number, it specifies a fraction of the mini-window frame's
  height. If it's an integer, it specifies the number of lines.

- User Option: *ido-record-commands*
  [[#index-ido_002drecord_002dcommands][¶]] :: If the value of this user
  option is non-=nil=, Ido will record commands in the variable
  =command-history=. Note that non-Ido equivalent is recorded.

- User Option: *ido-all-frames*
  [[#index-ido_002dall_002dframes][¶]] :: This user option will be
  passed to =walk-windows= as its =all-frames= argument when Ido is
  finding buffers. See
  [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#Cyclic-Window-Ordering][Cyclic Ordering of Windows]]
  in GNU Emacs Lisp Reference Manual.

- User Option: *ido-minibuffer-setup-hook*
  [[#index-ido_002dminibuffer_002dsetup_002dhook][¶]] :: This hook
  variable contains Ido-specific customization of minibuffer setup. It
  is run during minibuffer setup if Ido is active, and is intended for
  use in customizing ido for interoperation with other packages.

--------------

<<Misc>>

Next:
[[#GNU-Free-Documentation-License][GNU Free Documentation License]],
Previous: [[#Customization][Customization]], Up:
[[#Top][Interactive Do]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

** 6 Miscellaneous [[#Miscellaneous][¶]]
:PROPERTIES:
:CUSTOM_ID: Miscellaneous
:CLASS: chapter
:END:
After C-x b (=ido-switch-buffer=), the buffer at the head of the list
can be killed by pressing C-k. If the buffer needs saving, you will be
queried before the buffer is killed. C-S-b buries the buffer at the end
of the list.

Likewise, after C-x C-f, you can delete (i.e., physically remove) the
file at the head of the list with C-k. You will always be asked for
confirmation before deleting the file.

If you enter C-x b to switch to a buffer visiting a given file, and you
find that the file you are after is not in any buffer, you can press C-f
to immediately drop into =ido-find-file=. You can switch back to buffer
selection with C-b.

You can also use Ido in your Emacs Lisp programs:

#+begin_src example-preformatted
(setq my-pkgs (list "CEDET" "Gnus" "Rcirc" "Tramp" "Org" "all-of-them"))
(ido-completing-read "What's your favorite package? " my-pkgs)
#+end_src

- [[#All-Matching][All Matching]]
- [[#Replacement][Replacement]]
- [[#Other-Packages][Other Packages]]

--------------

<<All-Matching>>

Next: [[#Replacement][Replacement]], Up: [[#Misc][Miscellaneous]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

*** 6.1 All Matching [[#All-Matching-1][¶]]
:PROPERTIES:
:CUSTOM_ID: All-Matching-1
:CLASS: section
:END:
If you have many matching files, they may not all fit onto one line of
the minibuffer. Normally, the minibuffer window will grow to show you
more of the matching files (depending on the value of the variables
=resize-mini-windows= and =max-mini-window-height=). If you want Ido to
behave differently from the default minibuffer resizing behavior, set
the variable =ido-max-window-height=.

Also, to improve the responsiveness of Ido, the maximum number of
matching items is limited to 12, but you can increase or remove this
limit via the =ido-max-prospects= user option.

To see a full list of all matching buffers in a separate buffer, hit ?
or press TAB when there are no further completions to the substring.
Repeated TAB presses will scroll you through this separate buffer.

--------------

<<Replacement>>

Next: [[#Other-Packages][Other Packages]], Previous:
[[#All-Matching][All Matching]], Up: [[#Misc][Miscellaneous]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

*** 6.2 Replacement [[#Replacement-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Replacement-1
:CLASS: section
:END:
=ido-read-buffer= and =ido-read-file-name= have been written to be
drop-in replacements for the normal buffer and file name reading
functions =read-buffer= and =read-file-name=.

To use ido for all buffer and file selections in Emacs, customize the
variable =ido-everywhere=.

--------------

<<Other-Packages>>

Previous: [[#Replacement][Replacement]], Up: [[#Misc][Miscellaneous]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

*** 6.3 Other Packages [[#Other-Packages-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Other-Packages-1
:CLASS: section
:END:
If you don't want to rely on the =ido-everywhere= functionality,
=ido-read-buffer=, =ido-read-file-name=, and =ido-read-directory-name=
can be used by other packages to read a buffer name, a file name, or a
directory name in the /Ido/ way.

--------------

<<GNU-Free-Documentation-License>>

Next: [[#Function-Index][Function Index]], Previous:
[[#Misc][Miscellaneous]], Up: [[#Top][Interactive Do]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

** Appendix A GNU Free Documentation License [[#GNU-Free-Documentation-License-1][¶]]
:PROPERTIES:
:CUSTOM_ID: GNU-Free-Documentation-License-1
:CLASS: appendix
:END:

#+begin_center
Version 1.3, 3 November 2008
#+end_center

#+begin_src display-preformatted
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
https://fsf.org/

Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed.
#+end_src

0. [@0] PREAMBLE

   The purpose of this License is to make a manual, textbook, or other
   functional and useful document /free/ in the sense of freedom: to
   assure everyone the effective freedom to copy and redistribute it,
   with or without modifying it, either commercially or noncommercially.
   Secondarily, this License preserves for the author and publisher a
   way to get credit for their work, while not being considered
   responsible for modifications made by others.

   This License is a kind of “copyleft”, which means that derivative
   works of the document must themselves be free in the same sense. It
   complements the GNU General Public License, which is a copyleft
   license designed for free software.

   We have designed this License in order to use it for manuals for free
   software, because free software needs free documentation: a free
   program should come with manuals providing the same freedoms that the
   software does. But this License is not limited to software manuals;
   it can be used for any textual work, regardless of subject matter or
   whether it is published as a printed book. We recommend this License
   principally for works whose purpose is instruction or reference.

1. APPLICABILITY AND DEFINITIONS

   This License applies to any manual or other work, in any medium, that
   contains a notice placed by the copyright holder saying it can be
   distributed under the terms of this License. Such a notice grants a
   world-wide, royalty-free license, unlimited in duration, to use that
   work under the conditions stated herein. The “Document”, below,
   refers to any such manual or work. Any member of the public is a
   licensee, and is addressed as “you”. You accept the license if you
   copy, modify or distribute the work in a way requiring permission
   under copyright law.

   A “Modified Version” of the Document means any work containing the
   Document or a portion of it, either copied verbatim, or with
   modifications and/or translated into another language.

   A “Secondary Section” is a named appendix or a front-matter section
   of the Document that deals exclusively with the relationship of the
   publishers or authors of the Document to the Document's overall
   subject (or to related matters) and contains nothing that could fall
   directly within that overall subject. (Thus, if the Document is in
   part a textbook of mathematics, a Secondary Section may not explain
   any mathematics.) The relationship could be a matter of historical
   connection with the subject or with related matters, or of legal,
   commercial, philosophical, ethical or political position regarding
   them.

   The “Invariant Sections” are certain Secondary Sections whose titles
   are designated, as being those of Invariant Sections, in the notice
   that says that the Document is released under this License. If a
   section does not fit the above definition of Secondary then it is not
   allowed to be designated as Invariant. The Document may contain zero
   Invariant Sections. If the Document does not identify any Invariant
   Sections then there are none.

   The “Cover Texts” are certain short passages of text that are listed,
   as Front-Cover Texts or Back-Cover Texts, in the notice that says
   that the Document is released under this License. A Front-Cover Text
   may be at most 5 words, and a Back-Cover Text may be at most 25
   words.

   A “Transparent” copy of the Document means a machine-readable copy,
   represented in a format whose specification is available to the
   general public, that is suitable for revising the document
   straightforwardly with generic text editors or (for images composed
   of pixels) generic paint programs or (for drawings) some widely
   available drawing editor, and that is suitable for input to text
   formatters or for automatic translation to a variety of formats
   suitable for input to text formatters. A copy made in an otherwise
   Transparent file format whose markup, or absence of markup, has been
   arranged to thwart or discourage subsequent modification by readers
   is not Transparent. An image format is not Transparent if used for
   any substantial amount of text. A copy that is not “Transparent” is
   called “Opaque”.

   Examples of suitable formats for Transparent copies include plain
   ASCII without markup, Texinfo input format, LaTeX input format, SGML
   or XML using a publicly available DTD, and standard-conforming simple
   HTML, PostScript or PDF designed for human modification. Examples of
   transparent image formats include PNG, XCF and JPG. Opaque formats
   include proprietary formats that can be read and edited only by
   proprietary word processors, SGML or XML for which the DTD and/or
   processing tools are not generally available, and the
   machine-generated HTML, PostScript or PDF produced by some word
   processors for output purposes only.

   The “Title Page” means, for a printed book, the title page itself,
   plus such following pages as are needed to hold, legibly, the
   material this License requires to appear in the title page. For works
   in formats which do not have any title page as such, “Title Page”
   means the text near the most prominent appearance of the work's
   title, preceding the beginning of the body of the text.

   The “publisher” means any person or entity that distributes copies of
   the Document to the public.

   A section “Entitled XYZ” means a named subunit of the Document whose
   title either is precisely XYZ or contains XYZ in parentheses
   following text that translates XYZ in another language. (Here XYZ
   stands for a specific section name mentioned below, such as
   “Acknowledgements”, “Dedications”, “Endorsements”, or “History”.) To
   “Preserve the Title” of such a section when you modify the Document
   means that it remains a section “Entitled XYZ” according to this
   definition.

   The Document may include Warranty Disclaimers next to the notice
   which states that this License applies to the Document. These
   Warranty Disclaimers are considered to be included by reference in
   this License, but only as regards disclaiming warranties: any other
   implication that these Warranty Disclaimers may have is void and has
   no effect on the meaning of this License.

2. VERBATIM COPYING

   You may copy and distribute the Document in any medium, either
   commercially or noncommercially, provided that this License, the
   copyright notices, and the license notice saying this License applies
   to the Document are reproduced in all copies, and that you add no
   other conditions whatsoever to those of this License. You may not use
   technical measures to obstruct or control the reading or further
   copying of the copies you make or distribute. However, you may accept
   compensation in exchange for copies. If you distribute a large enough
   number of copies you must also follow the conditions in section 3.

   You may also lend copies, under the same conditions stated above, and
   you may publicly display copies.

3. COPYING IN QUANTITY

   If you publish printed copies (or copies in media that commonly have
   printed covers) of the Document, numbering more than 100, and the
   Document's license notice requires Cover Texts, you must enclose the
   copies in covers that carry, clearly and legibly, all these Cover
   Texts: Front-Cover Texts on the front cover, and Back-Cover Texts on
   the back cover. Both covers must also clearly and legibly identify
   you as the publisher of these copies. The front cover must present
   the full title with all words of the title equally prominent and
   visible. You may add other material on the covers in addition.
   Copying with changes limited to the covers, as long as they preserve
   the title of the Document and satisfy these conditions, can be
   treated as verbatim copying in other respects.

   If the required texts for either cover are too voluminous to fit
   legibly, you should put the first ones listed (as many as fit
   reasonably) on the actual cover, and continue the rest onto adjacent
   pages.

   If you publish or distribute Opaque copies of the Document numbering
   more than 100, you must either include a machine-readable Transparent
   copy along with each Opaque copy, or state in or with each Opaque
   copy a computer-network location from which the general network-using
   public has access to download using public-standard network protocols
   a complete Transparent copy of the Document, free of added material.
   If you use the latter option, you must take reasonably prudent steps,
   when you begin distribution of Opaque copies in quantity, to ensure
   that this Transparent copy will remain thus accessible at the stated
   location until at least one year after the last time you distribute
   an Opaque copy (directly or through your agents or retailers) of that
   edition to the public.

   It is requested, but not required, that you contact the authors of
   the Document well before redistributing any large number of copies,
   to give them a chance to provide you with an updated version of the
   Document.

4. MODIFICATIONS

   You may copy and distribute a Modified Version of the Document under
   the conditions of sections 2 and 3 above, provided that you release
   the Modified Version under precisely this License, with the Modified
   Version filling the role of the Document, thus licensing distribution
   and modification of the Modified Version to whoever possesses a copy
   of it. In addition, you must do these things in the Modified Version:

   1. Use in the Title Page (and on the covers, if any) a title distinct
      from that of the Document, and from those of previous versions
      (which should, if there were any, be listed in the History section
      of the Document). You may use the same title as a previous version
      if the original publisher of that version gives permission.
   2. List on the Title Page, as authors, one or more persons or
      entities responsible for authorship of the modifications in the
      Modified Version, together with at least five of the principal
      authors of the Document (all of its principal authors, if it has
      fewer than five), unless they release you from this requirement.
   3. State on the Title page the name of the publisher of the Modified
      Version, as the publisher.
   4. Preserve all the copyright notices of the Document.
   5. Add an appropriate copyright notice for your modifications
      adjacent to the other copyright notices.
   6. Include, immediately after the copyright notices, a license notice
      giving the public permission to use the Modified Version under the
      terms of this License, in the form shown in the Addendum below.
   7. Preserve in that license notice the full lists of Invariant
      Sections and required Cover Texts given in the Document's license
      notice.
   8. Include an unaltered copy of this License.
   9. Preserve the section Entitled “History”, Preserve its Title, and
      add to it an item stating at least the title, year, new authors,
      and publisher of the Modified Version as given on the Title Page.
      If there is no section Entitled “History” in the Document, create
      one stating the title, year, authors, and publisher of the
      Document as given on its Title Page, then add an item describing
      the Modified Version as stated in the previous sentence.
   10. Preserve the network location, if any, given in the Document for
       public access to a Transparent copy of the Document, and likewise
       the network locations given in the Document for previous versions
       it was based on. These may be placed in the “History” section.
       You may omit a network location for a work that was published at
       least four years before the Document itself, or if the original
       publisher of the version it refers to gives permission.
   11. For any section Entitled “Acknowledgements” or “Dedications”,
       Preserve the Title of the section, and preserve in the section
       all the substance and tone of each of the contributor
       acknowledgements and/or dedications given therein.
   12. Preserve all the Invariant Sections of the Document, unaltered in
       their text and in their titles. Section numbers or the equivalent
       are not considered part of the section titles.
   13. Delete any section Entitled “Endorsements”. Such a section may
       not be included in the Modified Version.
   14. Do not retitle any existing section to be Entitled “Endorsements”
       or to conflict in title with any Invariant Section.
   15. Preserve any Warranty Disclaimers.

   If the Modified Version includes new front-matter sections or
   appendices that qualify as Secondary Sections and contain no material
   copied from the Document, you may at your option designate some or
   all of these sections as invariant. To do this, add their titles to
   the list of Invariant Sections in the Modified Version's license
   notice. These titles must be distinct from any other section titles.

   You may add a section Entitled “Endorsements”, provided it contains
   nothing but endorsements of your Modified Version by various
   parties---for example, statements of peer review or that the text has
   been approved by an organization as the authoritative definition of a
   standard.

   You may add a passage of up to five words as a Front-Cover Text, and
   a passage of up to 25 words as a Back-Cover Text, to the end of the
   list of Cover Texts in the Modified Version. Only one passage of
   Front-Cover Text and one of Back-Cover Text may be added by (or
   through arrangements made by) any one entity. If the Document already
   includes a cover text for the same cover, previously added by you or
   by arrangement made by the same entity you are acting on behalf of,
   you may not add another; but you may replace the old one, on explicit
   permission from the previous publisher that added the old one.

   The author(s) and publisher(s) of the Document do not by this License
   give permission to use their names for publicity for or to assert or
   imply endorsement of any Modified Version.

5. COMBINING DOCUMENTS

   You may combine the Document with other documents released under this
   License, under the terms defined in section 4 above for modified
   versions, provided that you include in the combination all of the
   Invariant Sections of all of the original documents, unmodified, and
   list them all as Invariant Sections of your combined work in its
   license notice, and that you preserve all their Warranty Disclaimers.

   The combined work need only contain one copy of this License, and
   multiple identical Invariant Sections may be replaced with a single
   copy. If there are multiple Invariant Sections with the same name but
   different contents, make the title of each such section unique by
   adding at the end of it, in parentheses, the name of the original
   author or publisher of that section if known, or else a unique
   number. Make the same adjustment to the section titles in the list of
   Invariant Sections in the license notice of the combined work.

   In the combination, you must combine any sections Entitled “History”
   in the various original documents, forming one section Entitled
   “History”; likewise combine any sections Entitled “Acknowledgements”,
   and any sections Entitled “Dedications”. You must delete all sections
   Entitled “Endorsements.”

6. COLLECTIONS OF DOCUMENTS

   You may make a collection consisting of the Document and other
   documents released under this License, and replace the individual
   copies of this License in the various documents with a single copy
   that is included in the collection, provided that you follow the
   rules of this License for verbatim copying of each of the documents
   in all other respects.

   You may extract a single document from such a collection, and
   distribute it individually under this License, provided you insert a
   copy of this License into the extracted document, and follow this
   License in all other respects regarding verbatim copying of that
   document.

7. AGGREGATION WITH INDEPENDENT WORKS

   A compilation of the Document or its derivatives with other separate
   and independent documents or works, in or on a volume of a storage or
   distribution medium, is called an “aggregate” if the copyright
   resulting from the compilation is not used to limit the legal rights
   of the compilation's users beyond what the individual works permit.
   When the Document is included in an aggregate, this License does not
   apply to the other works in the aggregate which are not themselves
   derivative works of the Document.

   If the Cover Text requirement of section 3 is applicable to these
   copies of the Document, then if the Document is less than one half of
   the entire aggregate, the Document's Cover Texts may be placed on
   covers that bracket the Document within the aggregate, or the
   electronic equivalent of covers if the Document is in electronic
   form. Otherwise they must appear on printed covers that bracket the
   whole aggregate.

8. TRANSLATION

   Translation is considered a kind of modification, so you may
   distribute translations of the Document under the terms of section 4.
   Replacing Invariant Sections with translations requires special
   permission from their copyright holders, but you may include
   translations of some or all Invariant Sections in addition to the
   original versions of these Invariant Sections. You may include a
   translation of this License, and all the license notices in the
   Document, and any Warranty Disclaimers, provided that you also
   include the original English version of this License and the original
   versions of those notices and disclaimers. In case of a disagreement
   between the translation and the original version of this License or a
   notice or disclaimer, the original version will prevail.

   If a section in the Document is Entitled “Acknowledgements”,
   “Dedications”, or “History”, the requirement (section 4) to Preserve
   its Title (section 1) will typically require changing the actual
   title.

9. TERMINATION

   You may not copy, modify, sublicense, or distribute the Document
   except as expressly provided under this License. Any attempt
   otherwise to copy, modify, sublicense, or distribute it is void, and
   will automatically terminate your rights under this License.

   However, if you cease all violation of this License, then your
   license from a particular copyright holder is reinstated (a)
   provisionally, unless and until the copyright holder explicitly and
   finally terminates your license, and (b) permanently, if the
   copyright holder fails to notify you of the violation by some
   reasonable means prior to 60 days after the cessation.

   Moreover, your license from a particular copyright holder is
   reinstated permanently if the copyright holder notifies you of the
   violation by some reasonable means, this is the first time you have
   received notice of violation of this License (for any work) from that
   copyright holder, and you cure the violation prior to 30 days after
   your receipt of the notice.

   Termination of your rights under this section does not terminate the
   licenses of parties who have received copies or rights from you under
   this License. If your rights have been terminated and not permanently
   reinstated, receipt of a copy of some or all of the same material
   does not give you any rights to use it.

10. FUTURE REVISIONS OF THIS LICENSE

    The Free Software Foundation may publish new, revised versions of
    the GNU Free Documentation License from time to time. Such new
    versions will be similar in spirit to the present version, but may
    differ in detail to address new problems or concerns. See
    [[https://www.gnu.org/licenses/]].

    Each version of the License is given a distinguishing version
    number. If the Document specifies that a particular numbered version
    of this License “or any later version” applies to it, you have the
    option of following the terms and conditions either of that
    specified version or of any later version that has been published
    (not as a draft) by the Free Software Foundation. If the Document
    does not specify a version number of this License, you may choose
    any version ever published (not as a draft) by the Free Software
    Foundation. If the Document specifies that a proxy can decide which
    future versions of this License can be used, that proxy's public
    statement of acceptance of a version permanently authorizes you to
    choose that version for the Document.

11. RELICENSING

    “Massive Multiauthor Collaboration Site” (or “MMC Site”) means any
    World Wide Web server that publishes copyrightable works and also
    provides prominent facilities for anybody to edit those works. A
    public wiki that anybody can edit is an example of such a server. A
    “Massive Multiauthor Collaboration” (or “MMC”) contained in the site
    means any set of copyrightable works thus published on the MMC site.

    “CC-BY-SA” means the Creative Commons Attribution-Share Alike 3.0
    license published by Creative Commons Corporation, a not-for-profit
    corporation with a principal place of business in San Francisco,
    California, as well as future copyleft versions of that license
    published by that same organization.

    “Incorporate” means to publish or republish a Document, in whole or
    in part, as part of another Document.

    An MMC is “eligible for relicensing” if it is licensed under this
    License, and if all works that were first published under this
    License somewhere other than this MMC, and subsequently incorporated
    in whole or in part into the MMC, (1) had no cover texts or
    invariant sections, and (2) were thus incorporated prior to November
    1, 2008.

    The operator of an MMC Site may republish an MMC contained in the
    site under CC-BY-SA on the same site at any time before August 1,
    2009, provided the MMC is eligible for relicensing.

*** ADDENDUM: How to use this License for your documents [[#ADDENDUM_003a-How-to-use-this-License-for-your-documents][¶]]
:PROPERTIES:
:CUSTOM_ID: ADDENDUM_003a-How-to-use-this-License-for-your-documents
:CLASS: heading
:END:
To use this License in a document you have written, include a copy of
the License in the document and put the following copyright and license
notices just after the title page:

#+begin_src example-preformatted
  Copyright (C)  year  your name.
  Permission is granted to copy, distribute and/or modify this document
  under the terms of the GNU Free Documentation License, Version 1.3
  or any later version published by the Free Software Foundation;
  with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
  Texts.  A copy of the license is included in the section entitled ``GNU
  Free Documentation License''.
#+end_src

If you have Invariant Sections, Front-Cover Texts and Back-Cover Texts,
replace the “with...Texts.” line with this:

#+begin_src example-preformatted
    with the Invariant Sections being list their titles, with
    the Front-Cover Texts being list, and with the Back-Cover Texts
    being list.
#+end_src

If you have Invariant Sections without Cover Texts, or some other
combination of the three, merge those two alternatives to suit the
situation.

If your document contains nontrivial examples of program code, we
recommend releasing these examples in parallel under your choice of free
software license, such as the GNU General Public License, to permit
their use in free software.

--------------

<<Function-Index>>

Next: [[#Variable-Index][Variable Index]], Previous:
[[#GNU-Free-Documentation-License][GNU Free Documentation License]], Up:
[[#Top][Interactive Do]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

** Function Index [[#Function-Index-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Function-Index-1
:CLASS: unnumbered
:END:

|                | Index Entry                                                     | Section                                                             |
| -------------- |                                                                 |                                                                     |
| I              |                                                                 |                                                                     |
|                | [[#index-ido_002dcomplete][=ido-complete=]]                     | [[#Interactive-Substring-Matching][Interactive Substring Matching]] |
|                | [[#index-ido_002dfind_002dfile][=ido-find-file=]]               | [[#Interactive-Substring-Matching][Interactive Substring Matching]] |
|                | [[#index-ido_002dreread_002ddirectory][=ido-reread-directory=]] | [[#Working-Directories][Working Directories]]                       |
|                | [[#index-ido_002dselect_002dtext][=ido-select-text=]]           | [[#Interactive-Substring-Matching][Interactive Substring Matching]] |
|                | [[#index-ido_002dtoggle_002dignore][=ido-toggle-ignore=]]       | [[#Hidden-Buffers-and-Files][Hidden Buffers and Files]]             |
|                | [[#index-ido_002dtoggle_002dprefix][=ido-toggle-prefix=]]       | [[#Prefix-Matching][Prefix Matching]]                               |
|                | [[#index-ido_002dtoggle_002dregexp][=ido-toggle-regexp=]]       | [[#Regexp-Matching][Regexp Matching]]                               |
| -------------- |                                                                 |                                                                     |

--------------

<<Variable-Index>>

Previous: [[#Function-Index][Function Index]], Up:
[[#Top][Interactive Do]]  
[[[#SEC_Contents][Contents]]][[[#Function-Index][Index]]]

** Variable Index [[#Variable-Index-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Variable-Index-1
:CLASS: unnumbered
:END:

| Jump to:   | [[#Variable-Index_vr_letter-C][*C*]]   [[#Variable-Index_vr_letter-I][*I*]]   |

|                | Index Entry                                                                           | Section                                       |
| -------------- |                                                                                       |                                               |
| C              |                                                                                       |                                               |
|                | [[#index-completion_002dignored_002dextensions][=completion-ignored-extensions=]]     | [[#Ignoring][Ignoring]]                       |
| -------------- |                                                                                       |                                               |
| I              |                                                                                       |                                               |
|                | [[#index-ido_002dall_002dframes][=ido-all-frames=]]                                   | [[#Misc-Customization][Misc Customization]]   |
|                | [[#index-ido_002dcannot_002dcomplete_002dcommand][=ido-cannot-complete-command=]]     | [[#Misc-Customization][Misc Customization]]   |
|                | [[#index-ido_002dcase_002dfold][=ido-case-fold=]]                                     | [[#Misc-Customization][Misc Customization]]   |
|                | [[#index-ido_002dconfirm_002dunique_002dcompletion][=ido-confirm-unique-completion=]] | [[#Misc-Customization][Misc Customization]]   |
|                | [[#index-ido_002denable_002ddot_002dprefix][=ido-enable-dot-prefix=]]                 | [[#Misc-Customization][Misc Customization]]   |
|                | [[#index-ido_002denable_002dflex_002dmatching][=ido-enable-flex-matching=]]           | [[#Flexible-Matching][Flexible Matching]]     |
|                | [[#index-ido_002denable_002dregexp][=ido-enable-regexp=]]                             | [[#Regexp-Matching][Regexp Matching]]         |
|                | [[#index-ido_002dignore_002dbuffers][=ido-ignore-buffers=]]                           | [[#Ignoring][Ignoring]]                       |
|                | [[#index-ido_002dignore_002ddirectories][=ido-ignore-directories=]]                   | [[#Ignoring][Ignoring]]                       |
|                | [[#index-ido_002dignore_002dfiles][=ido-ignore-files=]]                               | [[#Ignoring][Ignoring]]                       |
|                | [[#index-ido_002dignore_002dunc_002dhost_002dregexps][=ido-ignore-unc-host-regexps=]] | [[#Ignoring][Ignoring]]                       |
|                | [[#index-ido_002dmax_002ddir_002dfile_002dcache][=ido-max-dir-file-cache=]]           | [[#Working-Directories][Working Directories]] |
|                | [[#index-ido_002dmax_002dfile_002dprompt_002dwidth][=ido-max-file-prompt-width=]]     | [[#Misc-Customization][Misc Customization]]   |
|                | [[#index-ido_002dmax_002dwindow_002dheight][=ido-max-window-height=]]                 | [[#Misc-Customization][Misc Customization]]   |
|                | [[#index-ido_002dmax_002dwork_002ddirectory_002dlist][=ido-max-work-directory-list=]] | [[#Working-Directories][Working Directories]] |
|                | [[#index-ido_002dminibuffer_002dsetup_002dhook][=ido-minibuffer-setup-hook=]]         | [[#Misc-Customization][Misc Customization]]   |
|                | [[#index-ido_002dmode][=ido-mode=]]                                                   | [[#Misc-Customization][Misc Customization]]   |
|                | [[#index-ido_002drecord_002dcommands][=ido-record-commands=]]                         | [[#Misc-Customization][Misc Customization]]   |
|                | [[#index-ido_002dsetup_002dhook][=ido-setup-hook=]]                                   | [[#Customization][Customization]]             |
|                | [[#index-ido_002dshow_002ddot_002dfor_002ddired][=ido-show-dot-for-dired=]]           | [[#Misc-Customization][Misc Customization]]   |
|                | [[#index-ido_002duse_002dfaces][=ido-use-faces=]]                                     | [[#Highlighting][Highlighting]]               |
|                | [[#index-ido_002duse_002durl_002dat_002dpoint][=ido-use-url-at-point=]]               | [[#Find-File-At-Point][Find File At Point]]   |
|                | [[#index-ido_002dwork_002ddirectory_002dlist][=ido-work-directory-list=]]             | [[#Working-Directories][Working Directories]] |
| -------------- |                                                                                       |                                               |

| Jump to:   | [[#Variable-Index_vr_letter-C][*C*]]   [[#Variable-Index_vr_letter-I][*I*]]   |
