<<Top>>

Next: [[#Overview][Overview]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

* Octave Mode [[#Octave-Mode][¶]]
:PROPERTIES:
:CUSTOM_ID: Octave-Mode
:CLASS: top
:END:
Copyright © 1996--2026 Free Software Foundation, Inc.

#+begin_quote
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being “A GNU Manual,” and
with the Back-Cover Texts as in (a) below. A copy of the license is
included in the section entitled “GNU Free Documentation License.”

(a) The FSF's Back-Cover Text is: “You have the freedom to copy and
modify this GNU manual.”
#+end_quote

<<SEC_Contents>>
** Table of Contents
:PROPERTIES:
:CUSTOM_ID: table-of-contents
:CLASS: contents-heading
:END:

- [[#Overview][1 Overview]]
- [[#Using-Octave-Mode][2 Using Octave Mode]]
- [[#Running-Octave-from-Within-Emacs][3 Running Octave from Within Emacs]]
- [[#GNU-Free-Documentation-License][4 GNU Free Documentation License]]
- [[#Key-Index][Key Index]]
- [[#Variable-Index][Variable Index]]
- [[#Lisp-Function-Index][Function Index]]
- [[#Concept-Index][Concept Index]]

--------------

<<Overview>>

Next: [[#Using-Octave-Mode][Using Octave Mode]], Previous:
[[#Top][Octave Mode]], Up: [[#Top][Octave Mode]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

** 1 Overview [[#Overview-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Overview-1
:CLASS: chapter
:END:
The development of Octave code can greatly be facilitated using Emacs
with Octave mode, a major mode for editing Octave files which can e.g.
automatically indent the code, do some of the typing (with Abbrev mode)
and show keywords, comments, strings, etc. in different faces (with
Font-lock mode on devices that support it).

It is also possible to run Octave from within Emacs, either by directly
entering commands at the prompt in a buffer in Inferior Octave mode, or
by interacting with Octave from within a file with Octave code. This is
useful in particular for debugging Octave code.

--------------

<<Using-Octave-Mode>>

Next:
[[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]],
Previous: [[#Overview][Overview]], Up: [[#Top][Octave Mode]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

** 2 Using Octave Mode [[#Using-Octave-Mode-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Using-Octave-Mode-1
:CLASS: chapter
:END:
In Octave mode, the following special Emacs commands can be used in
addition to the standard Emacs commands.

-  <<index-C_002dM_002dj>>C-M-j [[#index-C_002dM_002dj][¶]] :: Break
  Octave line at point, continuing comment if within one. Insert
  =octave-continuation-string= before breaking the line unless inside a
  list. If within a double-quoted string, insert
  =octave-string-continuation-marker= instead. Signal an error if within
  a single-quoted string.

-  <<index-C_002dc-_003b>>C-c ; [[#index-C_002dc-_003b][¶]] :: Query
  replace function names in function file comment.

-  <<index-C_002dc-C_002dp>>C-c C-p
  [[#index-C_002dc-C_002dp][¶]] :: Move one line of Octave code
  backward, skipping empty and comment lines
  (=octave-previous-code-line=). With numeric prefix argument =n=, move
  that many code lines backward (forward if =n= is negative).

-  <<index-C_002dc-C_002dn>>C-c C-n
  [[#index-C_002dc-C_002dn][¶]] :: Move one line of Octave code forward,
  skipping empty and comment lines (=octave-next-code-line=). With
  numeric prefix argument =n=, move that many code lines forward
  (backward if =n= is negative).

-  <<index-C_002dc-C_002da>>C-c C-a
  [[#index-C_002dc-C_002da][¶]] :: Move to the beginning of the physical
  line (=octave-beginning-of-line=). If point is in an empty or comment
  line, simply go to its beginning; otherwise, move backwards to the
  beginning of the first code line which is not inside a continuation
  statement, i.e., which does not follow a code line ending in ‘=...='
  or ‘=\=', or is inside an open parenthesis list.

-  <<index-C_002dc-C_002de>>C-c C-e
  [[#index-C_002dc-C_002de][¶]] :: Move to the end of the physical line
  (=octave-end-of-line=). If point is in a code line, move forward to
  the end of the first Octave code line which does not end in ‘=...=' or
  ‘=\=' or is inside an open parenthesis list. Otherwise, simply go to
  the end of the current line.

-  <<index-C_002dc-M_002dC_002dh>>C-c M-C-h
  [[#index-C_002dc-M_002dC_002dh][¶]] :: Put point at the beginning of
  this block, mark at the end (=octave-mark-block=). The block marked is
  the one that contains point or follows point.

- <<index-C_002dc-_005d>>C-c ] [[#index-C_002dc-_005d][¶]] :: Close the
  current block on a separate line (=smie-close-block=). An error is
  signaled if no block to close is found.

-  <<index-C_002dc-C_002df>>C-c C-f
  [[#index-C_002dc-C_002df][¶]] :: Insert a function skeleton, prompting
  for the function's name, arguments and return values which have to be
  entered without parentheses (=octave-insert-defun=) in one of your
  Emacs startup files.

The following variables can be used to customize Octave mode.

- <<index-octave_002dblink_002dmatching_002dblock>>=octave-blink-matching-block=
  [[#index-octave_002dblink_002dmatching_002dblock][¶]] :: Non-=nil=
  means show matching begin of block when inserting a space, newline or
  ‘=;=' after an else or end keyword. Default is =t=. This is an
  extremely useful feature for automatically verifying that the keywords
  match---if they don't, an error message is displayed.

- <<index-octave_002dblock_002doffset>>=octave-block-offset=
  [[#index-octave_002dblock_002doffset][¶]] :: Extra indentation applied
  to statements in block structures. Default is 2.

- <<index-octave_002dcontinuation_002doffset>>=octave-continuation-offset=
  [[#index-octave_002dcontinuation_002doffset][¶]] :: Extra indentation
  applied to Octave continuation lines. Default is 4.

- <<index-octave_002dfont_002dlock_002dtexinfo_002dcomment>>=octave-font-lock-texinfo-comment=
  [[#index-octave_002dfont_002dlock_002dtexinfo_002dcomment][¶]] :: Highlight
  texinfo comment blocks. The default value is =t=.

If Font Lock mode is enabled, Octave mode will display

- strings in =font-lock-string-face=
- comments in =font-lock-comment-face=
- the Octave reserved words (such as all block keywords) and the text
  functions (such as ‘=cd=' or ‘=who=') which are also reserved using
  =font-lock-keyword-face=
- the built-in operators (‘=&&=', ‘====', ...) using
  =font-lock-reference-face=
- and the function names in function declarations in
  =font-lock-function-name-face=.
- Function comments blocks in =octave-function-comment-block=

There is also rudimentary support for Imenu (see
[[https://www.gnu.org/software/emacs/manual/html_mono/emacs.html#Imenu][Imenu]]
in The GNU Emacs Manual). Currently, function names can be indexed.

ElDoc mode (see
[[https://www.gnu.org/software/emacs/manual/html_mono/emacs.html#Programming-Language-Doc][Programming Language Doc]]
in The GNU Emacs Manual) is supported. By customizing
=octave-eldoc-message-style= it can be changed from displaying one or
multi line hints.

Customization of Octave mode can be performed by modification of the
variable =octave-mode-hook=.

--------------

<<Running-Octave-from-Within-Emacs>>

Next:
[[#GNU-Free-Documentation-License][GNU Free Documentation License]],
Previous: [[#Using-Octave-Mode][Using Octave Mode]], Up:
[[#Top][Octave Mode]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

** 3 Running Octave from Within Emacs [[#Running-Octave-from-Within-Emacs-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Running-Octave-from-Within-Emacs-1
:CLASS: chapter
:END:
Octave mode provides commands for running an inferior Octave process in
a special Emacs buffer. Use

#+begin_src lisp-preformatted
M-x run-octave
#+end_src

to directly start an inferior Octave process.

This will start Octave in a special buffer the name of which is
specified by the variable =inferior-octave-buffer= and defaults to
=*Inferior Octave*=. From within this buffer, you can interact with the
inferior Octave process “as usual”, i.e., by entering Octave commands at
the prompt. The buffer is in Inferior Octave mode, which is derived from
the standard Comint mode, a major mode for interacting with an inferior
interpreter. See the documentation for =comint-mode= for more details,
and use C-h b to find out about available special key bindings.

You can also communicate with an inferior Octave process from within
files with Octave code (i.e., buffers in Octave mode), using the
following commands.

-  <<index-C_002dc-C_002di-l>>C-c C-i l
  [[#index-C_002dc-C_002di-l][¶]] :: Send the current line to the
  inferior Octave process (=octave-send-line=). With positive prefix
  argument =n=, send that many lines. If =octave-send-line-auto-forward=
  is non-=nil=, go to the next unsent code line.

-  <<index-C_002dc-C_002di-b>>C-c C-i b
  [[#index-C_002dc-C_002di-b][¶]] :: Send the current block to the
  inferior Octave process (=octave-send-block=).

-  <<index-C_002dc-C_002di-f>>C-c C-i f
  [[#index-C_002dc-C_002di-f][¶]] :: Send the current function to the
  inferior Octave process (=octave-send-defun=).

-  <<index-C_002dc-C_002di-r>>C-c C-i r
  [[#index-C_002dc-C_002di-r][¶]] :: Send the region to the inferior
  Octave process (=octave-send-region=).

-  <<index-C_002dc-C_002di-a>>C-c C-i a
  [[#index-C_002dc-C_002di-a][¶]] :: Send the entire buffer to the
  inferior Octave process (=octave-send-buffer=). If the buffer is
  associated with a file then sourcing the buffer by using C-c C-l
  (=octave-source-file=) should be preferred.

-  <<index-C_002dc-C_002di-s>>C-c C-i s
  [[#index-C_002dc-C_002di-s][¶]] :: Make sure that
  =inferior-octave-buffer= is displayed (=octave-show-process-buffer=).

-  <<index-C_002dc-C_002di-q>>C-c C-i q
  [[#index-C_002dc-C_002di-q][¶]] :: Delete all windows that display the
  inferior Octave buffer (=octave-hide-process-buffer=).

-  <<index-C_002dc-C_002di-k>>C-c C-i k
  [[#index-C_002dc-C_002di-k][¶]] :: Kill the inferior Octave process
  and its buffer (=octave-kill-process=).

-  <<index-C_002dc-C_002dl>>C-c C-l
  [[#index-C_002dc-C_002dl][¶]] :: Parse and execute the current file in
  the inferior Octave buffer (=octave-source-file=). This is done using
  Octave's =source= function.

-  <<index-M_002d_002e>>M-. [[#index-M_002d_002e][¶]] :: Find the
  definition of a function or variable. Functions implemented in C++ can
  be found if variable =octave-source-directories= is set correctly
  (=octave-find-definition=).

-  <<index-C_002dh-d>>C-h d [[#index-C_002dh-d][¶]] :: Display the
  documentation for function (=octave-help=). The buffer name can be
  changed by customizing =octave-help-buffer=.

-  <<index-C_002dh-a>>C-h a [[#index-C_002dh-a][¶]] :: Search for a
  given string in all the first sentence of function help strings
  (=octave-lookfor=). With a =universal-argument= the entire help string
  is searched.

The effect of the commands which send code to the Octave process can be
customized by the following variables.

- <<index-octave_002dsend_002decho_002dinput>>=octave-send-echo-input=
  [[#index-octave_002dsend_002decho_002dinput][¶]] :: Non-=nil= means
  echo input sent to the inferior Octave process. Default is =t=.

- <<index-octave_002dsend_002dshow_002dbuffer>>=octave-send-show-buffer=
  [[#index-octave_002dsend_002dshow_002dbuffer][¶]] :: Non-=nil= means
  display the buffer running the Octave process after sending a command
  (but without selecting it). Default is =t=.

If you send code and there is no inferior Octave process yet, it will be
started automatically.

The startup of the inferior Octave process is highly customizable. The
variable =inferior-octave-startup-args= can be used for specifying
command lines arguments to be passed to Octave on startup as a list of
strings. For example, to suppress the startup message and use
“traditional” mode, set this to =("-q" "--traditional")=. You can also
specify a startup file of Octave commands to be loaded on startup; note
that these commands will not produce any visible output in the process
buffer. Which file to use is controlled by the variable
=inferior-octave-startup-file=. The default is =~/.emacs-octave= or if
this file is not found =~/.emacs.d/init_octave.m=.

By customizing =inferior-octave-prompt-read-only= the prompt can be
changed to be read only. The default value is the same as
=comint-prompt-read-only=.

And finally, =inferior-octave-mode-hook= is run after starting the
process and putting its buffer into Inferior Octave mode. Hence, if you
like the up and down arrow keys to behave in the interaction buffer as
in the shell, and you want this buffer to use nice colors, add

#+begin_src lisp-preformatted
(add-hook 'inferior-octave-mode-hook
          (lambda ()
            (keymap-set inferior-octave-mode-map "<up>"
              'comint-previous-input)
            (keymap-set inferior-octave-mode-map "<down>"
              'comint-next-input)))
#+end_src

to your =.emacs= or =init.el= file. You could also swap the roles of C-a
(=beginning-of-line=) and =C-c C-a= (=comint-bol=) using this hook.

#+begin_quote
*Note* that if you set your Octave prompts to something different from
the defaults, make sure that =inferior-octave-prompt= matches them.
Otherwise, /nothing/ will work, because Emacs will not know when Octave
is waiting for input, or done sending output.
#+end_quote

--------------

<<GNU-Free-Documentation-License>>

Next: [[#Key-Index][Key Index]], Previous:
[[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]],
Up: [[#Top][Octave Mode]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

** 4 GNU Free Documentation License [[#GNU-Free-Documentation-License-1][¶]]
:PROPERTIES:
:CUSTOM_ID: GNU-Free-Documentation-License-1
:CLASS: chapter
:END:

#+begin_center
Version 1.3, 3 November 2008
#+end_center

#+begin_src display-preformatted
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
https://fsf.org/

Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed.
#+end_src

0. [@0] PREAMBLE

   The purpose of this License is to make a manual, textbook, or other
   functional and useful document /free/ in the sense of freedom: to
   assure everyone the effective freedom to copy and redistribute it,
   with or without modifying it, either commercially or noncommercially.
   Secondarily, this License preserves for the author and publisher a
   way to get credit for their work, while not being considered
   responsible for modifications made by others.

   This License is a kind of “copyleft”, which means that derivative
   works of the document must themselves be free in the same sense. It
   complements the GNU General Public License, which is a copyleft
   license designed for free software.

   We have designed this License in order to use it for manuals for free
   software, because free software needs free documentation: a free
   program should come with manuals providing the same freedoms that the
   software does. But this License is not limited to software manuals;
   it can be used for any textual work, regardless of subject matter or
   whether it is published as a printed book. We recommend this License
   principally for works whose purpose is instruction or reference.

1. APPLICABILITY AND DEFINITIONS

   This License applies to any manual or other work, in any medium, that
   contains a notice placed by the copyright holder saying it can be
   distributed under the terms of this License. Such a notice grants a
   world-wide, royalty-free license, unlimited in duration, to use that
   work under the conditions stated herein. The “Document”, below,
   refers to any such manual or work. Any member of the public is a
   licensee, and is addressed as “you”. You accept the license if you
   copy, modify or distribute the work in a way requiring permission
   under copyright law.

   A “Modified Version” of the Document means any work containing the
   Document or a portion of it, either copied verbatim, or with
   modifications and/or translated into another language.

   A “Secondary Section” is a named appendix or a front-matter section
   of the Document that deals exclusively with the relationship of the
   publishers or authors of the Document to the Document's overall
   subject (or to related matters) and contains nothing that could fall
   directly within that overall subject. (Thus, if the Document is in
   part a textbook of mathematics, a Secondary Section may not explain
   any mathematics.) The relationship could be a matter of historical
   connection with the subject or with related matters, or of legal,
   commercial, philosophical, ethical or political position regarding
   them.

   The “Invariant Sections” are certain Secondary Sections whose titles
   are designated, as being those of Invariant Sections, in the notice
   that says that the Document is released under this License. If a
   section does not fit the above definition of Secondary then it is not
   allowed to be designated as Invariant. The Document may contain zero
   Invariant Sections. If the Document does not identify any Invariant
   Sections then there are none.

   The “Cover Texts” are certain short passages of text that are listed,
   as Front-Cover Texts or Back-Cover Texts, in the notice that says
   that the Document is released under this License. A Front-Cover Text
   may be at most 5 words, and a Back-Cover Text may be at most 25
   words.

   A “Transparent” copy of the Document means a machine-readable copy,
   represented in a format whose specification is available to the
   general public, that is suitable for revising the document
   straightforwardly with generic text editors or (for images composed
   of pixels) generic paint programs or (for drawings) some widely
   available drawing editor, and that is suitable for input to text
   formatters or for automatic translation to a variety of formats
   suitable for input to text formatters. A copy made in an otherwise
   Transparent file format whose markup, or absence of markup, has been
   arranged to thwart or discourage subsequent modification by readers
   is not Transparent. An image format is not Transparent if used for
   any substantial amount of text. A copy that is not “Transparent” is
   called “Opaque”.

   Examples of suitable formats for Transparent copies include plain
   ASCII without markup, Texinfo input format, LaTeX input format, SGML
   or XML using a publicly available DTD, and standard-conforming simple
   HTML, PostScript or PDF designed for human modification. Examples of
   transparent image formats include PNG, XCF and JPG. Opaque formats
   include proprietary formats that can be read and edited only by
   proprietary word processors, SGML or XML for which the DTD and/or
   processing tools are not generally available, and the
   machine-generated HTML, PostScript or PDF produced by some word
   processors for output purposes only.

   The “Title Page” means, for a printed book, the title page itself,
   plus such following pages as are needed to hold, legibly, the
   material this License requires to appear in the title page. For works
   in formats which do not have any title page as such, “Title Page”
   means the text near the most prominent appearance of the work's
   title, preceding the beginning of the body of the text.

   The “publisher” means any person or entity that distributes copies of
   the Document to the public.

   A section “Entitled XYZ” means a named subunit of the Document whose
   title either is precisely XYZ or contains XYZ in parentheses
   following text that translates XYZ in another language. (Here XYZ
   stands for a specific section name mentioned below, such as
   “Acknowledgements”, “Dedications”, “Endorsements”, or “History”.) To
   “Preserve the Title” of such a section when you modify the Document
   means that it remains a section “Entitled XYZ” according to this
   definition.

   The Document may include Warranty Disclaimers next to the notice
   which states that this License applies to the Document. These
   Warranty Disclaimers are considered to be included by reference in
   this License, but only as regards disclaiming warranties: any other
   implication that these Warranty Disclaimers may have is void and has
   no effect on the meaning of this License.

2. VERBATIM COPYING

   You may copy and distribute the Document in any medium, either
   commercially or noncommercially, provided that this License, the
   copyright notices, and the license notice saying this License applies
   to the Document are reproduced in all copies, and that you add no
   other conditions whatsoever to those of this License. You may not use
   technical measures to obstruct or control the reading or further
   copying of the copies you make or distribute. However, you may accept
   compensation in exchange for copies. If you distribute a large enough
   number of copies you must also follow the conditions in section 3.

   You may also lend copies, under the same conditions stated above, and
   you may publicly display copies.

3. COPYING IN QUANTITY

   If you publish printed copies (or copies in media that commonly have
   printed covers) of the Document, numbering more than 100, and the
   Document's license notice requires Cover Texts, you must enclose the
   copies in covers that carry, clearly and legibly, all these Cover
   Texts: Front-Cover Texts on the front cover, and Back-Cover Texts on
   the back cover. Both covers must also clearly and legibly identify
   you as the publisher of these copies. The front cover must present
   the full title with all words of the title equally prominent and
   visible. You may add other material on the covers in addition.
   Copying with changes limited to the covers, as long as they preserve
   the title of the Document and satisfy these conditions, can be
   treated as verbatim copying in other respects.

   If the required texts for either cover are too voluminous to fit
   legibly, you should put the first ones listed (as many as fit
   reasonably) on the actual cover, and continue the rest onto adjacent
   pages.

   If you publish or distribute Opaque copies of the Document numbering
   more than 100, you must either include a machine-readable Transparent
   copy along with each Opaque copy, or state in or with each Opaque
   copy a computer-network location from which the general network-using
   public has access to download using public-standard network protocols
   a complete Transparent copy of the Document, free of added material.
   If you use the latter option, you must take reasonably prudent steps,
   when you begin distribution of Opaque copies in quantity, to ensure
   that this Transparent copy will remain thus accessible at the stated
   location until at least one year after the last time you distribute
   an Opaque copy (directly or through your agents or retailers) of that
   edition to the public.

   It is requested, but not required, that you contact the authors of
   the Document well before redistributing any large number of copies,
   to give them a chance to provide you with an updated version of the
   Document.

4. MODIFICATIONS

   You may copy and distribute a Modified Version of the Document under
   the conditions of sections 2 and 3 above, provided that you release
   the Modified Version under precisely this License, with the Modified
   Version filling the role of the Document, thus licensing distribution
   and modification of the Modified Version to whoever possesses a copy
   of it. In addition, you must do these things in the Modified Version:

   1. Use in the Title Page (and on the covers, if any) a title distinct
      from that of the Document, and from those of previous versions
      (which should, if there were any, be listed in the History section
      of the Document). You may use the same title as a previous version
      if the original publisher of that version gives permission.
   2. List on the Title Page, as authors, one or more persons or
      entities responsible for authorship of the modifications in the
      Modified Version, together with at least five of the principal
      authors of the Document (all of its principal authors, if it has
      fewer than five), unless they release you from this requirement.
   3. State on the Title page the name of the publisher of the Modified
      Version, as the publisher.
   4. Preserve all the copyright notices of the Document.
   5. Add an appropriate copyright notice for your modifications
      adjacent to the other copyright notices.
   6. Include, immediately after the copyright notices, a license notice
      giving the public permission to use the Modified Version under the
      terms of this License, in the form shown in the Addendum below.
   7. Preserve in that license notice the full lists of Invariant
      Sections and required Cover Texts given in the Document's license
      notice.
   8. Include an unaltered copy of this License.
   9. Preserve the section Entitled “History”, Preserve its Title, and
      add to it an item stating at least the title, year, new authors,
      and publisher of the Modified Version as given on the Title Page.
      If there is no section Entitled “History” in the Document, create
      one stating the title, year, authors, and publisher of the
      Document as given on its Title Page, then add an item describing
      the Modified Version as stated in the previous sentence.
   10. Preserve the network location, if any, given in the Document for
       public access to a Transparent copy of the Document, and likewise
       the network locations given in the Document for previous versions
       it was based on. These may be placed in the “History” section.
       You may omit a network location for a work that was published at
       least four years before the Document itself, or if the original
       publisher of the version it refers to gives permission.
   11. For any section Entitled “Acknowledgements” or “Dedications”,
       Preserve the Title of the section, and preserve in the section
       all the substance and tone of each of the contributor
       acknowledgements and/or dedications given therein.
   12. Preserve all the Invariant Sections of the Document, unaltered in
       their text and in their titles. Section numbers or the equivalent
       are not considered part of the section titles.
   13. Delete any section Entitled “Endorsements”. Such a section may
       not be included in the Modified Version.
   14. Do not retitle any existing section to be Entitled “Endorsements”
       or to conflict in title with any Invariant Section.
   15. Preserve any Warranty Disclaimers.

   If the Modified Version includes new front-matter sections or
   appendices that qualify as Secondary Sections and contain no material
   copied from the Document, you may at your option designate some or
   all of these sections as invariant. To do this, add their titles to
   the list of Invariant Sections in the Modified Version's license
   notice. These titles must be distinct from any other section titles.

   You may add a section Entitled “Endorsements”, provided it contains
   nothing but endorsements of your Modified Version by various
   parties---for example, statements of peer review or that the text has
   been approved by an organization as the authoritative definition of a
   standard.

   You may add a passage of up to five words as a Front-Cover Text, and
   a passage of up to 25 words as a Back-Cover Text, to the end of the
   list of Cover Texts in the Modified Version. Only one passage of
   Front-Cover Text and one of Back-Cover Text may be added by (or
   through arrangements made by) any one entity. If the Document already
   includes a cover text for the same cover, previously added by you or
   by arrangement made by the same entity you are acting on behalf of,
   you may not add another; but you may replace the old one, on explicit
   permission from the previous publisher that added the old one.

   The author(s) and publisher(s) of the Document do not by this License
   give permission to use their names for publicity for or to assert or
   imply endorsement of any Modified Version.

5. COMBINING DOCUMENTS

   You may combine the Document with other documents released under this
   License, under the terms defined in section 4 above for modified
   versions, provided that you include in the combination all of the
   Invariant Sections of all of the original documents, unmodified, and
   list them all as Invariant Sections of your combined work in its
   license notice, and that you preserve all their Warranty Disclaimers.

   The combined work need only contain one copy of this License, and
   multiple identical Invariant Sections may be replaced with a single
   copy. If there are multiple Invariant Sections with the same name but
   different contents, make the title of each such section unique by
   adding at the end of it, in parentheses, the name of the original
   author or publisher of that section if known, or else a unique
   number. Make the same adjustment to the section titles in the list of
   Invariant Sections in the license notice of the combined work.

   In the combination, you must combine any sections Entitled “History”
   in the various original documents, forming one section Entitled
   “History”; likewise combine any sections Entitled “Acknowledgements”,
   and any sections Entitled “Dedications”. You must delete all sections
   Entitled “Endorsements.”

6. COLLECTIONS OF DOCUMENTS

   You may make a collection consisting of the Document and other
   documents released under this License, and replace the individual
   copies of this License in the various documents with a single copy
   that is included in the collection, provided that you follow the
   rules of this License for verbatim copying of each of the documents
   in all other respects.

   You may extract a single document from such a collection, and
   distribute it individually under this License, provided you insert a
   copy of this License into the extracted document, and follow this
   License in all other respects regarding verbatim copying of that
   document.

7. AGGREGATION WITH INDEPENDENT WORKS

   A compilation of the Document or its derivatives with other separate
   and independent documents or works, in or on a volume of a storage or
   distribution medium, is called an “aggregate” if the copyright
   resulting from the compilation is not used to limit the legal rights
   of the compilation's users beyond what the individual works permit.
   When the Document is included in an aggregate, this License does not
   apply to the other works in the aggregate which are not themselves
   derivative works of the Document.

   If the Cover Text requirement of section 3 is applicable to these
   copies of the Document, then if the Document is less than one half of
   the entire aggregate, the Document's Cover Texts may be placed on
   covers that bracket the Document within the aggregate, or the
   electronic equivalent of covers if the Document is in electronic
   form. Otherwise they must appear on printed covers that bracket the
   whole aggregate.

8. TRANSLATION

   Translation is considered a kind of modification, so you may
   distribute translations of the Document under the terms of section 4.
   Replacing Invariant Sections with translations requires special
   permission from their copyright holders, but you may include
   translations of some or all Invariant Sections in addition to the
   original versions of these Invariant Sections. You may include a
   translation of this License, and all the license notices in the
   Document, and any Warranty Disclaimers, provided that you also
   include the original English version of this License and the original
   versions of those notices and disclaimers. In case of a disagreement
   between the translation and the original version of this License or a
   notice or disclaimer, the original version will prevail.

   If a section in the Document is Entitled “Acknowledgements”,
   “Dedications”, or “History”, the requirement (section 4) to Preserve
   its Title (section 1) will typically require changing the actual
   title.

9. TERMINATION

   You may not copy, modify, sublicense, or distribute the Document
   except as expressly provided under this License. Any attempt
   otherwise to copy, modify, sublicense, or distribute it is void, and
   will automatically terminate your rights under this License.

   However, if you cease all violation of this License, then your
   license from a particular copyright holder is reinstated (a)
   provisionally, unless and until the copyright holder explicitly and
   finally terminates your license, and (b) permanently, if the
   copyright holder fails to notify you of the violation by some
   reasonable means prior to 60 days after the cessation.

   Moreover, your license from a particular copyright holder is
   reinstated permanently if the copyright holder notifies you of the
   violation by some reasonable means, this is the first time you have
   received notice of violation of this License (for any work) from that
   copyright holder, and you cure the violation prior to 30 days after
   your receipt of the notice.

   Termination of your rights under this section does not terminate the
   licenses of parties who have received copies or rights from you under
   this License. If your rights have been terminated and not permanently
   reinstated, receipt of a copy of some or all of the same material
   does not give you any rights to use it.

10. FUTURE REVISIONS OF THIS LICENSE

    The Free Software Foundation may publish new, revised versions of
    the GNU Free Documentation License from time to time. Such new
    versions will be similar in spirit to the present version, but may
    differ in detail to address new problems or concerns. See
    [[https://www.gnu.org/licenses/]].

    Each version of the License is given a distinguishing version
    number. If the Document specifies that a particular numbered version
    of this License “or any later version” applies to it, you have the
    option of following the terms and conditions either of that
    specified version or of any later version that has been published
    (not as a draft) by the Free Software Foundation. If the Document
    does not specify a version number of this License, you may choose
    any version ever published (not as a draft) by the Free Software
    Foundation. If the Document specifies that a proxy can decide which
    future versions of this License can be used, that proxy's public
    statement of acceptance of a version permanently authorizes you to
    choose that version for the Document.

11. RELICENSING

    “Massive Multiauthor Collaboration Site” (or “MMC Site”) means any
    World Wide Web server that publishes copyrightable works and also
    provides prominent facilities for anybody to edit those works. A
    public wiki that anybody can edit is an example of such a server. A
    “Massive Multiauthor Collaboration” (or “MMC”) contained in the site
    means any set of copyrightable works thus published on the MMC site.

    “CC-BY-SA” means the Creative Commons Attribution-Share Alike 3.0
    license published by Creative Commons Corporation, a not-for-profit
    corporation with a principal place of business in San Francisco,
    California, as well as future copyleft versions of that license
    published by that same organization.

    “Incorporate” means to publish or republish a Document, in whole or
    in part, as part of another Document.

    An MMC is “eligible for relicensing” if it is licensed under this
    License, and if all works that were first published under this
    License somewhere other than this MMC, and subsequently incorporated
    in whole or in part into the MMC, (1) had no cover texts or
    invariant sections, and (2) were thus incorporated prior to November
    1, 2008.

    The operator of an MMC Site may republish an MMC contained in the
    site under CC-BY-SA on the same site at any time before August 1,
    2009, provided the MMC is eligible for relicensing.

*** ADDENDUM: How to use this License for your documents [[#ADDENDUM_003a-How-to-use-this-License-for-your-documents][¶]]
:PROPERTIES:
:CUSTOM_ID: ADDENDUM_003a-How-to-use-this-License-for-your-documents
:CLASS: heading
:END:
To use this License in a document you have written, include a copy of
the License in the document and put the following copyright and license
notices just after the title page:

#+begin_src example-preformatted
  Copyright (C)  year  your name.
  Permission is granted to copy, distribute and/or modify this document
  under the terms of the GNU Free Documentation License, Version 1.3
  or any later version published by the Free Software Foundation;
  with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
  Texts.  A copy of the license is included in the section entitled ``GNU
  Free Documentation License''.
#+end_src

If you have Invariant Sections, Front-Cover Texts and Back-Cover Texts,
replace the “with...Texts.” line with this:

#+begin_src example-preformatted
    with the Invariant Sections being list their titles, with
    the Front-Cover Texts being list, and with the Back-Cover Texts
    being list.
#+end_src

If you have Invariant Sections without Cover Texts, or some other
combination of the three, merge those two alternatives to suit the
situation.

If your document contains nontrivial examples of program code, we
recommend releasing these examples in parallel under your choice of free
software license, such as the GNU General Public License, to permit
their use in free software.

--------------

<<Key-Index>>

Next: [[#Variable-Index][Variable Index]], Previous:
[[#GNU-Free-Documentation-License][GNU Free Documentation License]], Up:
[[#Top][Octave Mode]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

** Key Index [[#Key-Index-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Key-Index-1
:CLASS: unnumbered
:END:

| Jump to:   | [[#Key-Index_ky_letter-C][*C*]]   [[#Key-Index_ky_letter-M][*M*]]   |

|                | Index Entry                                   | Section                                                                 |
| -------------- |                                               |                                                                         |
| C              |                                               |                                                                         |
|                | [[#index-C_002dc-_003b][=C-c ;=]]             | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-C_002dc-C_002da][=C-c C-a=]]         | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-C_002dc-C_002de][=C-c C-e=]]         | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-C_002dc-C_002df][=C-c C-f=]]         | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-C_002dc-C_002di-a][=C-c C-i a=]]     | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-C_002dc-C_002di-b][=C-c C-i b=]]     | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-C_002dc-C_002di-f][=C-c C-i f=]]     | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-C_002dc-C_002di-k][=C-c C-i k=]]     | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-C_002dc-C_002di-l][=C-c C-i l=]]     | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-C_002dc-C_002di-q][=C-c C-i q=]]     | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-C_002dc-C_002di-r][=C-c C-i r=]]     | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-C_002dc-C_002di-s][=C-c C-i s=]]     | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-C_002dc-C_002dl][=C-c C-l=]]         | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-C_002dc-C_002dn][=C-c C-n=]]         | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-C_002dc-C_002dp][=C-c C-p=]]         | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-C_002dc-M_002dC_002dh][=C-c M-C-h=]] | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-C_002dc-_005d][=C-c ]=]]             | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-C_002dh-a][=C-h a=]]                 | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-C_002dh-d][=C-h d=]]                 | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-C_002dM_002dj][=C-M-j=]]             | [[#Using-Octave-Mode][Using Octave Mode]]                               |
| -------------- |                                               |                                                                         |
| M              |                                               |                                                                         |
|                | [[#index-M_002d_002e][=M-.=]]                 | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
| -------------- |                                               |                                                                         |

| Jump to:   | [[#Key-Index_ky_letter-C][*C*]]   [[#Key-Index_ky_letter-M][*M*]]   |

--------------

<<Variable-Index>>

Next: [[#Lisp-Function-Index][Function Index]], Previous:
[[#Key-Index][Key Index]], Up: [[#Top][Octave Mode]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

** Variable Index [[#Variable-Index-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Variable-Index-1
:CLASS: unnumbered
:END:

| Jump to:   | [[#Variable-Index_vr_letter-I][*I*]]   [[#Variable-Index_vr_letter-O][*O*]]   |

|                | Index Entry                                                                                     | Section                                                                 |
| -------------- |                                                                                                 |                                                                         |
| I              |                                                                                                 |                                                                         |
|                | [[#index-inferior_002doctave_002dbuffer][=inferior-octave-buffer=]]                             | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-inferior_002doctave_002dmode_002dhook][=inferior-octave-mode-hook=]]                   | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-inferior_002doctave_002dprompt][=inferior-octave-prompt=]]                             | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-inferior_002doctave_002dprompt_002dread_002donly][=inferior-octave-prompt-read-only=]] | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-inferior_002doctave_002dstartup_002dargs][=inferior-octave-startup-args=]]             | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
| -------------- |                                                                                                 |                                                                         |
| O              |                                                                                                 |                                                                         |
|                | [[#index-octave_002dblink_002dmatching_002dblock][=octave-blink-matching-block=]]               | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-octave_002dblock_002doffset][=octave-block-offset=]]                                   | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-octave_002dcontinuation_002doffset][=octave-continuation-offset=]]                     | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-octave_002dcontinuation_002dstring][=octave-continuation-string=]]                     | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-octave_002deldoc_002dmessage_002dstyle][=octave-eldoc-message-style=]]                 | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-octave_002dfont_002dlock_002dtexinfo_002dcomment][=octave-font-lock-texinfo-comment=]] | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-octave_002dhelp_002dbuffer][=octave-help-buffer=]]                                     | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-octave_002dmode_002dhook][=octave-mode-hook=]]                                         | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-octave_002dsend_002decho_002dinput][=octave-send-echo-input=]]                         | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-octave_002dsend_002dline_002dauto_002dforward][=octave-send-line-auto-forward=]]       | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-octave_002dsend_002dshow_002dbuffer][=octave-send-show-buffer=]]                       | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-octave_002dsource_002ddirectories][=octave-source-directories=]]                       | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-octave_002dstring_002dcontinuation_002dmarker][=octave-string-continuation-marker=]]   | [[#Using-Octave-Mode][Using Octave Mode]]                               |
| -------------- |                                                                                                 |                                                                         |

| Jump to:   | [[#Variable-Index_vr_letter-I][*I*]]   [[#Variable-Index_vr_letter-O][*O*]]   |

--------------

<<Lisp-Function-Index>>

Next: [[#Concept-Index][Concept Index]], Previous:
[[#Variable-Index][Variable Index]], Up: [[#Top][Octave Mode]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

** Function Index [[#Function-Index][¶]]
:PROPERTIES:
:CUSTOM_ID: Function-Index
:CLASS: unnumbered
:END:

|                | Index Entry                                                                                           | Section                                                                 |
| -------------- |                                                                                                       |                                                                         |
| O              |                                                                                                       |                                                                         |
|                | [[#index-octave_002dbeginning_002dof_002dline][=octave-beginning-of-line=]]                           | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-octave_002dend_002dof_002dline][=octave-end-of-line=]]                                       | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-octave_002dfind_002ddefinition][=octave-find-definition=]]                                   | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-octave_002dhelp][=octave-help=]]                                                             | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-octave_002dhide_002dprocess_002dbuffer][=octave-hide-process-buffer=]]                       | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-octave_002dindent_002dnew_002dcomment_002dline][=octave-indent-new-comment-line=]]           | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-octave_002dinsert_002ddefun][=octave-insert-defun=]]                                         | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-octave_002dkill_002dprocess][=octave-kill-process=]]                                         | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-octave_002dlookfor][=octave-lookfor=]]                                                       | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-octave_002dmark_002dblock][=octave-mark-block=]]                                             | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-octave_002dnext_002dcode_002dline][=octave-next-code-line=]]                                 | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-octave_002dprevious_002dcode_002dline][=octave-previous-code-line=]]                         | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-octave_002dsend_002dblock][=octave-send-block=]]                                             | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-octave_002dsend_002dbuffer][=octave-send-buffer=]]                                           | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-octave_002dsend_002ddefun][=octave-send-defun=]]                                             | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-octave_002dsend_002dline][=octave-send-line=]]                                               | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-octave_002dsend_002dregion][=octave-send-region=]]                                           | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-octave_002dshow_002dprocess_002dbuffer][=octave-show-process-buffer=]]                       | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-octave_002dsource_002dfile][=octave-source-file=]]                                           | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
|                | [[#index-octave_002dupdate_002dfunction_002dfile_002dcomment][=octave-update-function-file-comment=]] | [[#Using-Octave-Mode][Using Octave Mode]]                               |
| -------------- |                                                                                                       |                                                                         |

--------------

<<Concept-Index>>

Previous: [[#Lisp-Function-Index][Function Index]], Up:
[[#Top][Octave Mode]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

** Concept Index [[#Concept-Index-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Concept-Index-1
:CLASS: unnumbered
:END:

| Jump to:   | [[#Concept-Index_cp_letter-E][*E*]]   [[#Concept-Index_cp_letter-I][*I*]]   [[#Concept-Index_cp_letter-U][*U*]]   |

|                | Index Entry                                           | Section                                                                 |
| -------------- |                                                       |                                                                         |
| E              |                                                       |                                                                         |
|                | [[#index-ElDoc-Mode-Support][ElDoc Mode Support]]     | [[#Using-Octave-Mode][Using Octave Mode]]                               |
| -------------- |                                                       |                                                                         |
| I              |                                                       |                                                                         |
|                | [[#index-Imenu-Support][Imenu Support]]               | [[#Using-Octave-Mode][Using Octave Mode]]                               |
|                | [[#index-Inferior-Octave-Mode][Inferior Octave Mode]] | [[#Running-Octave-from-Within-Emacs][Running Octave from Within Emacs]] |
| -------------- |                                                       |                                                                         |
| U              |                                                       |                                                                         |
|                | [[#index-Using-Octave-Mode][Using Octave Mode]]       | [[#Using-Octave-Mode][Using Octave Mode]]                               |
| -------------- |                                                       |                                                                         |

| Jump to:   | [[#Concept-Index_cp_letter-E][*E*]]   [[#Concept-Index_cp_letter-I][*I*]]   [[#Concept-Index_cp_letter-U][*U*]]   |
