<<Top>>

Next: [[#Basics][Basics]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

* rcirc Manual [[#rcirc-Manual][¶]]
:PROPERTIES:
:CUSTOM_ID: rcirc-Manual
:CLASS: top
:END:
=rcirc= is an Emacs IRC client.

IRC (Internet Relay Chat) is a multi-user chat protocol. Users
communicate with each other in real-time. Communication occurs both in
topic channels which are collections of many users, or privately, with
just one other user.

Copyright © 2006--2026 Free Software Foundation, Inc.

#+begin_quote
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being “A GNU Manual”, and
with the Back-Cover Texts as in (a) below. A copy of the license is
included in the section entitled “GNU Free Documentation License”.

(a) The FSF's Back-Cover Text is: “You have the freedom to copy and
modify this GNU manual.”
#+end_quote

<<SEC_Contents>>
** Table of Contents
:PROPERTIES:
:CUSTOM_ID: table-of-contents
:CLASS: contents-heading
:END:

- [[#Basics][1 Basics]]
  - [[#Internet-Relay-Chat][1.1 Internet Relay Chat]]
  - [[#Getting-started-with-rcirc][1.2 Getting started with rcirc]]
- [[#Reference][2 Reference]]
  - [[#rcirc-commands][2.1 rcirc commands]]
  - [[#Useful-IRC-commands][2.2 Useful IRC commands]]
  - [[#Configuration][2.3 Configuration]]
- [[#Fighting-Information-Overload][3 Fighting Information Overload]]
  - [[#Channels][3.1 Channels]]
  - [[#People][3.2 People]]
  - [[#Keywords][3.3 Keywords]]
  - [[#Notices][3.4 Notices]]
- [[#Hacking-and-Tweaking][4 Hacking and Tweaking]]
  - [[#Skipping-_002faway-messages-using-handlers][4.1 Skipping =/away= messages using handlers]]
  - [[#Using-fly-spell-mode][4.2 Using fly spell mode]]
  - [[#Scrolling-conservatively][4.3 Scrolling conservatively]]
  - [[#Changing-the-time-stamp-format][4.4 Changing the time stamp format]]
  - [[#Defining-a-new-command][4.5 Defining a new command]]
  - [[#Using-rcirc-with-bouncers][4.6 Using rcirc with bouncers]]
  - [[#Dealing-with-Bridge-Bots][4.7 Dealing with Bridge Bots]]
- [[#GNU-Free-Documentation-License][Appendix A GNU Free Documentation License]]
- [[#Key-Index][Key Index]]
- [[#Variable-Index][Variable Index]]
- [[#Index][Index]]

--------------

<<Basics>>

Next: [[#Reference][Reference]], Previous: [[#Top][rcirc Manual]], Up:
[[#Top][rcirc Manual]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

** 1 Basics [[#Basics-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Basics-1
:CLASS: chapter
:END:
This chapter contains a brief introduction to IRC (Internet Relay Chat),
and a quick tutorial on =rcirc=.

- [[#Internet-Relay-Chat][Internet Relay Chat]]
- [[#Getting-started-with-rcirc][Getting started with rcirc]]

--------------

<<Internet-Relay-Chat>>

Next: [[#Getting-started-with-rcirc][Getting started with rcirc]], Up:
[[#Basics][Basics]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

*** 1.1 Internet Relay Chat [[#Internet-Relay-Chat-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Internet-Relay-Chat-1
:CLASS: section
:END:
/Internet Relay Chat/ (IRC) is a form of instant communication over the
Internet. It is mainly designed for group (many-to-many) communication
in discussion forums called channels, but also allows one-to-one
communication.

Contrary to most Instant Messenger (IM) systems, users usually don't
connect to a central server. Instead, users connect to a random server
in a network, and servers relay messages from one to the next.

Here's a typical example:

When you connect to the Libera.Chat network (=https://libera.chat=), you
point your IRC client at the server =irc.libera.chat=. That server will
redirect your client to a random server on the network, such as
=zirconium.libera.chat=.

Once you're connected, you can send messages to all other users
connected to the same network, and you can join all channels on the same
network. You might join the =#emacs= and the =#rcirc= channels, for
example. (Typically, channel names begin with a hash character.)

Once you have joined a channel, anything you type will be broadcast to
all the other users on the same channel.

If you want to address someone specifically, for example as an answer to
a question, it is customary to prefix the message with the nick followed
by a colon, like this:

#+begin_src example-preformatted
deego: fsbot rules!
#+end_src

Since this is so common, you can use TAB to do nick completion. By
default rcirc will use the default completion system, but you can enable
=rcirc-cycle-completion-flag= to cycle nicks in place.

--------------

<<Getting-started-with-rcirc>>

Previous: [[#Internet-Relay-Chat][Internet Relay Chat]], Up:
[[#Basics][Basics]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

*** 1.2 Getting started with rcirc [[#Getting-started-with-rcirc-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Getting-started-with-rcirc-1
:CLASS: section
:END:
Use the command M-x irc to connect using the defaults. See
[[#Configuration][Configuration]], if you want to change the defaults.

Use C-u M-x irc if you don't want to use the defaults, e.g., if you want
to connect to a different network, or connect to the same network using
a different nick. This will prompt you for four things:

-  <<index-server_002c-connecting>>IRC Server
  [[#index-server_002c-connecting][¶]] :: What server do you want to
  connect to? All the servers in a particular network are equivalent.
  Some networks use a round-robin system where a single server redirects
  new connections to a random server in the network. =irc.libera.chat=
  is such a server for the Libera.Chat network. Libera.Chat's purpose is
  “to provide services such as a community platform for free open-source
  software and peer directed projects on a volunteer basis,” and was
  chosen as the official home of the GNU Project and the Free Software
  Foundation's IRC channels in June 2021 in the aftermath of the changes
  in governance and policies of the Freenode IRC network. GNU and FSF's
  announcements about this are at
  [[https://lists.gnu.org/archive/html/info-gnu/2021-06/msg00005.html]],
  [[https://lists.gnu.org/archive/html/info-gnu/2021-06/msg00007.html]],
  and
  [[https://lists.gnu.org/archive/html/info-gnu-emacs/2021-06/msg00000.html]].

-  <<index-port_002c-connecting>>IRC Port
  [[#index-port_002c-connecting][¶]] :: All network connections require
  a port. Just as web servers and clients use port 80 per default, IRC
  uses port 6667 per default. You rarely have to use a different port.

-  <<index-user_002dlogin_002dname>>IRC Nick
  [[#index-user_002dlogin_002dname][¶]] :: Every users needs a handle
  on-line. You will automatically be assigned a slightly different nick
  if your chosen nick is already in use. If your =user-login-name= is
  =alex=, and this nick is already in use, you might for example get
  assigned the nick =alex`=.

-  <<index-channels_002c-connecting>>IRC Channels
  [[#index-channels_002c-connecting][¶]] :: A space separated list of
  channels you want to join when connecting. You don't need to join any
  channels, if you just want to have one-to-one conversations with
  friends on the same network. If you're new to the Libera.Chat network,
  join =#emacs=, the channel about all things Emacs, or join =#rcirc=,
  the channel about =rcirc=.

When you have answered these questions, =rcirc= will create a server
buffer, which will be named something like =*irc.libera.chat*=, and a
channel buffer for each of the channels you wanted to join.

To talk in a channel, just type what you want to say in a channel
buffer, and press RET.

If you want to paste multiple lines, such as source code, you can use
C-c C-c to edit your message in a separate buffer. Use C-c C-c to finish
editing. You still need to press RET to send it, though. Generally, IRC
users don't like people pasting more than around four lines of code, so
use with care.

Once you are connected to multiple channels, or once you've turned you
attention to other buffers in Emacs, you probably want to be notified of
any activity in channels not currently visible. All you need to do is
switch channel tracking on using M-x rcirc-track-minor-mode. To make
this permanent, add the following to your init file:

#+begin_src example-preformatted
(rcirc-track-minor-mode 1)
#+end_src

Use C-c C-SPC to switch to these buffers.

If the user wishes to ignore events in the server buffer, set
=rcirc-track-ignore-server-buffer-flag= to a non-=nil= value.

--------------

<<Reference>>

Next: [[#Fighting-Information-Overload][Fighting Information Overload]],
Previous: [[#Basics][Basics]], Up: [[#Top][rcirc Manual]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

** 2 Reference [[#Reference-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Reference-1
:CLASS: chapter
:END:
This is the reference section of the manual. It is not complete. For
complete listings of =rcirc= features, use Emacs built-in documentation.

- [[#rcirc-commands][rcirc commands]]
- [[#Useful-IRC-commands][Useful IRC commands]]
- [[#Configuration][Configuration]]

--------------

<<rcirc-commands>>

Next: [[#Useful-IRC-commands][Useful IRC commands]], Up:
[[#Reference][Reference]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

*** 2.1 rcirc commands [[#rcirc-commands-1][¶]]
:PROPERTIES:
:CUSTOM_ID: rcirc-commands-1
:CLASS: section
:END:
This is a list of commands that you may use in =rcirc=. It is not
complete. For a complete listing, press C-h m in an =rcirc= buffer.

In addition to using regular Emacs key bindings, you can call them by
typing them into an =rcirc= buffer.

For instance, instead of using the command C-c C-j to join a new
channel, you may type this in an =rcirc= buffer, and press RET:

#+begin_src example-preformatted
/join #emacs
#+end_src

This is why you cannot start a message with a slash. You will have to
precede the command with a space, or rewrite your message in order to
send it to a channel.

Many commands take parameters. IRC commands usually ignore string
delimiters. Neither apostrophe nor double-quote have special meanings in
IRC.

#+begin_src example-preformatted
/nick "alex schroeder"
#+end_src

This will try to change your nick to ="alex=. Usually this will fail
because the double quote character is not a valid character for nicks.

These commands are case insensitive.

If a command isn't known by =rcirc=, it will simply be sent along to the
server. There is a list of some useful commands like that in the next
section.

-  <<index-C_002dc-C_002dj>>C-c C-j
  [[#index-C_002dc-C_002dj][¶]] :: This joins a channel such as =#rcirc=
  or =#emacs=. On most networks, anybody can create new channels. If you
  want to talk with some friends, for example, all you have to do is
  agree on a valid channel name and join that channel. (Also
  =/join #emacs=.)

-  <<index-C_002dc-C_002dp>>C-c C-p
  [[#index-C_002dc-C_002dp][¶]] :: This leaves the current channel. You
  can optionally provide a different channel name and reason for
  parting. When you kill a channel buffer, you automatically part the
  corresponding channel. (Also =/part #emacs you are too weird!=.)

-  <<index-C_002dc-C_002dr>>C-c C-r
  [[#index-C_002dc-C_002dr][¶]] :: This changes your nick to some other
  name. Your nick must be unique across the network. Most networks don't
  allow too many nick changes in quick succession, and have restrictions
  on the valid characters in nick names. (Also =/nick alex-test=)

-  <<index-C_002dc-C_002dw>>C-c C-w
  [[#index-C_002dc-C_002dw][¶]] :: Gives you some basic information
  about a nick. This often includes what other channels people are on.
  (Also =/whois fsbot=.)

-  <<index-C_002dc-C_002dq>>C-c C-q
  [[#index-C_002dc-C_002dq][¶]] :: Starts a one-to-one conversation with
  another person on the same network. A new buffer will be created for
  this conversation. It works like a channel with only two members.
  (Also =/query fsbot=.)

-  <<index-C_002dc-RET>>C-c RET [[#index-C_002dc-RET][¶]] :: This sends
  a single message to a nick. Like with C-c C-q, a new buffer is
  created, where the response from the other party will show up. (Also
  =/msg nickserv identify secret=.)

-  <<index-C_002dc-C_002dx>>C-c C-x
  [[#index-C_002dc-C_002dx][¶]] :: This disconnects from the server and
  parts all channels. You can optionally provide a reason for quitting.
  When you kill the server buffer, you automatically quit the server and
  part all channels. (Also =/quit ZZZzzz...=.)

-  <<index-_002freconnect>>/reconnect
  [[#index-_002freconnect][¶]] :: This reconnects after you have lost
  the connection.

  If you're chatting from a laptop, then you might be familiar with this
  problem: When your laptop falls asleep and wakes up later, your IRC
  client doesn't realize that it has been disconnected. It takes several
  minutes until the client decides that the connection has in fact been
  lost. The simple solution is to use M-x rcirc. The problem is that
  this opens an /additional/ connection, so you'll have two copies of
  every channel buffer, one dead and one live.

  One option therefore, is the =/reconnect= command.

  An other approach is to set =rcirc-reconnect-delay= to a value greater
  than 0, and allow rcirc to reconnect when it detects that the
  connection has been closed. By default it will try to do this three
  times (as specified by =rcirc-reconnect-attempts=), before giving up.

--------------

<<Useful-IRC-commands>>

Next: [[#Configuration][Configuration]], Previous:
[[#rcirc-commands][rcirc commands]], Up: [[#Reference][Reference]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

*** 2.2 Useful IRC commands [[#Useful-IRC-commands-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Useful-IRC-commands-1
:CLASS: section
:END:
As mentioned, if a command isn't known by =rcirc=, it will simply be
sent along to the server. Some such commands are available on nearly all
IRC servers, such as:

-  <<index-_002faway>>=/away= [[#index-_002faway][¶]] :: This sets your
  status as “being away” if you provide a reason, or sets your status as
  “being back” if you do not. People can use the C-c C-w command to
  check your status. Example: =/away food=.

Typical IRC servers implement many more commands. You can read more
about the fantastic world of IRC online at
[[https://www.irchelp.org/][the Internet Relay Chat (IRC) help archive]].

--------------

<<Configuration>>

Previous: [[#Useful-IRC-commands][Useful IRC commands]], Up:
[[#Reference][Reference]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

*** 2.3 Configuration [[#Configuration-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Configuration-1
:CLASS: section
:END:
These are some variables you can change to configure =rcirc= to your
liking.

-  <<index-rcirc_002dserver_002dalist>>=rcirc-server-alist=
  [[#index-rcirc_002dserver_002dalist][¶]] :: This variable contains an
  alist of servers to connect to by default and the keywords parameters
  to use. The keyword parameters are optional. If you don't provide any,
  the defaults as documented below will be used.

  The most important parameter is the =:channels= parameter. It controls
  which channels you will join by default as soon as you are connected
  to the server.

  Here's an example of how to set it:

  #+begin_src example-preformatted
  (add-to-list 'rcirc-server-alist
               '("otherworlders.org"
                 :channels ("#FUDGE" "#game-design")))
  #+end_src

  By default you will be connected to the =rcirc= support channel:
  =#rcirc= on =irc.libera.chat=.

  - =:nick= :: This overrides =rcirc-default-nick=.

  - =:port= :: This overrides =rcirc-default-port=.

  - =:user-name= :: This overrides =rcirc-default-user-name=.

  - =:full-name= :: This overrides =rcirc-default-full-name=.

  - =:channels= :: This describes which channels to join when connecting
    to the server. If absent, no channels will be connected to
    automatically.

- <<index-rcirc_002ddefault_002dnick>>=rcirc-default-nick=
  [[#index-rcirc_002ddefault_002dnick][¶]] :: This variable is used for
  the default nick. It defaults to the login name returned by
  =user-login-name=.

  #+begin_src example-preformatted
  (setopt rcirc-default-nick "kensanata")
  #+end_src

-  <<index-rcirc_002ddefault_002dport>>=rcirc-default-port=
  [[#index-rcirc_002ddefault_002dport][¶]] :: This variable contains the
  default port to connect to. It is 6667 by default and rarely needs
  changing.

-
  <<index-rcirc_002ddefault_002duser_002dname>>=rcirc-default-user-name=
  [[#index-rcirc_002ddefault_002duser_002dname][¶]] :: This variable
  contains the default user name to report to the server. It defaults to
  the login name returned by =user-login-name=, just like
  =rcirc-default-nick=.

-
  <<index-rcirc_002ddefault_002dfull_002dname>>=rcirc-default-full-name=
  [[#index-rcirc_002ddefault_002dfull_002dname][¶]] :: This variable is
  used to set your “real name” on IRC. It defaults to the name returned
  by =user-full-name=. If you want to hide your full name, you might
  want to set it to some pseudonym.

  #+begin_src example-preformatted
  (setopt rcirc-default-full-name "Curious Minds Want To Know")
  #+end_src

-  <<index-rcirc_002dauthinfo>>=rcirc-authinfo=
  [[#index-rcirc_002dauthinfo][¶]] :: This variable is an alist used to
  automatically identify yourself on networks. Each sublist starts with
  a regular expression that is compared to the server address you're
  connecting to. The second element in the list is a symbol representing
  the method to use, followed by the arguments this method requires.

  Here is an example to illustrate how you would set it:

  #+begin_src example-preformatted
  (setopt rcirc-authinfo
          '(("Libera.Chat" nickserv "bob" "p455w0rd")
            ("Libera.Chat" chanserv "bob" "#bobland" "passwd99")
            ("bitlbee" bitlbee "robert" "sekrit")))
  #+end_src

  And here are the valid method symbols and the arguments they require:

  - <<index-nickserv-authentication>>=nickserv=
    [[#index-nickserv-authentication][¶]] :: Use this symbol if you need
    to identify yourself as follows when connecting to a network:
    =/msg nickserv identify secret=. The necessary arguments are the
    nickname you want to use this for, and the password to use.

    Before you can use this method, you will have to register your nick
    and pick a password for it. Contact =nickserv= and check out the
    details. (Using =/msg nickserv help=, for example.)

    You can set the password to the keyword =:auth-source=, if you do
    not want to hard-code your password in your configuration. See
    [[https://www.gnu.org/software/emacs/manual/html_mono/auth.html#Top][Emacs auth-source Library]]
    for details on how and where Emacs gets the password from.

  - <<index-chanserv-authentication>>=chanserv=
    [[#index-chanserv-authentication][¶]] :: Use this symbol if you need
    to identify yourself as follows if you want to join a particular
    channel: =/msg chanserv identify #underground secret=. The necessary
    arguments are the nickname and channel you want to use this for, and
    the password to use.

    Before you can use this method, a channel contact must tell you
    about the password to use. Contact =chanserv= and check out the
    details. (Using =/msg chanserv help=, for example.)

  - <<index-bitlbee-authentication>>=bitlbee=
    [[#index-bitlbee-authentication][¶]] :: Use this symbol if you need
    to identify yourself in the Bitlbee channel as follows:
    =identify secret=. The necessary arguments are the nickname you want
    to use this for, and the password to use.

    Bitlbee acts like an IRC server, but in fact it is a gateway to a
    lot of other instant messaging services. You can either install
    Bitlbee locally or use a public Bitlbee server. There, you need to
    create an account with a password. This is the nick and password you
    need to provide for the bitlbee authentication method.

    Later, you will tell Bitlbee about your accounts and passwords on
    all the other instant messaging services, and Bitlbee will log you
    in. All =rcirc= needs to know, is the login to your Bitlbee account.
    Don't confuse the Bitlbee account with all the other accounts.

  - <<index-sasl-authentication>>=sasl=
    [[#index-sasl-authentication][¶]] :: Use this symbol if you want to
    use SASL authentication. The necessary arguments are the nickname
    you want to use this for, and the password to use.

  - <<index-certfp-authentication>>=certfp=
    [[#index-certfp-authentication][¶]] :: Use this symbol if you want
    to use CertFP authentication. The necessary arguments are the path
    to the key and to the client certificate associated with the
    account. The CertFP authentication requires a TLS connection.

--------------

<<Fighting-Information-Overload>>

Next: [[#Hacking-and-Tweaking][Hacking and Tweaking]], Previous:
[[#Reference][Reference]], Up: [[#Top][rcirc Manual]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

** 3 Fighting Information Overload [[#Fighting-Information-Overload-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Fighting-Information-Overload-1
:CLASS: chapter
:END:
This is the section of the manual that caters to the busy person online.
There are support channels with several hundred people in them. Trying
to follow a conversation in these channels can be a daunting task. This
chapters tells you how =rcirc= can help.

- [[#Channels][Channels]]
- [[#People][People]]
- [[#Keywords][Keywords]]
- [[#Notices][Notices]]

--------------

<<Channels>>

Next: [[#People][People]], Up:
[[#Fighting-Information-Overload][Fighting Information Overload]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

*** 3.1 Channels [[#Channels-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Channels-1
:CLASS: section
:END:
Most people want a notification when something is said on a channel they
have joined, particularly if they have been addressed directly. There is
a global minor mode that will do this kind of tracking for you. All you
need to do is switch it on using M-x rcirc-track-minor-mode. To make
this permanent, add the following to your init file:

#+begin_src example-preformatted
(rcirc-track-minor-mode 1)
#+end_src

When other people say things in buffers that are currently buried (no
window is showing them), the mode line will now show you the abbreviated
channel or nick name. Use C-c C-SPC to switch to these buffers.

By default the channel names are abbreviated, set
=rcirc-track-abbreviate-flag= to a non-=nil= value. This might be
interesting if the IRC activities are not tracked in the mode line, but
somewhere else.

If you prefer not to load =rcirc= immediately, you can delay the
activation of this mode:

#+begin_src example-preformatted
(add-hook 'rcirc-mode-hook
          (lambda ()
            (rcirc-track-minor-mode 1)))
#+end_src

If you've joined a very active support channel, tracking activity is no
longer useful. The channel will be always active. Switching to active
channels using C-c C-SPC no longer works as expected.

The solution is to mark this channel as a low priority channel. Use C-c
C-l to make the current channel a low-priority channel. Low priority
channels have the modeline indicator “LowPri”. C-c C-SPC will not switch
to low priority channels unless you use the C-u prefix.

If you prefer a channel to never show up in the modeline, then you have
to ignore it. Use C-c TAB to ignore the current channel.

--------------

<<People>>

Next: [[#Keywords][Keywords]], Previous: [[#Channels][Channels]], Up:
[[#Fighting-Information-Overload][Fighting Information Overload]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

*** 3.2 People [[#People-1][¶]]
:PROPERTIES:
:CUSTOM_ID: People-1
:CLASS: section
:END:
The most important command available to the discerning IRC user is
=/ignore=. It's the big equalizer online: If people aggravate you, just
ignore them.

This is of course a crude all-or-nothing solution. Fear not, =rcirc=
offers alternatives: You can “brighten” your buddies and “dim” certain
other nicks that you don't want to ignore altogether.

-  <<index-_002fignore>>=/ignore= [[#index-_002fignore][¶]] :: This
  command toggles the ignore status of a nick, if you provide one. If
  you don't provide a nick, the command lists all the nicks you are
  ignoring. All messages by ignored nicks are---you guessed
  it---ignored. Since only “operators” can kick people from channels,
  the ignore command is often the only way to deal with some of the more
  obnoxious fellows online. Example: =/ignore rudybot=.

-  <<index-_002fbright>>=/bright= [[#index-_002fbright][¶]] :: This
  command toggles the bright status of a nick, if you provide one. If
  you don't provide a nick, the command lists all the “brightened”
  nicks. All messages by brightened nicks are---you guessed
  it---brightened. Use this for your friends. Example: =/bright rcy=.

-  <<index-_002fdim>>=/dim= [[#index-_002fdim][¶]] :: This command
  toggles the dim status of a nick, if you provide one. If you don't
  provide a nick, the command lists all the “dimmed” nicks. All messages
  by dimmed nicks are---you guessed it---dimmed. Use this for boring
  people and bots. If you are tracking channel activity, messages by
  dimmed nicks will not register as activity. Example: =/dim fsbot=.

--------------

<<Keywords>>

Next: [[#Notices][Notices]], Previous: [[#People][People]], Up:
[[#Fighting-Information-Overload][Fighting Information Overload]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

*** 3.3 Keywords [[#Keywords-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Keywords-1
:CLASS: section
:END:
On a busy channel, you might want to ignore all activity (using C-c TAB)
and just watch for certain keywords. The following command allows you to
highlight certain keywords:

- <<index-_002fkeyword>>=/keyword= [[#index-_002fkeyword][¶]] :: This
  command toggles the highlighting of a keyword, if you provide one. If
  you don't provide a keyword, the current keywords are listed. Example:
  =/keyword manual=.

--------------

<<Notices>>

Previous: [[#Keywords][Keywords]], Up:
[[#Fighting-Information-Overload][Fighting Information Overload]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

*** 3.4 Notices [[#Notices-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Notices-1
:CLASS: section
:END:
In busy channels you might not be interested in all the joining,
parting, quitting, and renaming that goes on. You can omit those notices
using C-c C-o.

You can control which notices get omitted via the =rcirc-omit-responses=
variable. Here's an example of how to omit away messages:

#+begin_src example-preformatted
(setopt rcirc-omit-responses '("JOIN" "PART" "QUIT" "NICK" "AWAY"))
#+end_src

Notice that these messages will not be omitted if the nick in question
has recently been active. After all, you don't want to continue a
conversation with somebody who just left. That's why =rcirc= checks
recent lines in the buffer to figure out if a nick has been active and
only omits a message if the nick has not been active. The window =rcirc=
considers is controlled by the =rcirc-omit-threshold= variable.

Certain messages can be omitted by default, unless the user manual
requests them. For example, if you don't want to display =TOPIC= and
=NAMES= messages, after reconnecting, you can configure
=rcirc-omit-unless-requested= to hide:

#+begin_src example-preformatted
(setopt rcirc-omit-unless-requested '("TOPIC" "NAMES"))
#+end_src

Now NAMES will only be displayed, after it has been requested via the
=rcirc-cmd-name= command.

--------------

<<Hacking-and-Tweaking>>

Next:
[[#GNU-Free-Documentation-License][GNU Free Documentation License]],
Previous:
[[#Fighting-Information-Overload][Fighting Information Overload]], Up:
[[#Top][rcirc Manual]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

** 4 Hacking and Tweaking [[#Hacking-and-Tweaking-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Hacking-and-Tweaking-1
:CLASS: chapter
:END:
Here are some examples of stuff you can do to configure =rcirc=.

- [[#Skipping-_002faway-messages-using-handlers][Skipping =/away= messages using handlers]]
- [[#Using-fly-spell-mode][Using fly spell mode]]
- [[#Scrolling-conservatively][Scrolling conservatively]]
- [[#Changing-the-time-stamp-format][Changing the time stamp format]]
- [[#Defining-a-new-command][Defining a new command]]
- [[#Using-rcirc-with-bouncers][Using rcirc with bouncers]]
- [[#Dealing-with-Bridge-Bots][Dealing with Bridge Bots]]

--------------

<<Skipping-_002faway-messages-using-handlers>>

Next: [[#Using-fly-spell-mode][Using fly spell mode]], Up:
[[#Hacking-and-Tweaking][Hacking and Tweaking]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

*** 4.1 Skipping =/away= messages using handlers [[#Skipping-_002faway-messages-using-handlers-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Skipping-_002faway-messages-using-handlers-1
:CLASS: section
:END:
The IRC protocol specifies how certain events are signaled from server
to client. These events have numbers and are dealt with using so-called
handlers. You can override existing handlers by exploiting the naming
convention adopted for =rcirc=.

Here's how to stop =rcirc= from printing =/away= messages. Since =rcirc=
doesn't define a 301 handler, you don't need to require =rcirc= before
defining the handler:

#+begin_src example-preformatted
(defun rcirc-handler-301 (process cmd sender args)
  "/away message handler.")
#+end_src

--------------

<<Using-fly-spell-mode>>

Next: [[#Scrolling-conservatively][Scrolling conservatively]], Previous:
[[#Skipping-_002faway-messages-using-handlers][Skipping =/away= messages using handlers]],
Up: [[#Hacking-and-Tweaking][Hacking and Tweaking]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

*** 4.2 Using fly spell mode [[#Using-fly-spell-mode-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Using-fly-spell-mode-1
:CLASS: section
:END:
The following code activates Fly Spell Mode for =rcirc= buffers:

#+begin_src example-preformatted
(add-hook 'rcirc-mode-hook (lambda ()
                             (flyspell-mode 1)))
#+end_src

See
[[https://www.gnu.org/software/emacs/manual/html_mono/emacs.html#Spelling][Flyspell mode]]
in The GNU Emacs Manual, for details.

--------------

<<Scrolling-conservatively>>

Next:
[[#Changing-the-time-stamp-format][Changing the time stamp format]],
Previous: [[#Using-fly-spell-mode][Using fly spell mode]], Up:
[[#Hacking-and-Tweaking][Hacking and Tweaking]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

*** 4.3 Scrolling conservatively [[#Scrolling-conservatively-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Scrolling-conservatively-1
:CLASS: section
:END:
IRC buffers are constantly growing. If you want to see as much as
possible at all times, you would want the prompt at the bottom of the
window when possible. The following snippet uses a local value for
=scroll-conservatively= to achieve this:

#+begin_src example-preformatted
(add-hook 'rcirc-mode-hook
          (lambda ()
            (set (make-local-variable 'scroll-conservatively)
                 8192)))
#+end_src

See
[[https://www.gnu.org/software/emacs/manual/html_mono/emacs.html#Scrolling][Scrolling conservatively]]
in The GNU Emacs Manual, for details.

--------------

<<Changing-the-time-stamp-format>>

Next: [[#Defining-a-new-command][Defining a new command]], Previous:
[[#Scrolling-conservatively][Scrolling conservatively]], Up:
[[#Hacking-and-Tweaking][Hacking and Tweaking]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

*** 4.4 Changing the time stamp format [[#Changing-the-time-stamp-format-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Changing-the-time-stamp-format-1
:CLASS: section
:END:
=rcirc-time-format= is the format used for the time stamp. Here's how to
include the date in the time stamp:

#+begin_src example-preformatted
(setopt rcirc-time-format "%Y-%m-%d %H:%M ")
#+end_src

For log files, a different time format can be specified using the
=rcirc-log-time-format= user option.

If you don't wish to use verbose time formatting all the time, you can
use the =rcirc-when= command to display a complete timestamp for the
message at point.

--------------

<<Defining-a-new-command>>

Next: [[#Using-rcirc-with-bouncers][Using rcirc with bouncers]],
Previous:
[[#Changing-the-time-stamp-format][Changing the time stamp format]], Up:
[[#Hacking-and-Tweaking][Hacking and Tweaking]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

*** 4.5 Defining a new command [[#Defining-a-new-command-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Defining-a-new-command-1
:CLASS: section
:END:
Here's a simple new command, =/sv=. With it, you can boast about your
IRC client. It shows how you can use =rcirc-define-command= to define
new commands.

We're waiting for the definition of this command until =rcirc= is loaded
because =rcirc-define-command= is not yet available, and without =rcirc=
loaded, the command wouldn't do us much good anyway.

#+begin_src example-preformatted
(with-eval-after-load 'rcirc
  (rcirc-define-command sv ()
    "Boast about rcirc."
    (interactive "i")
    (rcirc-send-message process target "I use " rcirc-id-string)))
#+end_src

--------------

<<Using-rcirc-with-bouncers>>

Next: [[#Dealing-with-Bridge-Bots][Dealing with Bridge Bots]], Previous:
[[#Defining-a-new-command][Defining a new command]], Up:
[[#Hacking-and-Tweaking][Hacking and Tweaking]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

*** 4.6 Using rcirc with bouncers [[#Using-rcirc-with-bouncers-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Using-rcirc-with-bouncers-1
:CLASS: section
:END:
Some bouncers multiplex connections to various servers, but have to
modify nicks and channel names to make this work. The channel =#emacs=
on =irc.libera.chat= becomes =#emacs/irc.libera.chat=.

The options =rcirc-nick-filter= and =rcirc-channel-filter= can be used
to make this feel more natural. When set to functions, these will be
used to change how nicks and channel names are displayed. A simple
configuration to fix the above example might be:

#+begin_src example-preformatted
(defun my/rcirc-remove-suffix (STR)
  "Remove suffixes from STR."
  (save-match-data
    (if (string-match "/[[:alpha:]]+?\\'" str)
        (substring str 0 (match-beginning 0))
      str)))

(setopt rcirc-nick-filter #'my/rcirc-remove-suffix
        rcirc-channel-filter #'local/rcirc-soju-suffix)
#+end_src

--------------

<<Dealing-with-Bridge-Bots>>

Previous: [[#Using-rcirc-with-bouncers][Using rcirc with bouncers]], Up:
[[#Hacking-and-Tweaking][Hacking and Tweaking]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

*** 4.7 Dealing with Bridge Bots [[#Dealing-with-Bridge-Bots-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Dealing-with-Bridge-Bots-1
:CLASS: section
:END:
It is increasingly common for IRC channels to be “bridged” onto other
networks such as XMPP, Matrix, etc. Sometimes the software does a good
job at mapping each non-IRC user into an IRC user, but more often than
not it doesn't. In that case you might receive a message like:

#+begin_src verbatim
09:47 <bridge> <john> I am not on IRC
#+end_src

where ‘=bridge=' is a bot responsible for sending messages back and
forth between networks, and ‘=john=' is the user name of someone on a
different network. Note that the bot indicates this within the message
(=<john> I am not on IRC=) that appears in your chat buffer.

If this annoys you, the user option =rcirc-bridge-bot-alist= may be of
use. It consists of descriptions of what users are these kinds of
“bridge bots” and how they format their messages. To handle the above
example, we might set the user option to:

#+begin_src example-preformatted
(setopt rcirc-bridge-bot-alist
        '(("bridge" . "<\\(.+?\\)>[[:space:]]+")))
#+end_src

If there is an entry for the current user, =rcirc= will take the
associated regular expression and try to find a match in the message
string. If it manages to find anything, the matching expression is
deleted from the message. The regular expression must contain at least
one group that will match the user name of the bridged message. This
will then be used to replace the username of the bridge bot.

--------------

<<GNU-Free-Documentation-License>>

Next: [[#Key-Index][Key Index]], Previous:
[[#Hacking-and-Tweaking][Hacking and Tweaking]], Up:
[[#Top][rcirc Manual]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

** Appendix A GNU Free Documentation License [[#GNU-Free-Documentation-License-1][¶]]
:PROPERTIES:
:CUSTOM_ID: GNU-Free-Documentation-License-1
:CLASS: appendix
:END:

#+begin_center
Version 1.3, 3 November 2008
#+end_center

#+begin_src display-preformatted
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
https://fsf.org/

Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed.
#+end_src

0. [@0] PREAMBLE

   The purpose of this License is to make a manual, textbook, or other
   functional and useful document /free/ in the sense of freedom: to
   assure everyone the effective freedom to copy and redistribute it,
   with or without modifying it, either commercially or noncommercially.
   Secondarily, this License preserves for the author and publisher a
   way to get credit for their work, while not being considered
   responsible for modifications made by others.

   This License is a kind of “copyleft”, which means that derivative
   works of the document must themselves be free in the same sense. It
   complements the GNU General Public License, which is a copyleft
   license designed for free software.

   We have designed this License in order to use it for manuals for free
   software, because free software needs free documentation: a free
   program should come with manuals providing the same freedoms that the
   software does. But this License is not limited to software manuals;
   it can be used for any textual work, regardless of subject matter or
   whether it is published as a printed book. We recommend this License
   principally for works whose purpose is instruction or reference.

1. APPLICABILITY AND DEFINITIONS

   This License applies to any manual or other work, in any medium, that
   contains a notice placed by the copyright holder saying it can be
   distributed under the terms of this License. Such a notice grants a
   world-wide, royalty-free license, unlimited in duration, to use that
   work under the conditions stated herein. The “Document”, below,
   refers to any such manual or work. Any member of the public is a
   licensee, and is addressed as “you”. You accept the license if you
   copy, modify or distribute the work in a way requiring permission
   under copyright law.

   A “Modified Version” of the Document means any work containing the
   Document or a portion of it, either copied verbatim, or with
   modifications and/or translated into another language.

   A “Secondary Section” is a named appendix or a front-matter section
   of the Document that deals exclusively with the relationship of the
   publishers or authors of the Document to the Document's overall
   subject (or to related matters) and contains nothing that could fall
   directly within that overall subject. (Thus, if the Document is in
   part a textbook of mathematics, a Secondary Section may not explain
   any mathematics.) The relationship could be a matter of historical
   connection with the subject or with related matters, or of legal,
   commercial, philosophical, ethical or political position regarding
   them.

   The “Invariant Sections” are certain Secondary Sections whose titles
   are designated, as being those of Invariant Sections, in the notice
   that says that the Document is released under this License. If a
   section does not fit the above definition of Secondary then it is not
   allowed to be designated as Invariant. The Document may contain zero
   Invariant Sections. If the Document does not identify any Invariant
   Sections then there are none.

   The “Cover Texts” are certain short passages of text that are listed,
   as Front-Cover Texts or Back-Cover Texts, in the notice that says
   that the Document is released under this License. A Front-Cover Text
   may be at most 5 words, and a Back-Cover Text may be at most 25
   words.

   A “Transparent” copy of the Document means a machine-readable copy,
   represented in a format whose specification is available to the
   general public, that is suitable for revising the document
   straightforwardly with generic text editors or (for images composed
   of pixels) generic paint programs or (for drawings) some widely
   available drawing editor, and that is suitable for input to text
   formatters or for automatic translation to a variety of formats
   suitable for input to text formatters. A copy made in an otherwise
   Transparent file format whose markup, or absence of markup, has been
   arranged to thwart or discourage subsequent modification by readers
   is not Transparent. An image format is not Transparent if used for
   any substantial amount of text. A copy that is not “Transparent” is
   called “Opaque”.

   Examples of suitable formats for Transparent copies include plain
   ASCII without markup, Texinfo input format, LaTeX input format, SGML
   or XML using a publicly available DTD, and standard-conforming simple
   HTML, PostScript or PDF designed for human modification. Examples of
   transparent image formats include PNG, XCF and JPG. Opaque formats
   include proprietary formats that can be read and edited only by
   proprietary word processors, SGML or XML for which the DTD and/or
   processing tools are not generally available, and the
   machine-generated HTML, PostScript or PDF produced by some word
   processors for output purposes only.

   The “Title Page” means, for a printed book, the title page itself,
   plus such following pages as are needed to hold, legibly, the
   material this License requires to appear in the title page. For works
   in formats which do not have any title page as such, “Title Page”
   means the text near the most prominent appearance of the work's
   title, preceding the beginning of the body of the text.

   The “publisher” means any person or entity that distributes copies of
   the Document to the public.

   A section “Entitled XYZ” means a named subunit of the Document whose
   title either is precisely XYZ or contains XYZ in parentheses
   following text that translates XYZ in another language. (Here XYZ
   stands for a specific section name mentioned below, such as
   “Acknowledgements”, “Dedications”, “Endorsements”, or “History”.) To
   “Preserve the Title” of such a section when you modify the Document
   means that it remains a section “Entitled XYZ” according to this
   definition.

   The Document may include Warranty Disclaimers next to the notice
   which states that this License applies to the Document. These
   Warranty Disclaimers are considered to be included by reference in
   this License, but only as regards disclaiming warranties: any other
   implication that these Warranty Disclaimers may have is void and has
   no effect on the meaning of this License.

2. VERBATIM COPYING

   You may copy and distribute the Document in any medium, either
   commercially or noncommercially, provided that this License, the
   copyright notices, and the license notice saying this License applies
   to the Document are reproduced in all copies, and that you add no
   other conditions whatsoever to those of this License. You may not use
   technical measures to obstruct or control the reading or further
   copying of the copies you make or distribute. However, you may accept
   compensation in exchange for copies. If you distribute a large enough
   number of copies you must also follow the conditions in section 3.

   You may also lend copies, under the same conditions stated above, and
   you may publicly display copies.

3. COPYING IN QUANTITY

   If you publish printed copies (or copies in media that commonly have
   printed covers) of the Document, numbering more than 100, and the
   Document's license notice requires Cover Texts, you must enclose the
   copies in covers that carry, clearly and legibly, all these Cover
   Texts: Front-Cover Texts on the front cover, and Back-Cover Texts on
   the back cover. Both covers must also clearly and legibly identify
   you as the publisher of these copies. The front cover must present
   the full title with all words of the title equally prominent and
   visible. You may add other material on the covers in addition.
   Copying with changes limited to the covers, as long as they preserve
   the title of the Document and satisfy these conditions, can be
   treated as verbatim copying in other respects.

   If the required texts for either cover are too voluminous to fit
   legibly, you should put the first ones listed (as many as fit
   reasonably) on the actual cover, and continue the rest onto adjacent
   pages.

   If you publish or distribute Opaque copies of the Document numbering
   more than 100, you must either include a machine-readable Transparent
   copy along with each Opaque copy, or state in or with each Opaque
   copy a computer-network location from which the general network-using
   public has access to download using public-standard network protocols
   a complete Transparent copy of the Document, free of added material.
   If you use the latter option, you must take reasonably prudent steps,
   when you begin distribution of Opaque copies in quantity, to ensure
   that this Transparent copy will remain thus accessible at the stated
   location until at least one year after the last time you distribute
   an Opaque copy (directly or through your agents or retailers) of that
   edition to the public.

   It is requested, but not required, that you contact the authors of
   the Document well before redistributing any large number of copies,
   to give them a chance to provide you with an updated version of the
   Document.

4. MODIFICATIONS

   You may copy and distribute a Modified Version of the Document under
   the conditions of sections 2 and 3 above, provided that you release
   the Modified Version under precisely this License, with the Modified
   Version filling the role of the Document, thus licensing distribution
   and modification of the Modified Version to whoever possesses a copy
   of it. In addition, you must do these things in the Modified Version:

   1. Use in the Title Page (and on the covers, if any) a title distinct
      from that of the Document, and from those of previous versions
      (which should, if there were any, be listed in the History section
      of the Document). You may use the same title as a previous version
      if the original publisher of that version gives permission.
   2. List on the Title Page, as authors, one or more persons or
      entities responsible for authorship of the modifications in the
      Modified Version, together with at least five of the principal
      authors of the Document (all of its principal authors, if it has
      fewer than five), unless they release you from this requirement.
   3. State on the Title page the name of the publisher of the Modified
      Version, as the publisher.
   4. Preserve all the copyright notices of the Document.
   5. Add an appropriate copyright notice for your modifications
      adjacent to the other copyright notices.
   6. Include, immediately after the copyright notices, a license notice
      giving the public permission to use the Modified Version under the
      terms of this License, in the form shown in the Addendum below.
   7. Preserve in that license notice the full lists of Invariant
      Sections and required Cover Texts given in the Document's license
      notice.
   8. Include an unaltered copy of this License.
   9. Preserve the section Entitled “History”, Preserve its Title, and
      add to it an item stating at least the title, year, new authors,
      and publisher of the Modified Version as given on the Title Page.
      If there is no section Entitled “History” in the Document, create
      one stating the title, year, authors, and publisher of the
      Document as given on its Title Page, then add an item describing
      the Modified Version as stated in the previous sentence.
   10. Preserve the network location, if any, given in the Document for
       public access to a Transparent copy of the Document, and likewise
       the network locations given in the Document for previous versions
       it was based on. These may be placed in the “History” section.
       You may omit a network location for a work that was published at
       least four years before the Document itself, or if the original
       publisher of the version it refers to gives permission.
   11. For any section Entitled “Acknowledgements” or “Dedications”,
       Preserve the Title of the section, and preserve in the section
       all the substance and tone of each of the contributor
       acknowledgements and/or dedications given therein.
   12. Preserve all the Invariant Sections of the Document, unaltered in
       their text and in their titles. Section numbers or the equivalent
       are not considered part of the section titles.
   13. Delete any section Entitled “Endorsements”. Such a section may
       not be included in the Modified Version.
   14. Do not retitle any existing section to be Entitled “Endorsements”
       or to conflict in title with any Invariant Section.
   15. Preserve any Warranty Disclaimers.

   If the Modified Version includes new front-matter sections or
   appendices that qualify as Secondary Sections and contain no material
   copied from the Document, you may at your option designate some or
   all of these sections as invariant. To do this, add their titles to
   the list of Invariant Sections in the Modified Version's license
   notice. These titles must be distinct from any other section titles.

   You may add a section Entitled “Endorsements”, provided it contains
   nothing but endorsements of your Modified Version by various
   parties---for example, statements of peer review or that the text has
   been approved by an organization as the authoritative definition of a
   standard.

   You may add a passage of up to five words as a Front-Cover Text, and
   a passage of up to 25 words as a Back-Cover Text, to the end of the
   list of Cover Texts in the Modified Version. Only one passage of
   Front-Cover Text and one of Back-Cover Text may be added by (or
   through arrangements made by) any one entity. If the Document already
   includes a cover text for the same cover, previously added by you or
   by arrangement made by the same entity you are acting on behalf of,
   you may not add another; but you may replace the old one, on explicit
   permission from the previous publisher that added the old one.

   The author(s) and publisher(s) of the Document do not by this License
   give permission to use their names for publicity for or to assert or
   imply endorsement of any Modified Version.

5. COMBINING DOCUMENTS

   You may combine the Document with other documents released under this
   License, under the terms defined in section 4 above for modified
   versions, provided that you include in the combination all of the
   Invariant Sections of all of the original documents, unmodified, and
   list them all as Invariant Sections of your combined work in its
   license notice, and that you preserve all their Warranty Disclaimers.

   The combined work need only contain one copy of this License, and
   multiple identical Invariant Sections may be replaced with a single
   copy. If there are multiple Invariant Sections with the same name but
   different contents, make the title of each such section unique by
   adding at the end of it, in parentheses, the name of the original
   author or publisher of that section if known, or else a unique
   number. Make the same adjustment to the section titles in the list of
   Invariant Sections in the license notice of the combined work.

   In the combination, you must combine any sections Entitled “History”
   in the various original documents, forming one section Entitled
   “History”; likewise combine any sections Entitled “Acknowledgements”,
   and any sections Entitled “Dedications”. You must delete all sections
   Entitled “Endorsements.”

6. COLLECTIONS OF DOCUMENTS

   You may make a collection consisting of the Document and other
   documents released under this License, and replace the individual
   copies of this License in the various documents with a single copy
   that is included in the collection, provided that you follow the
   rules of this License for verbatim copying of each of the documents
   in all other respects.

   You may extract a single document from such a collection, and
   distribute it individually under this License, provided you insert a
   copy of this License into the extracted document, and follow this
   License in all other respects regarding verbatim copying of that
   document.

7. AGGREGATION WITH INDEPENDENT WORKS

   A compilation of the Document or its derivatives with other separate
   and independent documents or works, in or on a volume of a storage or
   distribution medium, is called an “aggregate” if the copyright
   resulting from the compilation is not used to limit the legal rights
   of the compilation's users beyond what the individual works permit.
   When the Document is included in an aggregate, this License does not
   apply to the other works in the aggregate which are not themselves
   derivative works of the Document.

   If the Cover Text requirement of section 3 is applicable to these
   copies of the Document, then if the Document is less than one half of
   the entire aggregate, the Document's Cover Texts may be placed on
   covers that bracket the Document within the aggregate, or the
   electronic equivalent of covers if the Document is in electronic
   form. Otherwise they must appear on printed covers that bracket the
   whole aggregate.

8. TRANSLATION

   Translation is considered a kind of modification, so you may
   distribute translations of the Document under the terms of section 4.
   Replacing Invariant Sections with translations requires special
   permission from their copyright holders, but you may include
   translations of some or all Invariant Sections in addition to the
   original versions of these Invariant Sections. You may include a
   translation of this License, and all the license notices in the
   Document, and any Warranty Disclaimers, provided that you also
   include the original English version of this License and the original
   versions of those notices and disclaimers. In case of a disagreement
   between the translation and the original version of this License or a
   notice or disclaimer, the original version will prevail.

   If a section in the Document is Entitled “Acknowledgements”,
   “Dedications”, or “History”, the requirement (section 4) to Preserve
   its Title (section 1) will typically require changing the actual
   title.

9. TERMINATION

   You may not copy, modify, sublicense, or distribute the Document
   except as expressly provided under this License. Any attempt
   otherwise to copy, modify, sublicense, or distribute it is void, and
   will automatically terminate your rights under this License.

   However, if you cease all violation of this License, then your
   license from a particular copyright holder is reinstated (a)
   provisionally, unless and until the copyright holder explicitly and
   finally terminates your license, and (b) permanently, if the
   copyright holder fails to notify you of the violation by some
   reasonable means prior to 60 days after the cessation.

   Moreover, your license from a particular copyright holder is
   reinstated permanently if the copyright holder notifies you of the
   violation by some reasonable means, this is the first time you have
   received notice of violation of this License (for any work) from that
   copyright holder, and you cure the violation prior to 30 days after
   your receipt of the notice.

   Termination of your rights under this section does not terminate the
   licenses of parties who have received copies or rights from you under
   this License. If your rights have been terminated and not permanently
   reinstated, receipt of a copy of some or all of the same material
   does not give you any rights to use it.

10. FUTURE REVISIONS OF THIS LICENSE

    The Free Software Foundation may publish new, revised versions of
    the GNU Free Documentation License from time to time. Such new
    versions will be similar in spirit to the present version, but may
    differ in detail to address new problems or concerns. See
    [[https://www.gnu.org/licenses/]].

    Each version of the License is given a distinguishing version
    number. If the Document specifies that a particular numbered version
    of this License “or any later version” applies to it, you have the
    option of following the terms and conditions either of that
    specified version or of any later version that has been published
    (not as a draft) by the Free Software Foundation. If the Document
    does not specify a version number of this License, you may choose
    any version ever published (not as a draft) by the Free Software
    Foundation. If the Document specifies that a proxy can decide which
    future versions of this License can be used, that proxy's public
    statement of acceptance of a version permanently authorizes you to
    choose that version for the Document.

11. RELICENSING

    “Massive Multiauthor Collaboration Site” (or “MMC Site”) means any
    World Wide Web server that publishes copyrightable works and also
    provides prominent facilities for anybody to edit those works. A
    public wiki that anybody can edit is an example of such a server. A
    “Massive Multiauthor Collaboration” (or “MMC”) contained in the site
    means any set of copyrightable works thus published on the MMC site.

    “CC-BY-SA” means the Creative Commons Attribution-Share Alike 3.0
    license published by Creative Commons Corporation, a not-for-profit
    corporation with a principal place of business in San Francisco,
    California, as well as future copyleft versions of that license
    published by that same organization.

    “Incorporate” means to publish or republish a Document, in whole or
    in part, as part of another Document.

    An MMC is “eligible for relicensing” if it is licensed under this
    License, and if all works that were first published under this
    License somewhere other than this MMC, and subsequently incorporated
    in whole or in part into the MMC, (1) had no cover texts or
    invariant sections, and (2) were thus incorporated prior to November
    1, 2008.

    The operator of an MMC Site may republish an MMC contained in the
    site under CC-BY-SA on the same site at any time before August 1,
    2009, provided the MMC is eligible for relicensing.

*** ADDENDUM: How to use this License for your documents [[#ADDENDUM_003a-How-to-use-this-License-for-your-documents][¶]]
:PROPERTIES:
:CUSTOM_ID: ADDENDUM_003a-How-to-use-this-License-for-your-documents
:CLASS: heading
:END:
To use this License in a document you have written, include a copy of
the License in the document and put the following copyright and license
notices just after the title page:

#+begin_src example-preformatted
  Copyright (C)  year  your name.
  Permission is granted to copy, distribute and/or modify this document
  under the terms of the GNU Free Documentation License, Version 1.3
  or any later version published by the Free Software Foundation;
  with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
  Texts.  A copy of the license is included in the section entitled ``GNU
  Free Documentation License''.
#+end_src

If you have Invariant Sections, Front-Cover Texts and Back-Cover Texts,
replace the “with...Texts.” line with this:

#+begin_src example-preformatted
    with the Invariant Sections being list their titles, with
    the Front-Cover Texts being list, and with the Back-Cover Texts
    being list.
#+end_src

If you have Invariant Sections without Cover Texts, or some other
combination of the three, merge those two alternatives to suit the
situation.

If your document contains nontrivial examples of program code, we
recommend releasing these examples in parallel under your choice of free
software license, such as the GNU General Public License, to permit
their use in free software.

--------------

<<Key-Index>>

Next: [[#Variable-Index][Variable Index]], Previous:
[[#GNU-Free-Documentation-License][GNU Free Documentation License]], Up:
[[#Top][rcirc Manual]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

** Key Index [[#Key-Index-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Key-Index-1
:CLASS: unnumbered
:END:

| Jump to:   | [[#Key-Index_ky_letter-C][*C*]]   [[#Key-Index_ky_letter-R][*R*]]   [[#Key-Index_ky_letter-T][*T*]]   |

|                | Index Entry                               | Section                                                     |
| -------------- |                                           |                                                             |
| C              |                                           |                                                             |
|                | [[#index-C_002dc-C_002dc][=C-c C-c=]]     | [[#Getting-started-with-rcirc][Getting started with rcirc]] |
|                | [[#index-C_002dc-C_002dj][=C-c C-j=]]     | [[#rcirc-commands][rcirc commands]]                         |
|                | [[#index-C_002dc-C_002dl][=C-c C-l=]]     | [[#Channels][Channels]]                                     |
|                | [[#index-C_002dc-C_002do][=C-c C-o=]]     | [[#Notices][Notices]]                                       |
|                | [[#index-C_002dc-C_002dp][=C-c C-p=]]     | [[#rcirc-commands][rcirc commands]]                         |
|                | [[#index-C_002dc-C_002dq][=C-c C-q=]]     | [[#rcirc-commands][rcirc commands]]                         |
|                | [[#index-C_002dc-C_002dr][=C-c C-r=]]     | [[#rcirc-commands][rcirc commands]]                         |
|                | [[#index-C_002dc-C_002dSPC][=C-c C-SPC=]] | [[#Channels][Channels]]                                     |
|                | [[#index-C_002dc-C_002dw][=C-c C-w=]]     | [[#rcirc-commands][rcirc commands]]                         |
|                | [[#index-C_002dc-C_002dx][=C-c C-x=]]     | [[#rcirc-commands][rcirc commands]]                         |
|                | [[#index-C_002dc-RET][=C-c RET=]]         | [[#rcirc-commands][rcirc commands]]                         |
|                | [[#index-C_002dc-TAB][=C-c TAB=]]         | [[#Channels][Channels]]                                     |
|                | [[#index-C_002dh-m][=C-h m=]]             | [[#rcirc-commands][rcirc commands]]                         |
| -------------- |                                           |                                                             |
| R              |                                           |                                                             |
|                | [[#index-RET][=RET=]]                     | [[#Getting-started-with-rcirc][Getting started with rcirc]] |
| -------------- |                                           |                                                             |
| T              |                                           |                                                             |
|                | [[#index-TAB][=TAB=]]                     | [[#Internet-Relay-Chat][Internet Relay Chat]]               |
| -------------- |                                           |                                                             |

| Jump to:   | [[#Key-Index_ky_letter-C][*C*]]   [[#Key-Index_ky_letter-R][*R*]]   [[#Key-Index_ky_letter-T][*T*]]   |

--------------

<<Variable-Index>>

Next: [[#Index][Index]], Previous: [[#Key-Index][Key Index]], Up:
[[#Top][rcirc Manual]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

** Variable Index [[#Variable-Index-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Variable-Index-1
:CLASS: unnumbered
:END:

| Jump to:   | [[#Variable-Index_vr_letter-R][*R*]]   [[#Variable-Index_vr_letter-S][*S*]]   [[#Variable-Index_vr_letter-U][*U*]]   |

|                | Index Entry                                                                                                   | Section                                                             |
| -------------- |                                                                                                               |                                                                     |
| R              |                                                                                                               |                                                                     |
|                | [[#index-rcirc_002dauthinfo][=rcirc-authinfo=]]                                                               | [[#Configuration][Configuration]]                                   |
|                | [[#index-rcirc_002dbridge_002dbot_002dalist][=rcirc-bridge-bot-alist=]]                                       | [[#Dealing-with-Bridge-Bots][Dealing with Bridge Bots]]             |
|                | [[#index-rcirc_002dchannel_002dfilter][=rcirc-channel-filter=]]                                               | [[#Using-rcirc-with-bouncers][Using rcirc with bouncers]]           |
|                | [[#index-rcirc_002dcycle_002dcompletion_002dflag][=rcirc-cycle-completion-flag=]]                             | [[#Internet-Relay-Chat][Internet Relay Chat]]                       |
|                | [[#index-rcirc_002ddefault_002dfull_002dname][=rcirc-default-full-name=]]                                     | [[#Configuration][Configuration]]                                   |
|                | [[#index-rcirc_002ddefault_002dnick][=rcirc-default-nick=]]                                                   | [[#Configuration][Configuration]]                                   |
|                | [[#index-rcirc_002ddefault_002dport][=rcirc-default-port=]]                                                   | [[#Configuration][Configuration]]                                   |
|                | [[#index-rcirc_002ddefault_002duser_002dname][=rcirc-default-user-name=]]                                     | [[#Configuration][Configuration]]                                   |
|                | [[#index-rcirc_002dlog_002dtime_002dformat][=rcirc-log-time-format=]]                                         | [[#Changing-the-time-stamp-format][Changing the time stamp format]] |
|                | [[#index-rcirc_002dmode_002dhook][=rcirc-mode-hook=]]                                                         | [[#Channels][Channels]]                                             |
|                | [[#index-rcirc_002dmode_002dhook-1][=rcirc-mode-hook=]]                                                       | [[#Using-fly-spell-mode][Using fly spell mode]]                     |
|                | [[#index-rcirc_002dmode_002dhook-2][=rcirc-mode-hook=]]                                                       | [[#Scrolling-conservatively][Scrolling conservatively]]             |
|                | [[#index-rcirc_002dnick_002dfilter][=rcirc-nick-filter=]]                                                     | [[#Using-rcirc-with-bouncers][Using rcirc with bouncers]]           |
|                | [[#index-rcirc_002domit_002dresponses][=rcirc-omit-responses=]]                                               | [[#Notices][Notices]]                                               |
|                | [[#index-rcirc_002domit_002dthreshold][=rcirc-omit-threshold=]]                                               | [[#Notices][Notices]]                                               |
|                | [[#index-rcirc_002domit_002dunless_002drequested][=rcirc-omit-unless-requested=]]                             | [[#Notices][Notices]]                                               |
|                | [[#index-rcirc_002dserver_002dalist][=rcirc-server-alist=]]                                                   | [[#Configuration][Configuration]]                                   |
|                | [[#index-rcirc_002dtime_002dformat][=rcirc-time-format=]]                                                     | [[#Changing-the-time-stamp-format][Changing the time stamp format]] |
|                | [[#index-rcirc_002dtrack_002dignore_002dserver_002dbuffer_002dflag][=rcirc-track-ignore-server-buffer-flag=]] | [[#Getting-started-with-rcirc][Getting started with rcirc]]         |
|                | [[#index-rcirc_002dtrack_002dminor_002dmode][=rcirc-track-minor-mode=]]                                       | [[#Channels][Channels]]                                             |
| -------------- |                                                                                                               |                                                                     |
| S              |                                                                                                               |                                                                     |
|                | [[#index-scroll_002dconservatively][=scroll-conservatively=]]                                                 | [[#Scrolling-conservatively][Scrolling conservatively]]             |
| -------------- |                                                                                                               |                                                                     |
| U              |                                                                                                               |                                                                     |
|                | [[#index-user_002dlogin_002dname][=user-login-name=]]                                                         | [[#Getting-started-with-rcirc][Getting started with rcirc]]         |
| -------------- |                                                                                                               |                                                                     |

| Jump to:   | [[#Variable-Index_vr_letter-R][*R*]]   [[#Variable-Index_vr_letter-S][*S*]]   [[#Variable-Index_vr_letter-U][*U*]]   |

--------------

<<Index>>

Previous: [[#Variable-Index][Variable Index]], Up:
[[#Top][rcirc Manual]]  
[[[#SEC_Contents][Contents]]][[[#Key-Index][Index]]]

** Index [[#Index-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Index-1
:CLASS: unnumbered
:END:

| Jump to:   | [[#Index_cp_symbol-1][*#*]]   [[#Index_cp_symbol-2][*/*]]   [[#Index_cp_symbol-3][*6*]]  \\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|            | [[#Index_cp_letter-A][*A*]]   [[#Index_cp_letter-B][*B*]]   [[#Index_cp_letter-C][*C*]]   [[#Index_cp_letter-D][*D*]]   [[#Index_cp_letter-E][*E*]]   [[#Index_cp_letter-F][*F*]]   [[#Index_cp_letter-G][*G*]]   [[#Index_cp_letter-H][*H*]]   [[#Index_cp_letter-I][*I*]]   [[#Index_cp_letter-J][*J*]]   [[#Index_cp_letter-K][*K*]]   [[#Index_cp_letter-L][*L*]]   [[#Index_cp_letter-M][*M*]]   [[#Index_cp_letter-N][*N*]]   [[#Index_cp_letter-O][*O*]]   [[#Index_cp_letter-P][*P*]]   [[#Index_cp_letter-Q][*Q*]]   [[#Index_cp_letter-R][*R*]]   [[#Index_cp_letter-S][*S*]]   [[#Index_cp_letter-T][*T*]]   [[#Index_cp_letter-U][*U*]]   [[#Index_cp_letter-W][*W*]]   [[#Index_cp_letter-Y][*Y*]]   |

|                | Index Entry                                                                                               | Section                                                                                 |
| -------------- |                                                                                                           |                                                                                         |
| ​#              |                                                                                                           |                                                                                         |
|                | [[#index-_0023-starts-a-channel-name][# starts a channel name]]                                           | [[#Internet-Relay-Chat][Internet Relay Chat]]                                           |
| -------------- |                                                                                                           |                                                                                         |
| /              |                                                                                                           |                                                                                         |
|                | [[#index-_002f-starts-a-command][/ starts a command]]                                                     | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-_002faway][/away]]                                                                               | [[#Useful-IRC-commands][Useful IRC commands]]                                           |
|                | [[#index-_002faway-messages][/away messages]]                                                             | [[#Skipping-_002faway-messages-using-handlers][Skipping /away messages using handlers]] |
|                | [[#index-_002fbright][/bright]]                                                                           | [[#People][People]]                                                                     |
|                | [[#index-_002fdim][/dim]]                                                                                 | [[#People][People]]                                                                     |
|                | [[#index-_002fignore][/ignore]]                                                                           | [[#People][People]]                                                                     |
|                | [[#index-_002fjoin][/join]]                                                                               | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-_002fkeyword][/keyword]]                                                                         | [[#Keywords][Keywords]]                                                                 |
|                | [[#index-_002fmsg][/msg]]                                                                                 | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-_002fnick][/nick]]                                                                               | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-_002fpart][/part]]                                                                               | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-_002fquery][/query]]                                                                             | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-_002fquit][/quit]]                                                                               | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-_002freconnect][/reconnect]]                                                                     | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-_002fwhois][/whois]]                                                                             | [[#rcirc-commands][rcirc commands]]                                                     |
| -------------- |                                                                                                           |                                                                                         |
| 6              |                                                                                                           |                                                                                         |
|                | [[#index-6667_002c-default-IRC-port][6667, default IRC port]]                                             | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
| -------------- |                                                                                                           |                                                                                         |
| A              |                                                                                                           |                                                                                         |
|                | [[#index-abbreviated-channel-names][abbreviated channel names]]                                           | [[#Channels][Channels]]                                                                 |
|                | [[#index-active-channel][active channel]]                                                                 | [[#Channels][Channels]]                                                                 |
|                | [[#index-addressing-other-people][addressing other people]]                                               | [[#Internet-Relay-Chat][Internet Relay Chat]]                                           |
|                | [[#index-AIM][AIM]]                                                                                       | [[#Configuration][Configuration]]                                                       |
|                | [[#index-authentication][authentication]]                                                                 | [[#Configuration][Configuration]]                                                       |
|                | [[#index-automatic-spelling][automatic spelling]]                                                         | [[#Using-fly-spell-mode][Using fly spell mode]]                                         |
|                | [[#index-away-notices_002c-how-to-omit][away notices, how to omit]]                                       | [[#Notices][Notices]]                                                                   |
|                | [[#index-away-status][away status]]                                                                       | [[#Useful-IRC-commands][Useful IRC commands]]                                           |
| -------------- |                                                                                                           |                                                                                         |
| B              |                                                                                                           |                                                                                         |
|                | [[#index-bitlbee-authentication][bitlbee authentication]]                                                 | [[#Configuration][Configuration]]                                                       |
|                | [[#index-bouncer][bouncer]]                                                                               | [[#Using-rcirc-with-bouncers][Using rcirc with bouncers]]                               |
|                | [[#index-bridge][bridge]]                                                                                 | [[#Dealing-with-Bridge-Bots][Dealing with Bridge Bots]]                                 |
|                | [[#index-brighten-nicks][brighten nicks]]                                                                 | [[#People][People]]                                                                     |
|                | [[#index-buddies][buddies]]                                                                               | [[#People][People]]                                                                     |
|                | [[#index-buddies_002c-highlight][buddies, highlight]]                                                     | [[#People][People]]                                                                     |
|                | [[#index-busy-channels][busy channels]]                                                                   | [[#Channels][Channels]]                                                                 |
| -------------- |                                                                                                           |                                                                                         |
| C              |                                                                                                           |                                                                                         |
|                | [[#index-call-commands][call commands]]                                                                   | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-case-insensitive-commands][case insensitive commands]]                                           | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-certfp-authentication][certfp authentication]]                                                   | [[#Configuration][Configuration]]                                                       |
|                | [[#index-change-name][change name]]                                                                       | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-changing-nick][changing nick]]                                                                   | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
|                | [[#index-channel][channel]]                                                                               | [[#Internet-Relay-Chat][Internet Relay Chat]]                                           |
|                | [[#index-channel-name][channel name]]                                                                     | [[#Internet-Relay-Chat][Internet Relay Chat]]                                           |
|                | [[#index-channels][channels]]                                                                             | [[#Channels][Channels]]                                                                 |
|                | [[#index-channels-other-people-are-on][channels other people are on]]                                     | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-channels_002c-configuration][channels, configuration]]                                           | [[#Configuration][Configuration]]                                                       |
|                | [[#index-channels_002c-connecting][channels, connecting]]                                                 | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
|                | [[#index-chanserv-authentication][chanserv authentication]]                                               | [[#Configuration][Configuration]]                                                       |
|                | [[#index-command-unknown][command unknown]]                                                               | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-commands][commands]]                                                                             | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-commands-1][commands]]                                                                           | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-commands-2][commands]]                                                                           | [[#Useful-IRC-commands][Useful IRC commands]]                                           |
|                | [[#index-commands_002c-defining][commands, defining]]                                                     | [[#Defining-a-new-command][Defining a new command]]                                     |
|                | [[#index-communicating][communicating]]                                                                   | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
|                | [[#index-completion-of-nicks][completion of nicks]]                                                       | [[#Internet-Relay-Chat][Internet Relay Chat]]                                           |
|                | [[#index-configuring-rcirc][configuring rcirc]]                                                           | [[#Configuration][Configuration]]                                                       |
|                | [[#index-connecting-to-a-server][connecting to a server]]                                                 | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
|                | [[#index-connection-end][connection end]]                                                                 | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-contact-one-person-only][contact one person only]]                                               | [[#rcirc-commands][rcirc commands]]                                                     |
| -------------- |                                                                                                           |                                                                                         |
| D              |                                                                                                           |                                                                                         |
|                | [[#index-date-time][date time]]                                                                           | [[#Changing-the-time-stamp-format][Changing the time stamp format]]                     |
|                | [[#index-defining-commands][defining commands]]                                                           | [[#Defining-a-new-command][Defining a new command]]                                     |
|                | [[#index-disappearing-messages-if-starting-with-a-slash][disappearing messages if starting with a slash]] | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-disconnect][disconnect]]                                                                         | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-disconnect-from-a-channel][disconnect from a channel]]                                           | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-disconnecting-servers_002c-reconnecting][disconnecting servers, reconnecting]]                   | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-discussion_002c-joining][discussion, joining]]                                                   | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-double_002dquotes][double-quotes]]                                                               | [[#rcirc-commands][rcirc commands]]                                                     |
| -------------- |                                                                                                           |                                                                                         |
| E              |                                                                                                           |                                                                                         |
|                | [[#index-edit-message-before-sending][edit message before sending]]                                       | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
|                | [[#index-end-connection][end connection]]                                                                 | [[#rcirc-commands][rcirc commands]]                                                     |
| -------------- |                                                                                                           |                                                                                         |
| F              |                                                                                                           |                                                                                         |
|                | [[#index-fly-spell][fly spell]]                                                                           | [[#Using-fly-spell-mode][Using fly spell mode]]                                         |
|                | [[#index-format-time-stamp][format time stamp]]                                                           | [[#Changing-the-time-stamp-format][Changing the time stamp format]]                     |
|                | [[#index-friends][friends]]                                                                               | [[#People][People]]                                                                     |
|                | [[#index-friends_002c-highlight][friends, highlight]]                                                     | [[#People][People]]                                                                     |
|                | [[#index-full-name][full name]]                                                                           | [[#Configuration][Configuration]]                                                       |
| -------------- |                                                                                                           |                                                                                         |
| G              |                                                                                                           |                                                                                         |
|                | [[#index-gateway-to-other-IM-services][gateway to other IM services]]                                     | [[#Configuration][Configuration]]                                                       |
|                | [[#index-getting-started][getting started]]                                                               | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
| -------------- |                                                                                                           |                                                                                         |
| H              |                                                                                                           |                                                                                         |
|                | [[#index-hacking-and-tweaking][hacking and tweaking]]                                                     | [[#Hacking-and-Tweaking][Hacking and Tweaking]]                                         |
|                | [[#index-handlers][handlers]]                                                                             | [[#Skipping-_002faway-messages-using-handlers][Skipping /away messages using handlers]] |
|                | [[#index-help-about-irc][help about irc]]                                                                 | [[#Useful-IRC-commands][Useful IRC commands]]                                           |
|                | [[#index-hide-some-posts][hide some posts]]                                                               | [[#People][People]]                                                                     |
|                | [[#index-highlight-other-people][highlight other people]]                                                 | [[#People][People]]                                                                     |
| -------------- |                                                                                                           |                                                                                         |
| I              |                                                                                                           |                                                                                         |
|                | [[#index-ICQ][ICQ]]                                                                                       | [[#Configuration][Configuration]]                                                       |
|                | [[#index-identification][identification]]                                                                 | [[#Configuration][Configuration]]                                                       |
|                | [[#index-identifying-people][identifying people]]                                                         | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-idiots-online][idiots online]]                                                                   | [[#People][People]]                                                                     |
|                | [[#index-ignored-channels][ignored channels]]                                                             | [[#Channels][Channels]]                                                                 |
|                | [[#index-ignoring-other-people][ignoring other people]]                                                   | [[#People][People]]                                                                     |
|                | [[#index-information-overload][information overload]]                                                     | [[#Fighting-Information-Overload][Fighting Information Overload]]                       |
|                | [[#index-initial-channels][initial channels]]                                                             | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
|                | [[#index-initial-channels_002c-configuration][initial channels, configuration]]                           | [[#Configuration][Configuration]]                                                       |
|                | [[#index-initial-servers_002c-configuration][initial servers, configuration]]                             | [[#Configuration][Configuration]]                                                       |
|                | [[#index-input-line][input line]]                                                                         | [[#Scrolling-conservatively][Scrolling conservatively]]                                 |
|                | [[#index-instant-messaging_002c-comparison][instant messaging, comparison]]                               | [[#Internet-Relay-Chat][Internet Relay Chat]]                                           |
|                | [[#index-instant-messaging_002c-other-services][instant messaging, other services]]                       | [[#Configuration][Configuration]]                                                       |
|                | [[#index-internet-relay-chat][internet relay chat]]                                                       | [[#Internet-Relay-Chat][Internet Relay Chat]]                                           |
|                | [[#index-irc][irc]]                                                                                       | [[#Internet-Relay-Chat][Internet Relay Chat]]                                           |
|                | [[#index-irc-command][irc command]]                                                                       | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
|                | [[#index-irc-commands][irc commands]]                                                                     | [[#Useful-IRC-commands][Useful IRC commands]]                                           |
|                | [[#index-irc-resources][irc resources]]                                                                   | [[#Useful-IRC-commands][Useful IRC commands]]                                           |
| -------------- |                                                                                                           |                                                                                         |
| J              |                                                                                                           |                                                                                         |
|                | [[#index-Jabber][Jabber]]                                                                                 | [[#Configuration][Configuration]]                                                       |
|                | [[#index-join-channels][join channels]]                                                                   | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-join-notices_002c-how-to-omit][join notices, how to omit]]                                       | [[#Notices][Notices]]                                                                   |
| -------------- |                                                                                                           |                                                                                         |
| K              |                                                                                                           |                                                                                         |
|                | [[#index-keywords][keywords]]                                                                             | [[#Keywords][Keywords]]                                                                 |
|                | [[#index-kill-channel-buffer][kill channel buffer]]                                                       | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-kill-connection][kill connection]]                                                               | [[#rcirc-commands][rcirc commands]]                                                     |
| -------------- |                                                                                                           |                                                                                         |
| L              |                                                                                                           |                                                                                         |
|                | [[#index-leave-a-channel][leave a channel]]                                                               | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-Libera_002eChat-network][Libera.Chat network]]                                                   | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
|                | [[#index-login][login]]                                                                                   | [[#Configuration][Configuration]]                                                       |
|                | [[#index-lost-connection][lost connection]]                                                               | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-low-priority-channels][low priority channels]]                                                   | [[#Channels][Channels]]                                                                 |
|                | [[#index-low-priority-channels-1][low priority channels]]                                                 | [[#Notices][Notices]]                                                                   |
| -------------- |                                                                                                           |                                                                                         |
| M              |                                                                                                           |                                                                                         |
|                | [[#index-message-sending][message sending]]                                                               | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-messages-starting-with-a-slash-disappear][messages starting with a slash disappear]]             | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-messages_002c-multiple-lines][messages, multiple lines]]                                         | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
|                | [[#index-modeline][modeline]]                                                                             | [[#Channels][Channels]]                                                                 |
|                | [[#index-modeline-tracks-activity][modeline tracks activity]]                                             | [[#Channels][Channels]]                                                                 |
|                | [[#index-MSN][MSN]]                                                                                       | [[#Configuration][Configuration]]                                                       |
|                | [[#index-multiline-messages][multiline messages]]                                                         | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
|                | [[#index-multiple-words-as-parameters][multiple words as parameters]]                                     | [[#rcirc-commands][rcirc commands]]                                                     |
| -------------- |                                                                                                           |                                                                                         |
| N              |                                                                                                           |                                                                                         |
|                | [[#index-name-changes][name changes]]                                                                     | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
|                | [[#index-network][network]]                                                                               | [[#Internet-Relay-Chat][Internet Relay Chat]]                                           |
|                | [[#index-new-command][new command]]                                                                       | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-new-commands_002c-defining][new commands, defining]]                                             | [[#Defining-a-new-command][Defining a new command]]                                     |
|                | [[#index-nick-changing][nick changing]]                                                                   | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-nick-completion][nick completion]]                                                               | [[#Internet-Relay-Chat][Internet Relay Chat]]                                           |
|                | [[#index-nick-notices_002c-how-to-omit][nick notices, how to omit]]                                       | [[#Notices][Notices]]                                                                   |
|                | [[#index-nick_002c-connecting][nick, connecting]]                                                         | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
|                | [[#index-nicks_002c-highlight][nicks, highlight]]                                                         | [[#People][People]]                                                                     |
|                | [[#index-nicks_002c-how-to-ignore][nicks, how to ignore]]                                                 | [[#People][People]]                                                                     |
|                | [[#index-nickserv][nickserv]]                                                                             | [[#Configuration][Configuration]]                                                       |
|                | [[#index-nickserv-authentication][nickserv authentication]]                                               | [[#Configuration][Configuration]]                                                       |
| -------------- |                                                                                                           |                                                                                         |
| O              |                                                                                                           |                                                                                         |
|                | [[#index-obnoxious-people-online][obnoxious people online]]                                               | [[#People][People]]                                                                     |
|                | [[#index-one_002dto_002done-conversation][one-to-one conversation]]                                       | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-other-channels][other channels]]                                                                 | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-other-name][other name]]                                                                         | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-other-people_002c-addressing-them][other people, addressing them]]                               | [[#Internet-Relay-Chat][Internet Relay Chat]]                                           |
| -------------- |                                                                                                           |                                                                                         |
| P              |                                                                                                           |                                                                                         |
|                | [[#index-part-a-channel][part a channel]]                                                                 | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-part-all-channels][part all channels]]                                                           | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-part-notices_002c-how-to-omit][part notices, how to omit]]                                       | [[#Notices][Notices]]                                                                   |
|                | [[#index-pasting-multiple-lines][pasting multiple lines]]                                                 | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
|                | [[#index-pause-status][pause status]]                                                                     | [[#Useful-IRC-commands][Useful IRC commands]]                                           |
|                | [[#index-people_002c-how-to-ignore][people, how to ignore]]                                               | [[#People][People]]                                                                     |
|                | [[#index-port][port]]                                                                                     | [[#Configuration][Configuration]]                                                       |
|                | [[#index-port_002c-connecting][port, connecting]]                                                         | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
|                | [[#index-private-conversation][private conversation]]                                                     | [[#rcirc-commands][rcirc commands]]                                                     |
| -------------- |                                                                                                           |                                                                                         |
| Q              |                                                                                                           |                                                                                         |
|                | [[#index-query-a-person][query a person]]                                                                 | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-quit][quit]]                                                                                     | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-quit-notices_002c-how-to-omit][quit notices, how to omit]]                                       | [[#Notices][Notices]]                                                                   |
|                | [[#index-quotes][quotes]]                                                                                 | [[#rcirc-commands][rcirc commands]]                                                     |
| -------------- |                                                                                                           |                                                                                         |
| R              |                                                                                                           |                                                                                         |
|                | [[#index-rabble-online][rabble online]]                                                                   | [[#People][People]]                                                                     |
|                | [[#index-rcirc-commands][rcirc commands]]                                                                 | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-rcirc_002dtrack_002dabbreviate_002dflag][rcirc-track-abbreviate-flag]]                           | [[#Channels][Channels]]                                                                 |
|                | [[#index-real-name][real name]]                                                                           | [[#Configuration][Configuration]]                                                       |
|                | [[#index-reason-for-quitting][reason for quitting]]                                                       | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-reconnect][reconnect]]                                                                           | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-redirection-to-random-servers][redirection to random servers]]                                   | [[#Internet-Relay-Chat][Internet Relay Chat]]                                           |
|                | [[#index-reference][reference]]                                                                           | [[#Reference][Reference]]                                                               |
|                | [[#index-rename-yourself][rename yourself]]                                                               | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-rooms_002c-joining][rooms, joining]]                                                             | [[#rcirc-commands][rcirc commands]]                                                     |
| -------------- |                                                                                                           |                                                                                         |
| S              |                                                                                                           |                                                                                         |
|                | [[#index-sasl-authentication][sasl authentication]]                                                       | [[#Configuration][Configuration]]                                                       |
|                | [[#index-scrolling][scrolling]]                                                                           | [[#Scrolling-conservatively][Scrolling conservatively]]                                 |
|                | [[#index-server][server]]                                                                                 | [[#Internet-Relay-Chat][Internet Relay Chat]]                                           |
|                | [[#index-server-buffer][server buffer]]                                                                   | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
|                | [[#index-server-buffer-killing][server buffer killing]]                                                   | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-server_002c-connecting][server, connecting]]                                                     | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
|                | [[#index-servers_002c-configuration][servers, configuration]]                                             | [[#Configuration][Configuration]]                                                       |
|                | [[#index-set-away-status][set away status]]                                                               | [[#Useful-IRC-commands][Useful IRC commands]]                                           |
|                | [[#index-single-message][single message]]                                                                 | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-slash-hides-message][slash hides message]]                                                       | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-soft_002dignore-other-people][soft-ignore other people]]                                         | [[#People][People]]                                                                     |
|                | [[#index-spell_002dchecking-as-you-type][spell-checking as you type]]                                     | [[#Using-fly-spell-mode][Using fly spell mode]]                                         |
|                | [[#index-spelling][spelling]]                                                                             | [[#Using-fly-spell-mode][Using fly spell mode]]                                         |
|                | [[#index-starting-a-private-conversation][starting a private conversation]]                               | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-startup-channels][startup channels]]                                                             | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
|                | [[#index-startup-channels_002c-configuration][startup channels, configuration]]                           | [[#Configuration][Configuration]]                                                       |
|                | [[#index-startup-servers_002c-configuration][startup servers, configuration]]                             | [[#Configuration][Configuration]]                                                       |
|                | [[#index-status-codes][status codes]]                                                                     | [[#Skipping-_002faway-messages-using-handlers][Skipping /away messages using handlers]] |
|                | [[#index-stop-talking-on-a-channel][stop talking on a channel]]                                           | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-string-delimiters][string delimiters]]                                                           | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-surname][surname]]                                                                               | [[#Configuration][Configuration]]                                                       |
|                | [[#index-switching-channels][switching channels]]                                                         | [[#Channels][Channels]]                                                                 |
| -------------- |                                                                                                           |                                                                                         |
| T              |                                                                                                           |                                                                                         |
|                | [[#index-talk-privately][talk privately]]                                                                 | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-talk-to-other-people][talk to other people]]                                                     | [[#Internet-Relay-Chat][Internet Relay Chat]]                                           |
|                | [[#index-talking][talking]]                                                                               | [[#Getting-started-with-rcirc][Getting started with rcirc]]                             |
|                | [[#index-time-stamp][time stamp]]                                                                         | [[#Changing-the-time-stamp-format][Changing the time stamp format]]                     |
|                | [[#index-tracking-activity][tracking activity]]                                                           | [[#Channels][Channels]]                                                                 |
|                | [[#index-trolls][trolls]]                                                                                 | [[#People][People]]                                                                     |
|                | [[#index-trolls_002c-ignoring][trolls, ignoring]]                                                         | [[#People][People]]                                                                     |
|                | [[#index-typing-commands][typing commands]]                                                               | [[#rcirc-commands][rcirc commands]]                                                     |
| -------------- |                                                                                                           |                                                                                         |
| U              |                                                                                                           |                                                                                         |
|                | [[#index-unavailable-status][unavailable status]]                                                         | [[#Useful-IRC-commands][Useful IRC commands]]                                           |
|                | [[#index-unknown-command][unknown command]]                                                               | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-user-name][user name]]                                                                           | [[#Configuration][Configuration]]                                                       |
| -------------- |                                                                                                           |                                                                                         |
| W              |                                                                                                           |                                                                                         |
|                | [[#index-what-channels-people-are-on][what channels people are on]]                                       | [[#rcirc-commands][rcirc commands]]                                                     |
|                | [[#index-who-are-these-people][who are these people]]                                                     | [[#rcirc-commands][rcirc commands]]                                                     |
| -------------- |                                                                                                           |                                                                                         |
| Y              |                                                                                                           |                                                                                         |
|                | [[#index-Yahoo_0021][Yahoo!]]                                                                             | [[#Configuration][Configuration]]                                                       |
| -------------- |                                                                                                           |                                                                                         |

| Jump to:   | [[#Index_cp_symbol-1][*#*]]   [[#Index_cp_symbol-2][*/*]]   [[#Index_cp_symbol-3][*6*]]  \\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|            | [[#Index_cp_letter-A][*A*]]   [[#Index_cp_letter-B][*B*]]   [[#Index_cp_letter-C][*C*]]   [[#Index_cp_letter-D][*D*]]   [[#Index_cp_letter-E][*E*]]   [[#Index_cp_letter-F][*F*]]   [[#Index_cp_letter-G][*G*]]   [[#Index_cp_letter-H][*H*]]   [[#Index_cp_letter-I][*I*]]   [[#Index_cp_letter-J][*J*]]   [[#Index_cp_letter-K][*K*]]   [[#Index_cp_letter-L][*L*]]   [[#Index_cp_letter-M][*M*]]   [[#Index_cp_letter-N][*N*]]   [[#Index_cp_letter-O][*O*]]   [[#Index_cp_letter-P][*P*]]   [[#Index_cp_letter-Q][*Q*]]   [[#Index_cp_letter-R][*R*]]   [[#Index_cp_letter-S][*S*]]   [[#Index_cp_letter-T][*T*]]   [[#Index_cp_letter-U][*U*]]   [[#Index_cp_letter-W][*W*]]   [[#Index_cp_letter-Y][*Y*]]   |
