<<Top>>

Next: [[#Wisent-Overview][Wisent Overview]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

* Wisent Parser Development [[#Wisent-Parser-Development][¶]]
:PROPERTIES:
:CUSTOM_ID: Wisent-Parser-Development
:CLASS: top
:END:
Wisent (the European Bison ;-) is an Emacs Lisp implementation of the
GNU Compiler Compiler Bison.

This manual describes how to use Wisent to develop grammars for
programming languages, and how to use grammars to parse language source
in Emacs buffers.

It also describes how Wisent is used with the /Semantic/ tool set
described in the
[[https://www.gnu.org/software/emacs/manual/html_mono/semantic.html#Top][Semantic Manual]].

Copyright © 1988--1993, 1995, 1998--2004, 2007, 2012--2026 Free Software
Foundation, Inc.

#+begin_quote
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being “A GNU Manual,” and
with the Back-Cover Texts as in (a) below. A copy of the license is
included in the section entitled “GNU Free Documentation License”.

(a) The FSF's Back-Cover Text is: “You have the freedom to copy and
modify this GNU manual.”
#+end_quote

<<SEC_Contents>>
** Table of Contents
:PROPERTIES:
:CUSTOM_ID: table-of-contents
:CLASS: contents-heading
:END:

- [[#Wisent-Overview][1 Wisent Overview]]
- [[#Wisent-Grammar][2 Wisent Grammar]]
  - [[#Grammar-format][2.1 Grammar format]]
  - [[#Example][2.2 Example]]
  - [[#Compiling-a-grammar][2.3 Compiling a grammar]]
  - [[#Conflicts][2.4 Conflicts]]
    - [[#Grammar-Debugging][2.4.1 Grammar debugging]]
    - [[#Understanding-the-automaton][2.4.2 Understanding the automaton]]
- [[#Wisent-Parsing][3 Wisent Parsing]]
  - [[#Writing-a-lexer][3.1 What the parser must receive]]
  - [[#Actions-goodies][3.2 Variables and macros useful in grammar actions.]]
  - [[#Report-errors][3.3 The error reporting function]]
  - [[#Error-recovery][3.4 Error recovery]]
  - [[#Debugging-actions][3.5 Debugging semantic actions]]
- [[#Wisent-Semantic][4 How to use Wisent with Semantic]]
  - [[#Grammar-styles][4.1 Grammar styles]]
    - [[#Iterative-style][4.1.1 Iterative style]]
    - [[#Bison-style][4.1.2 Bison style]]
    - [[#Mixed-style][4.1.3 Mixed style]]
    - [[#Start-nonterminals][4.1.4 Start nonterminals]]
    - [[#Useful-functions][4.1.5 Useful functions]]
  - [[#Wisent-Lex][4.2 The Wisent Lex lexer]]
- [[#GNU-Free-Documentation-License][Appendix A GNU Free Documentation License]]
- [[#Index][Index]]

--------------

<<Wisent-Overview>>

Next: [[#Wisent-Grammar][Wisent Grammar]], Previous:
[[#Top][Wisent Parser Development]], Up:
[[#Top][Wisent Parser Development]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

** 1 Wisent Overview [[#Wisent-Overview-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Wisent-Overview-1
:CLASS: chapter
:END:
/Wisent/ (the European Bison) is an implementation in Emacs Lisp of the
GNU Compiler Compiler Bison. Its code is a port of the C code of GNU
Bison 1.28 & 1.31.

For more details on the basic concepts for understanding Wisent, it is
worthwhile to read the
[[https://www.gnu.org/software/bison/manual/bison.html#Top][Bison Manual]].

Wisent can generate compilers compatible with the /Semantic/ tool set.
See the
[[https://www.gnu.org/software/emacs/manual/html_mono/semantic.html#Top][Semantic Manual]].

It benefits from these Bison features:

- It uses a fast but not so space-efficient encoding for the parse
  tables, described in Corbett's PhD thesis from Berkeley:

  #+begin_quote
  Static Semantics in Compiler Error Recovery\\
  June 1985, Report No. UCB/CSD 85/251.
  #+end_quote

- For generating the lookahead sets, Wisent uses the well-known
  technique of F. DeRemer and T. Pennello described in:

  #+begin_quote
  Efficient Computation of LALR(1) Look-Ahead Sets\\
  October 1982, ACM TOPLAS Vol 4 No 4, 615--49,
  [[https://doi.org/10.1145/69622.357187]].
  #+end_quote

- Wisent resolves shift/reduce conflicts using operator precedence and
  associativity.

- Parser error recovery is accomplished using rules which match the
  special token =error=.

Nevertheless there are some fundamental differences between Bison and
Wisent.

- Wisent is intended to be used in Emacs. It reads and produces Emacs
  Lisp data structures. All the additional code used in grammars is
  Emacs Lisp code.
- Contrary to Bison, Wisent does not generate a parser which combines
  Emacs Lisp code and grammar constructs. They exist separately. Wisent
  reads the grammar from a Lisp data structure and then generates
  grammar constructs as tables. Afterward, the derived tables can be
  included and byte-compiled in separate Emacs Lisp files, and be used
  at a later time by the Wisent's parser engine.
- Wisent allows multiple start nonterminals and allows a call to the
  parsing function to be made for a particular start nonterminal. For
  example, this is particularly useful to parse a region of an Emacs
  buffer. /Semantic/ heavily depends on the availability of this
  feature.

--------------

<<Wisent-Grammar>>

Next: [[#Wisent-Parsing][Wisent Parsing]], Previous:
[[#Wisent-Overview][Wisent Overview]], Up:
[[#Top][Wisent Parser Development]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

** 2 Wisent Grammar [[#Wisent-Grammar-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Wisent-Grammar-1
:CLASS: chapter
:END:
In order for Wisent to parse a language, it must be described by a
/context-free grammar/. That is a grammar specified as rules that can be
applied regardless of context. For more information, see
[[https://www.gnu.org/software/bison/manual/bison.html#Language-and-Grammar][(bison)Language and Grammar]],
in the Bison manual.

The formal grammar is formulated using /terminal/ and /nonterminal/
items. Terminals can be Emacs Lisp symbols or characters, and
nonterminals are symbols only.

Terminals (also known as /tokens/) represent the lexical elements of the
language like numbers, strings, etc..

For example ‘=PLUS=' can represent the operator ‘=+='.

Nonterminal symbols are described by rules:

#+begin_src example-preformatted
RESULT ≡ COMPONENTS...
#+end_src

‘=RESULT=' is a nonterminal that this rule describes and ‘=COMPONENTS='
are various terminals and nonterminals that are put together by this
rule.

For example, this rule:

#+begin_src example-preformatted
exp ≡ exp PLUS exp
#+end_src

Says that two groupings of type ‘=exp=', with a ‘=PLUS=' token in
between, can be combined into a larger grouping of type ‘=exp='.

- [[#Grammar-format][Grammar format]]
- [[#Example][Example]]
- [[#Compiling-a-grammar][Compiling a grammar]]
- [[#Conflicts][Conflicts]]

--------------

<<Grammar-format>>

Next: [[#Example][Example]], Up: [[#Wisent-Grammar][Wisent Grammar]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

*** 2.1 Grammar format [[#Grammar-format-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Grammar-format-1
:CLASS: section
:END:
To be acceptable by Wisent a context-free grammar must respect a
particular format. That is, must be represented as an Emacs Lisp list of
the form:

=(==terminals== ==assocs== . ==non-terminals==)=

- =terminals= :: Is the list of terminal symbols used in the grammar.

- <<index-associativity>>=assocs= [[#index-associativity][¶]] :: Specify
  the associativity of =terminals=. It is =nil= when there is no
  associativity defined, or an alist of
  =(==assoc-type== . ==assoc-value==)= elements.

  =assoc-type= must be one of the =default-prec=, =nonassoc=, =left= or
  =right= symbols. When =assoc-type= is =default-prec=, =assoc-value=
  must be =nil= or =t= (the default). Otherwise it is a list of tokens
  which must have been previously declared in =terminals=.

  For details, see
  [[https://www.gnu.org/software/bison/manual/bison.html#Contextual-Precedence][(bison)Contextual Precedence]],
  in the Bison manual.

- =non-terminals= :: Is the list of nonterminal definitions. Each
  definition has the form:

  =(==nonterm== . ==rules==)=

  Where =nonterm= is the nonterminal symbol defined and =rules= the list
  of rules that describe this nonterminal. Each rule is a list:

  =(==components== [==precedence==] [==action==])=

  Where:

  - =components= :: Is a list of various terminals and nonterminals that
    are put together by this rule.

    For example,

    #+begin_src example-preformatted
    (exp ((exp ?+ exp))          ;; exp: exp '+' exp
         )                       ;;    ;
    #+end_src

    Says that two groupings of type ‘=exp=', with a ‘=+=' token in
    between, can be combined into a larger grouping of type ‘=exp='.

    By convention, a nonterminal symbol should be in lower case, such as
    ‘=exp=', ‘=stmt=' or ‘=declaration='. Terminal symbols should be
    upper case to distinguish them from nonterminals: for example,
    ‘=INTEGER=', ‘=IDENTIFIER=', ‘=IF=' or ‘=RETURN='. A terminal symbol
    that represents a particular keyword in the language is
    conventionally the same as that keyword converted to upper case. The
    terminal symbol =error= is reserved for error recovery.

    Scattered among the components can be /middle-rule/ actions. Usually
    only =action= is provided (see [[#action][action]]).

    If =components= in a rule is =nil=, it means that the rule can match
    the empty string. For example, here is how to define a
    comma-separated sequence of zero or more ‘=exp=' groupings:

    #+begin_src example-preformatted
    (expseq  (nil)               ;; expseq: ;; empty
             ((expseq1))         ;;       | expseq1
             )                   ;;       ;

    (expseq1 ((exp))             ;; expseq1: exp
             ((expseq1 ?, exp))  ;;        | expseq1 ',' exp
             )                   ;;        ;
    #+end_src

  - <<index-precedence-level>>=precedence=
    [[#index-precedence-level][¶]] :: Assign the rule the precedence of
    the given terminal item, overriding the precedence that would be
    deduced for it, that is the one of the last terminal in it. Notice
    that only terminals declared in =assocs= have a precedence level.
    The altered rule precedence then affects how conflicts involving
    that rule are resolved.

    =precedence= is an optional vector of one terminal item.

    Here is how =precedence= solves the problem of unary minus. First,
    declare a precedence for a fictitious terminal symbol named
    =UMINUS=. There are no tokens of this type, but the symbol serves to
    stand for its precedence:

    #+begin_src example-preformatted
    ...
    ((default-prec t) ;; This is the default
     (left '+' '-')
     (left '*')
     (left UMINUS))
    #+end_src

    Now the precedence of =UMINUS= can be used in specific rules:

    #+begin_src example-preformatted
    (exp    ...                  ;; exp:    ...
             ((exp ?- exp))      ;;         | exp '-' exp
            ...                  ;;         ...
             ((?- exp) [UMINUS]) ;;         | '-' exp %prec UMINUS
            ...                  ;;         ...
            )                    ;;         ;
    #+end_src

    If you forget to append =[UMINUS]= to the rule for unary minus,
    Wisent silently assumes that minus has its usual precedence. This
    kind of problem can be tricky to debug, since one typically
    discovers the mistake only by testing the code.

    Using =(default-prec nil)= declaration makes it easier to discover
    this kind of problem systematically. It causes rules that lack a
    =precedence= modifier to have no precedence, even if the last
    terminal symbol mentioned in their components has a declared
    precedence.

    If =(default-prec nil)= is in effect, you must specify =precedence=
    for all rules that participate in precedence conflict resolution.
    Then you will see any shift/reduce conflict until you tell Wisent
    how to resolve it, either by changing your grammar or by adding an
    explicit precedence. This will probably add declarations to the
    grammar, but it helps to protect against incorrect rule precedences.

    The effect of =(default-prec nil)= can be reversed by giving
    =(default-prec t)=, which is the default.

    For more details, see
    [[https://www.gnu.org/software/bison/manual/bison.html#Contextual-Precedence][(bison)Contextual Precedence]],
    in the Bison manual.

    It is important to understand that =assocs= declarations defines
    associativity but also assign a precedence level to terminals. All
    terminals declared in the same =left=, =right= or =nonassoc=
    association get the same precedence level. The precedence level is
    increased at each new association.

    On the other hand, =precedence= explicitly assign the precedence
    level of the given terminal to a rule.

  - =action= :: An action is an optional Emacs Lisp function call, like
    this:

    =(identity $1)=

    The result of an action determines the semantic value of a rule.

    From an implementation standpoint, the function call will be
    embedded in a lambda expression, and several useful local variables
    will be defined:

    - <<index-_0024N>>=$==n= [[#index-_0024N][¶]] :: Where =n= is a
      positive integer. Like in Bison, the value of =$==n= is the
      semantic value of the =n=th element of =components=, starting
      from 1. It can be of any Lisp data type.

    - <<index-_0024regionn>>=$regionN=
      [[#index-_0024regionn][¶]] :: Where =n= is a positive integer. For
      each =$==n= variable defined there is a corresponding =$region==n=
      variable. Its value is a pair =(==start-pos== . ==end-pos==)= that
      represent the start and end positions (in the lexical input
      stream) of the =$==n= value. It can be =nil= when the component
      positions are not available, like for an empty string component
      for example.

    - <<index-_0024region>>=$region= [[#index-_0024region][¶]] :: Its
      value is the leftmost and rightmost positions of input data
      matched by all =components= in the rule. This is a pair
      =(==leftmost-pos== . ==rightmost-pos==)=. It can be =nil= when
      components positions are not available.

    - <<index-_0024nterm>>=$nterm= [[#index-_0024nterm][¶]] :: This
      variable is initialized with the nonterminal symbol (=nonterm=)
      the rule belongs to. It could be useful to improve error reporting
      or debugging. It is also used to automatically provide incremental
      re-parse entry points for /Semantic/ tags (see
      [[#Wisent-Semantic][How to use Wisent with Semantic]]).

    - <<index-_0024action>>=$action= [[#index-_0024action][¶]] :: The
      value of =$action= is the symbolic name of the current semantic
      action (see [[#Debugging-actions][Debugging semantic actions]]).

    When an action is not specified a default value is supplied, it is
    =(identity $1)=. This means that the default semantic value of a
    rule is the value of its first component. Excepted for a rule
    matching the empty string, for which the default action is to return
    =nil=.

--------------

<<Example>>

Next: [[#Compiling-a-grammar][Compiling a grammar]], Previous:
[[#Grammar-format][Grammar format]], Up:
[[#Wisent-Grammar][Wisent Grammar]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

*** 2.2 Example [[#Example-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Example-1
:CLASS: section
:END:
Here is an example to parse simple infix arithmetic expressions. See
[[https://www.gnu.org/software/bison/manual/bison.html#Infix-Calc][(bison)Infix Calc]],
in the Bison manual for details.

#+begin_src lisp-preformatted
'(
  ;; Terminals
  (NUM)

  ;; Terminal associativity & precedence
  ((nonassoc ?=)
   (left ?- ?+)
   (left ?* ?/)
   (left NEG)
   (right ?^))

  ;; Rules
  (input
   ((line))
   ((input line)
    (format "%s %s" $1 $2))
   )

  (line
   ((?;)
    (progn ";"))
   ((exp ?;)
    (format "%s;" $1))
   ((error ?;)
    (progn "Error;")))
   )

  (exp
   ((NUM)
    (string-to-number $1))
   ((exp ?= exp)
    (= $1 $3))
   ((exp ?+ exp)
    (+ $1 $3))
   ((exp ?- exp)
    (- $1 $3))
   ((exp ?* exp)
    (* $1 $3))
   ((exp ?/ exp)
    (/ $1 $3))
   ((?- exp) [NEG]
    (- $2))
   ((exp ?^ exp)
    (expt $1 $3))
   ((?\( exp ?\))
    (progn $2))
   )
  )
#+end_src

In the bison-like /WY/ format (see
[[#Wisent-Semantic][How to use Wisent with Semantic]]) the grammar looks
like this:

#+begin_src example-preformatted
%token <number> NUM

%nonassoc '=' ;; comparison
%left '-' '+'
%left '*' '/'
%left NEG     ;; negation--unary minus
%right '^'    ;; exponentiation

%%

input:
    line
  | input line
    (format "%s %s" $1 $2)
  ;

line:
    ';'
    {";"}
  | exp ';'
    (format "%s;" $1)
  | error ';'
    {"Error;"}
  ;

exp:
    NUM
    (string-to-number $1)
  | exp '=' exp
    (= $1 $3)
  | exp '+' exp
    (+ $1 $3)
  | exp '-' exp
    (- $1 $3)
  | exp '*' exp
    (* $1 $3)
  | exp '/' exp
    (/ $1 $3)
  | '-' exp %prec NEG
    (- $2)
  | exp '^' exp
    (expt $1 $3)
  | '(' exp ')'
    {$2}
  ;

%%
#+end_src

--------------

<<Compiling-a-grammar>>

Next: [[#Conflicts][Conflicts]], Previous: [[#Example][Example]], Up:
[[#Wisent-Grammar][Wisent Grammar]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

*** 2.3 Compiling a grammar [[#Compiling-a-grammar-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Compiling-a-grammar-1
:CLASS: section
:END:
After providing a context-free grammar in a suitable format, it must be
translated into a set of tables (an /automaton/) that will be used to
derive the parser. Like Bison, Wisent translates grammars that must be
/LALR(1)/.

A grammar is LALR(1) if it is possible to tell how to parse any portion
of an input string with just a single token of look-ahead: the
/look-ahead token/. See
[[https://www.gnu.org/software/bison/manual/bison.html#Language-and-Grammar][(bison)Language and Grammar]],
in the Bison manual for more information.

Grammar translation (compilation) is achieved by the function:

- Function: *wisent-compile-grammar* =grammar &optional start-list=
  [[#index-wisent_002dcompile_002dgrammar-1][¶]] :: Compile =grammar=
  and return an LALR(1) automaton.

  Optional argument =start-list= is a list of start symbols
  (nonterminals). If =nil= the first nonterminal defined in the grammar
  is the default start symbol. If =start-list= contains only one
  element, it defines the start symbol. If =start-list= contains more
  than one element, all are defined as potential start symbols, unless
  =wisent-single-start-flag= is non-=nil=. In that case the first
  element of =start-list= defines the start symbol and others are
  ignored.

  The LALR(1) automaton is a vector of the form:

  =[==actions gotos starts functions==]=

  - =actions= :: A state/token matrix telling the parser what to do at
    every state based on the current look-ahead token. That is shift,
    reduce, accept or error. See also
    [[#Wisent-Parsing][Wisent Parsing]].

  - =gotos= :: A state/nonterminal matrix telling the parser the next
    state to go to after reducing with each rule.

  - =starts= :: An alist which maps the allowed start symbols
    (nonterminals) to lexical tokens that will be first shifted into the
    parser stack.

  - =functions= :: An obarray of semantic action symbols. A semantic
    action is actually an Emacs Lisp function (lambda expression).

--------------

<<Conflicts>>

Previous: [[#Compiling-a-grammar][Compiling a grammar]], Up:
[[#Wisent-Grammar][Wisent Grammar]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

*** 2.4 Conflicts [[#Conflicts-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Conflicts-1
:CLASS: section
:END:
Normally, a grammar should produce an automaton where at each state the
parser has only one action to do (see
[[#Wisent-Parsing][Wisent Parsing]]).

In certain cases, a grammar can produce an automaton where, at some
states, there are more than one action possible. Such a grammar is
/ambiguous/, and generates /conflicts/.

The parser can't be driven by an automaton which isn't completely
/deterministic/, that is which contains conflicts. It is necessary to
resolve the conflicts to eliminate them. Wisent resolves conflicts like
Bison does.

There are two sorts of conflicts:

- <<index-shift_002freduce-conflicts>>/shift/reduce conflicts/
  [[#index-shift_002freduce-conflicts][¶]] :: When either a shift or a
  reduction would be valid at the same state.

  Such conflicts are resolved by choosing to shift, unless otherwise
  directed by operator precedence declarations. See
  [[https://www.gnu.org/software/bison/manual/bison.html#Shift_002fReduce][(bison)Shift/Reduce]],
  in the Bison manual for more information.

- <<index-reduce_002freduce-conflicts>>/reduce/reduce conflicts/
  [[#index-reduce_002freduce-conflicts][¶]] :: That occurs if there are
  two or more rules that apply to the same sequence of input. This
  usually indicates a serious error in the grammar.

  Such conflicts are resolved by choosing to use the rule that appears
  first in the grammar, but it is very risky to rely on this. Every
  reduce/reduce conflict must be studied and usually eliminated. See
  [[https://www.gnu.org/software/bison/manual/bison.html#Reduce_002fReduce][(bison)Reduce/Reduce]],
  in the Bison manual for more information.

- [[#Grammar-Debugging][Grammar debugging]]
- [[#Understanding-the-automaton][Understanding the automaton]]

--------------

<<Grammar-Debugging>>

Next: [[#Understanding-the-automaton][Understanding the automaton]], Up:
[[#Conflicts][Conflicts]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

**** 2.4.1 Grammar debugging [[#Grammar-debugging][¶]]
:PROPERTIES:
:CUSTOM_ID: Grammar-debugging
:CLASS: subsection
:END:
To help writing a new grammar, =wisent-compile-grammar= can produce a
verbose report containing a detailed description of the grammar and
parser (equivalent to what Bison reports with the =--verbose= option).

To enable the verbose report you can set to non-=nil= the variable:

- Option: *wisent-verbose-flag*
  [[#index-wisent_002dverbose_002dflag][¶]] :: non-=nil= means to report
  verbose information on generated parser.

Or interactively use the command:

- Command: *wisent-toggle-verbose-flag*
  [[#index-wisent_002dtoggle_002dverbose_002dflag-1][¶]] :: Toggle
  whether to report verbose information on generated parser.

The verbose report is printed in the temporary buffer =*wisent-log*=
when running interactively, or in file =wisent.output= when running in
batch mode. Different reports are separated from each other by a line
like this:

#+begin_src example-preformatted
,*** Wisent source-file - 2002-06-27 17:33
#+end_src

where =source-file= is the name of the Emacs Lisp file from which the
grammar was read. See
[[#Understanding-the-automaton][Understanding the automaton]], for
details on the verbose report.

- *Please Note* :: To help debugging the grammar compiler itself, you
  can set this variable to print the content of some internal data
  structures:

  - Variable: *wisent-debug-flag*
    [[#index-wisent_002ddebug_002dflag-1][¶]] :: non-=nil= means enable
    some debug stuff.

--------------

<<Understanding-the-automaton>>

Previous: [[#Grammar-Debugging][Grammar debugging]], Up:
[[#Conflicts][Conflicts]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

**** 2.4.2 Understanding the automaton [[#Understanding-the-automaton-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Understanding-the-automaton-1
:CLASS: subsection
:END:
This section (took from the manual of Bison 1.49) describes how to use
the verbose report printed by =wisent-compile-grammar= to understand the
generated automaton, to tune or fix a grammar.

We will use the following example:

#+begin_src example-preformatted
(let ((wisent-verbose-flag t)) ;; Print a verbose report!
  (wisent-compile-grammar
   '((NUM STR)                          ; %token NUM STR

     ((left ?+ ?-)                      ; %left '+' '-';
      (left ?*))                        ; %left '*'

     (exp                               ; exp:
      ((exp ?+ exp))                    ;    exp '+' exp
      ((exp ?- exp))                    ;  | exp '-' exp
      ((exp ?* exp))                    ;  | exp '*' exp
      ((exp ?/ exp))                    ;  | exp '/' exp
      ((NUM))                           ;  | NUM
      )                                 ;  ;

     (useless                           ; useless:
      ((STR))                           ;    STR
      )                                 ;  ;
     )
   'nil)                                ; no %start declarations
  )
#+end_src

When evaluating the above expression, grammar compilation first issues
the following two clear messages:

#+begin_src example-preformatted
Grammar contains 1 useless nonterminals and 1 useless rules
Grammar contains 7 shift/reduce conflicts
#+end_src

The =*wisent-log*= buffer details things!

The first section reports conflicts that were solved using precedence
and/or associativity:

#+begin_src example-preformatted
Conflict in state 7 between rule 1 and token '+' resolved as reduce.
Conflict in state 7 between rule 1 and token '-' resolved as reduce.
Conflict in state 7 between rule 1 and token '*' resolved as shift.
Conflict in state 8 between rule 2 and token '+' resolved as reduce.
Conflict in state 8 between rule 2 and token '-' resolved as reduce.
Conflict in state 8 between rule 2 and token '*' resolved as shift.
Conflict in state 9 between rule 3 and token '+' resolved as reduce.
Conflict in state 9 between rule 3 and token '-' resolved as reduce.
Conflict in state 9 between rule 3 and token '*' resolved as reduce.
#+end_src

The next section reports useless tokens, nonterminal and rules (note
that useless tokens might be used by the scanner):

#+begin_src example-preformatted
Useless nonterminals:

   useless


Terminals which are not used:

   STR


Useless rules:

#6     useless: STR;
#+end_src

The next section lists states that still have conflicts:

#+begin_src example-preformatted
State 7 contains 1 shift/reduce conflict.
State 8 contains 1 shift/reduce conflict.
State 9 contains 1 shift/reduce conflict.
State 10 contains 4 shift/reduce conflicts.
#+end_src

The next section reproduces the grammar used:

#+begin_src example-preformatted
Grammar

  Number, Rule
  1       exp -> exp '+' exp
  2       exp -> exp '-' exp
  3       exp -> exp '*' exp
  4       exp -> exp '/' exp
  5       exp -> NUM
#+end_src

And reports the uses of the symbols:

#+begin_src example-preformatted
Terminals, with rules where they appear

$EOI (-1)
error (1)
NUM (2) 5
STR (3) 6
'+' (4) 1
'-' (5) 2
'*' (6) 3
'/' (7) 4


Nonterminals, with rules where they appear

exp (8)
    on left: 1 2 3 4 5, on right: 1 2 3 4
#+end_src

The report then details the automaton itself, describing each state with
it set of /items/, also known as /pointed rules/. Each item is a
production rule together with a point (marked by ‘=.=') that the input
cursor.

#+begin_src example-preformatted
state 0

    NUM shift, and go to state 1

    exp go to state 2
#+end_src

State 0 corresponds to being at the very beginning of the parsing, in
the initial rule, right before the start symbol (‘=exp='). When the
parser returns to this state right after having reduced a rule that
produced an ‘=exp=', it jumps to state 2. If there is no such transition
on a nonterminal symbol, and the lookahead is a ‘=NUM=', then this token
is shifted on the parse stack, and the control flow jumps to state 1.
Any other lookahead triggers a parse error.

In the state 1...

#+begin_src example-preformatted
state 1

    exp  ->  NUM .   (rule 5)

    $default    reduce using rule 5 (exp)
#+end_src

the rule 5, ‘=exp: NUM;=', is completed. Whatever the lookahead
(‘=$default='), the parser will reduce it. If it was coming from state
0, then, after this reduction it will return to state 0, and will jump
to state 2 (‘=exp: go to state 2=').

#+begin_src example-preformatted
state 2

    exp  ->  exp . '+' exp   (rule 1)
    exp  ->  exp . '-' exp   (rule 2)
    exp  ->  exp . '*' exp   (rule 3)
    exp  ->  exp . '/' exp   (rule 4)

    $EOI        shift, and go to state 11
    '+' shift, and go to state 3
    '-' shift, and go to state 4
    '*' shift, and go to state 5
    '/' shift, and go to state 6
#+end_src

In state 2, the automaton can only shift a symbol. For instance, because
of the item ‘=exp -> exp . '+' exp=', if the lookahead if ‘=+=', it will
be shifted on the parse stack, and the automaton control will jump to
state 3, corresponding to the item ‘=exp -> exp . '+' exp=':

#+begin_src example-preformatted
state 3

    exp  ->  exp '+' . exp   (rule 1)

    NUM shift, and go to state 1

    exp go to state 7
#+end_src

Since there is no default action, any other token than those listed
above will trigger a parse error.

The interpretation of states 4 to 6 is straightforward:

#+begin_src example-preformatted
state 4

    exp  ->  exp '-' . exp   (rule 2)

    NUM shift, and go to state 1

    exp go to state 8



state 5

    exp  ->  exp '*' . exp   (rule 3)

    NUM shift, and go to state 1

    exp go to state 9



state 6

    exp  ->  exp '/' . exp   (rule 4)

    NUM shift, and go to state 1

    exp go to state 10
#+end_src

As was announced in beginning of the report,
‘=State 7 contains 1 shift/reduce conflict.=':

#+begin_src example-preformatted
state 7

    exp  ->  exp . '+' exp   (rule 1)
    exp  ->  exp '+' exp .   (rule 1)
    exp  ->  exp . '-' exp   (rule 2)
    exp  ->  exp . '*' exp   (rule 3)
    exp  ->  exp . '/' exp   (rule 4)

    '*' shift, and go to state 5
    '/' shift, and go to state 6

    '/' [reduce using rule 1 (exp)]
    $default    reduce using rule 1 (exp)
#+end_src

Indeed, there are two actions associated to the lookahead ‘=/=': either
shifting (and going to state 6), or reducing rule 1. The conflict means
that either the grammar is ambiguous, or the parser lacks information to
make the right decision. Indeed the grammar is ambiguous, as, since we
did not specify the precedence of ‘=/=', the sentence
‘=NUM + NUM / NUM=' can be parsed as ‘=NUM + (NUM / NUM)=', which
corresponds to shifting ‘=/=', or as ‘=(NUM + NUM) / NUM=', which
corresponds to reducing rule 1.

Because in LALR(1) parsing a single decision can be made, Wisent
arbitrarily chose to disable the reduction, see
[[#Conflicts][Conflicts]]. Discarded actions are reported in between
square brackets.

Note that all the previous states had a single possible action: either
shifting the next token and going to the corresponding state, or
reducing a single rule. In the other cases, i.e., when shifting /and/
reducing is possible or when /several/ reductions are possible, the
lookahead is required to select the action. State 7 is one such state:
if the lookahead is ‘=*=' or ‘=/=' then the action is shifting,
otherwise the action is reducing rule 1. In other words, the first two
items, corresponding to rule 1, are not eligible when the lookahead is
‘=*=', since we specified that ‘=*=' has higher precedence that ‘=+='.
More generally, some items are eligible only with some set of possible
lookaheads.

States 8 to 10 are similar:

#+begin_src example-preformatted
state 8

    exp  ->  exp . '+' exp   (rule 1)
    exp  ->  exp . '-' exp   (rule 2)
    exp  ->  exp '-' exp .   (rule 2)
    exp  ->  exp . '*' exp   (rule 3)
    exp  ->  exp . '/' exp   (rule 4)

    '*' shift, and go to state 5
    '/' shift, and go to state 6

    '/' [reduce using rule 2 (exp)]
    $default    reduce using rule 2 (exp)


state 9

    exp  ->  exp . '+' exp   (rule 1)
    exp  ->  exp . '-' exp   (rule 2)
    exp  ->  exp . '*' exp   (rule 3)
    exp  ->  exp '*' exp .   (rule 3)
    exp  ->  exp . '/' exp   (rule 4)

    '/' shift, and go to state 6

    '/' [reduce using rule 3 (exp)]
    $default    reduce using rule 3 (exp)


state 10

    exp  ->  exp . '+' exp   (rule 1)
    exp  ->  exp . '-' exp   (rule 2)
    exp  ->  exp . '*' exp   (rule 3)
    exp  ->  exp . '/' exp   (rule 4)
    exp  ->  exp '/' exp .   (rule 4)

    '+' shift, and go to state 3
    '-' shift, and go to state 4
    '*' shift, and go to state 5
    '/' shift, and go to state 6

    '+' [reduce using rule 4 (exp)]
    '-' [reduce using rule 4 (exp)]
    '*' [reduce using rule 4 (exp)]
    '/' [reduce using rule 4 (exp)]
    $default    reduce using rule 4 (exp)
#+end_src

Observe that state 10 contains conflicts due to the lack of precedence
of ‘=/=' wrt ‘=+=', ‘=-=', and ‘=*=', but also because the associativity
of ‘=/=' is not specified.

Finally, the state 11 (plus 12) is named the /final state/, or the
/accepting state/:

#+begin_src example-preformatted
state 11

    $EOI        shift, and go to state 12



state 12

    $default    accept
#+end_src

The end of input is shifted ‘=$EOI shift,=' and the parser exits
successfully (‘=go to state 12=', that terminates).

--------------

<<Wisent-Parsing>>

Next: [[#Wisent-Semantic][How to use Wisent with Semantic]], Previous:
[[#Wisent-Grammar][Wisent Grammar]], Up:
[[#Top][Wisent Parser Development]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

** 3 Wisent Parsing [[#Wisent-Parsing-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Wisent-Parsing-1
:CLASS: chapter
:END:
The Wisent's parser is what is called a /bottom-up/ or /shift-reduce/
parser which repeatedly:

- <<index-shift>>/shift/ [[#index-shift][¶]] :: That is pushes the value
  of the last lexical token read (the look-ahead token) into a value
  stack, and reads a new one.

- <<index-reduce>>/reduce/ [[#index-reduce][¶]] :: That is replaces a
  nonterminal by its semantic value. The values of the components which
  form the right hand side of a rule are popped from the value stack and
  reduced by the semantic action of this rule. The result is pushed back
  on top of value stack.

The parser will stop on:

- <<index-accept>>/accept/ [[#index-accept][¶]] :: When all input has
  been successfully parsed. The semantic value of the start nonterminal
  is on top of the value stack.

- <<index-syntax-error>>/error/ [[#index-syntax-error][¶]] :: When a
  syntax error (an unexpected token in input) has been detected. At this
  point the parser issues an error message and either stops or calls a
  recovery routine to try to resume parsing.

The above elementary actions are driven by the LALR(1) automaton built
by =wisent-compile-grammar= from a context-free grammar.

The Wisent's parser is entered by calling the function:

- Function: *wisent-parse* =automaton lexer &optional error start=
  [[#index-wisent_002dparse-1][¶]] :: Parse input using the automaton
  specified in =automaton=.

  - =automaton= :: Is an LALR(1) automaton generated by
    =wisent-compile-grammar= (see [[#Wisent-Grammar][Wisent Grammar]]).

  - =lexer= :: Is a function with no argument called by the parser to
    obtain the next terminal (token) in input (see
    [[#Writing-a-lexer][What the parser must receive]]).

  - =error= :: Is an optional reporting function called when a parse
    error occurs. It receives a message string to report. It defaults to
    the function =wisent-message= (see
    [[#Report-errors][The error reporting function]]).

  - =start= :: Specify the start symbol (nonterminal) used by the parser
    as its goal. It defaults to the start symbol defined in the grammar
    (see [[#Wisent-Grammar][Wisent Grammar]]).

The following two normal hooks permit doing some useful processing
respectively before starting parsing, and after the parser terminated.

- Variable: *wisent-pre-parse-hook*
  [[#index-wisent_002dpre_002dparse_002dhook-1][¶]] :: Normal hook run
  just before entering the =LR= parser engine.

- Variable: *wisent-post-parse-hook*
  [[#index-wisent_002dpost_002dparse_002dhook-1][¶]] :: Normal hook run
  just after the =LR= parser engine terminated.

- [[#Writing-a-lexer][What the parser must receive]]
- [[#Actions-goodies][Variables and macros useful in grammar actions.]]
- [[#Report-errors][The error reporting function]]
- [[#Error-recovery][Error recovery]]
- [[#Debugging-actions][Debugging semantic actions]]

--------------

<<Writing-a-lexer>>

Next:
[[#Actions-goodies][Variables and macros useful in grammar actions.]],
Up: [[#Wisent-Parsing][Wisent Parsing]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

*** 3.1 What the parser must receive [[#What-the-parser-must-receive][¶]]
:PROPERTIES:
:CUSTOM_ID: What-the-parser-must-receive
:CLASS: section
:END:
It is important to understand that the parser does not parse characters,
but lexical tokens, and does not know anything about characters in text
streams!

Reading input data to produce lexical tokens is performed by a lexer
(also called a scanner) in a lexical analysis step, before the syntax
analysis step performed by the parser. The parser automatically calls
the lexer when it needs the next token to parse.

A Wisent's lexer is an Emacs Lisp function with no argument. It must
return a valid lexical token of the form:

=(==token-class value== [==start== . ==end==])=

- =token-class= :: Is a category of lexical token identifying a terminal
  as specified in the grammar (see [[#Wisent-Grammar][Wisent Grammar]]).
  It can be a symbol or a character literal.

- =value= :: Is the value of the lexical token. It can be of any valid
  Emacs Lisp data type.

- =start=\\
  =end= :: Are the optional beginning and ending positions of =value= in
  the input stream.

When there are no more tokens to read the lexer must return the token
=(list wisent-eoi-term)= to each request.

- Variable: *wisent-eoi-term*
  [[#index-wisent_002deoi_002dterm-1][¶]] :: Predefined constant,
  End-Of-Input terminal symbol.

=wisent-lex= is an example of a lexer that reads lexical tokens produced
by a /Semantic/ lexer, and translates them into lexical tokens suitable
to the Wisent parser. See also [[#Wisent-Lex][The Wisent Lex lexer]].

To call the lexer in a semantic action use the function =wisent-lexer=.
See also
[[#Actions-goodies][Variables and macros useful in grammar actions.]].

--------------

<<Actions-goodies>>

Next: [[#Report-errors][The error reporting function]], Previous:
[[#Writing-a-lexer][What the parser must receive]], Up:
[[#Wisent-Parsing][Wisent Parsing]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

*** 3.2 Variables and macros useful in grammar actions. [[#Variables-and-macros-useful-in-grammar-actions_002e][¶]]
:PROPERTIES:
:CUSTOM_ID: Variables-and-macros-useful-in-grammar-actions_002e
:CLASS: section
:END:
- Variable: *wisent-input* [[#index-wisent_002dinput-1][¶]] :: The last
  token read. This variable only has meaning in the scope of
  =wisent-parse=.

- Function: *wisent-lexer* [[#index-wisent_002dlexer-1][¶]] :: Obtain
  the next terminal in input.

- Function: *wisent-region* =&rest positions=
  [[#index-wisent_002dregion-1][¶]] :: Return the start/end positions of
  the region including =positions=. Each element of =positions= is a
  pair =(==start-pos== . ==end-pos==)= or =nil=. The returned value is
  the pair =(==min-start-pos== . ==max-end-pos==)= or =nil= if no
  =positions= are available.

--------------

<<Report-errors>>

Next: [[#Error-recovery][Error recovery]], Previous:
[[#Actions-goodies][Variables and macros useful in grammar actions.]],
Up: [[#Wisent-Parsing][Wisent Parsing]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

*** 3.3 The error reporting function [[#The-error-reporting-function][¶]]
:PROPERTIES:
:CUSTOM_ID: The-error-reporting-function
:CLASS: section
:END:
When the parser encounters a syntax error it calls a user-defined
function. It must be an Emacs Lisp function with one argument: a string
containing the message to report.

By default the parser uses this function to report error messages:

- Function: *wisent-message* =string &rest args=
  [[#index-wisent_002dmessage-1][¶]] :: Print a one-line message if
  =wisent-parse-verbose-flag= is set. Pass =string= and =args= arguments
  to /message/.

- *Please Note:* :: =wisent-message= uses the following function to
  print lexical tokens:

  - Function: *wisent-token-to-string* =token=
    [[#index-wisent_002dtoken_002dto_002dstring][¶]] :: Return a printed
    representation of lexical token =token=.

  The general printed form of a lexical token is:

  =token==(==value==)@==location=

To control the verbosity of the parser you can set to non-=nil= this
variable:

- Option: *wisent-parse-verbose-flag*
  [[#index-wisent_002dparse_002dverbose_002dflag][¶]] :: non-=nil= means
  to issue more messages while parsing.

Or interactively use the command:

- Command: *wisent-parse-toggle-verbose-flag*
  [[#index-wisent_002dparse_002dtoggle_002dverbose_002dflag-1][¶]] :: Toggle
  whether to issue more messages while parsing.

When the error reporting function is entered the variable =wisent-input=
contains the unexpected token as returned by the lexer.

The error reporting function can be called from a semantic action too
using the special macro =wisent-error=. When called from a semantic
action entered by error recovery (see
[[#Error-recovery][Error recovery]]) the value of the variable
=wisent-recovering= is non-=nil=.

--------------

<<Error-recovery>>

Next: [[#Debugging-actions][Debugging semantic actions]], Previous:
[[#Report-errors][The error reporting function]], Up:
[[#Wisent-Parsing][Wisent Parsing]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

*** 3.4 Error recovery [[#Error-recovery-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Error-recovery-1
:CLASS: section
:END:
The error recovery mechanism of the Wisent's parser conforms to the one
Bison uses. See
[[https://www.gnu.org/software/bison/manual/bison.html#Error-Recovery][(bison)Error Recovery]],
in the Bison manual for details.

To recover from a syntax error you must write rules to recognize the
special token =error=. This is a terminal symbol that is automatically
defined and reserved for error handling.

When the parser encounters a syntax error, it pops the state stack until
it finds a state that allows shifting the =error= token. After it has
been shifted, if the old look-ahead token is not acceptable to be
shifted next, the parser reads tokens and discards them until it finds a
token which is acceptable.

Strategies for error recovery depend on the choice of error rules in the
grammar. A simple and useful strategy is simply to skip the rest of the
current statement if an error is detected:

#+begin_src example-preformatted
(statement (( error ?; )) ;; on error, skip until ';' is read
           )
#+end_src

It is also useful to recover to the matching close-delimiter of an
opening-delimiter that has already been parsed:

#+begin_src example-preformatted
(primary (( ?{ expr  ?} ))
         (( ?{ error ?} ))
         ...
         )
#+end_src

Note that error recovery rules may have actions, just as any other rules
can. Here are some predefined hooks, variables, functions or macros,
useful in such actions:

- Variable: *wisent-nerrs* [[#index-wisent_002dnerrs-1][¶]] :: The
  number of parse errors encountered so far.

- Variable: *wisent-recovering*
  [[#index-wisent_002drecovering-1][¶]] :: non-=nil= means that the
  parser is recovering. This variable only has meaning in the scope of
  =wisent-parse=.

- Function: *wisent-error* =msg=
  [[#index-wisent_002derror-1][¶]] :: Call the user supplied error
  reporting function with message =msg= (see
  [[#Report-errors][The error reporting function]]).

  For an example of use, See
  [[#wisent_002dskip_002dtoken][wisent-skip-token]].

- Function: *wisent-errok* [[#index-wisent_002derrok-1][¶]] :: Resume
  generating error messages immediately for subsequent syntax errors.

  The parser suppress error message for syntax errors that happens
  shortly after the first, until three consecutive input tokens have
  been successfully shifted.

  Calling =wisent-errok= in an action, make error messages resume
  immediately. No error messages will be suppressed if you call it in an
  error rule's action.

  For an example of use, See
  [[#wisent_002dskip_002dtoken][wisent-skip-token]].

- Function: *wisent-clearin*
  [[#index-wisent_002dclearin-1][¶]] :: Discard the current lookahead
  token. This will cause a new lexical token to be read.

  In an error rule's action the previous lookahead token is reanalyzed
  immediately. =wisent-clearin= may be called to clear this token.

  For example, suppose that on a parse error, an error handling routine
  is called that advances the input stream to some point where parsing
  should once again commence. The next symbol returned by the lexical
  scanner is probably correct. The previous lookahead token ought to be
  discarded with =wisent-clearin=.

  For an example of use, See
  [[#wisent_002dskip_002dtoken][wisent-skip-token]].

- Function: *wisent-abort* [[#index-wisent_002dabort-1][¶]] :: Abort
  parsing and save the lookahead token.

- Function: *wisent-set-region* =start end=
  [[#index-wisent_002dset_002dregion-1][¶]] :: Change the region of text
  matched by the current nonterminal. =start= and =end= are respectively
  the beginning and end positions of the region occupied by the group of
  components associated to this nonterminal. If =start= or =end= values
  are not a valid positions the region is set to =nil=.

  For an example of use, See
  [[#wisent_002dskip_002dtoken][wisent-skip-token]].

- Variable: *wisent-discarding-token-functions*
  [[#index-wisent_002ddiscarding_002dtoken_002dfunctions-1][¶]] :: List
  of functions to be called when discarding a lexical token. These
  functions receive the lexical token discarded. When the parser
  encounters unexpected tokens, it can discards them, based on what
  directed by error recovery rules. Either when the parser reads tokens
  until one is found that can be shifted, or when an semantic action
  calls the function =wisent-skip-token= or =wisent-skip-block=. For
  language specific hooks, make sure you define this as a local hook.

  For example, in /Semantic/, this hook is set to the function
  =wisent-collect-unmatched-syntax= to collect unmatched lexical tokens
  (see [[#Useful-functions][Useful functions]]).

- Function: *wisent-skip-token*
  [[#index-wisent_002dskip_002dtoken-1][¶]] ::

  Skip the lookahead token in order to resume parsing. Return =nil=.
  Must be used in error recovery semantic actions.

  It typically looks like this:

  #+begin_src lisp-preformatted
  (wisent-message "%s: skip %s" $action
                  (wisent-token-to-string wisent-input))
  (run-hook-with-args
   'wisent-discarding-token-functions wisent-input)
  (wisent-clearin)
  (wisent-errok)))
  #+end_src

- Function: *wisent-skip-block*
  [[#index-wisent_002dskip_002dblock-1][¶]] :: Safely skip a block in
  order to resume parsing. Return =nil=. Must be used in error recovery
  semantic actions.

  A block is data between an open-delimiter (syntax class =(=) and a
  matching close-delimiter (syntax class =)=):

  #+begin_src example-preformatted
  (a parenthesized block)
  [a block between brackets]
  {a block between braces}
  #+end_src

  The following example uses =wisent-skip-block= to safely skip a block
  delimited by ‘=LBRACE=' (={=) and ‘=RBRACE=' (=}=) tokens, when a
  syntax error occurs in ‘=other-components=':

  #+begin_src example-preformatted
  (block ((LBRACE other-components RBRACE))
         ((LBRACE RBRACE))
         ((LBRACE error)
          (wisent-skip-block))
         )
  #+end_src

--------------

<<Debugging-actions>>

Previous: [[#Error-recovery][Error recovery]], Up:
[[#Wisent-Parsing][Wisent Parsing]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

*** 3.5 Debugging semantic actions [[#Debugging-semantic-actions][¶]]
:PROPERTIES:
:CUSTOM_ID: Debugging-semantic-actions
:CLASS: section
:END:
Each semantic action is represented by a symbol interned in an /obarray/
that is part of the LALR(1) automaton (see
[[#Compiling-a-grammar][Compiling a grammar]]). =symbol-function= on a
semantic action symbol return the semantic action lambda expression.

A semantic action symbol name has the form =nonterminal==:==index=,
where =nonterminal= is the name of the nonterminal symbol the action
belongs to, and =index= is an action sequence number within the scope of
=nonterminal=. For example, this nonterminal definition:

#+begin_src example-preformatted
input:
   line                     [input:0]
 | input line
   (format "%s %s" $1 $2)   [input:1]
 ;
#+end_src

Will produce two semantic actions, and associated symbols:

- =input:0= :: A default action that returns =$1=.

- =input:1= :: That returns =(format "%s %s" $1 $2)=.

Debugging uses the Lisp debugger to investigate what is happening during
execution of semantic actions. Three commands are available to debug
semantic actions. They receive two arguments:

- The automaton that contains the semantic action.
- The semantic action symbol.

- Command: *wisent-debug-on-entry* =automaton function=
  [[#index-wisent_002ddebug_002don_002dentry-1][¶]] :: Request
  =automaton='s =function= to invoke debugger each time it is called.
  =function= must be a semantic action symbol that exists in
  =automaton=.

- Command: *wisent-cancel-debug-on-entry* =automaton function=
  [[#index-wisent_002dcancel_002ddebug_002don_002dentry-1][¶]] :: Undo
  effect of =wisent-debug-on-entry= on =automaton='s =function=.
  =function= must be a semantic action symbol that exists in
  =automaton=.

- Command: *wisent-debug-show-entry* =automaton function=
  [[#index-wisent_002ddebug_002dshow_002dentry-1][¶]] :: Show the source
  of =automaton='s semantic action =function=. =function= must be a
  semantic action symbol that exists in =automaton=.

--------------

<<Wisent-Semantic>>

Next:
[[#GNU-Free-Documentation-License][GNU Free Documentation License]],
Previous: [[#Wisent-Parsing][Wisent Parsing]], Up:
[[#Top][Wisent Parser Development]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

** 4 How to use Wisent with Semantic [[#How-to-use-Wisent-with-Semantic][¶]]
:PROPERTIES:
:CUSTOM_ID: How-to-use-Wisent-with-Semantic
:CLASS: chapter
:END:
This section presents how the Wisent's parser can be used to produce
/tags/ for the /Semantic/ tool set.

/Semantic/ tags form a hierarchy of Emacs Lisp data structures that
describes a program in a way independent of programming languages. Tags
map program declarations, like functions, methods, variables, data
types, classes, includes, grammar rules, etc..

To use the Wisent parser with /Semantic/ you have to define your grammar
in /WY/ form, a grammar format very close to the one used by Bison.

- [[#Grammar-styles][Grammar styles]]
- [[#Wisent-Lex][The Wisent Lex lexer]]

--------------

<<Grammar-styles>>

Next: [[#Wisent-Lex][The Wisent Lex lexer]], Up:
[[#Wisent-Semantic][How to use Wisent with Semantic]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

*** 4.1 Grammar styles [[#Grammar-styles-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Grammar-styles-1
:CLASS: section
:END:
/Semantic/ parsing heavily depends on how you wrote the grammar. There
are mainly two styles to write a Wisent's grammar intended to be used
with the /Semantic/ tool set: the /Iterative style/ and the /Bison
style/. Each one has pros and cons, and in certain cases it can be worth
a mix of the two styles!

- [[#Iterative-style][Iterative style]]
- [[#Bison-style][Bison style]]
- [[#Mixed-style][Mixed style]]
- [[#Start-nonterminals][Start nonterminals]]
- [[#Useful-functions][Useful functions]]

--------------

<<Iterative-style>>

Next: [[#Bison-style][Bison style]], Up:
[[#Grammar-styles][Grammar styles]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

**** 4.1.1 Iterative style [[#Iterative-style-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Iterative-style-1
:CLASS: subsection
:END:
The /iterative style/ is the preferred style to use with /Semantic/. It
relies on an iterative parser back-end mechanism which parses start
nonterminals one at a time and automagically skips unexpected lexical
tokens in input.

Compared to rule-based iterative functions (see
[[#Bison-style][Bison style]]), iterative parsers are better in that
they can handle obscure errors more cleanly.

Each start nonterminal must produces a /raw tag/ by calling a =TAG=-like
grammar macro with appropriate parameters. See also
[[#Start-nonterminals][Start nonterminals]].

Then, each parsing iteration automatically translates a raw tag into
/expanded tags/, updating the raw tag structure with internal properties
and buffer related data.

After parsing completes, it results in a tree of expanded tags.

The following example is a snippet of the iterative style Java grammar
provided in the /Semantic/ distribution in the file
=semantic/wisent/java-tags.wy=.

#+begin_src example-preformatted
...
;; Alternate entry points
;;    - Needed by partial re-parse
%start formal_parameter
...
;;    - Needed by EXPANDFULL clauses
%start formal_parameters
...

formal_parameter_list
  : PAREN_BLOCK
    (EXPANDFULL $1 formal_parameters)
  ;

formal_parameters
  : LPAREN
    ()
  | RPAREN
    ()
  | formal_parameter COMMA
  | formal_parameter RPAREN
  ;

formal_parameter
  : formal_parameter_modifier_opt type variable_declarator_id
    (VARIABLE-TAG $3 $2 nil :typemodifiers $1)
  ;
#+end_src

It shows the use of the =EXPANDFULL= grammar macro to parse a
‘=PAREN_BLOCK=' which contains a ‘=formal_parameter_list='. =EXPANDFULL=
tells to recursively parse ‘=formal_parameters=' inside ‘=PAREN_BLOCK='.
The parser iterates until it digested all available input data inside
the ‘=PAREN_BLOCK=', trying to match any of the ‘=formal_parameters='
rules:

- ‘=LPAREN='
- ‘=RPAREN='
- ‘=formal_parameter COMMA='
- ‘=formal_parameter RPAREN='

At each iteration it will return a ‘=formal_parameter=' raw tag, or
=nil= to skip unwanted (single ‘=LPAREN=' or ‘=RPAREN=' for example) or
unexpected input data. Those raw tags will be automatically expanded by
the iterative back-end parser.

--------------

<<Bison-style>>

Next: [[#Mixed-style][Mixed style]], Previous:
[[#Iterative-style][Iterative style]], Up:
[[#Grammar-styles][Grammar styles]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

**** 4.1.2 Bison style [[#Bison-style-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Bison-style-1
:CLASS: subsection
:END:
What we call the /Bison style/ is the traditional style of Bison's
grammars. Compared to iterative style, it is not straightforward to use
grammars written in Bison style in /Semantic/. Mainly because such
grammars are designed to parse the whole input data in one pass, and
don't use the iterative parser back-end mechanism (see
[[#Iterative-style][Iterative style]]). With Bison style the parser is
called once to parse the grammar start nonterminal.

The following example is a snippet of the Bison style Java grammar
provided in the /Semantic/ distribution in the file
=semantic/wisent/java.wy=.

#+begin_src example-preformatted
%start formal_parameter
...

formal_parameter_list
  : formal_parameter_list COMMA formal_parameter
    (cons $3 $1)
  | formal_parameter
    (list $1)
  ;

formal_parameter
  : formal_parameter_modifier_opt type variable_declarator_id
    (EXPANDTAG
     (VARIABLE-TAG $3 $2 :typemodifiers $1)
     )
  ;
#+end_src

The first consequence is that syntax errors are not automatically
handled by /Semantic/. Thus, it is necessary to explicitly handle them
at the grammar level, providing error recovery rules to skip unexpected
input data.

The second consequence is that the iterative parser can't do automatic
tag expansion, except for the start nonterminal value. It is necessary
to explicitly expand tags from concerned semantic actions by calling the
grammar macro =EXPANDTAG= with a raw tag as parameter. See also
[[#Start-nonterminals][Start nonterminals]], for incremental re-parse
considerations.

--------------

<<Mixed-style>>

Next: [[#Start-nonterminals][Start nonterminals]], Previous:
[[#Bison-style][Bison style]], Up: [[#Grammar-styles][Grammar styles]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

**** 4.1.3 Mixed style [[#Mixed-style-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Mixed-style-1
:CLASS: subsection
:END:

#+begin_src example-preformatted
%start grammar
;; Reparse
%start prologue epilogue declaration nonterminal rule
...

%%

grammar:
    prologue
  | epilogue
  | declaration
  | nonterminal
  | PERCENT_PERCENT
  ;
...

nonterminal:
    SYMBOL COLON rules SEMI
    (TAG $1 'nonterminal :children $3)
  ;

rules:
    lifo_rules
    (apply 'nconc (nreverse $1))
  ;

lifo_rules:
    lifo_rules OR rule
    (cons $3 $1)
  | rule
    (list $1)
  ;

rule:
    rhs
    (let* ((rhs $1)
           name type comps prec action elt)
      ...
      (EXPANDTAG
       (TAG name 'rule :type type :value comps :prec prec :expr action)
       ))
  ;
#+end_src

This example shows how iterative and Bison styles can be combined in the
same grammar to obtain a good compromise between grammar complexity and
an efficient parsing strategy in an interactive environment.

‘=nonterminal=' is parsed using iterative style via the main ‘=grammar='
rule. The semantic action uses the =TAG= macro to produce a raw tag,
automagically expanded by /Semantic/.

But ‘=rules=' part is parsed in Bison style! Why?

Rule delimiters are the colon (=:=), that follows the nonterminal name,
and a final semicolon (=;=). Unfortunately these delimiters are not
=open-paren=/=close-paren= type, and the Emacs syntactic analyzer can't
easily isolate data between them to produce a ‘=RULES_PART='
parenthesis-block-like lexical token. Consequently it is not possible to
use =EXPANDFULL= to iterate in ‘=RULES_PART=', like this:

#+begin_src example-preformatted
nonterminal:
    SYMBOL COLON rules SEMI
    (TAG $1 'nonterminal :children $3)
  ;

rules:
    RULES_PART  ;; Map a parenthesis-block-like lexical token
    (EXPANDFULL $1 'rules)
  ;

rules:
    COLON
    ()
    OR
    ()
    SEMI
    ()
    rhs
    rhs
    (let* ((rhs $1)
           name type comps prec action elt)
      ...
      (TAG name 'rule :type type :value comps :prec prec :expr action)
      )
  ;
#+end_src

In such cases, when it is difficult for Emacs to obtain
parenthesis-block-like lexical tokens, the best solution is to use the
traditional Bison style with error recovery!

In some extreme cases, it can also be convenient to extend the lexer, to
deliver new lexical tokens, to simplify the grammar.

--------------

<<Start-nonterminals>>

Next: [[#Useful-functions][Useful functions]], Previous:
[[#Mixed-style][Mixed style]], Up: [[#Grammar-styles][Grammar styles]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

**** 4.1.4 Start nonterminals [[#Start-nonterminals-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Start-nonterminals-1
:CLASS: subsection
:END:
When you write a grammar for /Semantic/, it is important to carefully
indicate the start nonterminals. Each one defines an entry point in the
grammar, and after parsing its semantic value is returned to the
back-end iterative engine. Consequently:

*The semantic value of a start nonterminal must be a produced by a TAG
like grammar macro*.

Start nonterminals are declared by =%start= statements. When nothing is
specified the first nonterminal that appears in the grammar is the start
nonterminal.

Generally, the following nonterminals must be declared as start symbols:

- The main grammar entry point

  #+begin_quote
  Of course!
  #+end_quote

- nonterminals passed to =EXPAND=/=EXPANDFULL=

  #+begin_quote
  These grammar macros recursively parse a part of input data, based on
  rules of the given nonterminal.

  For example, the following will parse ‘=PAREN_BLOCK=' data using the
  ‘=formal_parameters=' rules:

  #+begin_src example-preformatted
  formal_parameter_list
    : PAREN_BLOCK
      (EXPANDFULL $1 formal_parameters)
    ;
  #+end_src

  The semantic value of ‘=formal_parameters=' becomes the value of the
  =EXPANDFULL= expression. It is a list of /Semantic/ tags spliced in
  the tags tree.

  Because the automaton must know that ‘=formal_parameters=' is a start
  symbol, you must declare it like this:

  #+begin_src example-preformatted
  %start formal_parameters
  #+end_src
  #+end_quote

The =EXPANDFULL= macro has a side effect it is important to know,
related to the incremental re-parse mechanism of /Semantic/: the
nonterminal symbol parameter passed to =EXPANDFULL= also becomes the
=reparse-symbol= property of the tag returned by the =EXPANDFULL=
expression.

When buffer's data mapped by a tag is modified, /Semantic/ schedules an
incremental re-parse of that data, using the tag's =reparse-symbol=
property as start nonterminal.

*The rules associated to such start symbols must be carefully reviewed
to ensure that the incremental parser will work!*

Things are a little bit different when the grammar is written in Bison
style.

*The =reparse-symbol= property is set to the nonterminal symbol the rule
that explicitly uses =EXPANDTAG= belongs to.*

For example:

#+begin_src example-preformatted
rule:
    rhs
    (let* ((rhs $1)
           name type comps prec action elt)
      ...
      (EXPANDTAG
       (TAG name 'rule :type type :value comps :prec prec :expr action)
       ))
  ;
#+end_src

Set the =reparse-symbol= property of the expanded tag to ‘=rule='. An
important consequence is that:

*Every nonterminal having any rule that calls =EXPANDTAG= in a semantic
action, should be declared as a start symbol!*

--------------

<<Useful-functions>>

Previous: [[#Start-nonterminals][Start nonterminals]], Up:
[[#Grammar-styles][Grammar styles]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

**** 4.1.5 Useful functions [[#Useful-functions-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Useful-functions-1
:CLASS: subsection
:END:
Here is a description of some predefined functions it might be useful to
know when writing new code to use Wisent in /Semantic/:

- Function: *wisent-collect-unmatched-syntax* =input=
  [[#index-wisent_002dcollect_002dunmatched_002dsyntax-1][¶]] :: Add
  =input= lexical token to the cache of unmatched tokens, in variable
  =semantic-unmatched-syntax-cache=.

  See implementation of the function =wisent-skip-token= in
  [[#Error-recovery][Error recovery]], for an example of use.

--------------

<<Wisent-Lex>>

Previous: [[#Grammar-styles][Grammar styles]], Up:
[[#Wisent-Semantic][How to use Wisent with Semantic]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

*** 4.2 The Wisent Lex lexer [[#The-Wisent-Lex-lexer][¶]]
:PROPERTIES:
:CUSTOM_ID: The-Wisent-Lex-lexer
:CLASS: section
:END:
The lexical analysis step of /Semantic/ is performed by the general
function =semantic-lex=.

=semantic-lex= produces lexical tokens of the form:

#+begin_src example-preformatted
(token-class start . end)
#+end_src

- =token-class= :: Is a symbol that identifies a lexical token class,
  like =symbol=, =string=, =number=, or =PAREN_BLOCK=.

- =start=\\
  =end= :: Are the start and end positions of mapped data in the input
  buffer.

The Wisent's parser doesn't depend on the nature of analyzed input
stream (buffer, string, etc.), and requires that lexical tokens have a
different form (see [[#Writing-a-lexer][What the parser must receive]]):

#+begin_src example-preformatted
(token-class value [start . end])
#+end_src

=wisent-lex= is the default Wisent's lexer used in /Semantic/.

- Function: *wisent-lex* [[#index-wisent_002dlex-1][¶]] :: Return the
  next available lexical token in Wisent's form.

  The variable =wisent-lex-istream= contains the list of lexical tokens
  produced by =semantic-lex=. Pop the next token available and convert
  it to a form suitable for the Wisent's parser.

Mapping of lexical tokens as produced by =semantic-lex= into equivalent
Wisent lexical tokens is straightforward:

#+begin_src example-preformatted
(token-class start . end)
     ⇒ (token-class value start . end)
#+end_src

=value= is the input =buffer-substring= from =start= to =end=.

--------------

<<GNU-Free-Documentation-License>>

Next: [[#Index][Index]], Previous:
[[#Wisent-Semantic][How to use Wisent with Semantic]], Up:
[[#Top][Wisent Parser Development]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

** Appendix A GNU Free Documentation License [[#GNU-Free-Documentation-License-1][¶]]
:PROPERTIES:
:CUSTOM_ID: GNU-Free-Documentation-License-1
:CLASS: appendix
:END:

#+begin_center
Version 1.3, 3 November 2008
#+end_center

#+begin_src display-preformatted
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
https://fsf.org/

Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed.
#+end_src

0. [@0] PREAMBLE

   The purpose of this License is to make a manual, textbook, or other
   functional and useful document /free/ in the sense of freedom: to
   assure everyone the effective freedom to copy and redistribute it,
   with or without modifying it, either commercially or noncommercially.
   Secondarily, this License preserves for the author and publisher a
   way to get credit for their work, while not being considered
   responsible for modifications made by others.

   This License is a kind of “copyleft”, which means that derivative
   works of the document must themselves be free in the same sense. It
   complements the GNU General Public License, which is a copyleft
   license designed for free software.

   We have designed this License in order to use it for manuals for free
   software, because free software needs free documentation: a free
   program should come with manuals providing the same freedoms that the
   software does. But this License is not limited to software manuals;
   it can be used for any textual work, regardless of subject matter or
   whether it is published as a printed book. We recommend this License
   principally for works whose purpose is instruction or reference.

1. APPLICABILITY AND DEFINITIONS

   This License applies to any manual or other work, in any medium, that
   contains a notice placed by the copyright holder saying it can be
   distributed under the terms of this License. Such a notice grants a
   world-wide, royalty-free license, unlimited in duration, to use that
   work under the conditions stated herein. The “Document”, below,
   refers to any such manual or work. Any member of the public is a
   licensee, and is addressed as “you”. You accept the license if you
   copy, modify or distribute the work in a way requiring permission
   under copyright law.

   A “Modified Version” of the Document means any work containing the
   Document or a portion of it, either copied verbatim, or with
   modifications and/or translated into another language.

   A “Secondary Section” is a named appendix or a front-matter section
   of the Document that deals exclusively with the relationship of the
   publishers or authors of the Document to the Document's overall
   subject (or to related matters) and contains nothing that could fall
   directly within that overall subject. (Thus, if the Document is in
   part a textbook of mathematics, a Secondary Section may not explain
   any mathematics.) The relationship could be a matter of historical
   connection with the subject or with related matters, or of legal,
   commercial, philosophical, ethical or political position regarding
   them.

   The “Invariant Sections” are certain Secondary Sections whose titles
   are designated, as being those of Invariant Sections, in the notice
   that says that the Document is released under this License. If a
   section does not fit the above definition of Secondary then it is not
   allowed to be designated as Invariant. The Document may contain zero
   Invariant Sections. If the Document does not identify any Invariant
   Sections then there are none.

   The “Cover Texts” are certain short passages of text that are listed,
   as Front-Cover Texts or Back-Cover Texts, in the notice that says
   that the Document is released under this License. A Front-Cover Text
   may be at most 5 words, and a Back-Cover Text may be at most 25
   words.

   A “Transparent” copy of the Document means a machine-readable copy,
   represented in a format whose specification is available to the
   general public, that is suitable for revising the document
   straightforwardly with generic text editors or (for images composed
   of pixels) generic paint programs or (for drawings) some widely
   available drawing editor, and that is suitable for input to text
   formatters or for automatic translation to a variety of formats
   suitable for input to text formatters. A copy made in an otherwise
   Transparent file format whose markup, or absence of markup, has been
   arranged to thwart or discourage subsequent modification by readers
   is not Transparent. An image format is not Transparent if used for
   any substantial amount of text. A copy that is not “Transparent” is
   called “Opaque”.

   Examples of suitable formats for Transparent copies include plain
   ASCII without markup, Texinfo input format, LaTeX input format, SGML
   or XML using a publicly available DTD, and standard-conforming simple
   HTML, PostScript or PDF designed for human modification. Examples of
   transparent image formats include PNG, XCF and JPG. Opaque formats
   include proprietary formats that can be read and edited only by
   proprietary word processors, SGML or XML for which the DTD and/or
   processing tools are not generally available, and the
   machine-generated HTML, PostScript or PDF produced by some word
   processors for output purposes only.

   The “Title Page” means, for a printed book, the title page itself,
   plus such following pages as are needed to hold, legibly, the
   material this License requires to appear in the title page. For works
   in formats which do not have any title page as such, “Title Page”
   means the text near the most prominent appearance of the work's
   title, preceding the beginning of the body of the text.

   The “publisher” means any person or entity that distributes copies of
   the Document to the public.

   A section “Entitled XYZ” means a named subunit of the Document whose
   title either is precisely XYZ or contains XYZ in parentheses
   following text that translates XYZ in another language. (Here XYZ
   stands for a specific section name mentioned below, such as
   “Acknowledgements”, “Dedications”, “Endorsements”, or “History”.) To
   “Preserve the Title” of such a section when you modify the Document
   means that it remains a section “Entitled XYZ” according to this
   definition.

   The Document may include Warranty Disclaimers next to the notice
   which states that this License applies to the Document. These
   Warranty Disclaimers are considered to be included by reference in
   this License, but only as regards disclaiming warranties: any other
   implication that these Warranty Disclaimers may have is void and has
   no effect on the meaning of this License.

2. VERBATIM COPYING

   You may copy and distribute the Document in any medium, either
   commercially or noncommercially, provided that this License, the
   copyright notices, and the license notice saying this License applies
   to the Document are reproduced in all copies, and that you add no
   other conditions whatsoever to those of this License. You may not use
   technical measures to obstruct or control the reading or further
   copying of the copies you make or distribute. However, you may accept
   compensation in exchange for copies. If you distribute a large enough
   number of copies you must also follow the conditions in section 3.

   You may also lend copies, under the same conditions stated above, and
   you may publicly display copies.

3. COPYING IN QUANTITY

   If you publish printed copies (or copies in media that commonly have
   printed covers) of the Document, numbering more than 100, and the
   Document's license notice requires Cover Texts, you must enclose the
   copies in covers that carry, clearly and legibly, all these Cover
   Texts: Front-Cover Texts on the front cover, and Back-Cover Texts on
   the back cover. Both covers must also clearly and legibly identify
   you as the publisher of these copies. The front cover must present
   the full title with all words of the title equally prominent and
   visible. You may add other material on the covers in addition.
   Copying with changes limited to the covers, as long as they preserve
   the title of the Document and satisfy these conditions, can be
   treated as verbatim copying in other respects.

   If the required texts for either cover are too voluminous to fit
   legibly, you should put the first ones listed (as many as fit
   reasonably) on the actual cover, and continue the rest onto adjacent
   pages.

   If you publish or distribute Opaque copies of the Document numbering
   more than 100, you must either include a machine-readable Transparent
   copy along with each Opaque copy, or state in or with each Opaque
   copy a computer-network location from which the general network-using
   public has access to download using public-standard network protocols
   a complete Transparent copy of the Document, free of added material.
   If you use the latter option, you must take reasonably prudent steps,
   when you begin distribution of Opaque copies in quantity, to ensure
   that this Transparent copy will remain thus accessible at the stated
   location until at least one year after the last time you distribute
   an Opaque copy (directly or through your agents or retailers) of that
   edition to the public.

   It is requested, but not required, that you contact the authors of
   the Document well before redistributing any large number of copies,
   to give them a chance to provide you with an updated version of the
   Document.

4. MODIFICATIONS

   You may copy and distribute a Modified Version of the Document under
   the conditions of sections 2 and 3 above, provided that you release
   the Modified Version under precisely this License, with the Modified
   Version filling the role of the Document, thus licensing distribution
   and modification of the Modified Version to whoever possesses a copy
   of it. In addition, you must do these things in the Modified Version:

   1. Use in the Title Page (and on the covers, if any) a title distinct
      from that of the Document, and from those of previous versions
      (which should, if there were any, be listed in the History section
      of the Document). You may use the same title as a previous version
      if the original publisher of that version gives permission.
   2. List on the Title Page, as authors, one or more persons or
      entities responsible for authorship of the modifications in the
      Modified Version, together with at least five of the principal
      authors of the Document (all of its principal authors, if it has
      fewer than five), unless they release you from this requirement.
   3. State on the Title page the name of the publisher of the Modified
      Version, as the publisher.
   4. Preserve all the copyright notices of the Document.
   5. Add an appropriate copyright notice for your modifications
      adjacent to the other copyright notices.
   6. Include, immediately after the copyright notices, a license notice
      giving the public permission to use the Modified Version under the
      terms of this License, in the form shown in the Addendum below.
   7. Preserve in that license notice the full lists of Invariant
      Sections and required Cover Texts given in the Document's license
      notice.
   8. Include an unaltered copy of this License.
   9. Preserve the section Entitled “History”, Preserve its Title, and
      add to it an item stating at least the title, year, new authors,
      and publisher of the Modified Version as given on the Title Page.
      If there is no section Entitled “History” in the Document, create
      one stating the title, year, authors, and publisher of the
      Document as given on its Title Page, then add an item describing
      the Modified Version as stated in the previous sentence.
   10. Preserve the network location, if any, given in the Document for
       public access to a Transparent copy of the Document, and likewise
       the network locations given in the Document for previous versions
       it was based on. These may be placed in the “History” section.
       You may omit a network location for a work that was published at
       least four years before the Document itself, or if the original
       publisher of the version it refers to gives permission.
   11. For any section Entitled “Acknowledgements” or “Dedications”,
       Preserve the Title of the section, and preserve in the section
       all the substance and tone of each of the contributor
       acknowledgements and/or dedications given therein.
   12. Preserve all the Invariant Sections of the Document, unaltered in
       their text and in their titles. Section numbers or the equivalent
       are not considered part of the section titles.
   13. Delete any section Entitled “Endorsements”. Such a section may
       not be included in the Modified Version.
   14. Do not retitle any existing section to be Entitled “Endorsements”
       or to conflict in title with any Invariant Section.
   15. Preserve any Warranty Disclaimers.

   If the Modified Version includes new front-matter sections or
   appendices that qualify as Secondary Sections and contain no material
   copied from the Document, you may at your option designate some or
   all of these sections as invariant. To do this, add their titles to
   the list of Invariant Sections in the Modified Version's license
   notice. These titles must be distinct from any other section titles.

   You may add a section Entitled “Endorsements”, provided it contains
   nothing but endorsements of your Modified Version by various
   parties---for example, statements of peer review or that the text has
   been approved by an organization as the authoritative definition of a
   standard.

   You may add a passage of up to five words as a Front-Cover Text, and
   a passage of up to 25 words as a Back-Cover Text, to the end of the
   list of Cover Texts in the Modified Version. Only one passage of
   Front-Cover Text and one of Back-Cover Text may be added by (or
   through arrangements made by) any one entity. If the Document already
   includes a cover text for the same cover, previously added by you or
   by arrangement made by the same entity you are acting on behalf of,
   you may not add another; but you may replace the old one, on explicit
   permission from the previous publisher that added the old one.

   The author(s) and publisher(s) of the Document do not by this License
   give permission to use their names for publicity for or to assert or
   imply endorsement of any Modified Version.

5. COMBINING DOCUMENTS

   You may combine the Document with other documents released under this
   License, under the terms defined in section 4 above for modified
   versions, provided that you include in the combination all of the
   Invariant Sections of all of the original documents, unmodified, and
   list them all as Invariant Sections of your combined work in its
   license notice, and that you preserve all their Warranty Disclaimers.

   The combined work need only contain one copy of this License, and
   multiple identical Invariant Sections may be replaced with a single
   copy. If there are multiple Invariant Sections with the same name but
   different contents, make the title of each such section unique by
   adding at the end of it, in parentheses, the name of the original
   author or publisher of that section if known, or else a unique
   number. Make the same adjustment to the section titles in the list of
   Invariant Sections in the license notice of the combined work.

   In the combination, you must combine any sections Entitled “History”
   in the various original documents, forming one section Entitled
   “History”; likewise combine any sections Entitled “Acknowledgements”,
   and any sections Entitled “Dedications”. You must delete all sections
   Entitled “Endorsements.”

6. COLLECTIONS OF DOCUMENTS

   You may make a collection consisting of the Document and other
   documents released under this License, and replace the individual
   copies of this License in the various documents with a single copy
   that is included in the collection, provided that you follow the
   rules of this License for verbatim copying of each of the documents
   in all other respects.

   You may extract a single document from such a collection, and
   distribute it individually under this License, provided you insert a
   copy of this License into the extracted document, and follow this
   License in all other respects regarding verbatim copying of that
   document.

7. AGGREGATION WITH INDEPENDENT WORKS

   A compilation of the Document or its derivatives with other separate
   and independent documents or works, in or on a volume of a storage or
   distribution medium, is called an “aggregate” if the copyright
   resulting from the compilation is not used to limit the legal rights
   of the compilation's users beyond what the individual works permit.
   When the Document is included in an aggregate, this License does not
   apply to the other works in the aggregate which are not themselves
   derivative works of the Document.

   If the Cover Text requirement of section 3 is applicable to these
   copies of the Document, then if the Document is less than one half of
   the entire aggregate, the Document's Cover Texts may be placed on
   covers that bracket the Document within the aggregate, or the
   electronic equivalent of covers if the Document is in electronic
   form. Otherwise they must appear on printed covers that bracket the
   whole aggregate.

8. TRANSLATION

   Translation is considered a kind of modification, so you may
   distribute translations of the Document under the terms of section 4.
   Replacing Invariant Sections with translations requires special
   permission from their copyright holders, but you may include
   translations of some or all Invariant Sections in addition to the
   original versions of these Invariant Sections. You may include a
   translation of this License, and all the license notices in the
   Document, and any Warranty Disclaimers, provided that you also
   include the original English version of this License and the original
   versions of those notices and disclaimers. In case of a disagreement
   between the translation and the original version of this License or a
   notice or disclaimer, the original version will prevail.

   If a section in the Document is Entitled “Acknowledgements”,
   “Dedications”, or “History”, the requirement (section 4) to Preserve
   its Title (section 1) will typically require changing the actual
   title.

9. TERMINATION

   You may not copy, modify, sublicense, or distribute the Document
   except as expressly provided under this License. Any attempt
   otherwise to copy, modify, sublicense, or distribute it is void, and
   will automatically terminate your rights under this License.

   However, if you cease all violation of this License, then your
   license from a particular copyright holder is reinstated (a)
   provisionally, unless and until the copyright holder explicitly and
   finally terminates your license, and (b) permanently, if the
   copyright holder fails to notify you of the violation by some
   reasonable means prior to 60 days after the cessation.

   Moreover, your license from a particular copyright holder is
   reinstated permanently if the copyright holder notifies you of the
   violation by some reasonable means, this is the first time you have
   received notice of violation of this License (for any work) from that
   copyright holder, and you cure the violation prior to 30 days after
   your receipt of the notice.

   Termination of your rights under this section does not terminate the
   licenses of parties who have received copies or rights from you under
   this License. If your rights have been terminated and not permanently
   reinstated, receipt of a copy of some or all of the same material
   does not give you any rights to use it.

10. FUTURE REVISIONS OF THIS LICENSE

    The Free Software Foundation may publish new, revised versions of
    the GNU Free Documentation License from time to time. Such new
    versions will be similar in spirit to the present version, but may
    differ in detail to address new problems or concerns. See
    [[https://www.gnu.org/licenses/]].

    Each version of the License is given a distinguishing version
    number. If the Document specifies that a particular numbered version
    of this License “or any later version” applies to it, you have the
    option of following the terms and conditions either of that
    specified version or of any later version that has been published
    (not as a draft) by the Free Software Foundation. If the Document
    does not specify a version number of this License, you may choose
    any version ever published (not as a draft) by the Free Software
    Foundation. If the Document specifies that a proxy can decide which
    future versions of this License can be used, that proxy's public
    statement of acceptance of a version permanently authorizes you to
    choose that version for the Document.

11. RELICENSING

    “Massive Multiauthor Collaboration Site” (or “MMC Site”) means any
    World Wide Web server that publishes copyrightable works and also
    provides prominent facilities for anybody to edit those works. A
    public wiki that anybody can edit is an example of such a server. A
    “Massive Multiauthor Collaboration” (or “MMC”) contained in the site
    means any set of copyrightable works thus published on the MMC site.

    “CC-BY-SA” means the Creative Commons Attribution-Share Alike 3.0
    license published by Creative Commons Corporation, a not-for-profit
    corporation with a principal place of business in San Francisco,
    California, as well as future copyleft versions of that license
    published by that same organization.

    “Incorporate” means to publish or republish a Document, in whole or
    in part, as part of another Document.

    An MMC is “eligible for relicensing” if it is licensed under this
    License, and if all works that were first published under this
    License somewhere other than this MMC, and subsequently incorporated
    in whole or in part into the MMC, (1) had no cover texts or
    invariant sections, and (2) were thus incorporated prior to November
    1, 2008.

    The operator of an MMC Site may republish an MMC contained in the
    site under CC-BY-SA on the same site at any time before August 1,
    2009, provided the MMC is eligible for relicensing.

*** ADDENDUM: How to use this License for your documents [[#ADDENDUM_003a-How-to-use-this-License-for-your-documents][¶]]
:PROPERTIES:
:CUSTOM_ID: ADDENDUM_003a-How-to-use-this-License-for-your-documents
:CLASS: heading
:END:
To use this License in a document you have written, include a copy of
the License in the document and put the following copyright and license
notices just after the title page:

#+begin_src example-preformatted
  Copyright (C)  year  your name.
  Permission is granted to copy, distribute and/or modify this document
  under the terms of the GNU Free Documentation License, Version 1.3
  or any later version published by the Free Software Foundation;
  with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
  Texts.  A copy of the license is included in the section entitled ``GNU
  Free Documentation License''.
#+end_src

If you have Invariant Sections, Front-Cover Texts and Back-Cover Texts,
replace the “with...Texts.” line with this:

#+begin_src example-preformatted
    with the Invariant Sections being list their titles, with
    the Front-Cover Texts being list, and with the Back-Cover Texts
    being list.
#+end_src

If you have Invariant Sections without Cover Texts, or some other
combination of the three, merge those two alternatives to suit the
situation.

If your document contains nontrivial examples of program code, we
recommend releasing these examples in parallel under your choice of free
software license, such as the GNU General Public License, to permit
their use in free software.

--------------

<<Index>>

Previous:
[[#GNU-Free-Documentation-License][GNU Free Documentation License]], Up:
[[#Top][Wisent Parser Development]]  
[[[#SEC_Contents][Contents]]][[[#Index][Index]]]

** Index [[#Index-1][¶]]
:PROPERTIES:
:CUSTOM_ID: Index-1
:CLASS: unnumbered
:END:

| Jump to:   | [[#Index_cp_symbol-1][*$*]]  \\                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|            | [[#Index_cp_letter-A][*A*]]   [[#Index_cp_letter-B][*B*]]   [[#Index_cp_letter-C][*C*]]   [[#Index_cp_letter-D][*D*]]   [[#Index_cp_letter-E][*E*]]   [[#Index_cp_letter-G][*G*]]   [[#Index_cp_letter-I][*I*]]   [[#Index_cp_letter-L][*L*]]   [[#Index_cp_letter-M][*M*]]   [[#Index_cp_letter-N][*N*]]   [[#Index_cp_letter-P][*P*]]   [[#Index_cp_letter-R][*R*]]   [[#Index_cp_letter-S][*S*]]   [[#Index_cp_letter-T][*T*]]   [[#Index_cp_letter-U][*U*]]   [[#Index_cp_letter-W][*W*]]   |

|                | Index Entry                                                                                       | Section                                                       |
| -------------- |                                                                                                   |                                                               |
| $              |                                                                                                   |                                                               |
|                | [[#index-_0024action][=$action=]]                                                                 | [[#Grammar-format][Grammar format]]                           |
|                | [[#index-_0024N][=$N=]]                                                                           | [[#Grammar-format][Grammar format]]                           |
|                | [[#index-_0024nterm][=$nterm=]]                                                                   | [[#Grammar-format][Grammar format]]                           |
|                | [[#index-_0024region][=$region=]]                                                                 | [[#Grammar-format][Grammar format]]                           |
|                | [[#index-_0024regionn][=$region==n=]]                                                             | [[#Grammar-format][Grammar format]]                           |
| -------------- |                                                                                                   |                                                               |
| A              |                                                                                                   |                                                               |
|                | [[#index-accept][accept]]                                                                         | [[#Wisent-Parsing][Wisent Parsing]]                           |
|                | [[#index-ambiguous-grammar][ambiguous grammar]]                                                   | [[#Conflicts][Conflicts]]                                     |
|                | [[#index-associativity][associativity]]                                                           | [[#Grammar-format][Grammar format]]                           |
|                | [[#index-automaton][automaton]]                                                                   | [[#Compiling-a-grammar][Compiling a grammar]]                 |
| -------------- |                                                                                                   |                                                               |
| B              |                                                                                                   |                                                               |
|                | [[#index-bottom_002dup-parser][bottom-up parser]]                                                 | [[#Wisent-Parsing][Wisent Parsing]]                           |
| -------------- |                                                                                                   |                                                               |
| C              |                                                                                                   |                                                               |
|                | [[#index-compiling-a-grammar][compiling a grammar]]                                               | [[#Compiling-a-grammar][Compiling a grammar]]                 |
|                | [[#index-conflicts-resolution][conflicts resolution]]                                             | [[#Conflicts][Conflicts]]                                     |
|                | [[#index-context_002dfree-grammar][context-free grammar]]                                         | [[#Wisent-Grammar][Wisent Grammar]]                           |
| -------------- |                                                                                                   |                                                               |
| D              |                                                                                                   |                                                               |
|                | [[#index-debugging-semantic-actions][debugging semantic actions]]                                 | [[#Debugging-actions][Debugging actions]]                     |
|                | [[#index-deterministic-automaton][deterministic automaton]]                                       | [[#Conflicts][Conflicts]]                                     |
| -------------- |                                                                                                   |                                                               |
| E              |                                                                                                   |                                                               |
|                | [[#index-error-recovery][error recovery]]                                                         | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-error-recovery-actions][error recovery actions]]                                         | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-error-recovery-strategy][error recovery strategy]]                                       | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-error-reporting][error reporting]]                                                       | [[#Report-errors][Report errors]]                             |
|                | [[#index-error-token][error token]]                                                               | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-expanded-tag][expanded tag]]                                                             | [[#Iterative-style][Iterative style]]                         |
|                | [[#index-EXPANDFULL][=EXPANDFULL=]]                                                               | [[#Iterative-style][Iterative style]]                         |
| -------------- |                                                                                                   |                                                               |
| G              |                                                                                                   |                                                               |
|                | [[#index-grammar-bison-style][grammar bison style]]                                               | [[#Bison-style][Bison style]]                                 |
|                | [[#index-grammar-coding-conventions][grammar coding conventions]]                                 | [[#Grammar-format][Grammar format]]                           |
|                | [[#index-grammar-compilation][grammar compilation]]                                               | [[#Compiling-a-grammar][Compiling a grammar]]                 |
|                | [[#index-grammar-conflicts][grammar conflicts]]                                                   | [[#Conflicts][Conflicts]]                                     |
|                | [[#index-grammar-debugging][grammar debugging]]                                                   | [[#Grammar-Debugging][Grammar Debugging]]                     |
|                | [[#index-grammar-example][grammar example]]                                                       | [[#Example][Example]]                                         |
|                | [[#index-grammar-format][grammar format]]                                                         | [[#Grammar-format][Grammar format]]                           |
|                | [[#index-grammar-iterative-style][grammar iterative style]]                                       | [[#Iterative-style][Iterative style]]                         |
|                | [[#index-grammar-mixed-style][grammar mixed style]]                                               | [[#Mixed-style][Mixed style]]                                 |
|                | [[#index-grammar-styles][grammar styles]]                                                         | [[#Grammar-styles][Grammar styles]]                           |
|                | [[#index-grammar-verbose-description][grammar verbose description]]                               | [[#Grammar-Debugging][Grammar Debugging]]                     |
| -------------- |                                                                                                   |                                                               |
| I              |                                                                                                   |                                                               |
|                | [[#index-incremental-re_002dparse][incremental re-parse]]                                         | [[#Start-nonterminals][Start nonterminals]]                   |
| -------------- |                                                                                                   |                                                               |
| L              |                                                                                                   |                                                               |
|                | [[#index-LALR_00281_0029-grammar][LALR(1) grammar]]                                               | [[#Compiling-a-grammar][Compiling a grammar]]                 |
|                | [[#index-lexer][lexer]]                                                                           | [[#Writing-a-lexer][Writing a lexer]]                         |
|                | [[#index-lexical-analysis][lexical analysis]]                                                     | [[#Writing-a-lexer][Writing a lexer]]                         |
|                | [[#index-lexical-token-mapping][lexical token mapping]]                                           | [[#Wisent-Lex][Wisent Lex]]                                   |
|                | [[#index-lexical-tokens][lexical tokens]]                                                         | [[#Writing-a-lexer][Writing a lexer]]                         |
|                | [[#index-look_002dahead-token][look-ahead token]]                                                 | [[#Compiling-a-grammar][Compiling a grammar]]                 |
| -------------- |                                                                                                   |                                                               |
| M              |                                                                                                   |                                                               |
|                | [[#index-middle_002drule-actions][middle-rule actions]]                                           | [[#Grammar-format][Grammar format]]                           |
| -------------- |                                                                                                   |                                                               |
| N              |                                                                                                   |                                                               |
|                | [[#index-nonterminal][nonterminal]]                                                               | [[#Wisent-Grammar][Wisent Grammar]]                           |
| -------------- |                                                                                                   |                                                               |
| P              |                                                                                                   |                                                               |
|                | [[#index-precedence-level][precedence level]]                                                     | [[#Grammar-format][Grammar format]]                           |
| -------------- |                                                                                                   |                                                               |
| R              |                                                                                                   |                                                               |
|                | [[#index-raw-tag][raw tag]]                                                                       | [[#Iterative-style][Iterative style]]                         |
|                | [[#index-reduce][reduce]]                                                                         | [[#Wisent-Parsing][Wisent Parsing]]                           |
|                | [[#index-reduce_002freduce-conflicts][reduce/reduce conflicts]]                                   | [[#Conflicts][Conflicts]]                                     |
|                | [[#index-reparse_002dsymbol][reparse-symbol]]                                                     | [[#Start-nonterminals][Start nonterminals]]                   |
|                | [[#index-reparse_002dsymbol-property][=reparse-symbol= property]]                                 | [[#Start-nonterminals][Start nonterminals]]                   |
|                | [[#index-rule][rule]]                                                                             | [[#Wisent-Grammar][Wisent Grammar]]                           |
| -------------- |                                                                                                   |                                                               |
| S              |                                                                                                   |                                                               |
|                | [[#index-scanner][scanner]]                                                                       | [[#Writing-a-lexer][Writing a lexer]]                         |
|                | [[#index-semantic-action-symbols][semantic action symbols]]                                       | [[#Debugging-actions][Debugging actions]]                     |
|                | [[#index-semantic-actions][semantic actions]]                                                     | [[#Grammar-format][Grammar format]]                           |
|                | [[#index-semantic_002dlex][=semantic-lex=]]                                                       | [[#Wisent-Lex][Wisent Lex]]                                   |
|                | [[#index-shift][shift]]                                                                           | [[#Wisent-Parsing][Wisent Parsing]]                           |
|                | [[#index-shift_002dreduce-parser][shift-reduce parser]]                                           | [[#Wisent-Parsing][Wisent Parsing]]                           |
|                | [[#index-shift_002freduce-conflicts][shift/reduce conflicts]]                                     | [[#Conflicts][Conflicts]]                                     |
|                | [[#index-start-nonterminals][start nonterminals]]                                                 | [[#Start-nonterminals][Start nonterminals]]                   |
|                | [[#index-syntax-error][syntax error]]                                                             | [[#Wisent-Parsing][Wisent Parsing]]                           |
| -------------- |                                                                                                   |                                                               |
| T              |                                                                                                   |                                                               |
|                | [[#index-table_002ddriven-parser][table-driven parser]]                                           | [[#Wisent-Parsing][Wisent Parsing]]                           |
|                | [[#index-tags][tags]]                                                                             | [[#Wisent-Semantic][Wisent Semantic]]                         |
|                | [[#index-terminal][terminal]]                                                                     | [[#Wisent-Grammar][Wisent Grammar]]                           |
|                | [[#index-token][token]]                                                                           | [[#Wisent-Grammar][Wisent Grammar]]                           |
| -------------- |                                                                                                   |                                                               |
| U              |                                                                                                   |                                                               |
|                | [[#index-understanding-the-automaton][understanding the automaton]]                               | [[#Understanding-the-automaton][Understanding the automaton]] |
| -------------- |                                                                                                   |                                                               |
| W              |                                                                                                   |                                                               |
|                | [[#index-wisent_002dabort][=wisent-abort=]]                                                       | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002dabort-1][=wisent-abort=]]                                                     | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002dcancel_002ddebug_002don_002dentry][=wisent-cancel-debug-on-entry=]]           | [[#Debugging-actions][Debugging actions]]                     |
|                | [[#index-wisent_002dcancel_002ddebug_002don_002dentry-1][=wisent-cancel-debug-on-entry=]]         | [[#Debugging-actions][Debugging actions]]                     |
|                | [[#index-wisent_002dclearin][=wisent-clearin=]]                                                   | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002dclearin-1][=wisent-clearin=]]                                                 | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002dcollect_002dunmatched_002dsyntax][=wisent-collect-unmatched-syntax=]]         | [[#Useful-functions][Useful functions]]                       |
|                | [[#index-wisent_002dcollect_002dunmatched_002dsyntax-1][=wisent-collect-unmatched-syntax=]]       | [[#Useful-functions][Useful functions]]                       |
|                | [[#index-wisent_002dcompile_002dgrammar][=wisent-compile-grammar=]]                               | [[#Compiling-a-grammar][Compiling a grammar]]                 |
|                | [[#index-wisent_002dcompile_002dgrammar-1][=wisent-compile-grammar=]]                             | [[#Compiling-a-grammar][Compiling a grammar]]                 |
|                | [[#index-wisent_002ddebug_002dflag][=wisent-debug-flag=]]                                         | [[#Grammar-Debugging][Grammar Debugging]]                     |
|                | [[#index-wisent_002ddebug_002dflag-1][=wisent-debug-flag=]]                                       | [[#Grammar-Debugging][Grammar Debugging]]                     |
|                | [[#index-wisent_002ddebug_002don_002dentry][=wisent-debug-on-entry=]]                             | [[#Debugging-actions][Debugging actions]]                     |
|                | [[#index-wisent_002ddebug_002don_002dentry-1][=wisent-debug-on-entry=]]                           | [[#Debugging-actions][Debugging actions]]                     |
|                | [[#index-wisent_002ddebug_002dshow_002dentry][=wisent-debug-show-entry=]]                         | [[#Debugging-actions][Debugging actions]]                     |
|                | [[#index-wisent_002ddebug_002dshow_002dentry-1][=wisent-debug-show-entry=]]                       | [[#Debugging-actions][Debugging actions]]                     |
|                | [[#index-wisent_002ddiscarding_002dtoken_002dfunctions][=wisent-discarding-token-functions=]]     | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002ddiscarding_002dtoken_002dfunctions-1][=wisent-discarding-token-functions=]]   | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002deoi_002dterm][=wisent-eoi-term=]]                                             | [[#Writing-a-lexer][Writing a lexer]]                         |
|                | [[#index-wisent_002deoi_002dterm-1][=wisent-eoi-term=]]                                           | [[#Writing-a-lexer][Writing a lexer]]                         |
|                | [[#index-wisent_002derrok][=wisent-errok=]]                                                       | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002derrok-1][=wisent-errok=]]                                                     | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002derror][=wisent-error=]]                                                       | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002derror-1][=wisent-error=]]                                                     | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002dinput][=wisent-input=]]                                                       | [[#Actions-goodies][Actions goodies]]                         |
|                | [[#index-wisent_002dinput-1][=wisent-input=]]                                                     | [[#Actions-goodies][Actions goodies]]                         |
|                | [[#index-wisent_002dlex][=wisent-lex=]]                                                           | [[#Wisent-Lex][Wisent Lex]]                                   |
|                | [[#index-wisent_002dlex-1][=wisent-lex=]]                                                         | [[#Wisent-Lex][Wisent Lex]]                                   |
|                | [[#index-wisent_002dlex_002distream][=wisent-lex-istream=]]                                       | [[#Wisent-Lex][Wisent Lex]]                                   |
|                | [[#index-wisent_002dlexer][=wisent-lexer=]]                                                       | [[#Actions-goodies][Actions goodies]]                         |
|                | [[#index-wisent_002dlexer-1][=wisent-lexer=]]                                                     | [[#Actions-goodies][Actions goodies]]                         |
|                | [[#index-wisent_002dmessage][=wisent-message=]]                                                   | [[#Report-errors][Report errors]]                             |
|                | [[#index-wisent_002dmessage-1][=wisent-message=]]                                                 | [[#Report-errors][Report errors]]                             |
|                | [[#index-wisent_002dnerrs][=wisent-nerrs=]]                                                       | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002dnerrs-1][=wisent-nerrs=]]                                                     | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002dparse][=wisent-parse=]]                                                       | [[#Wisent-Parsing][Wisent Parsing]]                           |
|                | [[#index-wisent_002dparse-1][=wisent-parse=]]                                                     | [[#Wisent-Parsing][Wisent Parsing]]                           |
|                | [[#index-wisent_002dparse_002dtoggle_002dverbose_002dflag][=wisent-parse-toggle-verbose-flag=]]   | [[#Report-errors][Report errors]]                             |
|                | [[#index-wisent_002dparse_002dtoggle_002dverbose_002dflag-1][=wisent-parse-toggle-verbose-flag=]] | [[#Report-errors][Report errors]]                             |
|                | [[#index-wisent_002dparse_002dverbose_002dflag][=wisent-parse-verbose-flag=]]                     | [[#Report-errors][Report errors]]                             |
|                | [[#index-wisent_002dparse_002dverbose_002dflag-1][=wisent-parse-verbose-flag=]]                   | [[#Report-errors][Report errors]]                             |
|                | [[#index-wisent_002dpost_002dparse_002dhook][=wisent-post-parse-hook=]]                           | [[#Wisent-Parsing][Wisent Parsing]]                           |
|                | [[#index-wisent_002dpost_002dparse_002dhook-1][=wisent-post-parse-hook=]]                         | [[#Wisent-Parsing][Wisent Parsing]]                           |
|                | [[#index-wisent_002dpre_002dparse_002dhook][=wisent-pre-parse-hook=]]                             | [[#Wisent-Parsing][Wisent Parsing]]                           |
|                | [[#index-wisent_002dpre_002dparse_002dhook-1][=wisent-pre-parse-hook=]]                           | [[#Wisent-Parsing][Wisent Parsing]]                           |
|                | [[#index-wisent_002drecovering][=wisent-recovering=]]                                             | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002drecovering-1][=wisent-recovering=]]                                           | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002dregion][=wisent-region=]]                                                     | [[#Actions-goodies][Actions goodies]]                         |
|                | [[#index-wisent_002dregion-1][=wisent-region=]]                                                   | [[#Actions-goodies][Actions goodies]]                         |
|                | [[#index-wisent_002dset_002dregion][=wisent-set-region=]]                                         | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002dset_002dregion-1][=wisent-set-region=]]                                       | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002dsingle_002dstart_002dflag][=wisent-single-start-flag=]]                       | [[#Compiling-a-grammar][Compiling a grammar]]                 |
|                | [[#index-wisent_002dskip_002dblock][=wisent-skip-block=]]                                         | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002dskip_002dblock-1][=wisent-skip-block=]]                                       | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002dskip_002dtoken][=wisent-skip-token=]]                                         | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002dskip_002dtoken-1][=wisent-skip-token=]]                                       | [[#Error-recovery][Error recovery]]                           |
|                | [[#index-wisent_002dtoggle_002dverbose_002dflag][=wisent-toggle-verbose-flag=]]                   | [[#Grammar-Debugging][Grammar Debugging]]                     |
|                | [[#index-wisent_002dtoggle_002dverbose_002dflag-1][=wisent-toggle-verbose-flag=]]                 | [[#Grammar-Debugging][Grammar Debugging]]                     |
|                | [[#index-wisent_002dtoken_002dto_002dstring][=wisent-token-to-string=]]                           | [[#Report-errors][Report errors]]                             |
|                | [[#index-wisent_002dverbose_002dflag][=wisent-verbose-flag=]]                                     | [[#Grammar-Debugging][Grammar Debugging]]                     |
|                | [[#index-wisent_002dverbose_002dflag-1][=wisent-verbose-flag=]]                                   | [[#Grammar-Debugging][Grammar Debugging]]                     |
|                | [[#index-WY-grammar-format][WY grammar format]]                                                   | [[#Wisent-Semantic][Wisent Semantic]]                         |
| -------------- |                                                                                                   |                                                               |

| Jump to:   | [[#Index_cp_symbol-1][*$*]]  \\                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|            | [[#Index_cp_letter-A][*A*]]   [[#Index_cp_letter-B][*B*]]   [[#Index_cp_letter-C][*C*]]   [[#Index_cp_letter-D][*D*]]   [[#Index_cp_letter-E][*E*]]   [[#Index_cp_letter-G][*G*]]   [[#Index_cp_letter-I][*I*]]   [[#Index_cp_letter-L][*L*]]   [[#Index_cp_letter-M][*M*]]   [[#Index_cp_letter-N][*N*]]   [[#Index_cp_letter-P][*P*]]   [[#Index_cp_letter-R][*R*]]   [[#Index_cp_letter-S][*S*]]   [[#Index_cp_letter-T][*T*]]   [[#Index_cp_letter-U][*U*]]   [[#Index_cp_letter-W][*W*]]   |
