#!/usr/bin/env bash
# build-aux/android-build.sh — build a stock GNU Emacs APK with the
# host user's Doom config bundled as Android assets.
#
# Runs INSIDE the Containerfile.android image.  Bind mounts expected:
#
#   /work/cmacs           ← $PWD on the host (RW)
#   /work/doom-core       ← $HOME/.config/emacs on the host (RO)
#   /work/doom-private    ← $HOME/.config/doom  on the host (RO)
#   /work/out             ← $PWD/build/android-out on the host (RW)
#
# Environment (set by Containerfile.android):
#
#   ANDROID_HOME, ANDROID_NDK_HOME, ANDROID_API_LEVEL,
#   ANDROID_BUILD_TOOLS_VERSION, JAVA_HOME, PATH already extended.
#
# Output: build/android-out/emacs-<version>-<api>-<abi>.apk

set -euo pipefail

# ---------------------------------------------------------------- paths
SRC=/work/cmacs
DOOM_CORE_SRC=/work/doom-core
DOOM_PRIVATE_SRC=/work/doom-private
OUT=/work/out
BUNDLE_DIR="$SRC/build-aux/android-doom-bundle"

# Default ABI: aarch64.  Override with ANDROID_ABI=armv7|x86_64 if you
# need a 32-bit phone or emulator build.
ANDROID_ABI=${ANDROID_ABI:-aarch64}

case "$ANDROID_ABI" in
  aarch64) ANDROID_CC_TRIPLE=aarch64-linux-android ;;
  armv7)   ANDROID_CC_TRIPLE=armv7a-linux-androideabi ;;
  x86_64)  ANDROID_CC_TRIPLE=x86_64-linux-android ;;
  i686)    ANDROID_CC_TRIPLE=i686-linux-android ;;
  *) echo "unknown ANDROID_ABI=$ANDROID_ABI" >&2; exit 2 ;;
esac

ANDROID_JAR="$ANDROID_HOME/platforms/android-${ANDROID_API_LEVEL}/android.jar"
# NDK API can lag the SDK API: NDK r27c ships per-target compilers
# only up to android35.  That's what binds the APK's effective
# minSdk; the SDK jar (android-36) is what we compile *against*.
ANDROID_CC="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/${ANDROID_CC_TRIPLE}${ANDROID_NDK_API_LEVEL:-$ANDROID_API_LEVEL}-clang"
SDK_BUILD_TOOLS="$ANDROID_HOME/build-tools/${ANDROID_BUILD_TOOLS_VERSION}"

# ----------------------------------------------------------- preflight
echo "==> preflight"
test -f "$ANDROID_JAR"   || { echo "missing $ANDROID_JAR" >&2; exit 2; }
test -x "$ANDROID_CC"    || { echo "missing or not executable: $ANDROID_CC" >&2; exit 2; }
test -d "$SDK_BUILD_TOOLS" || { echo "missing $SDK_BUILD_TOOLS" >&2; exit 2; }
test -d "$SRC/.git" -o -f "$SRC/configure.ac" || {
  echo "source tree not found at $SRC (forgot the bind-mount?)" >&2; exit 2; }

cd "$SRC"

# ------------------------------------------------------------- doom bundle
#
# Stage the user's Doom config into build-aux/android-doom-bundle/.
# This directory is referenced by the patched java/Makefile.in
# install_temp rule and ends up under assets/doom-bundle/ in the APK.
#
# Excludes:
#   .local/, eln-cache/, straight/  — per-machine package caches
#                                     (regenerated by `doom sync' on-device)
#   server/                          — emacs daemon socket dir
#   .git                             — pointless on the phone
#   *~ *.elc~                        — editor cruft
# Set CMACS_ANDROID_VANILLA=1 to skip Doom embedding entirely (no
# bundle, no site-start.el shim).  Useful for diagnostic builds —
# isolates whether a startup crash is related to our customizations
# versus something in the upstream Emacs Android port.
if [ "${CMACS_ANDROID_VANILLA:-}" = "1" ]; then
  echo "==> CMACS_ANDROID_VANILLA=1 — skipping Doom bundle + site-start.el shim"
  rm -rf "$BUNDLE_DIR"
  # Move site-start.el out of the way so the lisp tree we ship
  # matches upstream exactly.  Restored at end-of-script regardless
  # of build outcome.
  if [ -f "$SRC/lisp/site-start.el" ]; then
    mv "$SRC/lisp/site-start.el" "$SRC/lisp/site-start.el.cmacs-disabled"
    trap 'mv "$SRC/lisp/site-start.el.cmacs-disabled" "$SRC/lisp/site-start.el" 2>/dev/null || true' EXIT
  fi
else
  echo "==> staging Doom bundle"
  rm -rf "$BUNDLE_DIR"
  mkdir -p "$BUNDLE_DIR/emacs" "$BUNDLE_DIR/doom"

  if [ -d "$DOOM_CORE_SRC" ] && [ "$(ls -A "$DOOM_CORE_SRC" 2>/dev/null)" ]; then
    rsync -a \
      --exclude='/.local' --exclude='/eln-cache' --exclude='/straight' \
      --exclude='/server' --exclude='.git' --exclude='*~' \
      "$DOOM_CORE_SRC/" "$BUNDLE_DIR/emacs/"
    echo "    doom core:    $(du -sh "$BUNDLE_DIR/emacs"    | cut -f1)"
  else
    echo "    doom core:    (empty mount — skipping)"
  fi

  if [ -d "$DOOM_PRIVATE_SRC" ] && [ "$(ls -A "$DOOM_PRIVATE_SRC" 2>/dev/null)" ]; then
    rsync -a --exclude='.git' --exclude='*~' \
      "$DOOM_PRIVATE_SRC/" "$BUNDLE_DIR/doom/"
    echo "    doom private: $(du -sh "$BUNDLE_DIR/doom"     | cut -f1)"
  else
    echo "    doom private: (empty mount — skipping)"
  fi
fi

# ----------------------------------------------------------- autogen
#
# Skip autogen.sh when configure already exists — saves a few seconds
# on incremental builds and keeps the container reusable across
# successive code changes without re-running autoconf.
if [ ! -f "$SRC/configure" ]; then
  echo "==> autogen"
  ./autogen.sh
fi

# ------------------------------------------------------------ configure
#
# Stock GNU Emacs for Android with the same library set the upstream
# Po Lu prebuilt APK ships.  Cross-compiled NDK ports (gnutls + deps,
# libjpeg/png/gif/tiff, libxml2, harfbuzz, tree-sitter, libffi) live
# at $NDK_PORTS_DIR (set by Containerfile.android).
#
# Without these, Emacs's startup takes degraded init paths that on
# at least HyperOS / Android 16 devices manifest as a libc-internal
# mutex race ("FORTIFY: pthread_mutex_lock called on a destroyed
# mutex") during framework property reads, killing the app before
# any Lisp can run.  The upstream prebuilt APK doesn't crash on
# those devices precisely because it has the full library set —
# matching that is the workaround.
#
# Disabled features:
#   - native-compilation: libgccjit not available for NDK
#   - cmacs C subsystems: none cross-compile to NDK (Wayland/glib
#     deps are Linux-desktop-specific)
#   - threads: still off as a precaution from earlier debugging.
#     Re-enable once the build is known stable on-device.
NDK_PATHS=$(ls -d "${NDK_PORTS_DIR:-/opt/ndk-ports}"/*/ 2>/dev/null \
            | tr '\n' ' ' | sed 's/ $//')
if [ -z "$NDK_PATHS" ]; then
  echo "no NDK ports found at ${NDK_PORTS_DIR:-/opt/ndk-ports}; \
rebuild the container image (\`just android-image')." >&2
  exit 2
fi

echo "==> configure (api=$ANDROID_API_LEVEL abi=$ANDROID_ABI)"
echo "    ndk-path:"
for p in $NDK_PATHS; do echo "      $p"; done
./configure \
  --with-android="$ANDROID_JAR" \
  ANDROID_CC="$ANDROID_CC" \
  SDK_BUILD_TOOLS="$SDK_BUILD_TOOLS" \
  --with-ndk-path="$NDK_PATHS" \
  --with-selinux=yes \
  --without-android-debug \
  --without-native-compilation \
  --without-webp --without-xpm --without-imagemagick \
  --without-json --without-mailutils \
  --without-cmacs-glib --without-cmacs-gi --without-cmacs-crispy \
  --without-cmacs-bacon --without-cmacs-gowl --without-cmacs-podomation \
  --without-cmacs-libreclaw --without-cmacs-org-ex --without-cmacs-mcp

# ------------------------------------------------------------- build
echo "==> make"
make all -j"$(nproc)"

# ------------------------------------------------------------- collect
echo "==> collect APK"
mkdir -p "$OUT"
shopt -s nullglob
APKS=( java/emacs-*.apk )
shopt -u nullglob
if [ ${#APKS[@]} -eq 0 ]; then
  echo "no APK produced in java/" >&2; exit 3
fi

for apk in "${APKS[@]}"; do
  cp -f "$apk" "$OUT/"
  base=$(basename "$apk")
  printf '    %s   %s   %s\n' \
    "$(stat -c%s "$apk" | numfmt --to=iec --suffix=B --format='%6.1f')" \
    "$(sha256sum "$apk" | cut -c1-12)" \
    "$base"
done

echo
echo "==> done.  APKs:"
ls -lh "$OUT"/*.apk
