/* cmacs-ai-image.c --- image generation DEFUNs.
 *
 * Copyright (C) 2026 Zach Podbielniak
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * Wraps AiImageGenerator (currently implemented by OpenAI, Gemini,
 * Grok clients).  Async by default; the result alist exposes the
 * generated bytes so the Elisp layer can dump them to a file and
 * insert an [[file:]] org link.  We do NOT make the synchronous
 * helper available because image gen takes seconds and would block
 * the main thread for the whole call. */

#include <config.h>

#ifdef HAVE_CMACS_AI

#include "lisp.h"
#include "cmacs-ai.h"
#include "cmacs-glib-loop.h"
#include "cmacs-eval-dispatch.h"

#include <ai-glib.h>
#include <glib.h>

typedef struct
{
  uint64_t cb_cookie;
} CmacsAiImageJob;

static Lisp_Object
cmacs_ai__image_response_to_lisp (AiImageResponse *resp)
{
  Lisp_Object out = Qnil;
  guint n = ai_image_response_get_image_count (resp);
  for (guint i = 0; i < n; i++)
    {
      AiGeneratedImage *img = ai_image_response_get_image (resp, i);
      if (!img) continue;
      const gchar *url    = ai_generated_image_get_url (img);
      const gchar *b64    = ai_generated_image_get_base64 (img);
      const gchar *mime   = ai_generated_image_get_mime_type (img);
      const gchar *revised = ai_generated_image_get_revised_prompt (img);
      Lisp_Object plist = Qnil;
      if (revised) plist = Fcons (build_string (revised),
                                  Fcons (intern (":revised"), plist));
      if (mime)    plist = Fcons (build_string (mime),
                                  Fcons (intern (":mime"), plist));
      if (b64)     plist = Fcons (build_string (b64),
                                  Fcons (intern (":base64"), plist));
      if (url)     plist = Fcons (build_string (url),
                                  Fcons (intern (":url"), plist));
      out = Fcons (Fnreverse (plist), out);
    }
  return Fnreverse (out);
}

static void
on_image_done (GObject *src, GAsyncResult *res, gpointer user)
{
  CmacsAiImageJob *j = user;
  GError *err = NULL;
  g_autoptr (AiImageResponse) resp = ai_image_generator_generate_image_finish (
    AI_IMAGE_GENERATOR (src), res, &err);
  Lisp_Object payload;
  if (resp == NULL)
    payload = list2 (intern (":error"),
                     build_string (err ? err->message : "image gen failed"));
  else
    payload = list2 (intern (":images"),
                     cmacs_ai__image_response_to_lisp (resp));
  cmacs_dispatch_callback_invoke1 (j->cb_cookie, payload);
  if (err) g_error_free (err);
  g_free (j);
}

DEFUN ("cmacs-ai-image-generate-async",
       Fcmacs_ai_image_generate_async,
       Scmacs_ai_image_generate_async, 3, 4, 0,
       doc: /* Generate an image asynchronously.
CLIENT is a client handle whose underlying GObject implements
AiImageGenerator (openai / gemini / grok).  PROMPT is the textual
description.  CALLBACK is fired once with a plist:
  (:images ((:url U :base64 B :mime M :revised R) ...))
or
  (:error MSG).
Optional OPTIONS is a plist with keys :model :size :quality :style
:count.  */)
  (Lisp_Object client, Lisp_Object prompt, Lisp_Object callback,
   Lisp_Object options)
{
  CHECK_FIXNAT (client);
  CHECK_STRING (prompt);
  gpointer raw = cmacs_ai_client_lookup (XFIXNUM (client));
  if (raw == NULL) error ("cmacs-ai: bad client handle");
  if (!AI_IS_IMAGE_GENERATOR (raw))
    error ("cmacs-ai: provider does not support image generation");

  g_autoptr (AiImageRequest) req = ai_image_request_new (SSDATA (prompt));

  Lisp_Object tail = options;
  while (CONSP (tail) && CONSP (XCDR (tail)))
    {
      Lisp_Object key = XCAR (tail);
      Lisp_Object val = XCAR (XCDR (tail));
      tail = XCDR (XCDR (tail));
      if (EQ (key, intern (":model")) && STRINGP (val))
        ai_image_request_set_model (req, SSDATA (val));
      else if (EQ (key, intern (":size")) && STRINGP (val))
        ai_image_request_set_size (req, ai_image_size_from_string (SSDATA (val)));
      else if (EQ (key, intern (":quality")) && STRINGP (val))
        ai_image_request_set_quality (req,
          ai_image_quality_from_string (SSDATA (val)));
      else if (EQ (key, intern (":style")) && STRINGP (val))
        ai_image_request_set_style (req,
          ai_image_style_from_string (SSDATA (val)));
      else if (EQ (key, intern (":count")) && FIXNUMP (val))
        ai_image_request_set_count (req, XFIXNUM (val));
    }

  CmacsAiImageJob *j = g_new0 (CmacsAiImageJob, 1);
  j->cb_cookie = cmacs_dispatch_callback_register (callback);
  ai_image_generator_generate_image_async (AI_IMAGE_GENERATOR (raw),
                                            req, NULL,
                                            on_image_done, j);
  return Qt;
}

void syms_of_cmacs_ai_image_defuns (void);
void
syms_of_cmacs_ai_image_defuns (void)
{
  defsubr (&Scmacs_ai_image_generate_async);
}

#endif /* HAVE_CMACS_AI */
