#!/bin/bash
# sync-deps-docs.sh — embed each dependency's docs/ tree into the cmacs
#                     interactive manual under doc_org/cmacs/deps/<dep>/
#
# Copyright (C) 2026 Zach Podbielniak
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Every vendored dependency under deps/<dep>/ ships its own docs/ folder
# (Org or Markdown).  cmacs installs doc_org/cmacs/ as a sibling of etc/
# and browses it from Emacs via M-x cmacs-manual / cmacs-manual-topic.
# This script mirrors each dep's docs/ verbatim into
#   doc_org/cmacs/deps/<dep>/
# so the dependency documentation ships with — and is browsable inside —
# cmacs.  The generated tree is a build artifact: it is NOT committed
# (see .gitignore) and is regenerated on every build (see Makefile.in's
# cmacs-deps-docs target).
#
# Files are copied as-is: .org open in org-mode, .md in markdown-mode.
# Other doc assets (images, etc.) are mirrored too.  A top-level
# doc_org/cmacs/deps/index.org is generated linking into each dep.
#
# This script is tolerant and idempotent: it is a clean no-op when there
# is no deps/ directory (e.g. an upstream-style / cmacs-off source tree),
# so wiring it into the build never breaks a non-cmacs build.
#
# Exit codes:
#   0  — success (including the no-op case)
#   2  — usage / environment error
#
# Usage:
#   tools/sync-deps-docs.sh            (from anywhere in the repo)
#   tools/sync-deps-docs.sh --quiet    (suppress per-dep progress output)

set -euo pipefail

usage () {
    cat <<'USAGE'
sync-deps-docs.sh — embed dependency docs into the cmacs manual

Usage: tools/sync-deps-docs.sh [--quiet]

Mirrors each deps/<dep>/docs/ tree into doc_org/cmacs/deps/<dep>/,
copying .org and .md (and any other doc assets) verbatim, then writes a
generated doc_org/cmacs/deps/index.org.  The result is a build artifact
and is not committed.  No-op when there is no deps/ directory.
USAGE
}

quiet=0
for arg in "$@"; do
    case "${arg}" in
        -h|--help) usage; exit 0 ;;
        --quiet)   quiet=1 ;;
        *)
            echo "sync-deps-docs.sh: unknown argument: ${arg}" >&2
            usage >&2
            exit 2
            ;;
    esac
done

say () { [[ ${quiet} -eq 0 ]] && echo "$@" || true; }

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
deps_dir="${repo_root}/deps"
out_dir="${repo_root}/doc_org/cmacs/deps"

# No deps/ at all → clean no-op (upstream-style / stripped tree).
if [[ ! -d "${deps_dir}" ]]; then
    say "sync-deps-docs.sh: no deps/ directory; nothing to embed"
    exit 0
fi

# Pick a mirror strategy once: prefer rsync for --delete semantics, fall
# back to a clear-then-copy with cp -a.
have_rsync=0
if command -v rsync >/dev/null 2>&1; then
    have_rsync=1
fi

mirror_tree () {
    # mirror_tree SRC DST — make DST an exact copy of SRC.
    local src="$1" dst="$2"
    if [[ ${have_rsync} -eq 1 ]]; then
        mkdir -p "${dst}"
        rsync -a --delete "${src}/" "${dst}/"
    else
        rm -rf "${dst}"
        mkdir -p "${dst}"
        cp -a "${src}/." "${dst}/"
    fi
}

# Find the entry-point doc for a dep, for the index link: prefer
# index.org, then index.md, then README.org/README.md, then the first
# .org, then the first .md.  Echoes a path relative to ${out_dir}.
entry_doc () {
    local dep="$1" base="${out_dir}/$1" cand f
    for cand in index.org index.md README.org README.md; do
        if [[ -f "${base}/${cand}" ]]; then
            echo "${dep}/${cand}"; return 0
        fi
    done
    f="$(cd "${base}" && find . -name '*.org' | sort | head -n1)"
    if [[ -n "${f}" ]]; then echo "${dep}/${f#./}"; return 0; fi
    f="$(cd "${base}" && find . -name '*.md' | sort | head -n1)"
    if [[ -n "${f}" ]]; then echo "${dep}/${f#./}"; return 0; fi
    return 1
}

# Refresh the output tree from scratch so removed deps/docs disappear.
rm -rf "${out_dir}"
mkdir -p "${out_dir}"

embedded=()
for dep_path in "${deps_dir}"/*/; do
    [[ -d "${dep_path}" ]] || continue
    dep="$(basename "${dep_path}")"
    docs="${dep_path}docs"
    if [[ ! -d "${docs}" ]]; then
        say "  skip ${dep} (no docs/)"
        continue
    fi
    mirror_tree "${docs}" "${out_dir}/${dep}"
    embedded+=("${dep}")
    say "  embed ${dep}"
done

# Generate the top-level index linking into each embedded dep.
{
    echo "#+TITLE: cmacs — Embedded Dependency Documentation"
    echo "#+OPTIONS: toc:nil num:nil"
    echo ""
    echo "# Generated by tools/sync-deps-docs.sh — do not edit by hand."
    echo "# This file and its sibling deps/ trees are build artifacts."
    echo ""
    echo "Documentation for the vendored dependencies under =deps/=,"
    echo "mirrored verbatim from each dependency's own =docs/= folder."
    echo ""
    if [[ ${#embedded[@]} -eq 0 ]]; then
        echo "No dependency documentation was found."
    else
        for dep in "${embedded[@]}"; do
            if entry="$(entry_doc "${dep}")"; then
                echo "- [[file:${entry}][${dep}]]"
            else
                echo "- ${dep}"
            fi
        done
    fi
} > "${out_dir}/index.org"

say "sync-deps-docs.sh: embedded ${#embedded[@]} dependency doc tree(s) into doc_org/cmacs/deps/"
exit 0
