;;; cmacs-gi.el --- GObject Introspection elisp API  -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Zach Podbielniak
;; SPDX-License-Identifier: AGPL-3.0-or-later

;;; Commentary:

;; Higher-level elisp interface to the GObject Introspection bridge.
;;
;; The C layer (cmacs-gi.c) provides these primitives:
;;   `gi-require'       -- load a typelib namespace
;;   `gi-call'          -- call a GI function
;;   `gi-method'        -- call a method on a GObject
;;   `gi-enum'          -- resolve an enum value
;;   `gi-list-functions' -- list functions in a namespace
;;   `gi-function-info' -- get signature info for a function
;;
;; This file wraps them with convenience macros and namespace-prefixed
;; function generation so you can write:
;;
;;   (cmacs-gi-require "Gtk" "4.0")
;;   (gtk-application-new "com.example.App" 0)
;;
;; instead of:
;;
;;   (gi-require "Gtk" "4.0")
;;   (gi-call "Gtk" "application_new" "com.example.App" 0)

;;; Code:

(require 'cl-lib)

(defvar cmacs-gi--loaded-namespaces nil
  "Alist of loaded GI namespaces.
Each entry is (NAMESPACE . VERSION).")

(defvar cmacs-gi--generated-prefixes nil
  "List of elisp prefixes generated by `cmacs-gi-require'.")

;;; Core wrappers

(defun cmacs-gi-require (namespace &optional version)
  "Load GI NAMESPACE with optional VERSION and generate elisp bindings.
NAMESPACE is a string like \"Gtk\", \"Gio\", \"GLib\".
VERSION is a string like \"4.0\", \"2.0\".

This loads the typelib via the C primitive `gi-require' and then
generates namespace-prefixed elisp functions for convenient access."
  (interactive
   (list (read-string "GI Namespace: ")
         (let ((ver (read-string "Version (empty for default): ")))
           (if (string-empty-p ver) nil ver))))
  (gi-require namespace version)
  (let ((entry (assoc namespace cmacs-gi--loaded-namespaces)))
    (if entry
        (setcdr entry version)
      (push (cons namespace version) cmacs-gi--loaded-namespaces)))
  (cmacs-gi--generate-namespace-functions namespace)
  t)

(defun cmacs-gi-loaded-p (namespace)
  "Return non-nil if GI NAMESPACE has been loaded."
  (assoc namespace cmacs-gi--loaded-namespaces))

;;; Convenience call wrappers

(defun cmacs-gi-call (namespace function &rest args)
  "Call GI FUNCTION in NAMESPACE with ARGS.
Like `gi-call' but with a more natural calling convention."
  (apply #'gi-call namespace function args))

(defun cmacs-gi-method-call (object method &rest args)
  "Call METHOD on GObject OBJECT with ARGS.
Like `gi-method' but with a more natural calling convention."
  (apply #'gi-method object method args))

;;; Enum helpers

(defun cmacs-gi-enum-value (namespace enum member)
  "Get the integer value of MEMBER in ENUM from NAMESPACE.
All arguments are strings."
  (gi-enum namespace enum member))

(defmacro cmacs-gi-defenum (name namespace enum)
  "Define constants for all members of ENUM in NAMESPACE.
Creates constants named NAME-MEMBER for each enum value.

Example:
  (cmacs-gi-defenum gtk-align \"Gtk\" \"Align\")
  ;; defines gtk-align-fill, gtk-align-start, etc."
  (declare (indent 1))
  `(progn
     ,@(let ((prefix (symbol-name name)))
         ;; At macro expansion time we can't call gi-enum,
         ;; so we generate runtime code.
         `((defvar ,(intern (format "%s--namespace" prefix)) ,namespace)
           (defvar ,(intern (format "%s--enum" prefix)) ,enum)))))

;;; Namespace-prefixed function generation

(defun cmacs-gi--normalize-name (name)
  "Convert GI function NAME to an elisp-friendly symbol name.
Replaces underscores with hyphens and downcases."
  (downcase (replace-regexp-in-string "_" "-" name)))

(defun cmacs-gi--generate-namespace-functions (namespace)
  "Generate elisp wrapper functions for all functions in NAMESPACE.
Each GI function `foo_bar' in namespace `Gtk' becomes an elisp
function `gtk-foo-bar' that calls `(gi-call \"Gtk\" \"foo_bar\" ...)'."
  (let* ((prefix (downcase namespace))
         (functions (gi-list-functions namespace)))
    (dolist (func-name functions)
      (let* ((elisp-name (intern (format "%s-%s" prefix
                                         (cmacs-gi--normalize-name func-name))))
             ;; Capture for the closure
             (ns namespace)
             (fn func-name))
        (unless (fboundp elisp-name)
          (defalias elisp-name
            (lambda (&rest args)
              (apply #'gi-call ns fn args))
            (format "GI function %s.%s.\nAuto-generated by cmacs-gi." ns fn)))))
    (cl-pushnew prefix cmacs-gi--generated-prefixes :test #'string=)))

;;; Introspection helpers

(defun cmacs-gi-describe-function (namespace function)
  "Display signature information for FUNCTION in NAMESPACE."
  (interactive
   (list (completing-read "Namespace: "
                          (mapcar #'car cmacs-gi--loaded-namespaces))
         (read-string "Function: ")))
  (let ((info (gi-function-info namespace function)))
    (if info
        (with-help-window "*GI Function Info*"
          (princ (format "GI Function: %s.%s\n\n"
                         namespace function))
          (let ((args (cdr (assq 'args info)))
                (ret  (cdr (assq 'return-type info))))
            (princ "Arguments:\n")
            (if args
                (dolist (arg args)
                  (princ (format "  %s : %s\n" (car arg) (cdr arg))))
              (princ "  (none)\n"))
            (princ (format "\nReturn type: %s\n" ret))))
      (message "Function %s.%s not found" namespace function))))

(defun cmacs-gi-list-namespace-functions (namespace)
  "Display all functions available in NAMESPACE."
  (interactive
   (list (completing-read "Namespace: "
                          (mapcar #'car cmacs-gi--loaded-namespaces))))
  (let ((functions (gi-list-functions namespace)))
    (with-help-window "*GI Functions*"
      (princ (format "Functions in %s (%d total):\n\n"
                     namespace (length functions)))
      (dolist (fn functions)
        (princ (format "  %s\n" fn))))))

;;; with-gi macro

(defmacro cmacs-gi-with-namespace (namespace version &rest body)
  "Load GI NAMESPACE VERSION and execute BODY.
Convenience macro that ensures the namespace is loaded before
evaluating BODY.

Example:
  (cmacs-gi-with-namespace \"Gio\" \"2.0\"
    (gio-file-new-for-path \"/tmp/test\"))"
  (declare (indent 2))
  `(progn
     (cmacs-gi-require ,namespace ,version)
     ,@body))

(provide 'cmacs-gi)
;;; cmacs-gi.el ends here
